### ISSUE TITLE
Gtk3 Windows have too high contrast

### ISSUE THREAD

**Issue by tom95** [elementary/gala#100]
From this reddit thread: https://www.reddit.com/r/elementaryos/comments/73w0kb/loki_updates_for_september_elementary_os_medium/

The problem is that some windows (CSD?, gtk3?) have considerably higher contrast, rendering them to look unpleasant and, in case of dark theme window, barely readable. Refer to the screenshot at the bottom.

Some random notes I could gather:
* started about a week ago I think, during a update. unfortunately didnt manage to track which packages were exactly updated since I didnt have enough time to check it in detail for a couple of days after it happened
* happens on both daily and stable ppa
* no immediate connection to any third party apparent
* happens on any libmutter based wm, but as said above not on metacity (tried gnome-shell session on same install and mutter wm from the repos in both sessions)
* only native/gtk3 apps affected - CSD-related? could be that the shadow is accidentally stretching over the app? it does look a lot more like a contrast-increasing shader though. wingpanel, slingshot and plank are also affected though, so the actual appearance of the headerbar seems to not be related
* weird observation: it seems to not happen when you maximize/unmaximize a window, which is when gala replaces the real window with a snapshot of just the window texture (thus it is most likely not to gtk itself/the client side drawing code). could be an indicator that the contrast change happens as some sort of post-pro effect on wm level
* picture of the issue: https://imgur.com/a/r7PCX (note how it affects the picture in Shotwell, plank, the muted icon in wingpanel, the terminal and nautilus)
* the colors of the terminal actually get less transparent (got it on its default in that picture), the whites stay white though, so it can really only be a contrast change or similar
* Environment: switched to daily after problems started occuring, intel cpu/gpu, HiDPI screen

**Comment by marcelogdeandrade** [comment]
I'm having this problem for the last 15 days, it's really ruining my eOS experience.

**Comment by donadigo** [comment]
@marcelogdeandrade could you tell us what hardware do you have, namely the graphics card and installed drivers?

**Comment by marcelogdeandrade** [comment]
@donadigo I have a XPS 13 9560 with Intel Graphics Card. My drivers are installed directly from Intel Graphics Update Tool for Ubuntu. I'm using 4.11 kernel as well

**Comment by tom95** [comment]
Try uninstalling the Intel graphics update tool drivers, if you feel confident enough to try that. More specifically, I just killed my pantheon session doing so, but it recovered after reinstalling some packages (I had some manually compiled packages lying around). The problem, however, has disappeared for now, without the newer drivers. I'm hoping that this was in fact the problem, I ran a big ppa cleanup session before rebooting.

I, too, am running an XPS 13 9360.

**Comment by arshubham** [comment]
Just to add to it, it is happening for me on using Intel graphics on kernel 4.10 with latest mesa from padoka ppa. Everything works fine when using nvidia drivers.

**Comment by GreyAsteroid** [comment]
After some testing it seems to be mesa that's causing this issue. After adding the mesa used in the oibaf ppa I become affected by the issue.

**Comment by worldofpeace** [comment]
@GreyAsteroid That's great to hear! 

You had the regualar graphics stack too with intel gpu?
Can you give me the steps you took to isolate this?

**Comment by GreyAsteroid** [comment]
Regular intel graphics stack, just added the oibaf ppa and updated just the mesa packages. 
I've also seen Arch users complaining about this issue affecting Gnome.

**Comment by worldofpeace** [comment]
@GreyAsteroid That's weird. I have arch with gnome and I haven't had this happen.

**Comment by GreyAsteroid** [comment]
@worldofpeace https://www.reddit.com/r/gnome/comments/73zlqr/adapta_gtk_theme_is_suddenly_very_different/

**Comment by marcelogdeandrade** [comment]
How can I downgrade my drivers to the default version and fix the problem?

**Comment by worldofpeace** [comment]
@tom95
I think you should file a bug report on mesa. Since this element gala is not causing this issue as far as we know of.

**Comment by tom95** [comment]
Based on a quick sweep on freedesktop, this looks promising: https://bugs.freedesktop.org/show_bug.cgi?id=102924

**Comment by worldofpeace** [comment]
@tom95 This has been fixed on  https://github.com/mesa3d/mesa/commit/9e779e59b20ea9510801a4484613d33d8a8e4c3e
Can someone test the latest mesa and still see if this issue persists?

**Comment by tom95** [comment]
Can confirm that it's fixed with updates from https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers
