### ISSUE TITLE
Gala leaves artifacts and leftover parts from context menus until drawn over

### ISSUE THREAD

**Issue by hanaral** [elementary/gala#1000]
This bug seems to have been prevelant for a long time and I've been unsure whether  to report it since I'm not sure if it's a problem on the elementary side. 

## What Happened
On Mesa systems, it seems to be a common bug for Gala to continue to render the backdrops and outlines of overlay menus when they are drawn directly over the desktop, over Gtk apps (or in the case of WebKitGtk, only over header bars).
This is observed with overlays such as Gtk context menus, firefox's context menus and shadows, and also certan qt menus. I have observed this only with Gala, and with both Mesa and NVidia's drivers.

## Expected Behavior
Much like the GNOME compsitor Mutter (which Gala is based on), there should be no part of the UX that displays such artifacts.

### Example 1:
1. Open a new workspace, and do not allow for Gala to re-draw the center of the screen (by opening a window, changing workspace etc)
2. Right click on the center of the screen
3. Hover over a few items, and then click off the menu
4. You should be able to observe the line east side of the menu either remaining there, or flickering as you do things outside the bugged area 

Video for referance:
https://user-images.githubusercontent.com/58219504/103150255-3e2a5800-476a-11eb-9c24-ee9fe485adfe.mp4

### Example 2:
1. Open evolution, or any app with a WebKitGtk view, and position it's window so it's context menu is either over plank and/or the desktop
2. Open a context menu close to the edge of the window
3. Observe the context menu's artifacts left behind 

Video for referance:
https://user-images.githubusercontent.com/58219504/103150259-4edace00-476a-11eb-81cc-1650defe80f6.mp4

### Example 3:
1. Open Firefox and position it's window with enough space on the desktop so that there is enough room for the context menu to render over the destkop
2. Open a context menu either from the titlebar or the browser contents
3. Observe the artifacting of the context menus over the firefox window, plank and/or the desktop

Video for referance:
https://user-images.githubusercontent.com/58219504/103150269-6619bb80-476a-11eb-9df2-9c20d8467581.mp4

### Logs
None that indicate anything abnormal:
![Screenshot from 2020-12-26 11-14-03](https://user-images.githubusercontent.com/58219504/103150374-8007ce00-476b-11eb-8143-cc295a1e1ea4.png)

## Platform Information
elementary OS 6 Daily 
Tested on Lenovo ThinkPad X240 with an i5-4300U CPU and Intel® HD Graphics 4400 (Used with default Mesa)

**Comment by Blast-City** [comment]
Hi.

Is this the same issue as #605?

If yes could you please close this and add your info to the issue mentioned above? Thanks.
