### ISSUE TITLE
Workspace Switcher doesn't scale for HiDPI [$50]

### ISSUE THREAD

**Issue by cassidyjames** [elementary/gala#101]
Like #31, the Workspace Switcher also doesn't scale by the UI scaling factor, meaning it's tiny on HiDPI.

**Comment by cassidyjames** [comment]
There is a [$50 bounty](https://www.bountysource.com/issues/52199057-workspace-switcher-doesn-t-scale-for-hidpi) on this issue.

**Comment by danrabbit** [comment]
punting since this is an enhancement not a regression

**Comment by peteruithoven** [comment]
I wouldn't really call this an enhancement? It's a bit of a shame to punt this one as it's one of the last open HiDPI issues, but you probably have you're reasons.

**Comment by donadigo** [comment]
@peteruithoven there's a branch here as WIP if you'd like to pick it up: https://github.com/elementary/gala/tree/workspace-switcher-hidpi, I unfortunately do not have a HiDPI display to test this on.

**Comment by peteruithoven** [comment]
@donadigo That's a shame, you're one of the great contributors to elementary OS, if someone deserves one it's you. 

@davidmhewitt could you maybe make a (WIP) pull request for that branch an mention this issue? That way it's easier to discover.

I tried building that branch but I appear to have an older Mutter version:
```
Native dependency libmutter found: NO found '3.18.4' but need: '>= 3.19' ; matched: '< 3.21'
```
Could it be that I'd need Juno to test this?
