### ISSUE TITLE
I can't minimize all windows

### ISSUE THREAD

**Issue by svetley1** [elementary/gala#1010]
Can this feature be added?
via hot corners and/or hotkey

**Comment by hanaral** [comment]
Minimising isn’t a part of the HIG. Showing and hiding is, but the user isn’t supposed to use it as their main way of navigating windows.

**Comment by svetley1** [comment]
I don't know what is HIG)  
Ok..  Oh..  Where I can find out how user **must** navigating windows?

**Comment by hanaral** [comment]
> I don't know what is HIG)

Human Interface Guidelines 😊️

> Ok.. Oh.. Where I can find out how user **must** navigating windows?

You can use the workspace system elementary OS to manage large windows, or/and use the 'run in the background when closed' setting that many apps have now

**Comment by svetley1** [comment]
Not sure if I can get used to it. Moreover, without support for gestures on the touchpad.
There is definitely a UI/UX problem here.

**Comment by hanaral** [comment]
> Not sure if I can get used to it.

Well, they were just suggestions. The workspace workflow is pretty good, I used to be quite anti-workspace, and now I see why its such a focus.

> Moreover, without support for gestures on the touchpad.

If you're feeling adventurous you might want to check out the [elementary 6 Early Access](https://builds.elementary.io/), which has workspace gestures. I've been using it for a while, be warned though, it's still incomplete in some areas.

**Comment by svetley1** [comment]
No thanks. I just need a stable tool in which everything (or almost) works out of the box. But everywhere, unfortunately, I meet problems (UI is not the main thing).

**Comment by hanaral** [comment]
Well I'm sure you are capable of reporting any of the issues you have 😊️

**Comment by danrabbit** [comment]
We lean heavily away from minimize in Pantheon. Instead of minimizing all windows, you can open a new workspace with the keyboard shortcut `Super` + `End`

Closing as "Design conflict"
