### ISSUE TITLE
Allow cycling through windows with arrow keys

### ISSUE THREAD

**Issue by batunii** [elementary/gala#1012]
### Existing condition
If a worksapce has multiple windows, to cycle through them you use a shortcut - `alt+Tab` 
This shortcut only cycles through windows in single order.

### Problem
If you have multiple windows open, chances of you missing/going past your desired window and then have to cycle all the way back to that said window are very high. 

### Solution
When in cycling view (`alt+tab` view) allow arrow keys to manually switch between next or the previous window.

**Comment by lenemter** [comment]
Duplicate of #124.
