### ISSUE TITLE
Plank appears on background when switching from fullscreen workspace

### ISSUE THREAD

**Issue by AlexDerbenev** [elementary/gala#1027]
## What Happened
![Снимок экрана от 2021-01-25 00-59-31](https://user-images.githubusercontent.com/39634495/105645212-23ebb300-5eab-11eb-8f1d-06a94249ce11.png)

https://user-images.githubusercontent.com/39634495/105645769-d8d29f80-5eac-11eb-81e6-7d3c81125bf4.mp4

## Steps to Reproduce
1. Open any app in fullscreen mode (browser or IDE) on one workspace
2. Slowly switch to another workspace using trackpad gesture
3. Plank will be visible both on workspace being entered and multitasking view background. You will also be able to see "visibility mask" on dock (could not capture using screenshot so had to record video on my phone).

By the way bug is not related to multitouch gestures. You can see this behaviour even when switching workspaces using keyboard shortcuts.

## Platform Information
![Снимок экрана от 2021-01-25 01-14-12](https://user-images.githubusercontent.com/39634495/105645130-b3449680-5eaa-11eb-8a28-1aceba3886d3.png)
![Снимок экрана от 2021-01-25 01-13-54](https://user-images.githubusercontent.com/39634495/105645131-b50e5a00-5eaa-11eb-9068-d8193960fdaf.png)

**Comment by JoseExposito** [comment]
Nice catch @AlexDerbenew , thanks for reporting this. I just created a PR to fix it :D
