### ISSUE TITLE
PiP window doesn't hide close and resize badges after PiP is dragged

### ISSUE THREAD

**Issue by hanaral** [elementary/gala#1035]
## What Happened

Creating a PiP window and dragging it causes the resize and close badges in it's corners not to go away.

## Expected Behavior

The badges fade out once the mouse cursor leaves the window.

## Steps to Reproduce

1. Create a PiP
2. Mouse over and drag the window around
3. Let go and make the cursor leave the view

### Logs

nothing useful:
```
Gtk-Message: 23:08:09.261: Failed to load module "pantheon-filechooser-module"
Window manager warning: Trying to re-add keybinding "switch-to-workspace-last".
Window manager warning: Trying to re-add keybinding "move-to-workspace-last".

** (gala:47089): WARNING **: 23:08:09.422: Preferences.vala:192: '/usr/share/themes/io.elementary.stylesheet.banana/plank-dark/dock.theme' is read-only!

** (gala:47089): WARNING **: 23:08:09.422: Preferences.vala:378: Missing key 'UrgentHueShift' for group 'PlankDockTheme' in preferences file '/usr/share/themes/io.elementary.stylesheet.banana/plank-dark/dock.theme' - using default value

```

## Platform Information

elementary OS 6 Daily

**Comment by hanaral** [comment]
@JoseExposito Any chance you could have a look at this?

**Comment by JoseExposito** [comment]
A little bit busy right now. It shouldn't be difficult to fix though

**Comment by JoseExposito** [comment]
Oops forgot about this one, just submitted a PR to fix it ;)
