### ISSUE TITLE
Multitasking View: Vertical scroll inverted?

### ISSUE THREAD

**Issue by Blast-City** [elementary/gala#1038]
## What Happened

Scrolling up switches the workspace to the left. Shouldn't the workspace switch to the right (+1) instead?
When there is a box with values scrolling up increases the value. The same with zoom.

Natural Scroll Disabled:
Scroll Left: Switch to the Left
Scroll Right: Switch to the Right
Scroll Up: Switch to the Left
Scroll Down: Switch to the Right

Natural Scroll Enabled:
Scroll Left: Switch to the Right
Scroll Right: Switch to the Left
Scroll Up: Switch to the Right
Scroll Down: Switch to the Left

## Expected Behavior

Natural Scroll Disabled:
Scroll Up: Switch to the Right
Scroll Down: Switch to the Left
Scroll Left: Switch to the Left
Scroll Right: Switch to the Right

Natural Scroll Enabled:
Scroll Up: Switch to the Left
Scroll Down: Switch to the Right
Scroll Left: Switch to the Right
Scroll Right: Switch to the Left

## Steps to Reproduce

1. Open an application
2. Go to the Multitasking View
3. Scroll Up or Down.

## Platform Information

elementary OS 5.1.7 Hera

**Comment by lenemter** [comment]
Fixed in OS 6.
