### ISSUE TITLE
Margin around some applications when using quicktile

### ISSUE THREAD

**Issue by peteruithoven** [elementary/gala#104]
I've been using [quicktile](https://github.com/ssokolow/quicktile) because it enables quarter tiling (https://github.com/elementary/gala/issues/105) and it enables resizing snapped windows (https://github.com/elementary/gala/issues/46).
One issue is that a lot of Elementary Apps like the Terminal, Videos, Files, Quilter, Webpin have a big margin around them when being tiled by quicktile. Applications like Firefox and Atom don't have this margin. 
![33fe922a-e856-11e4-8d6f-71f2feff2efd](https://user-images.githubusercontent.com/523210/31317653-227b8a2a-ac45-11e7-8600-b605588ae600.png)

There was an issue opened at the quicktile repo already: https://github.com/ssokolow/quicktile/issues/49

From this issue I understand that quicktile asks the window manager (Gala in this case?) to resize. 

I'm assuming this has something to do with the wide shadow, that also appears when taking screenshot of applications. 

Is there something Gala can do?

**Comment by Philip-Scott** [comment]
This is something that must be fixed In quicktile. GTK windows have a shadow that gets concidered part of the window, while other non-native apps don't. So the Developer of quicktile must take that into account.

**Comment by peteruithoven** [comment]
Thanks for the quick answer, I'll forward the tip to the Quicktile repo.

**Comment by peteruithoven** [comment]
@Philip-Scott do you happen to know if `libwnck` takes this into account? The developer of quicktile [responded](https://github.com/ssokolow/quicktile/issues/49#issuecomment-335065834) with:

> I'll double-check when I have time to address this, but QuickTile should be relying on libwnck (a GNOME-family library, just like GTK+) for getting and setting window geometry specifically to avoid this kind of "What definition of 'window geometry'?" mess.

**Comment by cassidyjames** [comment]
There was a change in window geometry between GTK 3.18 and GTK 3.22 that I believe should have fixed this. It fixed window size requests for a lot of things in GTK itself, no longer allocating the shadows as part of the window.

**Comment by ssokolow** [comment]
Makes sense.

If it turns out that *doesn't* fix it, I'm hoping to find time to port to GTK+ 3.x to account for libwnck 2.x being pulled from Ubuntu 18.x as unmaintained. (Something about QuickTile triggers a segfault in the PyGTK API porting shim on *buntu 14.04 LTS, so it's a bit of an involved process to do the port.)
