### ISSUE TITLE
3/4 finger swipe-down on desktop should show all windows

### ISSUE THREAD

**Issue by hanaral** [elementary/gala#1045]
## Problem

There is no way for the user to open the ‘all windows’ or ‘all windows on this workspace’ view without the key combination. This is critical if elementary OS does not want to push the dock as the main way of multitasking

## Proposed

Like exposé on macOS, it should probably dim the wallpaper a bit to visually distinguish itself from the workspace overview. Possibly the menu could even say ‘All windows:’ or ‘All windows in this workspace:’ to make it really obvious what it is.

**Comment by cassidyjames** [comment]
See #485; the intent is to deduplicate the already similar Multitasking View and window spread, in favor of making the Multitasking View the single place to get to open windows and workspaces. Since you can already get there with a swipe up, a swipe down doesn't make sense. Plus, I like #1026 to help communicate the physicality of the gesture.

**Comment by hanaral** [comment]
I get not wanting the workspace spread, but man if you have a bunch of windows open being able to immediately go to the one you want makes it easy

**Comment by cassidyjames** [comment]
@hanaral it's possible we could do something more clever, though, like a second swipe up on the Multitasking View could gather all windows from all workspaces. But regardless of what we do, we want to have a single "Multitasking View" that handles this instead of two separate implementations.

**Comment by hanaral** [comment]
@cassidyjames Would it be possible then to have an option to set whether the swipe up gesture uses the show all windows rather than workspaces?

**Comment by hanaral** [comment]
Seems to conflict with plans
