### ISSUE TITLE
Multitasking View: Bottom edge makes the dock visible on exit if "Pressure Reveal" is enabled.

### ISSUE THREAD

**Issue by Blast-City** [elementary/gala#1047]
## What Happened

Pressuring the bottom edge of the Multitasking view makes the Dock visible when returning to the Desktop if "Pressure Reveal" is enabled in Dock Settings.

## Expected Behavior

Multitasking View shouldn't change the Dock hidden status.

## Steps to Reproduce

1. Go to Desktop Settings/Dock and enable "Pressure Reveal"
2. Open an Application and move the window to the bottom area to hide the Dock.
3. Open Multitasking View and Pressure the bottom center with mouse.
4. Exit Multitasking view.

## Platform Information

elementary OS 5.1.7 Hera

**Comment by leolost2605** [comment]
The whole logic around dock reveal was rewritten so this doesn't apply anymore :)
