### ISSUE TITLE
Add bounce animation to Granite.MessageDialog

### ISSUE THREAD

**Issue by hanaral** [elementary/gala#1049]
## Problem

Message dialogues aren't very visually distinct from other windows when they are opened unless you view the contents. This is even more the case since message dialogues are almost always of some importance or urgency

I'm also aware that this is a cross-project request, but since animations are Gala's problem I opened it here
## Proposal

Make Granite.MessageDialogs emit a signal so that Gala can animate it openening. 
This would make them easily distinguishable from windows and other dialogues by giving them a 'bounce' animation when they appear. This not only gives them +300% quirkyness but also helps if the user takes longer read the dialogue contents and realise that they didn't just accidentally open something. 

## Prior Art

Another nice demo:

https://user-images.githubusercontent.com/58219504/107857460-57748a00-6e26-11eb-9cbf-6098d4adb407.mov

**Comment by tintou** [comment]
I think that this should be possible for any Gtk.Dialog as it should expose some hints to the WM that it is a Dialog and not a Window. Moving it to Gala and assigning UX for confirmation.

**Comment by hanaral** [comment]
> I think that this should be possible for any Gtk.Dialog as it should expose some hints to the WM that it is a Dialog and not a Window. Assigning UX for confirmation.

The reason I say this is partly due to the new Granite.Dialog which afaik is not a Gtk.Dialog. The other oart is that a lot of apps use Gtk.Dialog as a lazy way of rounding their corners, which would confuse users and leave them questioning why not all windows do it.

**Comment by tintou** [comment]
Granite.Dialog is a Gtk.Dialog subclass and apps misusing Gtk.Dialog should fix their copy as Gtk.Dialog is really made to work with a Gtk.Window (it will raise a message if it is shown alone without Gtk.Window)

**Comment by lenemter** [comment]
I believe this issue can be considered to be fixed in #1297.
