### ISSUE TITLE
Multitasking view bug.

### ISSUE THREAD

**Issue by ghost** [elementary/gala#1056]
When you holding SUPER KEY and ARROW UP you got bug with screen tearing.
[https://www.youtube.com/watch?v=XFOMVs5ZxS4&feature=youtu.be](https://www.youtube.com/watch?v=XFOMVs5ZxS4&feature=youtu.be) Video.

**Comment by hanaral** [comment]
Cannot reproduce on Odin, it looks to be a graphics driver bug

**Comment by lenemter** [comment]
Cannot reproduce in OS 7.
