### ISSUE TITLE
Improper animation when use Multitasking View and Show all windows one after another

### ISSUE THREAD

**Issue by SteveFour** [elementary/gala#1059]
### What Happened
When I activate each one after another I found that both animations overlap each other. This only happens when activate them through Hot Corners.

![Screenshot from 2021-02-22 22-14-00](https://user-images.githubusercontent.com/79463793/108730086-c4da9600-755d-11eb-81c0-b37adf4496fe.png)

https://user-images.githubusercontent.com/79463793/108730488-2ac71d80-755e-11eb-9665-1ce9fa7ffcdf.mp4

### Expected Behavior
Disable Multitasking View while using Show all windows and disable Show all windows while using Multitasking View.

### Platform Information
![Screenshot from 2021-02-22 22-38-35](https://user-images.githubusercontent.com/79463793/108731053-bf318000-755e-11eb-8dee-9e0915d02471.png)

**Comment by lenemter** [comment]
Fixed in #1587.
