### ISSUE TITLE
Crashes when closing a window

### ISSUE THREAD

**Issue by tintou** [elementary/gala#106]
I get constant crashes when closing a window.

Here is the backtrace:
[gala.log](https://github.com/elementary/gala/files/1369114/gala.log)

**Comment by Philip-Scott** [comment]
@tintou Do you have the steps to reproduce this? I can confirm that i also get crashes sometimes when closing windows, but haven't being able to reliably reproduce it

Also, are you on Loki or Juno?

**Comment by tintou** [comment]
fixed with mutter 3.26.1-2
