### ISSUE TITLE
Gestures should only require 3/4 fingers to initiate

### ISSUE THREAD

**Issue by hanaral** [elementary/gala#1060]
## Problem

Gestures require all 3/4 fingers to be present at all times, which makes the gesture feel more artificial and cumbersome rather than a natural 'glide' of the fingers

## Proposal

Like on macOS, gestures only require the set number of fingers to initiate the gesture. This would make it feel far more natural and would likely more accurately track a gesture

**Comment by cassidyjames** [comment]
This might be a limitation of Touchégg or of LibInput itself.

**Comment by hanaral** [comment]
@cassidyjames I was hoping that something like the current workspace overview would be possible, as it only needs to latch on until the user lets go. How about experimenting with it?

**Comment by JoseExposito** [comment]
This is how a gesture is defined by libinput:

> A gesture starts when the finger position and/or finger motion is unambiguous as to what gesture to trigger and continues until the first finger belonging to this gesture is lifted.
https://wayland.freedesktop.org/libinput/doc/latest/gestures.html#lifetime-of-a-gesture

This is also frequently requested on Touchégg, but unfortunately I can not change how it works. You can try to request this upstream, but I don't think this is something libinput would change, it behaves exactly as it is defined.
