### ISSUE TITLE
Allow users to ctrl+click for context menu

### ISSUE THREAD

**Issue by hanaral** [elementary/gala#1061]
## Problem

Users cannot right click if they use a mouse without a dedicated right click button, or they need or want to right click on a touchpad without timing a 2 finger click 

## Proposal

There should be a toggle under System Settings > Mouse and Touchpad for enabling ctrl+click 

## Prior Art

Macs used to use this as the main mode of right clicking in both hardware and software until the late 00s I believe (you still can in Big Sur)

**Comment by hanaral** [comment]
@JoseExposito Would you be able to judge how hard something like this would be to implement, is it Gala that controls the spawning of a context menu?
If it isn't, would you say it's feasible to just send right click when the user ctrl clicks?

**Comment by danrabbit** [comment]
This seems extremely specific to users who have only used very old Apple computers. It would likely have to be implemented lower in the input stack to work across toolkits. I don't think this is worth pursuing.

**Comment by JoseExposito** [comment]
Yes, Daniel is right, this can not be handled by Gala.

**Comment by danrabbit** [comment]
Closing as "Out of scope"

**Comment by hanaral** [comment]
All the Apple mice made up until the Magic Mouse lacked a right click afaik.
There much of a choice in terms of opening context menus using a mouse without a dedicated button - could there really not be an accessibility plugin that does this similar to Gala's zoom?
