### ISSUE TITLE
Weird behavior in trackpad gestures

### ISSUE THREAD

**Issue by andirsun** [elementary/gala#1067]
## What Happened

![deepin-screen-recorder_Select area_20210302001406](https://user-images.githubusercontent.com/22928302/109601076-4301e400-7aec-11eb-918c-4926ebcbb001.gif)

## Expected Behavior

hide the dock

## Steps to Reproduce

1. Put the mouse on dock
2.3 finger swipe up
3.see

## Platform Information

6.0 Daily

**Comment by JoseExposito** [comment]
It seems happen when a tooltip window is visible. The same bug can be reproduced if the mouse is over a tab in Files and the tooltip is being displayed.
