### ISSUE TITLE
"Tile left/right" disallows resizing by mouse

### ISSUE THREAD

**Issue by Janiczek** [elementary/gala#107]
When I tile windows left/right (by keyboard shortcuts or by snapping to the left/right screen edge), I lose the ability to resize the window horizontally (to occupy more/less than the 50%).

To do that I have to "unsnap" the window by moving it to the center, then reposition it to the side, and then resize it. *It would be nice to be able to resize the window when "snapped" too.*

**Comment by peteruithoven** [comment]
I think this is a duplicate of: https://github.com/elementary/gala/issues/46

**Comment by Janiczek** [comment]
@peteruithoven You're right. I'll close this.
