### ISSUE TITLE
Window shadows drawn improperly 

### ISSUE THREAD

**Issue by hanaral** [elementary/gala#1075]
## What Happened

Openening non elementary and gnome apps seem to result in the window shadows being cut off until the workspace is animated or the window is moved

## Expected Behavior

Shadows look consistent

## Steps to Reproduce

1. Open a non-curated app like Firefox
2. Focus the app by clicking on the tab rather than the titlebar

https://user-images.githubusercontent.com/58219504/109743123-17ecc280-7bc8-11eb-92f6-d6a61243c40c.mp4

## Platform Information

elementary OS 6 Daily

**Comment by lenemter** [comment]
Closing because I cannot reproduce the issue in OS 7. If you still encounter it, please reply here.
