### ISSUE TITLE
Gala shouldn't have to grab focus to use shortcuts or system keybindings

### ISSUE THREAD

**Issue by hanaral** [elementary/gala#1077]
## What Happened

This has been a long standing issue to me, and I'd appretiate it if it wasn't just dismissed as an upstream issue - this issue should be used to track the progress of it being fixed.

Gala has to take the focus away from an app or UI element when a key combo is pressed/held or super is pressed/held. Apps or parts of the UI that require focus to be kept are broken due to this behaviour -  if the user uses a key combo for adjusting display brightness, volume, or even just tapping super even if it is not bound causes:

- Apps like Ephemeral that remove input text when the search field focus is lost (this is by design afaik)
- Input method overlays like Mozc get toggled again and have their boxes re-appear 
- The focused app to constantly refocus which looks janky and disorientating for users (in the case of rapidly tapping vol. up/down)
- Apps like Screenshot grab focus which have literally lead me to give up on issue reports for bugs because they require focus, which is lost when I try to screenshot

And there are probably many more cases of apps misbehaving because they are just respecting the desktop paradigm of focused windows.

This optimally shouldn't be the default behaviour of a desktop OS.

## Expected Behavior

Focus is never lost when interacting with background features or non-user application related tasks like media controls, shortcuts and pressing modifier keys like super. 

## Platform Information

elementary OS 6 Daily

**Comment by danrabbit** [comment]
This is a limitation of X11 and can't be fixed in Gala. Closing as "Out of Scope"

**Comment by hanaral** [comment]
ah shucks.
