### ISSUE TITLE
Maximise current window hot corner shouldn't maximise every app

### ISSUE THREAD

**Issue by Suzie97** [elementary/gala#1089]
I've been making an applet for elementary OS. 

By default, the app doesn't offer a maximize button because it is not designed to be used in a maximized state. 

The app isn't maximized when I press super + up arrow on the keyboard and it is also not maximized when I drag it to the top ot the screen.

But when I use the hot corner which is set to maximize the current window, it maximizes the app and it doesn't look good.

The same problem exist with the app Niu by Lains. While some apps like Nimbus by Daniel Fore aren't maximized by the hot corner.

Should this thing be solved by the developers by making the app unmaximizable or should Gala only maximize those apps which provide a maximize button?

**Comment by tintou** [comment]
It is up to the application to set `resizable = false` on the window so that it can't be resized.

**Comment by Suzie97** [comment]
> It is up to the application to set `resizable = false` on the window so that it can't be resized.

I tried doing that, but the app still gets maximized.

**Comment by Suzie97** [comment]
https://user-images.githubusercontent.com/68198116/112966002-6c537580-9167-11eb-935e-a90bc2ad3801.mp4

As you can see in this video, the apps Time Limit and Niu can be maximized using the hot corner. These apps have `resizable = false` in their code.

![Screenshot from 2021-03-30 14-53-13](https://user-images.githubusercontent.com/68198116/112966829-39f64800-9168-11eb-9995-4694f930d290.png)

![Screenshot from 2021-03-30 14-54-54](https://user-images.githubusercontent.com/68198116/112966933-52fef900-9168-11eb-9589-cb70bcf226a1.png)

Nimbus also has the same property, but it doesn't get maximized with the hot corner.

![Screenshot from 2021-03-30 14-52-43](https://user-images.githubusercontent.com/68198116/112966967-5befca80-9168-11eb-92f3-6ac22edecd96.png)
