### ISSUE TITLE
An app should launch on the workspace where I commanded it to launch

### ISSUE THREAD

**Issue by Loreno10** [elementary/gala#1090]
I work with multiple workspaces. When I turn on my PC, I generally start with setting up my workspaces. I'm on workspace 1, I launch some apps, I switch to workspace 2, I do the same, and so on.
Some apps (especially snaps) are slow to start. It happens sometimes, that I open some app in workspace 1, and I switch to another workspace before the app loads. The app launches on workspace 2, instead of workspace 1, where it was commanded to launch.

I think this is wrong behavior. The app should show up on the workspace where it was launched.

**Comment by Blast-City** [comment]
Hi.

Is it the same issue as #258? If yes, please close this one since it is a duplicate.

Thanks

**Comment by Loreno10** [comment]
Right, it's exactly the same idea. Shame that it's hanging in there since about 2 years.
