### ISSUE TITLE
The gray background twitches when flipping through desktops

### ISSUE THREAD

**Issue by andaran** [elementary/gala#1099]
When scrolling desktops to the right, the gray background jerks when the arrow is pressed further. Sometimes the background moves correctly, and sometimes it spreads across the desktop surface. When recording the screen, the problem disappears, so I attach a video from the phone. This issue occurs on both the virtual machine and the host machine.

https://user-images.githubusercontent.com/58528987/113612318-59a1da80-9658-11eb-80f4-2763a2dc901e.mp4

**Comment by cassidyjames** [comment]
@andaran are you on elementary OS 5.1 or OS 6 Early Access?

**Comment by andaran** [comment]
> @andaran вы используете elementary OS 5.1 или OS 6 в раннем доступе?

elementary 5.1

**Comment by Blast-City** [comment]
Hi.

Could you check #504? Is it the same issue? If yes, please close this one since is a duplicate.

Thanks.

**Comment by andaran** [comment]
> Hi.
> 
> Could you check #504? Is it the same issue? If yes, please add your video to the one mentioned before and close this one.
> 
> Thanks.

Yes, this is the same problem.
