### ISSUE TITLE
Cannot see menu check marks (white color)

### ISSUE THREAD

**Issue by bksubhuti** [elementary/gala#110]
The menu check marks are white color against grey color.  It is not easy to see unless you highlight that particular menu item.  Choose a higher contrast color.  aka black when not highlighted and white when highlighted.  See picture.  There is a menu item that is checked already.  You need to look very carefully to see the white checkmark.
![screenshot from 2017-10-22 19 44 18](https://user-images.githubusercontent.com/18184280/31871692-44d6af80-b7dc-11e7-9c88-52d8c196958a.png)

**Comment by danrabbit** [comment]
Please report this issue in LibreOffice. Closing as invalid for Gala since there's nothing that can be done in this codebase to resolve the issue
