### ISSUE TITLE
Use gestures for "move to workspace"

### ISSUE THREAD

**Issue by danirabbit** [elementary/gala#1109]
## Problem

When using keyboard shortcuts you can either switch to a workspace with super + arrows or move a window to a workspace with super + alt + arrows. With gestures however, there is only the option to switch to a workspace, it's not possible to move a window to another workspace

## Proposal

It would be nice to be able to configure a horizontal swipe gesture to move the focused window in the direction of the swipe. For example, by default swiping horizontally with 3 fingers switches workspaces, and optionally one could move the focused window with a 4-finger swipe.

**Comment by JoseExposito** [comment]
It's _possible_ to do this at the moment in a very natural way:

- Place the mouse pointer on the window title
- "Click" with your thumb on your touchpad to start dragging your window
- Without lifting your thumb swipe to the next/previous workspace

I think this is a more natural interaction and doesn't require to memorize another gesture.... But the animation is broken.

**Comment by hanaral** [comment]
@JoseExposito I can't at all manage to do this.

Maybe this should be left as a context menu thing tbh

**Comment by danrabbit** [comment]
@JoseExposito ah yeah I mean that technically works, and it does make sense, but it is not an easy gesture to perform even on a huge magic trackpad. I can't imagine trying to do that on a laptop

**Comment by JoseExposito** [comment]
Yeah, I should also mention that it is only possible if you have a ["clickpad"](https://wayland.freedesktop.org/libinput/doc/latest/clickpad-softbuttons.html?highlight=clickpad#clickpad-software-button-behavior), so it is not suitable for all hardware... But I wish it were, it feels like the natural thing to do.

**Comment by janxkoci** [comment]
Throwing my hat into the idea ring:

- 3 fingers = change workspace (~Super+Arrow)
- 4 fingers = move window while changing workspace (~Super+Alt+Arrow)

Originally posted in https://github.com/elementary/switchboard-plug-mouse-touchpad/issues/186#issuecomment-1071492313
