### ISSUE TITLE
Drag and drop should always use the correct icon size drag point

### ISSUE THREAD

**Issue by hanaral** [elementary/gala#1110]
## Problem

I have no clue if this is entirely Gtk or if Gala actually handles this, but it seems that DnD'ing icons from Gtk apps alot of the time looks jank:

https://user-images.githubusercontent.com/58219504/114471342-570b2c00-9be8-11eb-8ccb-3b351fc9fb64.mp4

Files looks OK, but it would be more helpful at least in list modes to display the entire box as being dragged rather than iconifying it(which is utterly useless if the file/folder has no preview image)

https://user-images.githubusercontent.com/58219504/114471593-cd0f9300-9be8-11eb-91c1-d176bb06cd68.mp4

## Proposal

MacOS has always had fantastic DnD support, and even if the preview is as big as the item being dragged (with obviously an upper limit for the icon size) it is a true-to-life representation on what the user is dragging. This is why I really like the way Gala's own drag and drop looks in the multitasking overlay. Again, I've no clue whether or not Gala can control how DnD looks, (maybe Gtk css can if Gala can't) if all else fails maybe some hacky workaround could work.

## Prior Art

https://user-images.githubusercontent.com/58219504/114472048-7ce50080-9be9-11eb-80e9-03dd6c84e35f.mp4

**Comment by jeremypw** [comment]
You could open a wishlist issue against Files about the drag icon.  I think it is doable.

**Comment by danrabbit** [comment]
You'll need to make reports against each app where you feel things could be better. Gala does not control DnD previews, this is handled in Gtk
