### ISSUE TITLE
Giant size between notifications

### ISSUE THREAD

**Issue by tomaswarynyca** [elementary/gala#1112]
When receiving several notifications together there is a giant space between the view 
I am on the latest version of ElementaryOS 6

![Captura de pantalla de 2021-04-13 16-00-48 (copia)](https://user-images.githubusercontent.com/41587659/114606786-1eb03000-9c72-11eb-8fea-47d1e2fa0d78.png)

**Comment by danrabbit** [comment]
Transferring to `gala` since it controls the placement of notification window types
