### ISSUE TITLE
Melhoria no sistema operacional

### ISSUE THREAD

**Issue by Tarelho-1993** [elementary/gala#1113]
Boa noite, estou usando a distro elementary os 5.1.7 Hera, no trabalho e no meu computador em casa, em ambos utilizo fones de ouvido bluetooth, seria ótimo se incluirem a porcentagem de batéria no dispositivo de som conectado via bluetooth, faço varias reuniões com o fone de ouvido bluetooth e não quero ficar na mão sem meu fone de ouvido.

**Comment by Blast-City** [comment]
Hi.

Could you check elementary/wingpanel-indicator-power#141? Is it the same issue? If yes, please close this one and give a thumbs up on elementary/wingpanel-indicator-power#141.

Thanks.

**Comment by lenemter** [comment]
Closing as duplicate of https://github.com/elementary/wingpanel-indicator-power/issues/141.
