### ISSUE TITLE
Doubled battery notification

### ISSUE THREAD

**Issue by Loreno10** [elementary/gala#1114]
I see this:

![image](https://user-images.githubusercontent.com/10273406/114932508-dfcbd700-9e37-11eb-9751-5cfa01c038f7.png)

I guess one would be enough :)

**Comment by danrabbit** [comment]
These notifications are sent by the power plugin in GNOME Settings daemon. Please report an issue upstream in GNOME Gitlab

Closing as "out of scope" since Gala doesn't send these notifications
