### ISSUE TITLE
Use screenshot backend for screenshot key behaviour 

### ISSUE THREAD

**Issue by hanaral** [elementary/gala#1120]
## What Happened

gnome-settings-daemon seems to have a mind of its own when it comes to naming screenshots, the issue particularly effects other locales where only the Screenshot correctly localises filenames.

## Expected Behavior

All screenshots have their filename localised the same way.

## Steps to Reproduce

1. Choose a system locale that Screenshot saves with a localised filename 
2. Take a screenshot with the system key combo
3. Take another with the Screenshot app and compare their filenames

## Platform Information

elementary OS 6 Daily

**Comment by lenemter** [comment]
Gala now has its own mechanism for screenshots and I cannot reproduce the issue in OS 7. If you still encounter it, please reply here.
