### ISSUE TITLE
Irregular Wingpanel Behavior on Zoom and Multitasking View

### ISSUE THREAD

**Issue by candiedoperation** [elementary/gala#1127]
## What Happened

On Zooming in using gestures (happens also while using **⌘ + Plus**) and using gestures (or **⌘ + S**) for multitasking view, Wingpanel instead of hiding comes below and is visible

## Expected Behavior

On switching to multitasking view, wingpanel should hide as usual but it does not
**This irregular behavior was not experienced in elementary OS 5 (Hera)**

## Steps to Reproduce

1. Zoom in using gestures (or ⌘ + Plus)
2. Use gestures or (⌘ + S) to switch to multitasking view
3. You will see the issue

![Peek 2021-05-05 19-11](https://user-images.githubusercontent.com/47198395/117104199-5a35aa00-ad99-11eb-9f33-61a4270d8d3e.gif)

Additional Screenshots:
**Before Zoom**
![001](https://user-images.githubusercontent.com/47198395/119247566-326f8000-bba8-11eb-9ba2-6bfcadd14843.png)

**After Zoom**
![000 (3)](https://user-images.githubusercontent.com/47198395/119247564-2daacc00-bba8-11eb-96d0-06a8c58e3614.png)

### Logs

None

## Platform Information

Operating System: elementary OS 6
Edition: (Public Beta)
Hardware Information:
- Quad-Core Intel® Core™ i5-8250U CPU @ 1.60GHz
- Intel® UHD Graphics 620 (Kabylake GT2)
- 7.7 GiB memory
- 467.2 GB storage (SSD)

Laptop Information: HP Pavilion x360

**Comment by candiedoperation** [comment]
Hi there @davidmhewitt, the Public Beta has this issue and I have opened this in Gala. Do I need to open it in wingpanel or Multitasking View?

**Comment by davidmhewitt** [comment]
This is probably a gala issue, it handles gestures, zooming and multitasking view. Someone will move this issue if it is not the correct place for it.

**Comment by lenemter** [comment]
I cannot reproduce this issue on OS 7. Please reopen if you still encounter the issue.
