### ISSUE TITLE
Swipe Gesture to close apps in Multitasking View

### ISSUE THREAD

**Issue by candiedoperation** [elementary/gala#1128]
## Problem

Need to move the cursor more further to the close button of an app in multitasking view
![Screenshot from 2021-05-06 19 07 17](https://user-images.githubusercontent.com/47198395/117307587-53dd2600-ae9e-11eb-91fc-f7cc9596008c.png)

## Proposal

When an user uses **three finger up** gesture to launch multitasking view, closing apps from it should not require to move the mouse to the little cross icon located at the top-left corner of that window's thumbnail instead, on swiping with two fingers up on the thumbnail (similar to closing apps on smartphones), the app should close

## Prior Art

User needs to move the mouse pointer to the cross arrow located at the top-left corner of the open app's thumbnail in multitasking view

**Comment by JoseExposito** [comment]
Hi! At the moment you can close apps by tapping with 3 fingers instead of swiping.

**Comment by candiedoperation** [comment]
Okay, Thank You. I did not know about it.
