### ISSUE TITLE
Custom desktop right-click menu like OpenBox3

### ISSUE THREAD

**Issue by ergose** [elementary/gala#113]
I saw on the eOS StackExchange to send feature requests this way. I'm also glad to see these projects on GitHub.

One thing that I really, and I mean really, miss is the custom right-click menu I could have with Fluxbox/Openbox. I tried installing OpenBox3 in hopes that I could just run it with Gala and Pantheon, but it wouldn't since a window manager was being used. I tried the --replace param with OpenBox and the desktop bugged up, so that's out too. Besides, I like what you all have built, I just want a right-click menu.

Any possibility a custom desktop right click menu could be an option in the future?

Here's why I see value in it: 

- I like my Plank/Docky small with Chrome, Brackets, GitKraken, Terminator, and ST3.
- The right-click, I'd like to have a custom menu anywhere on the desktop with my 2nd most used apps.
    - (like alternate browsers, Meld, Postman, Calculator, IDEs)
- Then I could get to apps that are rarely used, but not worth uninstalling, via Applications

**Comment by jeremypw** [comment]
I am not sure that this will find favour with the UX team, but as a possible alternative, try making a folder in your home directory named "Other apps" or whatever and then copy the desktop files for the apps you want from /usr/shar/applications into this folder.  Then drag the folder onto Plank.  Clicking this folder icon will open a menu of those apps. Just click which one you want to open.

**Comment by janxkoci** [comment]
There is also and app in the AppCenter called desktop folder, it allows to put custom widgets on desktop, including shortcuts and enables some right-click action too (I think)

**Comment by danrabbit** [comment]
Closing in favor of #521

**Comment by janxkoci** [comment]
## Tangentially related rant follows:
Feel free to ignore and enjoy Xmas :wink: 

Why people want desktop actions anyway? I, for example, see no reason I should loose a functionality whenever I maximize a window :open_mouth: 

This question/rant applies to:
- desktop menus
- desktop icons (why hide my "most important stuff" under all the windows I opened?)
- most desktop widgets (those in elementary at least show up in Expo view, e.g. Nimbus or Nino)

I never understood why people defend desktop so vigorously. I mean yeah, it's what is expected after coming from Windows, but it took me a few minutes to realize that **the linux home folder is way better** for most of this stuff. And those minutes happened way back on a desktop that actually allowed desktop icons etc (i.e. some old Ubuntu). I never had more than a handful of icons on any linux desktop. The home folder is just way better system, objectively.

And Applications menu is available at all times, no matter how many programs I opened or maximized (plus completely available from keyboard, including search - I would never give that up for "secondary mouse click"). Not to mention that I often hear this complaint from the same people that complain about headerbars giving them "too little space to drag windows around". I do that action much less frequently then I open or maximize stuff.

## End of irrelevant rant, feel free to go on with your life :smiley:
