### ISSUE TITLE
Paste copied items using a three finger tap.

### ISSUE THREAD

**Issue by Suzie97** [elementary/gala#1132]
I just discovered this by accident on Firefox. You can select text anywhere and just tap with three fingers on firefox to paste that text. Its super handy as it doesn't require the user to right click and then copy and then right click to paste again.

How about implementing this to gala?

**Comment by andreasfelix** [comment]
The middle click copy/paste works on most distros and was disabled in elementary for GTK apps by default in https://github.com/elementary/default-settings/issues/5 some time ago.

You can enable it under **Settings > Mouse & Touchpad > Middle click paste** (or use gsettings */org/gnome/desktop/interface/gtk-enable-primary-paste*)
