### ISSUE TITLE
Plank sliding isn't animated with small size when switching to Multitasking view (eOS 6 Public Beta).

### ISSUE THREAD

**Issue by lilvadim** [elementary/gala#1134]
Dock smoothly slides down when I switch to Multitasking View, but it doesn't animated with Icon size set to something < 36.

**Comment by lilvadim** [comment]
With last updates, it seems like issue still is here, but how it appears with sizes less than 31.

**Comment by JoseExposito** [comment]
Yes, at the moment only the 3 sizes available in system settings are supported.
