### ISSUE TITLE
Low fps overview animation

### ISSUE THREAD

**Issue by lilvadim** [elementary/gala#1136]
Multitasking animations have noticeable FPS drops in the beginning and in the end of gesture (when windows are bigger).
Especially with multiple Chrome windows.

It's about lags that I see when using 1:1 touchpad gestures.
_Specs: 
AMD Ryzen 5 3500U with mobile Vega 8 graphics (laptop).
FullHD screen, Large text selected._

**Comment by lilvadim** [comment]
Maybe it's possible to somehow optimize performance of windows scaling animations? Then your DE will be greater than GNOME, because GNOME 40 has huge laggy animations problems when it comes to multitasking view with more than zero windows opened.

**Comment by Condor157** [comment]
Hi. Have the same problem. Animations in the end are shuttering. This is a bit sad. I am a shop assistant and have tested it on several new laptops with AMD 4700U, AMD 3500U, Intel 10300H and others. But even on my Intel® Celeron® G4920 there is the same problem. It would be great to fix that. I can add photos and videos if it is needed. I am always open to help improoving this great OS.

**Comment by okitoxo** [comment]
I have the same problem with a graphic card RX 570. FPS have low when I open multitask or close it only

**Comment by okitoxo** [comment]
This is a video recorded with slow motion

https://user-images.githubusercontent.com/5513927/129086201-34210fa7-3de1-4ef7-9054-163897c4bcfc.mp4

**Comment by danirabbit** [comment]
@lenemter should this be closed?

**Comment by lenemter** [comment]
@danirabbit Nope, multitasking view still lags for me even after latest optimizations.

**Comment by lenemter** [comment]
I'll close this because #1603 improved performance a lot and multitasking view animation no longer lags for me.
