### ISSUE TITLE
Gestures, no touch tolerance  - (eOS 6 Public Beta)

### ISSUE THREAD

**Issue by Gabriel-AB** [elementary/gala#1141]
## Problem

Currently, any gesture is cancelled if any finger is lifted
When reaching at the corner of the touchpad, one or two fingers may stop touching.

## Proposal

Keep track of the gesture until 2 fingers, if less or equal to 1 touch, stop the gesture. 
That would make the touchpad virtually bigger and ease the use of 4 fingers gestures.

## Prior Art

Windows 10 Gestures

**Comment by JoseExposito** [comment]
elmentary OS uses libinput under the hood for gestures, and that's how gestures are mean to work on libinput:

> A gesture starts when the finger position and/or finger motion is unambiguous as to what gesture to trigger and continues until the first finger belonging to this gesture is lifted.
> https://wayland.freedesktop.org/libinput/doc/latest/gestures.html#lifetime-of-a-gesture

You can try to report this on the libinput bug tracker, but I'm not sure this is something they are interesting in changing.

**Comment by Gabriel-AB** [comment]
I'll try report there, thanks for answering
