### ISSUE TITLE
Misaligned Multitasking View on changing Scaling Factor

### ISSUE THREAD

**Issue by candiedoperation** [elementary/gala#1142]
## What Happened

While changing from LoDPI to HiDPI and reverting the configuration back to LoDPI causes **application windows to become smaller** and **icons in multitasking view really big**.

## Expected Behavior

The expected behavior is the one in elementary OS Hera where, on **changing scaling factor** using switchboard (LoDPI to HiDPI) **and then reverting**, all the **window sizes revert to the original** (or the deafault size) and **multitasking view also has icons of the correct size**.

## Steps to Reproduce

1. Open Display Settings in switchboard
2. Change Scaling Factor from LoDPI (1x) to HiDPI (2x)
3. Click on **Restore Previous Configuration** when the setting confirmation pops up

I've attached few screenshots of every native applications before and after following the above steps
| Before Changing DPI | After Reverting DPI |
| --- | --- |
|![DPI_Issue_Before](https://user-images.githubusercontent.com/47198395/119003283-38e4d880-b9ab-11eb-94c4-89098489a3c0.png)|![DPI_Issue](https://user-images.githubusercontent.com/47198395/119003503-66ca1d00-b9ab-11eb-9b9b-bac154294230.png)|
|![FILES_OLD](https://user-images.githubusercontent.com/47198395/119003589-777a9300-b9ab-11eb-97f1-ad0268c0e5c4.png)|![FILES_NEW](https://user-images.githubusercontent.com/47198395/119003637-82352800-b9ab-11eb-8c9e-93fc29089a65.png)|
|![PDF_OLD](https://user-images.githubusercontent.com/47198395/119003712-92e59e00-b9ab-11eb-8321-38b8d0cdb6d8.png)|![PDF_NEW](https://user-images.githubusercontent.com/47198395/119003682-8bbe9000-b9ab-11eb-8051-052e5d3e51f4.png)|
|![SWITCH_OLD](https://user-images.githubusercontent.com/47198395/119003777-a0028d00-b9ab-11eb-994a-8a9ea5c50cc2.png)|![SWITCH_NEW](https://user-images.githubusercontent.com/47198395/119003798-a5f86e00-b9ab-11eb-8572-529c260cb939.png)|

### Logs

No Logs

## Platform Information

Operating System: elementary OS 6
Edition: (Public Beta)
Hardware Information:
- Quad-Core Intel® Core™ i5-8250U CPU @ 1.60GHz
- Intel® UHD Graphics 620 (Kabylake GT2)
- 7.7 GiB memory
- 467.2 GB storage (SSD)

Laptop Information: HP Pavilion x360

**Comment by JoseExposito** [comment]
Fixed by https://github.com/elementary/gala/pull/1161
