### ISSUE TITLE
Three-finger swiping gesture to switch between active applications

### ISSUE THREAD

**Issue by jh070** [elementary/gala#1143]
Three-finger swiping gesture to switch between active applications like Windows 10.
This is a really handy gesture. EOS currently has the three-finger up swipe that brings up all active applications, but it is tedious, whereas in Windows 10 the three-finger swipe gesture really does the magic.
It will be much appreciated if the EOS team does something about it.

**Comment by JoseExposito** [comment]
Hi and thanks for you feature request.

I believe this was already reported in https://github.com/elementary/gala/issues/979

Closing this one so we can keep track in a single place.
