### ISSUE TITLE
Launching app from terminal when already open on another workspace appears to do nothing

### ISSUE THREAD

**Issue by jeremypw** [elementary/gala#1147]
## Steps to Reproduce

1. Open e.g. Code on one workspace
2. Switch to second workspace
3. Open Terminal and type `io.elementary.code`
4. Code does not open on second workspace nor does the view switch to the first workspace.
5. The only change is an almost invisible alteration in the dock icon for Code

## Expected Behavior

The user should see a Code app window. Either by launching a new window on the current workspace, switching to the workspace containing the Code window or by moving the Code window onto the second workspace.  If there is no obvious "right" answer then I suppose a dialog could be shown.

## Platform Information

elementary 6 daily

**Comment by andreasfelix** [comment]
I think this is not an gala issue but with the [`Gtk.Window.present`](https://valadoc.org/gtk+-3.0/Gtk.Window.present.html) method. Using [`Gtk.Window.present_with_time`](https://valadoc.org/gtk+-3.0/Gtk.Window.present_with_time.html) solves the issue.

**Comment by Blast-City** [comment]
Will this also fix elementary/applications-menu#464?

**Comment by jeremypw** [comment]
Unfortunately the linked PR does not fix this issue on my system. The issue affects all the native elementary apps I've tried so really needs to fixed at a higher level if possible.

**Comment by jeremypw** [comment]
This issue affects ApplicationsMenu as well, but not the dock so may be worth looking into Dock code to see how that launches apps differently.

**Comment by jeremypw** [comment]
I think this comes down to providing an AppLaunchContext at the point the launch is initiated.  This means it is not possible to fix this by patching the apps - by the time they are activated it is too late.  So the ApplicationsMenu issue may be fixable by getting a context from the current display in the same way as Dock.  Not sure this is possible with Terminal though.

**Comment by jeremypw** [comment]
So I am not sure Gala can do anything about this but I will leave this open here for now in the hope that someone more knowledgeable of Gala can offer further information.

**Comment by andreasfelix** [comment]
sorry the PR didn't fix it.

I think the two relevant functions in the dock are:

https://github.com/elementary/dock/blob/9150dd81bc3741d76eefee54993d7fc89d8d0d03/lib/Services/WindowControl.vala#L363
https://github.com/elementary/dock/blob/9150dd81bc3741d76eefee54993d7fc89d8d0d03/lib/Items/ApplicationDockItem.vala#L320

**Comment by leolost2605** [comment]
Fixed by #2041
