### ISSUE TITLE
Will there ever be an "EOSConnect" like kdeconnect or zorinconnect

### ISSUE THREAD

**Issue by KarkanAlzwayed** [elementary/gala#1149]
I honestly didn't know where to post this, but thought it is a bit related to "multitasking". Will there ever be an "EOSConnect" like zorinConnect, KDE connect and apple's airplay on Elementary? I think it would be an amazing addition to the distro. Maybe you don't even need to build it from scratch, just a fork of zorin connect or GSconnect? I am not a dev, so I could be wrong on the last statement. I'd love to know if there are any plans on that in the future.
Thanks

**Comment by tintou** [comment]
Duplicate of https://github.com/elementary/wingpanel/issues/338
