### ISSUE TITLE
Mouse cursor does not seem to abide "scaling factor" when hovering over window edges

### ISSUE THREAD

**Issue by bennothommo** [elementary/gala#115]
I have Elementary installed on a Dell XPS 15 9560 laptop, and am currently using a dock to provide video for two external monitors. The Dell laptop has a 4K resolution screen, but the external monitors run at 1920 x 1200 resolution. Elementary seems to automatically apply a GNOME scaling factor of 2 when initially logging in on the laptop.

I am using the gsettings "scaling-factor" tweak to shrink GNOME to 1x for the external monitors, and everything seems to scale down correctly except for the mouse cursor. The mouse cursor appears to remain at 2x the size, but only when it hovers over any window edges, toolbars or the main applications and indicator bar at the top of the screen. The mouse cursor appears to scale down correctly when it is placed inside the application itself.

I tried to screenshot this using the Elementary OS screenshot tool, however, the mouse cursor appeared fine in the screenshot.

**Comment by nkkollaw** [comment]
Same here. The cursor if minuscule in some situations, and the right size in other.

**Comment by alex285** [comment]
Can you please install gdm3 `apt install gdm3` and then login with gdm3 and test?

**Comment by kyentei** [comment]
When logging in with lightdm, using the pantheon greeter, the scaling seems broken except inside gtk2 applications (such as firefox). Logging in using the lightdm-gtk-greeter seems to fix it, just like using gdm fixes it.

I think the problem is caused by the lightdm pantheon greeter.

Tested on an XPS 13 (9360) using both Fedora and Elementary OS.

**Comment by kyentei** [comment]
using `lightdm-gtk-greeter` fixes the cursor scaling issue.

**Comment by kyentei** [comment]
Possibly related to https://github.com/elementary/greeter/issues/149

**Comment by oscarkraemer** [comment]
I'm using a big 4k monitor with the 'LoDPI' scaling setting, so the huge cursor is really annoying. I can confirm that is possible to bypass the problem by changing the greeter. The drawback is that the lightdm-gtk-greeter is not as pretty as the elementary greeter. This is how I did it:
`# apt install lightdm-gtk-greeter
# echo '[SeatDefaults]
greeter-session=lightdm-gtk-greeter' > /etc/lightdm/lightdm.conf
`
and restart the computer, logging out is not enough,

**Comment by oscarkraemer** [comment]
This change in the greeter fixed the issue for me: https://github.com/elementary/greeter/pull/181

**Comment by bennothommo** [comment]
I've switched distros so I can't test this anymore, but glad to hear it has been fixed.
