### ISSUE TITLE
Ability to use compositor without replacing WM

### ISSUE THREAD

**Issue by coreybruce** [elementary/gala#1168]
Hey just wanted to request a option to just use the compositor without replacing the WM As I just want to be able to use the compositor on Xfce4 and not replace it's WM.

**Comment by davidmhewitt** [comment]
Gala is a compositor and WM as one monolithic component and that's how we use it on elementary OS, so it's unlikely to get changed.

You could however look at the greeter repository as that has a simpler mutter-based "window manager" in the source tree that we're using as pretty much just a compositor and disabling most of the window management functions. You may need to figure out how to adapt it to your needs.
