### ISSUE TITLE
Can't click anything in JavaFX application

### ISSUE THREAD

**Issue by alexgleason** [elementary/gala#1174]
## What Happened
I launched a JavaFX application and am unable to click anything in it. The click goes straight through it to the window below:

https://user-images.githubusercontent.com/3639540/124624286-5f1ee480-de42-11eb-81ed-89a890fa5b58.mp4

I tried with multiple different JavaFX applications, and the same thing happens on all of them. Upstream issue: https://github.com/developersu/ns-usbloader/issues/97

## Expected Behavior
I can click things in a JavaFX application.

## Steps to Reproduce
1. Download [ns-usbloader](https://github.com/developersu/ns-usbloader/releases/tag/v5.0) or any other JavaFX jar
2. `java -jar ns-usbloader-5.0.jar`
3. Try to click the GUI. It clicks the window behind it instead.

## Platform Information
elementary OS 5.1.7 Hera

**Comment by Marukesu** [comment]
That's one more bug caused by `GTK_CSD=1`. You can run the app with `GTK_CSD=0 java -jre ns-usbloader-5.0.jar`.

elementary already stopped to set it on Odin.

**Comment by alexgleason** [comment]
Wow that totally worked, thank you! If it's already fixed, I'll close this then.
