### ISSUE TITLE
Workspace Switching with Keyboard (meta) + Mouse scroll

### ISSUE THREAD

**Issue by kp2401075** [elementary/gala#1178]
## Problem
Moving between workspaces when you're using mouse and keyboard to gather.
Currently the way to do this is wither open multi-tasking view(meta + s) and then move with mouse / scroll with mouse.

## Proposal
Direct switching of workspaces with holding down meta + scroll.
This will greatly improve workflow for those using mouse + keyboard.

## Prior Art
Not sure if any other system implements this.

I've searched through open issues could not find anything matching this.

If it is duplicate please close the issue.
Thanks:)

**Comment by haeckle** [comment]
I (and presumably [others](https://elementaryos.stackexchange.com/q/17870)) totally second this. GNOME Shell has this built in ([Source](https://discourse.gnome.org/t/how-to-disable-super-mousewheel-switching-workspaces/8109/2)). However this will be conflicting #815
