### ISSUE TITLE
Loki. Shutdown Window doesn't get focus when other windows are open or when you press other icons in the wingpanel in an empty workspace..

### ISSUE THREAD

**Issue by Astro-City** [elementary/gala#118]
Hi.  

I don't know if this is a known issue, but this happens in two situations:

Empty desktop: Press shutdown in the wingpanel. You can use the keyboard to select restart, cancel or shutdown.
                         Press applications or another of the wingpanel buttons. The keyboard doesn't work on the shut down window because it doesn't have focus.

Another Windows open: Press shutdown button in the wingpanel.  The keyboard doesn't work on the shutdown window because it doesn't have focus.  

The logout works like it should.

**Comment by ryonakano** [comment]
Duplication of #71
