### ISSUE TITLE
Gala takes 100% cpu when computer is idle

### ISSUE THREAD

**Issue by marcolinuz** [elementary/gala#1186]
## What Happened
I'm running Elementary on my laptop from more than 1 year, the system is a Dell XPS 15 7590 with nvidia graphic.
This issue happens every time I leave the computer doing something like downloading large files and I go away from it.
As soon as the system goes in DPMS (turns off the screen) the fans starts spinning and one core goes to 100% CPU usage.

Using the "top" command as follows into a never ending loop i found that the process "gala" goes to 100% cpu during the idle time.
Command: top -b -d 3 -n 5 | tee -a logfile.txt
Content:
top - 11:18:22 up 21:44,  1 user,  load average: 1,04, 0,88, 0,77
Tasks: 369 total,   2 running, 263 sleeping,   0 stopped,   0 zombie
%Cpu(s):  5,1 us,  2,1 sy,  0,0 ni, 92,4 id,  0,1 wa,  0,0 hi,  0,3 si,  0,0 st
KiB Mem : 32500884 total, 17615640 free,  6776060 used,  8109184 buff/cache
KiB Swap: 33554428 total, 33554428 free,        0 used. 24550348 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 6869 shad0w    20   0 2161812 754864  87140 R 100,0  2,3 942:35.46 gala
22822 shad0w    20   0   69832   4216   3584 R   6,2  0,0   0:00.01 top
    1 root      20   0  225768   9568   6680 S   0,0  0,0   0:02.74 systemd
    2 root      20   0       0      0      0 S   0,0  0,0   0:00.07 kthreadd
    3 root       0 -20       0      0      0 I   0,0  0,0   0:00.00 rcu_gp
    4 root       0 -20       0      0      0 I   0,0  0,0   0:00.00 rcu_par_gp
    6 root       0 -20       0      0      0 I   0,0  0,0   0:00.00 kworker/0:0H-kb
    9 root       0 -20       0      0      0 I   0,0  0,0   0:00.00 mm_percpu_wq
   10 root      20   0       0      0      0 S   0,0  0,0   0:00.54 ksoftirqd/0
   11 root      20   0       0      0      0 I   0,0  0,0   1:02.44 rcu_sched

After that, I ran the following command and waited for it to happen again:
strace -t -T -p {gala's pid} -s 256 -o logfile.txt

And I found that the process literally loops forever thousands of times per second on this system call when it goes at 100% cpu:
13:47:53 sched_yield()                  = 0 <0.000003>

## Expected Behavior
The system continues to run at low cpu usage.

## Steps to Reproduce
1. set system to never suspend
2. Just wait until the system turns off the display
3. The fans stast spinning gala goes to 100% cpu

### Logs
Rilevant lines from logs already showed above.

## Platform Information
elementary OS 5.1.7 Hera
Linux scrat 5.4.0-80-generic #90~18.04.1-Ubuntu SMP Tue Jul 13 19:40:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
GTK 3.22.30
Intel® Core™ i9-8950HK CPU @ 2.90GHz × 6
NVIDIA Corporation GP107M [GeForce GTX 1050 Ti Mobile] (rev a1)
32,5 GB memory
67,1 GB storage

**Comment by lenemter** [comment]
Closing the issue as stale.
