### ISSUE TITLE
Settings schema 'org.gnome.settings-daemon.peripherals.mouse' is not installed

### ISSUE THREAD

**Issue by alucryd** [elementary/gala#1187]
## What Happened
The `org.gnome.settings-daemon.peripherals.mouse` schema is deprecated in Gnome 40 (and is named `org.gnome.settings-daemon.peripherals.mouse.deprecated`). This prevents gala from starting.

## Expected Behavior
Gala should either use the deprecated schema or be updated to use its replacement.

## Steps to Reproduce
1. Install the gala package on Arch Linux
2. Launch gala

### Logs
```
(gala:9025): Glib-GIO-ERROR **: 16:07:21.473: Settings schema 'org.gnome.settings-daemon.peripherals.mouse' is not installed
```

## Platform Information
Arch Linux
gala 6.0.0

**Comment by efectn** [comment]
We are adding old schemas to fix this issue on tearch linux. You can look at https://gitlab.com/tearch-linux/packages/tearch-packages/gnome-settings-daemon/-/blob/master/PKGBUILD. I think eos waits Ubuntu 21.04 for gsd and mutter 40.

**Comment by alucryd** [comment]
Thanks for the link. We try to ship vanilla packages so that's not an option unfortunately. Maybe I will temporarily have gala use the deprecated names though.

**Comment by tintou** [comment]
I don't see where we are using `org.gnome.settings-daemon.peripherals.mouse` though, a complete crash backtrace might give more hint what is actually using it.

**Comment by tintou** [comment]
Looking at https://gitlab.gnome.org/GNOME/gnome-control-center/-/merge_requests/939/diffs#03e22430f38927cdd3251f7160cc241ba56a7192_370_369 `org.gnome.settings-daemon.peripherals.mouse` is replaced by `org.gnome.desktop.peripherals.mouse` which is provided by the `gsettings-desktop-schemas` in archlinux

**Comment by alucryd** [comment]
@tintou Here's a complete strace, hopefully that can shed some light: https://paste.xinu.at/hZ1yztJsi4jnsOso/

The gsettings-desktop-schemas package is installed, in fact the whole gnome environment is already installed on my test VM.

**Comment by tintou** [comment]
@alucryd I don't see where the `org.gnome.settings-daemon.peripherals.mouse` error occurs here, a simple gdb trace with complete symbols would be enough for me

**Comment by alucryd** [comment]
I rebuilt gala with debug symbols and ran it through gdb: https://paste.xinu.at/Ar3aA521dXO09TKT/

Please let me know if I need to rebuild more things with debug symbols, mutter looks like a good candidate.

**Comment by alucryd** [comment]
Same with mutter debug symbols: https://paste.xinu.at/7Y2vqvvmVk8eE0g3/

**Comment by tintou** [comment]
Ah okay, now I see what is going on, you are using Mutter 3.38 with the gsettings-desktop-schemas from GNOME 40 which are not compatible. You best luck would be to have https://github.com/elementary/gala/pull/980

**Comment by alucryd** [comment]
@tintou It's working, thanks a lot!
