### ISSUE TITLE
Three-fingers gesture to open Multitasking View doesn't work if fingers are placed vertically.

### ISSUE THREAD

**Issue by delight-aug** [elementary/gala#1199]
## What Happened

Three-fingers gesture to open Multitasking View doesn't work if fingers are placed vertically. All the other gestures, even closing Multitasking View, work in both ways.

## Expected Behavior

The gesture should work if my fingers are placed vertically, as well as when horizontally.

## Steps to Reproduce

Try opening Multitasking View by swiping up with 3 fingers simultaneously, but fingers should be each on top of the other, like in the photo.

![photo_2021-08-11_08-43-44](https://user-images.githubusercontent.com/51861383/128975845-3215f6f2-1997-409a-bbfc-d3edf3ce2b7e.jpg)

## Platform Information

![Screenshot from 2021-08-11 08 47 41](https://user-images.githubusercontent.com/51861383/128976236-aa54ee48-e665-47bc-912b-4356f8fbe75c.png)

**Comment by hotsezus** [comment]
Cannot reproduce this on my Mi Notebook Pro. It seems like this can be a problem of trackpad in your laptop?

**Comment by delight-aug** [comment]
Now, as I tried to do it more, they seem to actually work, but it starts capturing the gesture too late, and so I have too little travel distance. Or not. Anyway, it's easier to bend fingers than to understand this issue.
