### ISSUE TITLE
Tooltips that appear near the edge of the screen are drawn on two monitors

### ISSUE THREAD

**Issue by Extravert-ir** [elementary/gala#12]
Tooltip should not spread to several displays (see image, this is a border between two displays).
It must be wholly drawn on the display that 'called' it
![screenshot from 2017-05-23 23-13-43](https://cloud.githubusercontent.com/assets/961957/26374402/ea40ed38-400d-11e7-90d1-66eab97358fd.png)

**Comment by cassidyjames** [comment]
I'm not sure if we have control over this in Gala, it may be an upstream GTK bug.

**Comment by lenemter** [comment]
Closing because gala doesn't control tooltips' position.
