### ISSUE TITLE
after waking from sleep  & logging in screen is black

### ISSUE THREAD

**Issue by stem2580** [elementary/gala#1200]
## What Happened
after waking device from sleep and  logging in this is what happens:

{video soon}

& as you see when using touchpad gestures it displays the multi tasking view but after clicking app or closing it with the gestures it returns to be black

## Expected Behavior
i should be able to see the windows and interact with them.

## Steps to Reproduce

1.close laptop lid to make laptop sleep
2.open the lid and login
3.black screen appears

## Platform Information
elementary OS 6 Odin (downloaded from site when it released yesterday)
Linux 5.11.0-25-generic

Dual-Core Intel® Core™ i3-1005G1 CPU @ 1.20GHz

**Comment by tomaswarynyca** [comment]
Duplicated #1126

**Comment by stem2580** [comment]
> Duplicated #1126

sry, i'll close it
