### ISSUE TITLE
Dock when alternating windows doesn't follow system theme

### ISSUE THREAD

**Issue by marcelovbcfilho** [elementary/gala#1207]
## What Happened

I'm using the default auto change theme in Desktop settings, but when the theme change the dock on the botton when using 
ALT +TAB, isn't following the system theme, only after a restart the dock changes to the system theme.

Image 1 - Showing that the system is configured to "Default" theme
![Screenshot from 2021-08-13 09-15-35](https://user-images.githubusercontent.com/51462138/129356063-1d76d420-144d-4e8e-8c6c-5d509a6d5009.png)

Image 2 - Showing that even I'm using the "Default" theme the ALT-TAB dock isn't following it
![Screenshot from 2021-08-13 09-15-22](https://user-images.githubusercontent.com/51462138/129356606-a7ab8ae2-dcc3-4069-944d-9b497d306214.png)

 
## Expected Behavior

The expected behavior was that the dock should follow the system theme after change, and not only after system restart.

## Steps to Reproduce

1. Change the theme from "Default" to "Dark" or vice versa
2. Have more than 1 window openned
3. Use ALT + TAB to alternate windows.

## Platform Information

Elementary OS 6 stable release.

**Comment by cassidyjames** [comment]
This is not relevant anymore with the new window switcher.
