### ISSUE TITLE
dragging and dropping to another window

### ISSUE THREAD

**Issue by i74ifa** [elementary/gala#1212]
## What Happened

If you drag a file from another window using the shortcut `Alt+tab`

The shortcut will freeze after I lift my finger from the buttons `Alt+tab`

## Expected Behavior

Window freeze similar to what happens when switching between windows

### Logs

![GitHub Logo](https://i.postimg.cc/ZqMq1rx1/Screenshot-from-2021-08-16-12-47-36.png)

## Platform Information

elementary os 6 Odin

**Comment by lenemter** [comment]
I guess it was fixed in #1234.
