### ISSUE TITLE
Is not possible to use drag and drop with Alt+Tab

### ISSUE THREAD

**Issue by Maccer1** [elementary/gala#122]
This issue affects all apps (I've checked that it happens on pantheon-files, firefox, chrome, gimp, vlc...).

I've made [a video](https://gfycat.com/gifs/detail/WarmFlawedAyeaye) to explain the issue. Basically what I'm trying to do is selecting 3 files, dragging them with the mouse, then pressing Alt+Tab and dropping them in another window of `pantheon-files`. As you see, it doesn't work. Somehow it gets stuck in the Alt+Tab animation and doesn't paste the files.

However, when I copy the files (right click> copy), press Alt+Tab and paste them; it works as it should.

**Comment by janxkoci** [comment]
Does this even work in other DEs? I'm not home now, but tomorrow I could check Gnome in Ubuntu on my other laptop.. Just currious, I never thought of interacting with desktop this way..

**Comment by carn1x** [comment]
This kinda works in 5.0/Juno however it acts very strangely. You can begin dragging a file and then press Alt-Tab to switch to the next app. If you Alt-Tab twice to switch to the 3rd app it works but immediately disengages the Alt-Tab interface despite whether you continue to hold Alt button down. There is no way to Alt-Tab to the 4th app in the queue when dragging.

I've also found that dragging a single file is fairly reliable, however dragging 2+ files seems to cause really strange behaviour when you drop it, I've had the entire UI lock up or apps lock up as a result of this, or sometimes simply not work. My usual case is dragging files to Thunderbird for attachments, but often other cases too.

**Comment by Maccer1** [comment]
It doesn't work for me on Juno. Did you see the video I've linked on the top post? Does it behave any different?

**Comment by Maccer1** [comment]
So now I've been trying this again. It kinda works but gets stuck many times. 
What I've found:

* **Dragging one or more files causes the Alt+Tab animation to stop on the third window.** This is what @carn1x said as well.
Normally, when you press Alt+Tab and release Tab while holding Alt you'll see the icons of the apps that are open on the bottom bar and you can cycle between them. However, if you are dragging anything this doesn't happen. The animation just disappears after the third window (the third time you press Alt+Tab). If you press Alt+Tab again you can continue switching between those 3 windows but not the rest of the windows that you have opened.

* **Drag and drop with Alt+Tab works between those 3 windows.** However you can only do it with the first and third window. This means that you'd need to press Alt+Tab 4 times to drop something on the second window (instead of one).

* **UI lockup when dragging something to the second  Alt+Tab window.** As I said earlier, drag and drop with Alt+Tab just works between the first and third window. If you just press Alt+Tab once you'll get a lockup. You'd need to press Alt+Tab again to get out of the lockup.

* **Drag and drop works with any number of files**. I didn't face any special issue regarding the number of files that I've tried to drag.

**Comment by janxkoci** [comment]
BTW much to my surprise it works *flawlessly* with Super+Tab (i.e. dragging between workspaces) - really cool :wink: .

**Comment by lenemter** [comment]
Seems to be fixed in #1234.
