### ISSUE TITLE
Multitasking View Wallpaper not shown in the primary monitor

### ISSUE THREAD

**Issue by Hedronmx** [elementary/gala#1221]
## What Happened
Everytime I activate the multitasking view, the wallpaper on the primary monitor is not shown, it either has a solid white or solid gray as a background

## Expected Behavior
To correctly display the currently assigned wallpaper

## Steps to Reproduce

1. Open Multitaskingview
2.Wallpaper not displayed correctly

![Screenshot from 2021-08-20 08 29 13](https://user-images.githubusercontent.com/26935602/130257423-90dab60e-dada-4349-9778-e8dcd1d24f84.png)

## Platform Information
![Screenshot from 2021-08-20 08-32-38](https://user-images.githubusercontent.com/26935602/130257413-0ed8494b-38b9-4ad8-9ac6-3abeccf07a5b.png)

**Comment by leolost2605** [comment]
There was quite some refactoring going on here a while ago so I think it's pretty safe to assume this is fixed?
