### ISSUE TITLE
[Odin] YouTube video played in fullscreen (Epiphany, Chrome, Firefox) prevents Alt+Tab from switching tasks on same desktop

### ISSUE THREAD

**Issue by dennismayr** [elementary/gala#1223]
## What Happened
When YouTube video is played in fullscreen mode (Epiphany, Chrome, Firefox), _Alt+Tab_ only shows *that* window, and it's impossible to switch to other open applications on same desktop unless exiting fullscreen-mode.

Current situation:
If I'm watching a programming tutorial and I need a terminal window, a browser window, and the IDE window available at the same time to navigate between them, watching the video in fullscreen doesn't allow me to switch tasks.

## Expected Behavior
Watching the video in fullscreen allows me to switch tasks, just like in GNOME, KDE, or XFCE. App windows can overlap the fullscreen video canvas.

## Steps to Reproduce

1. Open any text editor
2. Open a terminal window
3. Open any browser
4. Go to [YouTube](https://www.youtube.com)
5. Play any video, enter fullscreen mode
6. Try switching tasks with _Alt-Tab_

## Platform Information
* Elementary OS 6, Odin - kernel _5.11.0-27-generic_
* Browsers: Epiphany, Chrome 92, Firefox 91
* Hardware: ThinkPad-T410s
* Processor: Intel® Core™ i5 CPU 540M  @ 2.53GHz
* Video hardware: Intel® Ironlake Mobile + NVIDIA Corporation GT218M [NVS 3100M] (Optimus)
* Video drivers: `i915` `(modeset=1)` as primary display, `nouveau` (headless) as DRI_PRIME backend
* Memory: 7,6 GiB

**Comment by cassidyjames** [comment]
By default, fullscreen apps move to their own workspace, and Alt+Tab switches between windows on the current workspace. You can turn off the former in **System Settings** → **Desktop** → **Multitasking**.

**Comment by dennismayr** [comment]
Duly noted, chief.
Thanks for the heads-up!
