### ISSUE TITLE
Support minimizing apps that run in the background when pressing the Close button

### ISSUE THREAD

**Issue by divmgl** [elementary/gala#1224]
I opened a Reddit thread to summarize my problem before I knew how the internals of Elementary worked. I'll also post it here because I think it deserves visibility.

https://www.reddit.com/r/elementaryos/comments/paatjd/request_apps_should_have_a_minimize_button_if_the/

## Problem

Almost all of the applications I use need to run in the background, and "closing" them merely means minimizing them to the system tray. To give you some examples: Telegram, Slack, Discord, Steam, 1Password, etc. All of these applications have interfaces that can be closed but they all run in the background.

ElementaryOS closes these processes when you press the Close button on the top left. This means that every time you want to use one of these apps, the app has to boot up again. This breaks several things:

* Slack doesn't stay open, so I don't get notifications
* I have to type in my 1Password password over and over again
* ~I mistakenly close Steam when I want to download games in the background~ looks like Steam actually works as intended, but it doesn't use the system window manager, it has its own UI.

This is a pretty big usability miss and both MacOS and Windows don't behave this way. Let me know if you need any more details, thanks.

## Proposal
Support APIs that allow developers to specify what the close button should do.

**Comment by Blast-City** [comment]
Hi.

I've wondered if the close button on windows should just minimize the app and for quitting an user would use the dock icon. This creates a problem when apps use multiple windows, thought.

In the meantime, have you thought of letting the windows open on other workspaces? This way, if you get a notification just switch the workspace.

**Comment by cassidyjames** [comment]
The fundamental issue here is that _there are already APIs for this_, and in fact, several of the apps you listed work this way today on elementary OS, at least in their Flatpaks.
- Slack stays running in the background when I hit the "Close" button, and sends notifications when messages are sent to me
- I don't use 1Password, but Bitwarden (a similar password manager) has an option to keep running in the "system tray," and checking that enables it to run in the background regardless.

In fact, native apps like AppCenter, Web, and Music stay open in the background when it makes sense, like when installing updates, downloading a file, or actively playing music. The same APIs are available to all app developers.

Given that, I think the actual issues that need to be filed here are against the apps you're using that are misbehaving.
