### ISSUE TITLE
ALT + tab switching menu is in wrong spot

### ISSUE THREAD

**Issue by nkkollaw** [elementary/gala#123]
When switching open apps with alt+tab, menu showing apps you can switch to is shown in Plank.

While this might look like a cute effect, it's pretty unusable in day-to-day use. While I'm working I'm always staring at the middle of the screen, not at the dock. When switching apps I would therefore expect the menu to be shown in the middle of the screen, and not in the dock.

In addition, the dock changes its purpose and look, there are multiple icons if an app has multiple windows open, and it becomes super-small on HiDPI displays.

I would personally prefer leaving the dock how it is, and showing a more traditional menu in the middle of the screen.

**Comment by SneWs** [comment]
I'd second this. It's highly confusing that the dock becomes the window switchers visual representation. I would love to see a similar impl. as is found in macOS where you get big icons centered on the primary screen representing the apps one can switch between.

IMHO, the switcher should by default include all open application windows from all work spaces. It just adds to the confusion when a window from another workspace isn't represented when one ALT+TAB.

**Comment by nkkollaw** [comment]
Forget it, they've already said they will never change it.

elementary OS are pretty set into their ideas--which is great--but often those ideas don't make a lot of sense.

**Comment by hakanersu** [comment]
I tried elementary os at least 3-4 times over the years, every experience was great except alt-tab behaviour. And everytime i switched back to another linux distro just for this problem. After reading this issue and related other ones it seems they wont change this behaviour.

**Comment by jeremypw** [comment]
There does not seem to be a documented @elementary/ux opinion on this in the bug tracker and is has not been marked "Design Conflict" so I'll flag for an opinion.
