### ISSUE TITLE
Firefox close and maximize button misplaced

### ISSUE THREAD

**Issue by Zoldyako** [elementary/gala#1236]
## What Happened
In Firefox, the close and maximize button are misplaced in the top left corner. I have reported [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1727991) to mozilla bug tracker and they asked me to file a issue here fist to be sure it's not a problem with eOS window manager.

## Expected Behavior
The buttons should be properly placed as any elementary app. 

e.g of Firefox misplaced buttons vs Chrome showing the buttons correctly:
![image](https://user-images.githubusercontent.com/52394177/131385171-6e26474d-10a7-411d-820b-0cdf91b576cc.png)

This [eOS theme for Firefox](https://github.com/Zonnev/elementaryos-firefox-theme) custom CSS place the close/maximize buttons correctly, so it is possible to do, just don't know if it is a problem in Gala or Firefox.

## Steps to Reproduce

1. Install Firefox
2. Open Firefox

## Platform Information
eOS 6 Odin
Firefox 91.0.2, Mozilla Firefox for Ubuntu (I tested and Flatpak and Snap version have the same problem)
PC: [Intel i3 7100](https://www.intel.com.br/content/www/br/pt/products/sku/97455/intel-core-i37100-processor-3m-cache-3-90-ghz/specifications.html) Gráficos HD Intel® 630 - 8gb Ram - 1T HD

**Comment by cassidyjames** [comment]
This is a bug in Firefox; elementary OS does not and cannot control the client-side window button positioning of apps.

**Comment by Zoldyako** [comment]
Thanks for respond so quickly Cassidy! Have a great day 🙏
