### ISSUE TITLE
Navigate with arrow keys while holding ALT+TAB

### ISSUE THREAD

**Issue by nkkollaw** [elementary/gala#124]
There should be a way to navigate with arrow keys while holding ALT+TAB while on the exposed view, that you can navigate left and right between open apps before you pick the one you want.

Many times I pass the app I want and clicking on the left arrow would be a lot better than reaching for the mouse/trackpad.

**Comment by Maccer1** [comment]
I think they are working on that already: 
https://github.com/elementary/gala/issues/72

**Comment by nkkollaw** [comment]
That's more of an alternative to the current approach, this issue would only be about adding the arrow key behavior to the current solution.

**Comment by cassidyjames** [comment]
This sounds sane to me; if we're showing a left-to-right UI element on the screen, it would be reasonable to expect the left- and right-arrow keys to navigate it.
