### ISSUE TITLE
Option to limit the number of virtual workspaces or a switch to disable workspaces

### ISSUE THREAD

**Issue by vbuell** [elementary/gala#1240]
## Problem
The way virtual workspaces work right now is sometimes confusing: some applications tend to open up on some random workspace (also see the reddit link below).

## Proposal
There should be a way to disable or limit the number of workspaces to some constant number. That would be a life saver for ppl who don't usually use workspaces but suffer from this problem.

A previous discussion on Reddit:
https://www.reddit.com/r/elementaryos/comments/iymxtp/disablling_virtual_workspaces/

**Comment by cassidyjames** [comment]
Since that has been posted, we've added options to System Settings → Desktop → Multitasking. You can disable the move-on-fullscreen behavior which I believe is the root of the original issue, and then you can just ignore workspaces altogether if you prefer.

**Comment by vbuell** [comment]
Thanks Cassidy. It works fine now move-on-fullscreen checkbox disabled.
Closing the issue.
