### ISSUE TITLE
Clutter.Color broken since Mutter 41 compatibility patch

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/gala#1243]
Since #1228, `Clutter.Color.from_string` does not work _for all versions of Mutter_. So, even if we compile Gala against our current version of Mutter on Odin.

This breaks things like the ScreenShield as it can't set a black color for itself, and probably anywhere else where we use `Clutter.Color`.

I think removing `color_from_* skip` from `Clutter-9.metadata` and letting `vapigen` generate those methods (and of course reverting the changes to Gala) should work, but I don't have enough of an environment set up to test these changes on all versions of Mutter.

However, this is a release blocker, **do not release another version of Gala until this issue is resolved**

**Comment by tintou** [comment]
@davidmhewitt Can you give more details on what is broken, it doesn't seem obvious from here

**Comment by davidmhewitt** [comment]
Doing

```
var color = Clutter.Color ();
color.from_string ("black");
```

isn't actually setting the color on the `color` object.

You can test this by locking the screen and you will see that it no longer fades to black like it used to and you can still see the contents of the screen until you move the mouse and it goes back the lock screen.
