### ISSUE TITLE
Offset Border around Desktop

### ISSUE THREAD

**Issue by jpgleeson** [elementary/gala#1281]
### What Happened?

There’s a small border on the left, and top and bottom of my screen. The left border is ~2x the size of the top and bottom, so this may be a positioning error somewhere.

I’m running a daily pinebook pro image, with the latest updates. The image itself is probably 2-3 weeks old at this point, so may be an old kernel, but I only noticed this today after updates yesterday.

![19BDA741-935D-417A-90B8-7F502A78DDD3](https://user-images.githubusercontent.com/227077/139496787-4eebd9fa-4d6e-4593-b482-21d7d52da743.jpeg)

### Steps to Reproduce

Boot into elementary. Desktop immediately shows black border to top, left and bottom.

### Expected Behavior

No border or consistent borders.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by cassidyjames** [comment]
@jpgleeson I think that is the actual physical border of the display; Gala doesn't do any sort of overscan correction afaik. I can see something similar on my Slimbook where there's slightly more of a black border on the left side of the display than the right, and that's just due to production tolerances.

**Comment by cassidyjames** [comment]
(Correct me if I'm wrong and we can re-open or move this issue to investigate further!)

**Comment by davidmhewitt** [comment]
My Pinebook is the same and it's definitely hardware/production issue. In fact, in certain lighting, you can see the border between active pixels and black display "border", even when the display is off. The two parts are a slightly different colour/texture.
