### ISSUE TITLE
Attempting to move parent of modal child moves child off screen

### ISSUE THREAD

**Issue by cassidyjames** [elementary/gala#1286]
### What Happened?

If you have a window with a modal dialog and try to move the parent, it moves the child way off to the right of the display.

### Steps to Reproduce

1. Open an app with a modal dialog, e.g. Music
2. Open the modal dialog (e.g. Preferences)
3. Attempt to move the parent window

### Expected Behavior

Either moving the window shouldn't be possible, or more likely, it should move the parent and the child dialog in sync.

### OS Version

6.x (Odin)

### Software Version

Compiled from git

**Comment by lenemter** [comment]
Fixed in OS 7

**Comment by Marukesu** [comment]
i still can reproduce this with terminal and code modal dialogs.
