### ISSUE TITLE
Selected wallpaper is not applied 

### ISSUE THREAD

**Issue by x1unix** [elementary/gala#13]
This issue is redirected from https://github.com/elementary/switchboard-plug-pantheon-shell/issues/61#event-1094577982.

Hardware acceleration and virtualization are enabled.
Video memory: 768 MB.

**Comment by Nine-H** [comment]
this has been happening to me too.

**Comment by Nine-H** [comment]
steps to reproduce:
1. plug in external vga monitor while running.

I'm curious what happens with hdmi and multi-monitor setups.

**Comment by nkkollaw** [comment]
I was actually never able to set one in Loki (ok in Freya), even without a monitor attached.

**Comment by jlnr** [comment]
I've had it happen both in VMware Fusion, but also in my native/real installation that uses the proprietary Nvidia drivers.

**Comment by cassidyjames** [comment]
This seems to be remedied by restarting Gala. It's like Gala stops properly updating the wallpaper, no matter which source you're setting it from. I've seen this when switching displays (plugging/unplugging a monitor), but not reliably enough to track it down.

**Comment by x1unix** [comment]
Have to check it this issue is applicable to the latest EOS release.

**Comment by rugglcon** [comment]
@x1unix this is confirmed an issue on the latest release

**Comment by J0Ar** [comment]
This is really a weird bug...
I saw this bug report and tried myself to change the wallpaper...and came to this...
https://streamable.com/s4ily

(do not know if this works with the video upload...if anybody know a better alternative...tell me!^^ Produced GIF was too big =/ )

**Comment by rugglcon** [comment]
That happens to me sometimes as well.

**Comment by peteruithoven** [comment]
> This seems to be remedied by restarting Gala.

This can be easily done by executing `gala -r` in the Applications menu.

@donadigo do you perhaps know the chain of events of how this should happen? Is it just Gala? If Gala is responsible I'd love to add some logging so that we can check journalctl afterwards.

**Comment by donadigo** [comment]
I'm not really into wallpaper code for gala, but what I do know is I've experienced some issues as well with changing them. Sometimes gala even crashes. I'm pretty sure it is an issue within gala though.

There's a report with some logs above, with a method that fails an assertion, maybe we should look at the produced C code and go into that direction.

**Comment by peteruithoven** [comment]
The logs from other (duplicate) issues:

Using Desktop system settings, syslog:
```
Aug 14 10:30:16 Latitude-E5470 gnome-session[1671]: (switchboard:11912): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name
Aug 14 10:30:16 Latitude-E5470 gnome-session[1671]: (switchboard:11912): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name
Aug 14 10:30:16 Latitude-E5470 gnome-session[1671]: (switchboard:11912): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
Aug 14 10:30:20 Latitude-E5470 gnome-session[1671]: ** (gala:1891): WARNING **: Preferences.vala:192: '/usr/share/themes/elementary/plank/dock.theme' is read-only!
Aug 14 10:30:27 Latitude-E5470 gnome-session[1671]: (gala:1891): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Aug 14 10:30:59 Latitude-E5470 gnome-session[1671]: message repeated 15 times: [ (gala:1891): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed]
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: FileEnumerator.vala:39: Looking up contracts in: /home/davidak/.local/share/contractor
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** (process:12011): WARNING **: FileEnumerator.vala:60: Could not process directory '/home/davidak/.local/share/contractor': Error opening directory '/home/davidak/.local/share/contractor': No such file or directory
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: FileEnumerator.vala:39: Looking up contracts in: /usr/share/pantheon/contractor
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** (process:12011): WARNING **: FileEnumerator.vala:60: Could not process directory '/usr/share/pantheon/contractor': Error opening directory '/usr/share/pantheon/contractor': No such file or directory
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: FileEnumerator.vala:39: Looking up contracts in: /usr/local/share/contractor
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** (process:12011): WARNING **: FileEnumerator.vala:60: Could not process directory '/usr/local/share/contractor': Error opening directory '/usr/local/share/contractor': No such file or directory
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: FileEnumerator.vala:39: Looking up contracts in: /usr/share/contractor
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: ContractSource.vala:65: Contract file '/usr/share/contractor/set-wallpaper.contract' loaded successfully.
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: ContractSource.vala:65: Contract file '/usr/share/contractor/file-roller-compress.contract' loaded successfully.
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: ContractSource.vala:65: Contract file '/usr/share/contractor/file-roller-extract-here.contract' loaded successfully.
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: ContractSource.vala:65: Contract file '/usr/share/contractor/gnome-bluetooth.contract' loaded successfully.
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: ContractSource.vala:65: Contract file '/usr/share/contractor/mail-attach.contract' loaded successfully.
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: ContractSource.vala:65: Contract file '/usr/share/contractor/print.contract' loaded successfully.
Aug 14 10:31:30 Latitude-E5470 org.elementary.Contractor[1744]: (set-wallpaper:12017): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name
Aug 14 10:31:30 Latitude-E5470 org.elementary.Contractor[1744]: (set-wallpaper:12017): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name
Aug 14 10:31:30 Latitude-E5470 org.elementary.Contractor[1744]: (set-wallpaper:12017): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
Aug 14 10:31:31 Latitude-E5470 gnome-session[1671]: ** (gala:1891): CRITICAL **: gala_background_manager_swap_background_actor: assertion '_tmp0_ != NULL' failed
Aug 14 10:31:31 Latitude-E5470 gnome-session[1671]: message repeated 3 times: [ ** (gala:1891): CRITICAL **: gala_background_manager_swap_background_actor: assertion '_tmp0_ != NULL' failed]
Aug 14 10:31:32 Latitude-E5470 gnome-session[1671]: (gala:1891): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Aug 14 10:31:32 Latitude-E5470 gnome-session[1671]: (gala:1891): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: (tumblerd:11985): GdkPixbuf-CRITICAL **: gdk_pixbuf_new: assertion 'width > 0' failed
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: (tumblerd:11985): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: (tumblerd:11985): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: (tumblerd:11985): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: (tumblerd:11985): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: (tumblerd:11985): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: (tumblerd:11985): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: **
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: tumbler-poppler-thumbnailer:ERROR:poppler-thumbnailer.c:362:poppler_thumbnailer_create: assertion failed: (pixbuf != NULL)
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: BAD status: invalid value (typically too big) for the size of the input (surface, pattern, etc.)
```

When using Set as Desktop Background in Files:
```
Jul 10 23:04:28 io.elementary.c[2613]: set-wallpaper.vala:161: Error removing file /home/helder/.thumbnails: Directory not empty
Jul 10 23:04:28 io.elementary.c[2613]: set-wallpaper.vala:207: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Método “SetBackgroundFile” inexistente
Jul 10 23:04:28 gala[1754]: gala_background_manager_swap_background_actor: assertion '_tmp0_ != NULL' failed
Jul 10 23:04:28 gala[1754]: gala_background_manager_swap_background_actor: assertion '_tmp0_ != NULL' failed
Jul 10 23:04:28 gala[1754]: gala_background_manager_swap_background_actor: assertion '_tmp0_ != NULL' failed
Jul 10 23:04:29 gala[1754]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jul 10 23:04:29 gala[1754]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

Some interesting observations from @rugglcon:
>  it stops and starts working unexpectedly, both via command line and with the Files app and with Switchboard.

>I looked with dconf-editor if the background setting was set to the correct picture after I change the background, and it is, and it has been copied to ~/.local/share/backgrounds. My lock screen changed, but the main desktop background did not. I restarted my machine and then the correct background was displayed. I was able to set my background a few times before it stopped working again. 

>  I copy the file to ~/.local/share/background manually and then try and set the background via command line, doesn't work. HOWEVER the file then shows up in Switchboard -> Desktop, and when I click it there it sets the background correctly and the lock screen. The command line seems to be really hit or miss. So long story short, this seems to be a gnome desktop issue and not strictly a Files issue

> I think I found how to reproduce the problem. On my laptop, after a restart I'm able to set my desktop background as many times as I want just fine. However, if I put it to sleep a few times and wake it up from sleep, then I'm no longer able to set the background. I'm not sure where to report this issue.

**Comment by peteruithoven** [comment]
So I'm pretty sure this is the interesting line: 
```
** (gala:1891): CRITICAL **: gala_background_manager_swap_background_actor: assertion '_tmp0_ != NULL' failed
```
And that's probably triggered on this line: 
https://github.com/elementary/gala/blob/master/src/Background/BackgroundManager.vala#L67

But how could such a line trigger such an error?

**Comment by peteruithoven** [comment]
Looks like I can easily reproduce this issue by plugging in my projector. 

Looks like that triggers this monitor changed callback: https://github.com/elementary/gala/blob/master/src/Background/BackgroundSource.vala#L46-L62 which disconnects it from background changes. It needs this connect though to notice that the picture-uri settings change.  
Now that change happens, it's noticed by a Background instance, but nobody is listening anymore.

**Comment by queeup** [comment]
I can reproduce this issue with suspending my laptop overnight. (Suspending short period of time not triggering this issue)

After waking from suspend I can't change my wallpaper from gsettings or system settings app.

**Comment by peteruithoven** [comment]
I'm going to look into this a bit more and share some information / updates in this comment.

The code is quite hard to get into, so I created a sort of UML class diagram of the relevant bits:

![Gala background uml](https://user-images.githubusercontent.com/523210/59934944-00e65b00-944d-11e9-9101-14ae14b4af50.png)
