### ISSUE TITLE
Urgent bug fix needed for 5.15 mainline generic kernel users causing system to freeze on boot for Elementary OS 6

### ISSUE THREAD

**Issue by skulldealer** [elementary/gala#1300]
### What Happened?

Hello,
Please take a look at https://github.com/hamadmarri/TT-CPU-Scheduler/issues/3 where xanmod devs have found out a serious conflict between Elementary os 6 and mainline generic 5.15 kernel which causes random freezing as soon as os is booted. (it has nothing to do with xanmod kernel).
It would be great if you could fix it as this issue is specific to elementary os  6 and not specific to ubuntu. This will allow users to atleast test 5.15 because right now the kernel is unusable due to system freezing at boot.
You may have to anyways adress this before February 2022 when 20.04 will move to 5.15.

### Steps to Reproduce

1. get mainline generic 5.15 version.
2. start mutitasking workflow quickly like changing workspaces with super+arrow,super+down,super+A, type a lot and scroll the web. Usually soon after booting.
3. Or just wait for system to freeze in few minutes after booting. 

### Expected Behavior

Shouldn't have happened

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
Nov  7 07:16:29 localhost kernel: [   72.155890] io.elementary.g[5855]: segfault at 5 ip 00007fe4e145211f sp 00007ffc68d0bc60 error 4 in libgtk-3.so.0.2404.16[7fe4e11e0000+36f000]
Nov  7 07:16:29 localhost kernel: [   72.155930] Code: 56 41 55 41 54 55 53 48 85 ff 0f 84 db 00 00 00 48 89 fd 49 89 f4 41 89 d5 e8 2d fb ff ff 48 89 c6 48 8b 45 00 48 85 c0 74 05 <48> 39 30 74 10 48 89 ef e8 34 cb d9 ff 85 c0 0f 84 ac 00 00 00 4d
Nov  7 07:16:33 localhost kernel: [   75.480055] io.elementary.g[7126]: segfault at 5 ip 00007fed0249c11f sp 00007ffe154f2f90 error 4 in libgtk-3.so.0.2404.16[7fed0222a000+36f000]
Nov  7 07:16:33 localhost kernel: [   75.480092] Code: 56 41 55 41 54 55 53 48 85 ff 0f 84 db 00 00 00 48 89 fd 49 89 f4 41 89 d5 e8 2d fb ff ff 48 89 c6 48 8b 45 00 48 85 c0 74 05 <48> 39 30 74 10 48 89 ef e8 34 cb d9 ff 85 c0 0f 84 ac 00 00 00 4d
Nov  7 07:16:42 localhost kernel: [   84.512718] rfkill: input handler disabled
Nov  7 07:19:14 localhost kernel: [  236.659664] rfkill: input handler enabled
Nov  7 07:19:14 localhost kernel: [  236.680879] dbus-daemon[7426]: segfault at 0 ip 00007fc0eb0f90d7 sp 00007ffd67563148 error 6 in libdbus-1.so.3.19.11[7fc0eb0d5000+2e000]
Nov  7 07:19:14 localhost kernel: [  236.680915] Code: 44 00 00 48 89 d6 e9 58 fe ff ff 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 48 8b 46 08 48 39 f0 74 43 48 8b 16 48 89 42 08 48 8b 16 <48> 89 10 48 39 37 74 11 48 c7 46 08 00 00 00 00 48 c7 06 00 00 00
```

### Hardware Info

no nvidia gpu, integrated gpu, few years old intel cpu, very regular hardware setup

**Comment by JoseExposito** [comment]
I'm running 5.15 and I'm not experimenting any issues.

Well, my AMD GPU driver throws a bunch of errors, but it is unrelated and it is not causing any problem.

Could you share your kernel config? I'll give it a try.

I need to read the other bug report with more time but, any conclusions about what is causing the problem?

**Comment by skulldealer** [comment]
Sorry, recently found out that the problem I am facing is not related to elementary os 6.
Thank You
