### ISSUE TITLE
Proper support for minimizing all/show dekstop

### ISSUE THREAD

**Issue by ChildishGiant** [elementary/gala#1302]
### Problem

Currently there is half-baked support for this feature (it's possible to control this using wmctrl but there are no animations and if a notification is received it's impossible to get the old windows back up except manually). Currently I have [a script](https://gist.github.com/ChildishGiant/f751ea2860477eff819c8aa6f0c5e923) that I have called on a hot corner and keyboard shortcut to allow toggling this. I have had a cursory look at implementing this but have no clue where in the 10k lines controls this or how to do it properly instead of bodging it.

### Proposal

Fully implement show desktop, preferably with a slick animation. This would allow users to set a keyboard shortcut or hot corner to toggle show desktop without touching the command line.
![image](https://user-images.githubusercontent.com/13716824/140798599-608c985a-31d2-42aa-a855-4e9fa4f55d48.png)

### Prior Art (Optional)

https://youtu.be/uPFK-QC3kTY?t=28

Hard to find videos of this online but Mac OS seems to slide all windows under the header bar.

**Comment by hanaral** [comment]
But there *isn't* a desktop to show.
I'd say this is a design conflict unless there is utility that I'm not seeing

**Comment by ChildishGiant** [comment]
Ah, so I use this for if I want to quickly minimise all my apps if someone is coming in. It's more about minimising and restoring all the apps than showing the desktop but that's what most DEs call it

**Comment by hanaral** [comment]
Would the 'Switch to new workspace' shortcut (super + End) achieve the same thing if it's to hide screen contents?

**Comment by ChildishGiant** [comment]
Not on multiple screens, no.

**Comment by hanaral** [comment]
This still seems like a completely roundabout solution for your use-case - wouldn't a 'blank screen' multitasking shortcut be better?

**Comment by danirabbit** [comment]
Yeah, Pantheon is built around workspaces, not minimize. Closing as "Design conflict" since we don't support a minimize concept and there's nothing to minimize to
