### ISSUE TITLE
“Does the display look OK?” dialogue box layout and colour scheme issue

### ISSUE THREAD

**Issue by aral** [elementary/gala#1306]
### What Happened?

The “Does the display look OK?” dialogue box:

  1. Doesn’t use the system colour scheme.
  2. Wraps its label oddly.

![Screenshot from 2021-11-12 10-07-31@2x](https://user-images.githubusercontent.com/41798/141450717-9b1cdd3c-7165-4933-a43f-8f1507972cf2.png)

### Steps to Reproduce

1. Change a display setting.

### Expected Behavior

The dialogue should use the system colour scheme.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
n/a
```

### Hardware Info

n/a

**Comment by cassidyjames** [comment]
@JoseExposito @donadigo same question as #1282; any idea if this is something we can provide our own dialog for?

**Comment by davidmhewitt** [comment]
There's no reason why this dialog couldn't run in a separate DBus-activated GTK process, like the window menus do.

**Comment by Marukesu** [comment]
> There's no reason why this dialog couldn't run in a separate DBus-activated GTK process, like the window menus do.

In that case, should a generic `show_dialog ()` function on gala deamon begin enough for this and #1282?

**Comment by JoseExposito** [comment]
Yes, at least for this issue replacing `Meta.Util.show_dialog ()` with our custom dialog in Gala daemon should be enough.

https://github.com/elementary/gala/issues/1282 is a bit different though, we'd need to implement Mutter's `meta_plugin_manager_create_close_dialog` callback. That'd also allow us to improve a bit the design of the close dialog.

Are you going to implement it @Marukesu? Or should I look into it?

**Comment by Marukesu** [comment]
> Yes, at least for this issue replacing `Meta.Util.show_dialog ()` with our custom dialog in Gala daemon should be enough.

I decided to use the `org.freedesktop.portal.impl.Access` for this, so we don't need to keep copying the parenting code to here.

The Change Display Dialog is working, just need to center it, but I don't know if that should be doing in the portal code or in gala when a new modal is created without an parent.

> https://github.com/elementary/gala/issues/1282 is a bit different though, we'd need to implement Mutter's `meta_plugin_manager_create_close_dialog` callback. That'd also allow us to improve a bit the design of the close dialog.

For the CloseDialog, we just need to create a subclass of `Meta.CloseWindow` and return that in `create_close_window`.

we can also reuse the portal/daemon here too, maybe abusing of it a little with a extra option o transform the accept action in a destructive one. the default implementation is already reusing `Meta.Util.show_dialog` here.

One thing that i can't find how to do is create a xdg_foreign handler for an `Meta.Window` so we can do parenting of the CloseDialog under Wayland, but neither the default implementation can.

> Are you going to implement it @Marukesu? Or should I look into it?

Working on it.
