### ISSUE TITLE
Disabling Window animations should also disable the zoom effects when Alt + Tabbing

### ISSUE THREAD

**Issue by nicekiwi** [elementary/gala#1308]
### What Happened?

The "Window animations" toggle in System Settings -> Desktop -> Multitasking, when turned off should also turn off the zoom in and out animation when cycling through alt+tab.

### Steps to Reproduce

1. Go to System Settings -> Desktop -> Multitasking.
2. Turn off Window animations
3. Press and hold Alt+tab with multiple windows open

### Expected Behavior

Windows should change positions/focus and transparency instantly instead of animating. 

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
No logs.
```

**Comment by nicekiwi** [comment]
Should also disable the dock zooming together and back form the sides of the screen.

**Comment by hanaral** [comment]
The animation you are talking about has already been completely re-done, and is now not too dissimilar to that of macOS'

**Comment by nicekiwi** [comment]
@hanaral what do you mean re-done? In macOS with animations off the windows don't preview at all, it's just a popup with icons, is that what it will be in the next elementary release?

**Comment by hanaral** [comment]
Yes, Alt+Tab just has an icon popup now:
![image](https://user-images.githubusercontent.com/58219504/142416923-1d6ae1b0-7e27-43c8-a471-4ac9b18a49f3.png)

**Comment by nicekiwi** [comment]
Oooo nice :)

**Comment by cassidyjames** [comment]
Closing since this was addressed with the new window switcher design.
