### ISSUE TITLE
Bad animation when switch workspace with mutter >= 3.38

### ISSUE THREAD

**Issue by mojahed-yavazi** [elementary/gala#1325]
### What Happened?

Bad and ugly animation when switch workspace with mutter 3.38 and up.

with mutter 3.36:

https://user-images.githubusercontent.com/33109339/144166699-052328d6-032c-4c7a-af95-dfddd18fca9f.mp4

with mutter >= 3.38:

https://user-images.githubusercontent.com/33109339/144166835-3283a4c9-de6f-4a38-8c87-2785d5b71b13.mp4

### Steps to Reproduce

1. Swittch workspace

### Expected Behavior

Smooth animation like mutter 3.36

### OS Version

Other Linux

### Software Version

Compiled from git

### Hardware Info

GPU: Intel HD Graphics 530

**Comment by Alecaddd** [comment]
Not sure if it's needed, but I can confirm the issue.

**Comment by lenemter** [comment]
I can't reproduce this issue in OS 7. I guess it was resolved while fixing OS 7 regressions. Feel free to reopen if you still encounter it.
