### ISSUE TITLE
Visual feedback on snapping windows

### ISSUE THREAD

**Issue by SubhadeepJasu** [elementary/gala#133]
In elementary OS, the windows can be dragged to top to maximize or dragged to sides to snap them to sides. A visual feedback like the one in Ubuntu would be good and let users know that the windows is going to be snapped. It is not just like an eye candy. It lets users know whether the windows would be snapped or not while the user is dragging the window, and also on which direction it would be snapped, preventing user from accidentally snapping while dragging. 
![image](https://user-images.githubusercontent.com/20795161/33389229-29438a56-d558-11e7-82ce-9c05b6525a00.png)

**Comment by peteruithoven** [comment]
I'm afraid there already is an issue on this: https://github.com/elementary/gala/issues/8

**Comment by SubhadeepJasu** [comment]
Ok
