### ISSUE TITLE
Hot Corner for Application Menu glitches on 4K monitor

### ISSUE THREAD

**Issue by Lacplesis** [elementary/gala#1330]
### What Happened?

I have a desktop with a 4K monitor and a laptop with a 1080P monitor and I've used Elementary on both. On the laptop, the applications hot corner is snappy and responsive and always behaves exactly as you would expect. On the 4k monitor however, it's a lot more sensitive and if I flick my cursor into the top left corner, the Applications menu will flicker on and then immediately hide again, sometimes blinking multiple times. If I really ease the cursor in, I can make the menu appear as it should.

Also, it's worth noting that even though the visible applications menu disappears, it still seems to have focus since other windows become unresponsive until I manually click the applications menu and then click off again.

I thought that maybe it was an issue with the hot corners in general at 4k resolution, but I tested that with other hot corner options, and it's only the Applications menu that has the issue. I even tried putting the applications hot corner on other corners and the same glitch occurs.

### Steps to Reproduce

1. with the applications hot corner enabled, on a 4k monitor, drag the cursor to the hot corner
2. Flickering begins on applications menu (if not, repeat and it likely will)

### Expected Behavior

Drag cursor to Applications hot corner and have the applications menu appear.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Ryzen 1600AF CPU
AMD Radeon 570 GPU w/ 4GB RAM
64GB DDR4 RAM

**Comment by danrabbit** [comment]
Transferring to Gala since hotcorners are handled there

**Comment by danirabbit** [comment]
Closing since this was supposedly fixed in #1421
