### ISSUE TITLE
ALT + TAB

### ISSUE THREAD

**Issue by Kofusu** [elementary/gala#1339]
### Problem

I personally like old ALT+ TAB its easy  to focus tab display thats 1 point why i use elementary os

### Proposal

My reccomend is add feature to user for choose ALT + TAB display self

**Comment by lenemter** [comment]
We will not return the old window switcher. The old window switcher had many issues, you can read about this at https://blog.elementary.io/elementary-os-6-1-available-now/#quick-window-switching
