### ISSUE TITLE
Alt + Shift + Tab 

### ISSUE THREAD

**Issue by andreabbondanza** [elementary/gala#1345]
### What Happened?

The selector for the app switch with alt + tab remains stucked if you press alt + shift + tab. 
Alt + shift + tab can be useful to scroll the applications in reverse mode, however, from who came from windows is normal to try to press alt + shift + tab, and in this case the selector remains stucked. The only way to close it is to click with the mouse on the application.

### Steps to Reproduce

1. Open 3 or more applications
2. Press alt + tab
3. Press alt + shift + tab
4. Even if alt + shift + tab is not supported, the selector remains enabled and you have to click on the icon of an app to remove it

### Expected Behavior

Honestly I expect that if I press ALT + SHIFT + TAB the selection is inverted, however if this combination is not supported, I expect that the selector is closed like when you simply press alt + tab 

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

HP Spectre x360 2020 edition

**Comment by JoseExposito** [comment]
Closing this bug report as duplicated of https://github.com/elementary/gala/issues/1307

Check my comment for a workaround.
