### ISSUE TITLE
virt-manager dosn't open console window.

### ISSUE THREAD

**Issue by ercan-IO** [elementary/gala#1352]
### What Happened?

when start virt-manager dosn't open console window and I don't see virtual machine console.

$ sudo tail -f /var/log/syslog
Dec 24 15:26:48 ercan gala.desktop[2145]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1e00003
Dec 24 15:26:53 ercan gala[2145]: invalid (NULL) pointer instance
Dec 24 15:26:53 ercan gala[2145]: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

I was installed cockpit-machine and I saw virtual machine console in cockpit. 

### Steps to Reproduce

1. run virt-machine
2. open VM console

### Expected Behavior

before 1 or 2 mount ago I able to open console. I don't rebember after which update saw the bug.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
$ sudo tail -f /var/log/syslog
Dec 24 15:26:48 ercan gala.desktop[2145]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1e00003
Dec 24 15:26:53 ercan gala[2145]: invalid (NULL) pointer instance
Dec 24 15:26:53 ercan gala[2145]: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

### Hardware Info

lenovo x240

**Comment by lenemter** [comment]
I really think it's virt-manager issue, not gala one. Please reopen if you still can reproduce the issue
