### ISSUE TITLE
Issue with rounded corners of window switcher

### ISSUE THREAD

**Issue by aral** [elementary/gala#1355]
### What Happened?

Just installed the latest updates and noticed that there’s a regression on the WindowSwitcher when drawing the rounded corners (There is a faint square border around it and the space between the border and the rounded corners is transparent.)

I can’t take a screen capture of it because X11 was released in 1984 :)

Also the colour seems different and/or there is less shadow (?) – I don’t know what it is but it blends into the other windows instead of standing out.

### Steps to Reproduce

1. Open a few apps
2. Make sure you have a light wallpaper in dark mode so you can see the issue
3. Use the WindowSwitcher.

### Expected Behavior

  - There shouldn’t be a square border around it.
  - It should stand out from the other windows instead of blending into them.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment]
The screenshot of an issue:

![1](https://user-images.githubusercontent.com/80143868/209511123-d3f01fc4-d88a-421c-9f91-94115e38498b.png)
