### ISSUE TITLE
Wallpaper is dimmed in multitasking view

### ISSUE THREAD

**Issue by danrabbit** [elementary/gala#1356]
### What Happened?

When entering multitasking view, the wallpaper becomes dimmed

### Steps to Reproduce

1. Open Multitasking View
2. Notice the dim wallpaper

### Expected Behavior

No dimming :)

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by Tireg** [comment]
Seems to be the case since Mutter 40 if it can help
