### ISSUE TITLE
ALT+tab on fullscreened window is not showing all alternatives

### ISSUE THREAD

**Issue by undergroundwires** [elementary/gala#1357]
### What Happened?

I cannot alt-tab without exiting F11.

### Steps to Reproduce

1. Open some apps so there are alt-tabbable alternatives
2. Use F11 to maximize a Window
3. Press alt+tab

### Expected Behavior

See other window alternatives

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by cassidyjames** [comment]
F11 is fullscreen, which by default moves windows to a new workspace. Alt+Tab cycles between apps on the current workspace, so it won't show any alternatives by default. You can change fullscreen to not move windows to a new workspace from System Settings → Desktop → Multitasking.

**Comment by undergroundwires** [comment]
Thanks for clear explanation and fast response. I see that it's by design and it was my lack of knowledge.  Setting the setting solves the issue for me.
