### ISSUE TITLE
Replacement for Gtk.Window.keep_above ()

### ISSUE THREAD

**Issue by danirabbit** [elementary/gala#1365]
### Problem

According to [this post](https://discourse.gnome.org/t/gtk-4-how-to-replace-gtk-window-set-keep-above-and-gtk-window-set-keep-below/3550) there is no replacement for Gtk.Window.keep_above in GTK4 since not all window managers implement this behavior

### Proposal

Implement an API in Gala or see if there's something in Mutter so that system components can be set as `keep_above`

**Comment by tintou** [comment]
I have implemented it in our custom Wayland protocol https://github.com/elementary/gala/pull/1705
