### ISSUE TITLE
Support of nautilus python scripts in Gala

### ISSUE THREAD

**Issue by cazzoo** [elementary/gala#1372]
### Problem

Hello,

I wrote some scripts for Nautilus python to extend right-click over folders and files and I tried to get it working the same for EOS Window Manager (Gala) unfortunately with no success.

### Proposal

Do you plan to implement such a feature?
Maybe this is already there, thus, could you please point me to any doc to help me achieving the same?
Thanks

**Comment by lenemter** [comment]
Gala already has support for plugins but we are not planning to support Nautilus scripts.
