### ISSUE TITLE
Invisible window switcher modal (alt-tab thing) steal mouse click even after window change

### ISSUE THREAD

**Issue by milouse** [elementary/gala#1375]
### What Happened?

Since my move to pantheon desktop, I’ve encounter a very weird error I take time to understand from where it comes. From time to time (hard to reproduce), a zone in the center of my screen become unclickable. The problem is particularly noticeable in any web browser, when trying to click on a link in that zone, or trying to right click to interact with any object bellow.

I finally discovered that this "zone" is in fact the reminiscent of the Alt+tab popover, as if the window switching feature always leave/reserve a zone to be displayed at the center of the screen, and grab the click event.

### Steps to Reproduce

1. Open a few windows, take care to have at least a web-browser toward the middle of the screen (as exemple, it works with every thing in fact : right click in libreoffice, on the desktop…)
2. Use Alt-tab to select another window
3. Try to interact with the mouse where the window switcher was previously displayed

### Expected Behavior

The click works as expected.

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
N/A
```

### Hardware Info

Not really hardware related, but I explicitely select my window selection mode in dconf as being "sloppy".

**Comment by aral** [comment]
I’ve noticed this also but hadn’t narrowed it down to the area used by the alt-tab task switcher.

As far as I remember, this wasn’t an issue with Catts or when it was first integrated into Gala to I’m assuming it’s a regression that happened after the initial release (?).

**Comment by milouse** [comment]
Wow, I just take time to dig a bit further, and it seems my issue is a duplicate of #1322 

I’ll try to use the latest master including 962accdf1a3529a7968b529ad6f35595252ff386 to check if it fix the problem. If not, and waiting for a better fix, the other issue confirm that switching back to default window selection mode seems to be sufficient.

**Comment by milouse** [comment]
I confirm 962accdf1a3529a7968b529ad6f35595252ff386 resolves the problem. Time to make a new release?
