### ISSUE TITLE
Use of title bar space/functionality for applications - e.g. Firefox

### ISSUE THREAD

**Issue by armaccloud** [elementary/gala#138]
When for example Firefox is installed, the title bar takes up a lot of space without much functionality.
For example in MacOS, the top bar for Firefox is tightly integrated with Firefox functionality (address/search/buttons/etc.). Maybe the design can be modified so installed applications make better use of the top space?

There used to be an addon that could hide the title bar, but it doesn't seem to work. But then again, a global design could benefit more than just Firefox.

**Comment by peteruithoven** [comment]
Relevant: 
http://www.omgubuntu.co.uk/2017/11/firefox-nightly-adds-csd-option
https://bugzilla.mozilla.org/show_bug.cgi?id=1283299
https://bugzilla.mozilla.org/show_bug.cgi?id=1414212

**Comment by danrabbit** [comment]
This is a problem with Firefox. There’s nothing Gala can do to make Firefox use client-side decorations. Closing as “invalid” for Gala since there’s no action that we can take
