### ISSUE TITLE
Only the close button is showing

### ISSUE THREAD

**Issue by Gusaroo** [elementary/gala#1392]
### What Happened?

I installed Gala on my desktop (Xubuntu 21.10) running Xfce, but for some reason the only window button that shows is the close button.

### Steps to Reproduce

1. Followed this tutorial right here, except I used the stable ppa instead of the daily ppa (https://gist.github.com/valc93/9a476b9ba9419ed632a8)

### Expected Behavior

By default it’s supposed to show a maximize button on the left and as I’ve set it, the minimize and maximize button next to it. I’m wondering if there is any possible way to fix this.

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment]
I don't think gala overrides button-layout setting, so it is not a bug. You can set elementary OS window controls layout by running `gsettings set  org.gnome.desktop.wm.preferences button-layout 'close:maximize'` in terminal.
