### ISSUE TITLE
Alt+Tab application switcher doesn't select the highlighted application

### ISSUE THREAD

**Issue by Alecaddd** [elementary/gala#1396]
### What Happened?

When using the <kbd>Alt</kbd>+<kbd>Tab</kbd> keyboard shortcut, the application chooser doesn't disappear when the <kbd>Alt</kbd> key is released.
In that stage, clicking on the application or "outside" the chooser makes it disappear, but until then is not possible to "confirm" the highlighted application from the chooser.
Press <kbd>Enter</kbd> or <kbd>Space</kbd> doesn't do anything as the focus seems to be back on whatever application is currently visible.

### Steps to Reproduce

1. Install elementary OS 7
2. Open multiple applications
3. Press <kbd>Alt</kbd>+<kbd>Tab</kbd> to cycle through opened apps
4. Release the <kbd>Alt</kbd> key

### Expected Behavior

The highlighted application should be selected when the <kbd>Alt</kbd> key is released, and the switcher should disappear.

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by TomiOhl** [comment]
Can confirm, I'm experiencing the same since the new app switcher.
I've been recommended to disable the keyboard layout switch shortcut, since it defaults to Ctrl + Alt, it's know to conflict with Ctrl + Alt + Tab. However, that's a different issue and doesn't help the case.

**Comment by vjr** [comment]
I was testing the code with some of my changes and it appears that the `key_focus_out` and `key_release_event` signals (handlers) are not being triggered which are where the switcher is closed after focusing the selected window icon.

I see the signal method itself is overridden so I tried changing them to handler methods and connecting to the same signals with no luck.

I believe `Gtk.Window` (or is it `Widget`) requires some flags to be set on the event mask to allow key release events to be triggered but don't see similar for `Clutter.Actor` so no luck there either.

Anyone has any suggestions or knows why the events are apparently not being triggered?

**Comment by jeremypw** [comment]
I wonder whether its something to do with the update to `mutter-42`? That seems to involve changes to do with `grab` (see https://github.com/elementary/gala/commit/cdcb87afcb4fb5729548a934885ba46b40a601ac).  Unfortunately I do not know much about Mutter.  Maybe @tintou can suggest something.

**Comment by vjr** [comment]
> I wonder whether its something to do with the update to `mutter-42`? That seems to involve changes to do with `grab` (see [cdcb87a](https://github.com/elementary/gala/commit/cdcb87afcb4fb5729548a934885ba46b40a601ac)). Unfortunately I do not know much about Mutter. Maybe @tintou can suggest something.

Seems to be exactly this :-) Although I don't know why the CI build is failing on my PR.

**Comment by vjr** [comment]
OK seems to fixed and ready for review now :-)
