### ISSUE TITLE
Clicking an app in multitasking view doesn't focus that app

### ISSUE THREAD

**Issue by danirabbit** [elementary/gala#1413]
### What Happened?

When using multitasking view, clicking an app doesn't bring that app into focus. There's no effect when clicking apps

### Steps to Reproduce

1. Open multitasking view
2. Click an app to focus it
3. Nothing happens

### Expected Behavior

Clicking an app in the multitasking view should bring it into focus. This is probably a mutter-related regression

### OS Version

7.x (Early Access)

### Software Version

Compiled from git

**Comment by davidmhewitt** [comment]
Fixed in #1464
