### ISSUE TITLE
Jarring animation when navigating from first workspace with the keyboard

### ISSUE THREAD

**Issue by danrabbit** [elementary/gala#1414]
### What Happened?

When navigation from the first workspace using keyboard shortcuts, there is a jarring animation. It looks like maybe the bump animation is playing

### Steps to Reproduce

1. Have multiple workspaces open
2. Navigating with keyboard shortcuts from workspace 1 to 2
3. Notice the bump animation
4. Navigating back to workspace 1
5. Notice there is no bump animation

### Expected Behavior

Animation should be smooth when navigating between workspaces

### OS Version

7.x (Early Access)

### Software Version

Compiled from git

**Comment by davidmhewitt** [comment]
I'm trying to track this down, and it doesn't seem to be the bump animation, or at least I can't see that code path being hit.

Perhaps more interestingly, this only seems to happen when the mouse cursor is on a window. If you have the mouse cursor over the desktop when you trigger the workspace switch, it doesn't seem to happen, at least not for me... :confused:

**Comment by danrabbit** [comment]
@davidmhewitt I think I got it! Spent all day trying a million things ha
