### ISSUE TITLE
Sometimes Win+Alt+left/right and Win+UP keys are not working properly

### ISSUE THREAD

**Issue by itoshkov** [elementary/gala#1416]
### What Happened?

Sometimes the Win+Alt and Win+UP keys are not working. I think this happened after the introduction of new option to use Win key for multitasking view.

In my case, ⌘ key behavior is set to Disabled, but I tried with all the rest and the bug is still present.

### Steps to Reproduce

1. Open a window (e.g. Calendar or Tasks or any other resizable application)
2. Press Alt-Tab
3. (If this wasn't the only window, press Alt-Tab again until it's back to focus)
4. Press Win+UP - nothing happens.

The same happens with Win+Alt+Left/right.

### Expected Behavior

Pressing Win+UP should maximize the window.

Pressing Win+Alt+Left/Right should move the window to the left or right workspace.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by marco4mp** [comment]
I think this is issue is related to https://github.com/elementary/gala/issues/1401

**Comment by itoshkov** [comment]
Yes, it's probably the same. I'll close this one as duplicate.
