### ISSUE TITLE
Alt+F4 does not close windows about half of the time (hit or miss)

### ISSUE THREAD

**Issue by dennismayr** [elementary/gala#1425]
### What Happened?

For about a couple of months now, `Alt+F4` does not close windows about half of the time.
Can't tell which type of apps are affected (i.e. Flatpak vs Snaps vs regular DEB packages).

For starters, elementary Terminal won't.
I've already reset all settings with `dconf reset -f /`, and the problem persists.

This didn't happen at the beginning of the year, for what I can recall at the moment.

### Steps to Reproduce

1. Open elementary Terminal or System Settings
2. Close the focused window with `Alt+F4`
3. See that it isn't closed; `Ctrl+Q` may or may not work, either.
4. Try other random apps, both GTK and Qt.
5. The above may or may not work randomly.

### Expected Behavior

All windows are closed by `Alt+F4`.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

ThinkPad T410s with Optimus dual graphics (integrated Intel video + Nvidia NVS3100M), working in PRIME configuration.
Memory: 8Gb
Keyboard layout: Spanish (Latin America)

**Comment by dennismayr** [comment]
Follow up:

I've just noticed that some `flatpak` apps seem to somehow hijack or block access to these keyboard shortcuts.

_e.g._ Elementary _Terminal_ won't close with `Alt+F4` unless I quit _QBittorrent_ installed from `flatpak`, and the same happens with other apps that were installed in the same way.

**Comment by lenemter** [comment]
I encountered this issue in OS 6 but surprisingly not in OS 7. Please reopen if you encounter the issue even in OS 7.

**Comment by dennismayr** [comment]
I will try installing OS 7 on another computer during the weekend and report back.
