### ISSUE TITLE
Desktop takes too long to load

### ISSUE THREAD

**Issue by aggalex** [elementary/gala#143]
My elementary OS desktop sometimes takes too long to load (wingpanel and plank to appear). Sometimes though it does it almost swiftly, around a second after a second from logging in. At the beginning there was no problem, but as time passed this problem started to appear more and more often. Now the desktop appears immediately very rarely. Also, even if there is a significant delay at loading the desktop, the animations displayed after loading (plank sliding up, wingpanel sliding down) are completely normal and flawless, regardless the delay.

It notable that if I'm lucky to have any upgradeable packages or any deep-depending removable packages that are no longer needed I can switch to any other TTY, login, and type `sudo apt upgrade` or `sudo apt autoremove`, and after the command processes some triggers I can switch to TTY 7 and I wait for around 1 second and the desktop will load perfectly.
_I suspect there is something in the trigger-processing process that activates gala or whatever._

Please fix it, it has been a nuisance for quite some time. 

EDIT:
Apparently elementary OS uses an old version of dbus (3-year-old version?) as stated by @peteruithoven, which was known to cause such problems, but was fixed on a version released around a year later. Whoever can, shall transfer this bug from Gala to elementary OS core.

**Comment by Tidrek** [comment]
I had a similar problem after one of kernel updates (along with other updates). I disabled and removed zeitgeist, enabled ubuntu-16.04-hwe to update to the newer stable kernel (4.10). Don't have this problem since.

**Comment by aggalex** [comment]
Could you explain? What is zeitgeist (other than "the spirit of time" in German) and ubuntu-16.04-hwe? How to enable/disable/remove them?

**Comment by Astro-City** [comment]
Hi.  

Rename this file /etc/xdg/autostart/at-spi-dbus-bus.desktop to /etc/xdg/autostart/at-spi-dbus-bus.desktop.disabled 

It's a known bug.

**Comment by aggalex** [comment]
Thank you, it worked!!! One question though, does this have any side effects?

**Comment by Astro-City** [comment]
I don't know, but i think the process is called either way.  

Try to see if you have the at-spi-bus-launcher process when you do a pidof or ps -A.

**Comment by aggalex** [comment]
Yes, there is a process called "at-spi-bus-launcher" indeed. Thank you!

**Comment by peteruithoven** [comment]
(omg that https://bugs.launchpad.net/elementaryos/+bug/1596377 bug report has a lot of useless me2's etc)

Useful comments:
https://bugs.launchpad.net/elementaryos/+bug/1596377/comments/22
> I noticed in journalctl command (at least a couple of times that I checked) the following log line when there is an approx 90 second delay in my login:
> Oct 11 20:50:18 skybird gnome-session[2743]: gnome-session-binary[2743]: WARNING: Application 'at-spi-dbus-bus.desktop' failed to register before timeout
> Apparently this is AT-SPI something to do with gnome assistive/a11y technology. Will try disabling the .desktop file in /etc/xdg/autostart folder and report back.

https://bugs.launchpad.net/elementaryos/+bug/1596377/comments/27
> I think the related problem is explained and fixed here:
https://mail.gnome.org/archives/commits-list/2016-July/msg02793.html
> OS Loki is running dbus-daemon 1.10.6 from 2015-12-1 while the problem was fixed in July 2016. An update to newer dbus version (one after 1.10.10) should fix the issue.
> To fix the issue for now:
Rename the file to at-spi-dbus-bus.desktop

I don't know why Elementary didn't update dbus-daemon?

**Comment by danrabbit** [comment]
Closing this issue since it's an issue with dbus and not with Gala.

Cody is testing a patch for dbus, but it's not possible to wholesale update dbus without breaking lots of things

**Comment by peteruithoven** [comment]
@danrabbit any change you could share more information? Is there an dbus issue we could follow?

**Comment by peteruithoven** [comment]
This looks like a relevant issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840618

> We believe that the bug you reported is fixed in the latest version of
at-spi2-core, which is due to be installed in the Debian FTP archive.
> A summary of the changes between this version and the previous one is
attached
> Version: 2.22.0-4
> Description:
> at-spi2-core - Assistive Technology Service Provider Interface (dbus core)
> patches/register-client-early: Fix crash by moving registration after getting sm_proxy

I'm running an up to date loki and have: version `2.18.3-4ubuntu1`. (According to `apt show at-spi2-core`)

**Comment by peteruithoven** [comment]
Looking at the following page Ubuntu 18.04 (Bionic Beaver), where elementary OS Juno in built on, includes version 2.26.2-2 of at-spi2-core, which probably mean this issue is fixed in elementary Juno.
https://pkgs.org/download/at-spi2-core
