### ISSUE TITLE
[Window switcher] The top outline and roundness is not drawn on the window switcher if the plank theme doen't have a negative top padding.

### ISSUE THREAD

**Issue by Blast-City** [elementary/gala#144]
Hi.  

If the value TopPadding= is equal or grater than 0 on the plank .theme file the top outline (LineWidth=) and roundness (TopRoundness=) doesn't work on the window switcher.  

You can see this by selectin the included theme called matte.

**Comment by LvLs9** [comment]
# I illustrated this bug on gif:
![gifout](https://user-images.githubusercontent.com/34302242/39655295-709f97fe-5001-11e8-8ecc-c7431fab846c.gif)

**Comment by Astro-City** [comment]
Thanks.

**Comment by lenemter** [comment]
Closing because window switcher was reworked in #1234
