### ISSUE TITLE
[Request] Force rounded corners on other apps

### ISSUE THREAD

**Issue by Radical4ever** [elementary/gala#1441]
### Problem

Some apps doesnt have the bottom rounded corners. and it feels like none of the apps are integrated with the system, making it look like its just a complete other app with just the theme (something that is more commonly seen on windows OS)

### Proposal

make a mod or script (i find out using gnome a window manager called mutter-rounded. see [here](https://github.com/yilozt/mutter-rounded if you need some repo as example). this script makes all apps (including wine and flatpak apps) to have rounded corners. the downsides that i saw on this proyect on testing is when changing the gtk theme that bugs the windows(but it immediately solves reopening the app).
![Captura desde 2022-06-19 15-13-04](https://user-images.githubusercontent.com/83252104/174495099-80afe181-5dd3-4cce-a836-ce18410a1ade.png)

or when you want to open a custom file on an app (portals i think its called that) and when its too big so the script makes the same thing like before :
![Captura desde 2022-06-19 15-18-57](https://user-images.githubusercontent.com/83252104/174495125-910e87aa-e24f-434a-b302-55358ee95ff7.png)
 
but rather than that it works mostly fine and strangely it makes all apps look integrated :) !

### Prior Art (Optional)

Like i said this makes the apps somehow look more integrated:

- **Gnome (With mutter rounded script installed)**

![Captura desde 2022-06-19 15-27-39](https://user-images.githubusercontent.com/83252104/174495453-67fd785a-5e8c-4e13-8543-78a73b6080d7.png)

- **Windows**

![Windows-11-rounded-corners-update](https://user-images.githubusercontent.com/83252104/174495356-d4fdc90c-b538-404f-a438-a964d41e47e3.jpg)

- **Mac OS**

![c7e1a1103346677 5f4b5988631cf](https://user-images.githubusercontent.com/83252104/174495395-cc8c94ba-b5fa-4161-bfc2-452d88d4cba0.png)

**Comment by danrabbit** [comment]
Hey thanks for your feature requests. Window decorations including corners and shadows are drawn on the "client side", which means by the app. In general our policy is not to modify the contents of apps. As more apps migrate to Gtk4 you should see them using rounded bottom corners, but we won't be modifying legacy or non-native apps. If an app you love doesn't have rounded bottom corners, consider filing an issue report against that app.
