### ISSUE TITLE
Taking area screenshot to clipboard with keyboard shortcut crashes window manager

### ISSUE THREAD

**Issue by eppixx** [elementary/gala#1458]
### What Happened?

Sometimes taking a screenshot with shift + ctrl + print crashes the window manager (the window decoration is removed, but comes back in a few seconds) and occasionally throws you out of a session to the login screen.

Everything seems to be okay when the application is opened and using the functionallity there.

### Steps to Reproduce

1. press shift + ctrl + print keys
2. go to step 1

### Expected Behavior

not crashing window manager or the session

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment]
Closing because cannot reproduce the issue on OS 7. Reply here if you still encounter the issue in OS 7 please.
