### ISSUE TITLE
Unable to drag windows to move them in multitasking view

### ISSUE THREAD

**Issue by danirabbit** [elementary/gala#1467]
### What Happened?

When in multitasking view, windows are no longer draggable to other workspaces

### Steps to Reproduce

1. Open some windows
2. Open multitasking view
3. Try to drag a window to another workspace

### Expected Behavior

This is a regression. Behavior should be the same as in OS 6

### OS Version

7.x (Early Access)

### Software Version

Compiled from git

**Comment by tintou** [comment]
This is because our DragDropAction need to be updated to Mutter 42 API with handle_event like in https://gitlab.gnome.org/GNOME/mutter/-/commit/5133815cc1a6b9fbf61f18b3fbca2321d5559ffd
