### ISSUE TITLE
Gala unable to start

### ISSUE THREAD

**Issue by lenemter** [elementary/gala#1476]
### What Happened?

"Oh no! Something has gone wrong." screen

### Steps to Reproduce

1. i don't know

### Expected Behavior

I expect to see my desktop

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by davidmhewitt** [comment]
I imagine this may have been caused by incompatible versions of the Gala plugin for Wingpanel after there were issues with it building yesterday. Is this still happened with up to date packages?

I can't reproduce it here.

**Comment by lenemter** [comment]
Yes the issue still persists

journalctl output when i log in:

[logs.txt](https://github.com/elementary/gala/files/9791207/logs.txt)

**Comment by lenemter** [comment]
After some testing I found out that this bug starts happening in commit 7c540a2a0669fb7de84ed1071f85f5d331398040 (#1241)
Gala stars fine in previous commit 80db0620dc82211811fe4fc504b3df110eaa8c71

**Comment by davidmhewitt** [comment]
From your log:

`gala.desktop[6475]: gala: symbol lookup error: gala: undefined symbol: gala_app_system_lookup_app`

This is why it's crashing. Gala loads it's own `libgala` shared library, and the version it's loading doesn't have that method.

That method was added in the PR/commit you linked. So it looks like Gala is loading an older shared library without that method, even after you've installed a newer version.

So, I think what's happening is that you have an old version of gala installed in a path that isn't getting overwritten with the new versions you're installing.

Check in `/usr/local` for any gala files and remove them. Gala could have been installed to here at some point in the past if you accidentally ran meson without the `--prefix=/usr` argument.

**Comment by lenemter** [comment]
That fixed the issue. Thank you very much
