### ISSUE TITLE
PiP: Log spam on elementary OS 7.0

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/gala#1478]
### What Happened?

Originally reported in https://github.com/elementary/gala/issues/1474 but seems unrelated to the resizing, it just generally happens with the PiP window open.

### Steps to Reproduce

1. Open a PiP window on elementary OS 7.0
2. Journal gets filled up with log spam

### Expected Behavior

No log spam

### OS Version

7.x (Early Access)

### Software Version

Compiled from git

### Log Output

```shell
(gala:5031): Clutter-WARNING **: 13:48:06.028: (../clutter/clutter/clutter-actor.c:12430):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)
```

**Comment by bobby285271** [comment]
For easier triage, https://github.com/elementary/gala/pull/1506#issuecomment-1366374402 is probably related.
