### ISSUE TITLE
Upgraded Gala 6.3.1 to Gala 6.3.2 - Multitasking View become very slow and Dynamic Workspace Enabled result some problems.

### ISSUE THREAD

**Issue by LightColoredLines** [elementary/gala#1481]
### What Happened?

Multitasking view become very slow after upgraded to Gala 6.3.2. But this update fixing some problem that i have before.
But here is another problem that i think never got fixed since months ago:
If i'm enabled Dynamic workspace on dconf, there is a problem. when i have multiple apps opened in workspace 1 and then i switching to workspace 2, no problem. but when switching back to workspace 1 with (Multitasking view way) and click the workspace 1 box at the bottom, all the apps inside workspace 1 become all closed

### Steps to Reproduce

Dynamic Workspace Enabled: (/org/gnome/mutter/dynamic-workspaces)
1. Open Multitasking View via top left hot corner
2. Switching to workspace 2
3. Switching back to workspace 1 with clicking the box at the bottom
4. All apps closed

https://user-images.githubusercontent.com/10070295/195999850-c22198fb-1ac5-4ec6-961a-2acb93fbe8f5.mp4

### Expected Behavior

It should be back to workspace 1 without closing all apps at once. (i don't clicking the X button at the corner of the box accidentally)

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

**Comment by Ppamungkas** [comment]
+1 for this, also happen to me.

**Comment by lenemter** [comment]
Closing in favour of #1517.
