### ISSUE TITLE
Wingpanel and applications menu stretch in multitasking view

### ISSUE THREAD

**Issue by lenemter** [elementary/gala#1483]
### What Happened?

https://user-images.githubusercontent.com/80143868/196366785-185fc03d-cea5-4180-a436-88530da70d75.mp4

### Steps to Reproduce

1. Open the multitasking view
2. Open application menu with a shortcut

### Expected Behavior

Application menu shouldn't open in multitasking view

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by TomiOhl** [comment]
It can be opened on 6.1, too, however, it doesn't cause that weird wingpanel slide up animation when closing.
