### ISSUE TITLE
0S6.1: quick three fingers swipe up with immediate release... kills an application

### ISSUE THREAD

**Issue by ysbaddaden** [elementary/gala#1485]
### What Happened?

The 3 fingers swipe up looked like a nice gesture, but it actually (almost) always kills a window that was opened on the workspace. If I only had one application

### Steps to Reproduce

1. Enable the 3-fingers swipe up gesture;
2. Open an application on a workspace;
3. Quickly swipe up with 3 fingers and remove them from the trackpad (fingers up in the air);
4. The application is immediately closed.

This isn't happening if I diligently keep my fingers on the trackpad for a while.

Gala wrongly believes that my 3 fingers swipe was also a 3 fingers tap.

### Expected Behavior

The multi-tasking view is opened and my applications aren't closed until I make a _real_ 3 fingers tap.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by TomiOhl** [comment]
Duplicate of #1434

**Comment by ysbaddaden** [comment]
Closed as duplicate.
