### ISSUE TITLE
Multi Monitor multi-task view issue

### ISSUE THREAD

**Issue by juanfgs** [elementary/gala#150]
Hello, i've started using Pantheon desktop recently and I've noticed a small issue when working on multiple monitors. The mullti task view is very useful to arrange windows and manage workspaces, however when having two monitors it's kinda cumbersome to manage the windows on the secondary display using only the mouse. 

When the multi-task view is activated it's only present on the primary display, the other display is greyed-out, thus preventing any interaction with windows. 

So, for example:

If I have a window on the secondary display on workspace 1 and I want to move it to the secondary display on workspace 3 I have to:

- first drag it to the primary display 

- activate multi task

- drag it to the 3rd workspace

- drag it back to the secondary display.

It would be nice if the secondary display was also managed by the multi-task view, with a workspace switcher of it's own. The ideal behaviour I see is the way you can do it with the multi monitor extension on gnome, where the workspace switcher is shown on both monitors.

**Comment by lenemter** [comment]
Fixed in https://github.com/elementary/gala/pull/1640.
