### ISSUE TITLE
"Not responding" dialog and not responding app close after inactivity

### ISSUE THREAD

**Issue by lenemter** [elementary/gala#1505]
### What Happened?

"Not responding" dialog and not responding app close after inactivity because
`Dialogs.vala:198: Timeout was reached`

### Steps to Reproduce

1. Open "Not responding" dialog (e.g. elementary/switchboard#245)
2. Wait a while

### Expected Behavior

Dialog and an application stay until user or application responds

### OS Version

7.x (Early Access)

### Software Version

Compiled from git

**Comment by Marukesu** [comment]
That's the DBus timeout. This should be easily fixed by setting the call timeout to `Int.MAX`, vala support setting the timeout with the `[DBus (timeout = value)]` attribute, but it only accept literals, so we can't use the constant here.
