### ISSUE TITLE
The second time I click on a workspace, all applications in that workspace close

### ISSUE THREAD

**Issue by marco4mp** [elementary/gala#1517]
### What Happened?

The second time I click on a workspace, all applications in that workspace close.

Fresh install of elementary 7 Stable Release.

### Steps to Reproduce

https://user-images.githubusercontent.com/52709674/216159328-141dba6f-f92d-47c4-a181-caaad684fc25.mp4

### Expected Behavior

Clicking should not close the workspace and apps.

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by TomiOhl** [comment]
Can confirm this on OS7
