### ISSUE TITLE
Animation Lags Switching from Multi-task View to a Window

### ISSUE THREAD

**Issue by GavinXSF** [elementary/gala#1525]
### What Happened?

Every time when I choose an application from the multi-tasking view, the animation of window focus lags no matter what the app is.
However, entering multi-tasking view is smooth.

### Steps to Reproduce

1. enter multi-tasking
2. choose an app to switch to the window

### Expected Behavior

The latency is too obvious.

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Lenovo Laptop, AMD Ryzen R7-5800H, integrated graphics card.

**Comment by lenemter** [comment]
Hello. Thanks for reporting. I'm going to close this as duplicate of #1136.

**Comment by GavinXSF** [comment]
> 

I checked #1136 and found that you have merged #1498, isn't it included in OS 7?

**Comment by lenemter** [comment]
@GavinXSF #1498 is included in OS 7 but as you can see perfomance issues are still there.

**Comment by GavinXSF** [comment]
> @GavinXSF #1498 is included in OS 7 but as you can see performance issues are still there.

OK, I'll see if further updates improve this. Thanks for your help.
