### ISSUE TITLE
Empty window appears on clicking Show Desktop from Plank

### ISSUE THREAD

**Issue by biswaz** [elementary/gala#153]
An empty window appears on clicking Show Desktop from Dock.
![screenshot from 2018-01-06 22-46-04](https://user-images.githubusercontent.com/12367632/34642085-995dc236-f333-11e7-89c1-4b3a1c0fbad2.png)

**Comment by biswaz** [comment]
@donadigo Haven't anyone reported such an error before? I cant seem them on other issues.

**Comment by donadigo** [comment]
@biswaz no I haven't seen such bug before. Also, we elementary OS doesn't really have support for this "hidden" feature, although it seems like that should be fixed, either in gala or plank.

**Comment by biswaz** [comment]
@donadigo  What can I do to help resolve this bug?

**Comment by donadigo** [comment]
If you have this window opened, it would first be appropriate to identify what process owns the window. In terminal type `xwininfo` and click the empty window. Paste the output from that here.

**Comment by biswaz** [comment]
xwininfo: Window id: 0x2600006 "Desktop"

  Absolute upper-left X:  0
  Absolute upper-left Y:  0
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 1366
  Height: 768
  Depth: 32
  Visual: 0xad
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x2600005 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +0+0  -0+0  -0-0  +0-0
  -geometry 1366x768+0+0

I think you can reproduce this bug by opening any video in VLC and then going full screen and exiting the full screen and clicking show desktop button in plank.

**Comment by danrabbit** [comment]
This doesn't appear to happen anymore
