### ISSUE TITLE
Strange shadow artifacts in Java desktop applications

### ISSUE THREAD

**Issue by activey** [elementary/gala#1534]
### What Happened?

I use Intellij IDEA heavily on my machine and noticed strange shadow artifacts under the window, just to make sure I've installed some other Java based application (jedit this time) and problem can be reproducd with this one as well.

### Steps to Reproduce

1. Install any Java desktop app,
2. Run the app,
3. Move the window here and there...

Attaching a video recording.

https://user-images.githubusercontent.com/1751891/218254855-088ac599-f68e-472e-800e-a0b1a854bf05.mp4

### Expected Behavior

No strange shadow artifacts remain on the screen.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by vjr** [comment]
Do you have a hidpi display? I see the same issue and IINM this PR should fix it https://github.com/elementary/gala/pull/1531

**Comment by activey** [comment]
Hm 🤔 I believe Im not on hidpi, the rest of the apps behave fine, just having issues with Java based

**Comment by activey** [comment]
I was able to observe the same thing with Brave browser for few seconds...

**Comment by activey** [comment]
It seems this https://github.com/elementary/gala/issues/1443 has not been fully resolved ;)

**Comment by notanimposter** [comment]
This is happening to me with Discord, so it's definitely not limited to Java-based applications.
I have a 10 year old NVIDIA GPU (GTX 760 using legacy 470 driver). I don't know if that's related but it's worth mentioning in case it's a commonality. It too often seems to be the culprit in cases of graphical glitches.

**Comment by tofylion** [comment]
I have the same issue happening with several apps. Here are 2 ways I could reproduce it:
1. Picture in Picture
  - Use a browser that has picture in picture (ms edge in my case)
  - Play a video (eg. youtube)
  - (Optional) To show the artifacts clearly, change the webpage theme to light theme
  - Click on the pip icon
  - Move the pip window around slowly and notice the shadows
2. Android Emulator
  -  Open android emulator
  - Move the emulator around (preferably on a bright background) and notice the horrible shadows

I'm using an RTX 2070 (laptop) discrete GPU with intel integrated UHD 630 graphics and the build in display

**Comment by IanHead** [comment]
For me it seems to be happening in any app that isn't using client-side window decorations. It includes reminder and message windows in Thunderbird (but not the main window), lots of applications running under Wine, Joplin and others.

**Comment by activey** [comment]
Yeah, it looks like it's dirty ;>

**Comment by lenemter** [comment]
@activey I created #1625 to solve the issue. Can you please check if it solves it for you too please?

**Comment by vjr** [comment]
@lenemter appears to fix the issue for me (I use the unofficial IntelliJ IDEA IDE flatpak)...
