### ISSUE TITLE
Several (un-)maximize animations are not played

### ISSUE THREAD

**Issue by eppixx** [elementary/gala#1536]
### What Happened?

Several Animations for maximizing and unmaximizing are not playing.

Windows that use headerbars (maybe all gtk based ones?) do not use the unmaximize animation.
Among these are:
- Files
- Code
- Music
- Mail
- Web (Epiphany)
- Firefox

Then there are windows that don't ue the maximize and unmaximize animations.
Among these are:
- xournal++
- keepassxc
- Chromium
- Emacs

### Steps to Reproduce

1. Open window
2. Maximize it by double clicking the header or using the maximize button 
3. unmaximize it

### Expected Behavior

Play the animation

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Using Nvidia driver 525

**Comment by activey** [comment]
It seems all the non-gtk4 apps are affected?

**Comment by eppixx** [comment]
I think all  gtk based apps don't have a unmaximize animation, while all other don't hava a maximize and unmaximize animation.
