### ISSUE TITLE
Multitasking View closes apps and crashes when dragging apps

### ISSUE THREAD

**Issue by diogopessoa** [elementary/gala#1538]
### What Happened?

When showing the multitasking view, and moving apps from one space to another, the apps close unexpectedly and cause crashes.

### Steps to Reproduce

1. Open the multitasking view and drag the app from one space to another;
2. Applications close unexpectedly and cause crashes;
3. Press the Esc key to exit;
4. Apps that are in use no longer appear open in the dock.

Attaching a video recording:

https://user-images.githubusercontent.com/12633864/218731233-42a29bb6-d5bb-4e32-b47d-dfbaaa2cf702.mp4

### Expected Behavior

When opening the multitasking view and dragging the app between workspaces, the apps should still appear in the dock and workspace.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Notebook Asus S46CA
Intel i5 8GB memory SSD 500GB
Intel HD graphics 4000

**Comment by lenemter** [comment]
This looks like a combination of #1517 and #1482, both have already been fixed. AFAIK we plan to release Gala update towards the end of February.
