### ISSUE TITLE
Multitasking view icons transition issue

### ISSUE THREAD

**Issue by peteruithoven** [elementary/gala#1541]
### What Happened?

When I go into the multitasking view the transition/animation of app icons seems off. It's like their starting point is further to the bottom right than they should be? 

[Peek 2023-02-18 12-23.webm](https://user-images.githubusercontent.com/523210/219866089-b6b1a692-8009-4342-bc8d-18686604c281.webm)

Here I'm going in the the multitasking view twice quickly the second time you can see the icons seem to follow the window previews, but delayed. 

[Peek 2023-02-18 13-07.webm](https://user-images.githubusercontent.com/523210/219867500-b1c00c02-862a-4ab9-b4f5-040d70cf2971.webm)

More zoomed in with better framerate

[Peek 2023-02-18 13-24.webm](https://user-images.githubusercontent.com/523210/219868352-1c2b38e2-a12e-479e-88bd-e35b074824b2.webm)

### Steps to Reproduce

1. Open Multitasking view

### Expected Behavior

The icons move in sync with the application window previews

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

I'm using a scaling factor of 2x.

**Comment by lenemter** [comment]
Can you check if #1529 fixes it please?

**Comment by peteruithoven** [comment]
@lenemter Great that you've already been looking into this. Your PR  doesn't appear to fix it I'm afraid. 
I've checked out your branch (verified I had you changes locally). Build and installed gala following the readme and even rebooted to be sure. But the animation still seems off in the same way.

**Comment by peteruithoven** [comment]
I'm very happy to report it's fixed! 
Gala feels much better for it. Thanks for all your recent improvements!
