### ISSUE TITLE
Taking screenshot stopped working and system freezes

### ISSUE THREAD

**Issue by gorghino** [elementary/gala#155]
**Kernel**:
Linux dago 4.4.0-108-generic #131-Ubuntu SMP Sun Jan 7 14:34:49 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Print key stopped working.
If you try to take screenshot multiple time, gala takes 90% CPU and the system slowly hangs.
I was able to change tty and save logs.

![2018-01-10 11 11 22](https://user-images.githubusercontent.com/1898283/34767636-e87bc558-f5f8-11e7-83a7-f7f53096e1a9.jpg)
![2018-01-10 11 10 22](https://user-images.githubusercontent.com/1898283/34767641-ea8ad320-f5f8-11e7-8418-bf68b2c2232b.jpg)

**Comment by gorghino** [comment]
It seems it doesn't happen with Linux dago 4.4.0-109-generic though

**Comment by artemanufrij** [comment]
Just tested it. It happens everytime on my system.

reproduce:
press `print`-key 3-5 times
