### ISSUE TITLE
Multitasking view doesn't reliably re-order workspaces

### ISSUE THREAD

**Issue by dwmckee** [elementary/gala#1558]
### What Happened?

The GUI pauses for many seconds and sometime workspaces disappear taking any open programs with them.
The mouse pointer remains responsive, but attempted actions are not represented by user-visible changes in the display. If the workspace doesn't disappear, it eventually ends up back where it started.

### Steps to Reproduce

1. Start the OS and log in
2. Open something in the initial workspace
3. Repeat several times: [switch to a new workspace and open a new program]
4. Open the multitasking view, try to re-arrange workspaces (I have more trouble moving them left than right but it has wedged both ways.).

### Expected Behavior

You can move workspaces around freely and they never go away while you're doing it.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Dell Latitude 7250 (rather old) dual-core i5. 8GB RAM, 256 GB SSD. Default Bios setting, Disk not encrypted.

**Comment by lenemter** [comment]
Hello. Thanks for reporting. This has been reported several times in #1517 #1539 #1538. The fix is merged so you need to wait for an update.
