### ISSUE TITLE
New desktop menu items

### ISSUE THREAD

**Issue by camellan** [elementary/gala#1572]
### Problem

It would be nice to add new items to the context menu of the desktop.

### Proposal

You can add a terminal startup and a system shutdown item.

**Comment by danirabbit** [comment]
Following discussion at #1573 I don't think these are a great fit for the right click menu here. The idea of this menu was to make wallpaper and display settings more easily accessible/discoverable for folks coming from other platforms. I don't think there's a compelling case to launch apps from here or to have actions which are already quickly accessible from the panel appear here

Closing as "Not planned"
