### ISSUE TITLE
Provide affordance for keep-below windows

### ISSUE THREAD

**Issue by cassidyjames** [elementary/gala#158]
When a window with `keep-below` set is mapped, it's currently difficult to know anything even happened. For example, launching an "applet" app like Nimbus or Monilet from AppCenter maps the window onto the desktop, but the AppCenter client is above it, so you never see it spawn.

Instead, we could do something clever like briefly fade all open windows to (mostly?) transparent to show that a new keep-below app is spawned.

This _might_ be a little visually heavy, so we'll need to keep it brief and simple (probably no 3D transform going on, just simple opacity). We should also consider if this will tie into a future "widget layer" that lives onto the desktop or not, and if so, we should probably use the same sort of animation for it.

Another thing to keep in mind: the applets are keep-below, which means spatially they're below the windows. So they shouldn't come in on top of the other open windows or anything.

**Comment by donadigo** [comment]
As for performance: there should be really no performance cost on even more advanced effects since Clutter uses OpenGL internally to draw things, so as long as someone have an integrated or dedicated GPU, this should work no problem on older systems.
