### ISSUE TITLE
When 2 windows are tiled and then resized, the inactive one gets glitched, leaving its full-sized picture as an artifact when minimized.

### ISSUE THREAD

**Issue by 1280px** [elementary/gala#1584]
### What Happened?

See reconding:

https://user-images.githubusercontent.com/71165491/227715891-cc8ab7c5-2247-4503-ac89-fe6292ee86d9.mp4

_(recorded on VM with fresh Horus installed from ISO, but can be reproduced on real hardware and with latest updates as well!)_

### Steps to Reproduce

1. [0:12] Open 2 any apps that support tiling 
2. [0:22] Tile the apps, so they would "snap" to each other

3. _(at this point, the bug is not presented, and none of the windows leave any artifacts)_

4. [0:32] Resize one of the apps (it will automatically resize the "snapped" one as well)
5. [0:44] Try to minimize the **inactive** tiled app
6. _(at this point, you can untile everything else and resize the glitched app however you want. The bug will only go away after the glitched instance is closed)_

### Expected Behavior

Step 6 problems wouldn't occur.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment]
Hello, thanks for reporting. Can you check if #1585 fixes the issue for you please?

**Comment by 1280px** [comment]
Hello! Yes — the inactive windows don't leave any artifacts now, at least from what I've tested.

While testing, though, I found one more small bug with window tiling. It's not a regression, as I managed to reproduce it on VM with no patch as well: #TBD
