### ISSUE TITLE
WM allows tiling the second window near the first tiled window, no matter if the width is enough for it to fit

### ISSUE THREAD

**Issue by 1280px** [elementary/gala#1586]
### What Happened?

See recording:

https://user-images.githubusercontent.com/71165491/227735607-7ce7743a-7659-451d-ba8b-f6fdabd5d163.mp4

_(recorded on VM with fresh Horus installed from ISO, but can be reproduced on real hardware and with latest updates as well!)_

### Steps to Reproduce

1. [0:18] Open either 1 or 2 apps that support tiling, and tile them the specific way there's only a narrow gap left for a new window to be tiled.

2. The window manager will suggest to tile the windows into this space, no matter if the width is smaller than the minimal width of the window to be tiled [0:36] or not [0:52].

3. [0:42] In the first case, tiling the window will turn it to a state when WM treats it as maximized, even though it's actually not.

### Expected Behavior

There should be a check if the window's minimal height is enough to fit it in (just like with regular tiling)

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment]
I can reproduce the issue in Fedora 37 with Gnome 43, so I guess this is an issue in mutter.

**Comment by 1280px** [comment]
Yeah, managed to replicate on F38 beta as well. Closing the issue as out-of-scope

**Comment by 1280px** [comment]
wrong button, dammit
