### ISSUE TITLE
All text gone after suspension

### ISSUE THREAD

**Issue by inad9300** [elementary/gala#16]
Sometimes after coming back from a suspended state, this happens:

![screenshot from 2017-06-03 18 41 55](https://cloud.githubusercontent.com/assets/3440331/26759922/87593fba-490c-11e7-87ab-9380d6894057.png)

![screenshot from 2017-06-03 18 42 07](https://cloud.githubusercontent.com/assets/3440331/26759925/95159e96-490c-11e7-8682-e0c6acbfa753.png)

**Comment by cassidyjames** [comment]
This is an Intel driver issue, not a Gala issue. @inad9300 can you open a Terminal and run

```shell
lsb_release -a && uname -r && lspci -v | grep VGA -A 1
```

...to output some pertinent system information?

**Comment by inad9300** [comment]
I can happily do so. Here is the output:
```
No LSB modules are available.
Distributor ID:	elementary
Description:	elementary OS 0.4.1 Loki
Release:	0.4.1
Codename:	loki
4.4.0-83-generic
00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06) (prog-if 00 [VGA controller])
	Subsystem: Lenovo 4th Gen Core Processor Integrated Graphics Controller
--
01:00.0 VGA compatible controller: NVIDIA Corporation GK107M [GeForce GT 755M] (rev ff) (prog-if ff)
	!!! Unknown header type 7f
```
