### ISSUE TITLE
Shortcuts such as ctrl+e, ctrl+c, ctrl+v doesn't work on russian keyboard layout in intelliJ

### ISSUE THREAD

**Issue by ityulkanov** [elementary/gala#1601]
## Prerequisites
- [x ] I have searched open and closed issues for duplicates.

## Describe the bug

Seems that it is an OS bug, hotkeys doesn't work on NetBeans as well, so I assume any Java based app might have the same problem - their shortcuts only works with english language, but not russian.  

On russian layout none of the shortcuts in Intellij Community 2020.1, and NetBeans work.

### To Reproduce
1. Go to Intellij Community Edition 2020.1 or NetBeans IDE10
2. Click switch keyboard to russian layout
3. Try to copy, paste, or cut keyboard shortcuts
4. Nothing happens
5. Switch to english keyboard layout -> all shortcuts works. 

### Expected behavior

Shortcuts works no matter which layout I use - russian or english. 

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [ x] I'm using the latest released stable version

**Comment by lenemter** [comment]
Cannot reproduce the issue in OS 7. Recently #1589 got merged which should have solved most issues like this. Reply here if you still encounter the issue please.

**Comment by archdron** [comment]
Just spun up the Elementary 7 virtual machine, selected two keyboard layouts (eng, ukr) during the installation, and applied all the updates with apt and flatpak.

In-app keyboard shortcuts (specifically [modifier+letter]) still don't work in OmegaT (neither flatpak nor the tarball from the website), IntelliJ (flatpak), or NetBeans (flatpak). The shortcuts [modifier + number] or [modifier + F-key] do work, however.

**Comment by lenemter** [comment]
@archdron You are right, reopened.

**Comment by lenemter** [comment]
Interesting... I just tried it again and shortcuts in OmegaT worked fine with Russian layout.

@archdron The new gala release is out so can you confirm that this is fixed on your end too please?

**Comment by archdron** [comment]
I confirm, the bug is no longer there! Tested in a freshly updated Elementary 7 VM, with OmegaT and IntelliJ IDEA. Thank you so much! ♥️

**Comment by lenemter** [comment]
@archdron Thank you!

Closing as fixed.
