### ISSUE TITLE
Bottom of screen glitches with NVIDIA 340 drivers

### ISSUE THREAD

**Issue by Argentus** [elementary/gala#161]
The bottom ~20 pixel line of screen flickers - either replaced by some magenta/black glitch or rotates some amount to the right (whole line is shifted to the right, what was "pushed out" of the screen appears on the left side).
This happens on desktop view and login screen, not in app windows. When I run `mutter --replace` , problem is not present. (But I don't want to use mutter).

Machine is MacBook "Core 2 Duo" 2.26 13-Inch, with NVIDIA GeForce 9400M

UPDATE: Now I noticed this also sometimes happening in Chrome browser, so not sure if this is specifically Gala-related.

**Comment by peteruithoven** [comment]
This might be related to:
https://github.com/elementary/gala/issues/21
https://elementaryos.stackexchange.com/questions/8952/artifacts-in-background

**Comment by Argentus** [comment]
Not sure if related. I also had problem with the mentioned artifacts, but this is not affected by restarting the window manager and is not something that occurs and then stays corrupted until you fix it, it is something constantly happening - the glitch area flickering on and off etc.

**Comment by AlecThompson** [comment]
> Got the same issue. Nvidia geforce 9400m on macbook pro 5.5 (mid 2009). It goes away within first minute(s).

did you ever figure out a way to fix this issue?

**Comment by AlecThompson** [comment]
> The bottom ~20 pixel line of screen flickers - either replaced by some magenta/black glitch or rotates some amount to the right (whole line is shifted to the right, what was "pushed out" of the screen appears on the left side).
> This happens on desktop view and login screen, not in app windows. When I run `mutter --replace` , problem is not present. (But I don't want to use mutter).
> 
> Machine is MacBook "Core 2 Duo" 2.26 13-Inch, with NVIDIA GeForce 9400M
> 
> UPDATE: Now I noticed this also sometimes happening in Chrome browser, so not sure if this is specifically Gala-related.
> 
> Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/54123220-bottom-of-screen-glitches-with-nvidia-340-drivers?utm_campaign=plugin&utm_content=tracker%2F62872462&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F62872462&utm_medium=issues&utm_source=github).

did you ever find a way to fix this issue?

**Comment by thefoxie** [comment]
> > Got the same issue. Nvidia geforce 9400m on macbook pro 5.5 (mid 2009). It goes away within first minute(s).
> 
> did you ever figure out a way to fix this issue?

@AlecThompson I switched to Antergos (arch linux with GUI installer and preconfigured gnome) as I've used Arch since 2011. I don't care about proprietary drivers anymore. I remember I had it working on xorg session (except brightness control which I could control only via different shortcut). I even went to the depth of having former triple finger drag/select or what it was back in 2016 available on mac os. Lol they moved it to accessibility menu https://support.apple.com/HT20460

**Comment by Argentus** [comment]
> > The bottom ~20 pixel line of screen flickers - either replaced by some magenta/black glitch or rotates some amount to the right (whole line is shifted to the right, what was "pushed out" of the screen appears on the left side).
> > This happens on desktop view and login screen, not in app windows. When I run `mutter --replace` , problem is not present. (But I don't want to use mutter).
> > Machine is MacBook "Core 2 Duo" 2.26 13-Inch, with NVIDIA GeForce 9400M
> > UPDATE: Now I noticed this also sometimes happening in Chrome browser, so not sure if this is specifically Gala-related.
> > Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/54123220-bottom-of-screen-glitches-with-nvidia-340-drivers?utm_campaign=plugin&utm_content=tracker%2F62872462&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F62872462&utm_medium=issues&utm_source=github).
> 
> did you ever find a way to fix this issue?

No and yes - with the latest elementaryOS I experience none of the problems I had with the open-source driver. Suspend works OK and performance seems fine. So I simply do not have a reason to use the proprietary driver anymore and that fixes this issue for me.

**Comment by peteruithoven** [comment]
I would love if someone could include a screenshot / screenrecording to clarify where this happens and how this looks.

**Comment by gallerman** [comment]
I don't know if I am able to help. I am running Ubuntu and I have the problem . I was considering to install elementary just because @argentus says it fixed the problem.  Do you want me to put the screenshot?

**Comment by peteruithoven** [comment]
Depends on the screenshot... :P 
If you see it in Ubuntu you should raise the issue with Ubuntu, that might also solve the issue for elementary OS since it build on top of Ubuntu.

**Comment by Blast-City** [comment]
> The bottom ~20 pixel line of screen flickers - either replaced by some magenta/black glitch or rotates some amount to the right (whole line is shifted to the right, what was "pushed out" of the screen appears on the left side).
> This happens on desktop view and login screen, not in app windows. When I run `mutter --replace` , problem is not present. (But I don't want to use mutter).
> 
> Machine is MacBook "Core 2 Duo" 2.26 13-Inch, with NVIDIA GeForce 9400M
> 
> UPDATE: Now I noticed this also sometimes happening in Chrome browser, so not sure if this is specifically Gala-related.
> 
> Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/54123220-bottom-of-screen-glitches-with-nvidia-340-drivers?utm_campaign=plugin&utm_content=tracker%2F62872462&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F62872462&utm_medium=issues&utm_source=github).

Sorry for the Off Topic, but could you tell me how much ram do you have on your computer?

Thanks.

**Comment by Argentus** [comment]
> > The bottom ~20 pixel line of screen flickers - either replaced by some magenta/black glitch or rotates some amount to the right (whole line is shifted to the right, what was "pushed out" of the screen appears on the left side).
> > This happens on desktop view and login screen, not in app windows. When I run `mutter --replace` , problem is not present. (But I don't want to use mutter).
> > Machine is MacBook "Core 2 Duo" 2.26 13-Inch, with NVIDIA GeForce 9400M
> > UPDATE: Now I noticed this also sometimes happening in Chrome browser, so not sure if this is specifically Gala-related.
> > Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/54123220-bottom-of-screen-glitches-with-nvidia-340-drivers?utm_campaign=plugin&utm_content=tracker%2F62872462&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F62872462&utm_medium=issues&utm_source=github).
> 
> Sorry for the off topic, but could you tell me how much ram do you have on your computer?
> 
> Thanks.

8GB RAM

**Comment by gallerman** [comment]
I found the workaround to make it work.... I have 8 GB of memory but the
workaround was to use the open source driver instead of the provided by
Nvidia.. ¯\_(ツ)_/¯

**Comment by Blast-City** [comment]
> > > The bottom ~20 pixel line of screen flickers - either replaced by some magenta/black glitch or rotates some amount to the right (whole line is shifted to the right, what was "pushed out" of the screen appears on the left side).
> > > This happens on desktop view and login screen, not in app windows. When I run `mutter --replace` , problem is not present. (But I don't want to use mutter).
> > > Machine is MacBook "Core 2 Duo" 2.26 13-Inch, with NVIDIA GeForce 9400M
> > > UPDATE: Now I noticed this also sometimes happening in Chrome browser, so not sure if this is specifically Gala-related.
> > > Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/54123220-bottom-of-screen-glitches-with-nvidia-340-drivers?utm_campaign=plugin&utm_content=tracker%2F62872462&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F62872462&utm_medium=issues&utm_source=github).
> > 
> > 
> > Sorry for the off topic, but could you tell me how much ram do you have on your computer?
> > Thanks.
> 
> 8GB RAM

Hi.

So you have put more ram than the officially supported, right? Does it recognize all the ram? Did you noticed any problem using Linux?

Thanks and sorry for asking this questions here, but I have a similar computer and I'm debating if I should upgrade it to 8GB or 4GB.

**Comment by Blast-City** [comment]
> I found the workaround to make it work.... I have 8 GB of memory but the workaround was to use the open source driver instead of the provided by Nvidia.. ¯\_(ツ)_/¯
> […](#)

One weird thing that I noticed when I tried Loki was, when using the Live USB, turning down the brightness all the way down would turn off the display, but when I installed the OS, the display wouldn't turn off. Because of this, the display would sort of flicker when on the minimum brightness.

Is it the same on Juno?

**Comment by peteruithoven** [comment]
I'm going to close the issue as out of scope because it's most likely a proprietaryy Nvidia driver issue and incomplete because we're not getting the required information from the author. 
There are also a lot of offtopic discussions, that should probably happen on other communication channels like stack exchange, reddit or slack.

**Comment by amminadabz** [comment]
I'm having this issue as well, so here's a video. Hope we can find a solution.
https://photos.app.goo.gl/jQ4A8cX4akhETx4YA

**Comment by mhixson** [comment]
I'm seeing this exact same thing on my MacBook. The only reason I want to use the NVidia driver over the open source one is because the NVidia driver can control the screen brightness. If it weren't for this feature I'd be totally fine with the open source driver. Is there a way to control screen brightness with the open source driver that I don't know about? Thanks.

**Comment by Argentus** [comment]
My brightness setting works fine with the open source driver.

**Comment by thefoxie** [comment]
Everything works flawlessly on nouveau (open drivers) but I think it draws more power. I use my old MBP with arch and closed drivers on xorg instead of wayland and I can even get multitouch gestures working.

**Comment by Tha14** [comment]
Hello, I am also experiencing this exact same issue on the Macbook6,1 late 2009. What I found out is that if I increase the Underscan option in "X Server Display Configuration" by one the problem completely disappears but I cannot reach the dock anymore. This only happens when using gala. I need to use the nvidia proprietary driver for some opengl features that nouveau has issues with and for the overall performance increase(Which is quite noticeable).

**Comment by jemerocay** [comment]
I did what @Tha14 recommended and the issue seems to be resolve on ubuntu 18

**Comment by amminadabz** [comment]
I think that worked for me! (on my a1342 with the latest elementary updates)
I set the underscan to 1 (see screenshot), and it solved the problem. However, it reverted after a restart, so I clicked "Save to X Configuration File" and created the file at /etc/X11/xorg.conf and then it stuck around after restarts. However, the macbook no longer can wake from suspend properly, and I cannot adjust the brightness from the usual keyboard buttons. I will investigate more into where the noveau driver stores its xorg.config and try to merge the two together and see if that solves any problems or just creates more.
Please note that I know almost nothing about how the linux desktop or graphics drivers work under the hood, so anyone more qualified is welcome to correct me.
I will soon test whether this driver now works with multiple monitors, as this was my original goal.
![Screenshot from 2020-03-01 21 23 35](https://user-images.githubusercontent.com/51542239/75643300-2fcfe600-5c04-11ea-8b18-d18c17493527.png)

**Comment by Tha14** [comment]
> 
> 
> I think that worked for me! (on my a1342 with the latest elementary updates)
> I set the underscan to 1 (see screenshot), and it solved the problem. However, it reverted after a restart, so I clicked "Save to X Configuration File" and created the file at /etc/X11/xorg.conf and then it stuck around after restarts. However, the macbook no longer can wake from suspend properly, and I cannot adjust the brightness from the usual keyboard buttons. I will investigate more into where the noveau driver stores its xorg.config and try to merge the two together and see if that solves any problems or just creates more.
> Please note that I know almost nothing about how the linux desktop or graphics drivers work under the hood, so anyone more qualified is welcome to correct me.
> I will soon test whether this driver now works with multiple monitors, as this was my original goal.
> Edit: It works with multiple monitors. I had to restart while the monitor was plugged in once, but after that I can plug and unplug as much as I want.
> ![Screenshot from 2020-03-01 21 23 35](https://user-images.githubusercontent.com/51542239/75643300-2fcfe600-5c04-11ea-8b18-d18c17493527.png)

Hey, I completely forgot to reply to you but I fixed my backlight issue with nvidiabl. I don't know if it is of any help to you now. You need version  0.88 from this repo https://github.com/madsherlock/nvidiabl
It fixed my backlight but I kept having issues with it going to full brightness when starting certain applications. In the end I settled for dual-booting windows 10(without proper backlight but not a huge issue since everything else works.) and macos sierra. Cheers

**Comment by Imhaet** [comment]
> I think that worked for me! (on my a1342 with the latest elementary updates)
> I set the underscan to 1 (see screenshot), and it solved the problem. However, it reverted after a restart, so I clicked "Save to X Configuration File" and created the file at /etc/X11/xorg.conf and then it stuck around after restarts. However, the macbook no longer can wake from suspend properly, and I cannot adjust the brightness from the usual keyboard buttons. I will investigate more into where the noveau driver stores its xorg.config and try to merge the two together and see if that solves any problems or just creates more.
> Please note that I know almost nothing about how the linux desktop or graphics drivers work under the hood, so anyone more qualified is welcome to correct me.
> I will soon test whether this driver now works with multiple monitors, as this was my original goal.
> Edit: It works with multiple monitors. I had to restart while the monitor was plugged in once, but after that I can plug and unplug as much as I want.
> ![Screenshot from 2020-03-01 21 23 35](https://user-images.githubusercontent.com/51542239/75643300-2fcfe600-5c04-11ea-8b18-d18c17493527.png)

To enable the brightness with the usual Mac buttons you may need to edit your xorg.conf file, on the Screen section and add the following line and reboot:
`Option         "RegistryDwords" "EnableBrightnessControl=1;"`

This happened to me on Debian so I followed the instructions on the troubleshooting from [this page](https://wiki.debian.org/NvidiaGraphicsDrivers).

My xorg.conf file looks like this:
Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option "metamodes" "nvidia-auto-select +0+0 { viewportout=1278x798+1+0 }"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection

**Comment by Humming-Owl** [comment]
I had this issue (Lubuntu 18.04) and the workaround mentioned above helped with the issue (Geforce 9400M). But this issue does not occur if installing the driver directly from the RUN file provided by the NVIDIA website (I had to upgrade the kernel to the lastest available on Lubuntu 18.04 because the installer was complaining about the previous one). Cheers.
