### ISSUE TITLE
Automatically set wallpapers for light/dark mode

### ISSUE THREAD

**Issue by aitor-gomila** [elementary/gala#1615]
### Problem

I have my elementary set to auto change to dark mode & night light when it's 7PM. Problem is I have to change the wallpaper manually every time this happens.

### Proposal

It would be nice if we could have a wallpaper for light theme and dark theme. How would this be implemented?

**Comment by lenemter** [comment]
I'll close this in favour of https://github.com/elementary/switchboard-plug-pantheon-shell/issues/261. Adding support for this in Gala is easy and straightforward but a lot more work needs to be done in the Pantheon Shell plug.
