### ISSUE TITLE
Option to Disable/Enable Hot Corners 

### ISSUE THREAD

**Issue by hrstwn** [elementary/gala#1648]
### Problem

Hot corners is a really nice feature that I use a lot, but on certain apps, it's quite annoying to have it activated. Especially when playing games that expect the cursor to go from corner to corner. In my case, (on some Proton games, so it's probably not elementary's fault) sometimes the _multitasking view_ makes the game crash and the _maximize current window_ moves the game window to another monitor which makes it necessary for me to turn it off. 

The problem is, the only way right now to make this work is to open settings, and set all my corners manually (one by one) to _'do nothing'_ whenever I want to play games, and reactivating it (one by one) when I'm done with my game. It's probably a very niche problem and not many people have the issue but I'd be very thankful if it's solved.

### Proposal

I think it'd be nice to have an switch to disable/enable hot corners or maybe a checkbox to disable hot corners for full-screen apps only. I'm not sure.

**Comment by danirabbit** [comment]
I think it probably makes sense for us to disable hotcorners altogether for fullscreen apps.

Thoughts @lenemter ?

**Comment by danirabbit** [comment]
@lenemter that makes sense to me. Just a single setting to enable/disable all hot corners for full screen apps probably solves the issue
