### ISSUE TITLE
Window switcher mouse interaction issue

### ISSUE THREAD

**Issue by peteruithoven** [elementary/gala#1657]
### What Happened?

I noticed that the window switcher, when it's on my secondary screen, doesn't always respond to mouse hovers / clicks properly. In some cases it stops responding to the mouse completely. 

In the following screenrecording you can see alt+tab works fine. But it only responds to mouse hovers on the last 2 items. When the applications change it's still the last 2 items that respond. 
![Peek 2023-04-15 18-18](https://user-images.githubusercontent.com/523210/232237698-a93c44fe-4690-44b7-9855-98b19d6524a2.gif)

When this happens the window switcher on my primary screen works perfectly. 

### Steps to Reproduce

1. Unknown
2. Move mouse to secondary screen and pressing alt tab
3. Hover over items

### Expected Behavior

All items respond to hovers and when clicked the application is focused. 

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by ngnhat** [comment]
my cycle windows border has a issue too.
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/22524118/235284426-e5d14489-b2c1-4ed7-89f0-606164c50eb1.gif)

**Comment by peteruithoven** [comment]
@ngnhat can you use a few more words. I have no idea what issue you're showing in your screen recording.

**Comment by ngnhat** [comment]
sorry,
I got few white pixels on border radius.
Now I'm not using this OS, Idk if this issue still exists or has been resolved.

**Comment by peteruithoven** [comment]
But that's not at all what this issue is about.
