### ISSUE TITLE
Four finger (horizontal) swipe to Tile hovered window to the side to which it was swiped

### ISSUE THREAD

**Issue by rasmus91** [elementary/gala#1667]
### Problem

Since we gained multitouch gestures in elementary OS, the touchpad has become much more of a natural way to interact with the desktop, workspaces and windows. Many have a workflow with tiled windows in workspaces, being able to tile a window with a quick gesture would support this well.

### Proposal

Simply allowing users in the gestures config to configure a four finger horizontal swipe to tile windows, would enable easy tiling via touchpad. (could also be three fingers, if there should be more options). I think this would be a very intutive expansion of the gestures functionality.

**Comment by lenemter** [comment]
Hello! Thanks for reporting. There is a similar issue https://github.com/elementary/gala/issues/1151 so I'll close this issue as a duplicate.

**Comment by rasmus91** [comment]
> Hello! Thanks for reporting. There is a similar issue #1151 so I'll close this issue as a duplicate.

Sorry I completely missed that even as I looked through existing :(
