### ISSUE TITLE
No context menu on wallpaper in Wayland

### ISSUE THREAD

**Issue by danirabbit** [elementary/gala#1695]
### What Happened?

I'm not able to reliably open the context menu when running under Wayland

### Steps to Reproduce

1. Run a wayland session
2. secondary click the wallpaper
3. Nothing happens

### Expected Behavior

Context menu with options for changing the wallpaper, display settings, etc

### OS Version

7.x (Horus)

### Software Version

Compiled from git

**Comment by monomere** [comment]
Installed on arch manually (today) and it works the first time but fails after that.
