### ISSUE TITLE
Three Finger Swipe Gesture (or something similar) to Scroll Through Windows 

### ISSUE THREAD

**Issue by theuser18** [elementary/gala#1699]
### Problem

Currently, there is not a great way to switch windows if you have many open, especially if you have multiple windows of the same application open.

Adding a gesture to quickly scroll through windows would great improve laptop workflow.

### Proposal

Add the option to scroll through and select a window to bring the the foreground using a three finger gesture.

**Comment by lenemter** [comment]
Closing as duplicate of https://github.com/elementary/gala/issues/979
