### ISSUE TITLE
Always on top from right click menu doesn't always get applied to the window

### ISSUE THREAD

**Issue by Nine-H** [elementary/gala#17]
setting one app to always on top is great (unless it's gtk2 where the menu doesn't appear)

setting two apps to always on top means that the first one is always on top, and the second one sinks when it loses focus to a non always on top window that overlaps it.

expected behaviour: on top windows should only sink if another on top window that overlaps it gets focus: there should be a "top layer" window buffer for the top flagged windows that keeps them on top instead of just one.

**Comment by Philip-Scott** [comment]
Which windows are you trying to set to the top, and what method are you using to do so? I use set `Super + T` to set the window on top right from the Keyboard Settings and i can't confirm that it's not working as expected

**Comment by Nine-H** [comment]
I updated and rebooted my computer (on stable) and it keeps happening, here are the steps to reproduce:

1. open chromium
2. open appcenter
3. open scratch
4. set scratch to always on top from the right click menu
5. set appcenter to always on top from right click menu
6. click chromium icon on plank or it's titlebar

it will pop up _UNDER_ scratch, and _OVER_ appcenter.

the correct behaviour for one window always on top is _OVER_ scratch, _UNDER_ appcenter
the correct behaviour if you allow multiple always on top windows is _UNDER_ scratch, _UNDER_ appcenter _OVER_ any other shit you have open.

I believe that multiple always on top windows is the correct behaviour because it allows users to "pin" multiple widget apps over for example a browser window.

**Comment by Philip-Scott** [comment]
Interesting... It appears that the always on top doesn't always get applied from the right click menu. I think that's the bug here

**Comment by Nine-H** [comment]
cool beans. how do I work around this bug like you did? because I want tomato and hourglass to keep me focused when I study.

**Comment by Philip-Scott** [comment]
You could set a keyboard shortcut to toggle always on top.

`Settings > Keyboard > Shortcuts`

![screenshot from 2017-06-12 07 48 57](https://user-images.githubusercontent.com/10786508/27034505-da592870-4f32-11e7-9a9f-e3ff60e6a513.png)
