### ISSUE TITLE
PiP doesn't become visible by changing workspaces

### ISSUE THREAD

**Issue by zeebok** [elementary/gala#1700]
### What Happened?

If you switch workspaces away from the window you activated PiP on, the PiP view will not appear.

### Steps to Reproduce

1. Activate PiP for a window
2. Make sure that window is focused and the PiP view is hidden
3. Change workspaces
4. Note PiP view is still hidden

### Expected Behavior

Changing workspaces should have the same behavior as changing windows and show/hide the PiP view as necessary.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by zeebok** [comment]
Something I just noticed was that if I am in this state and a notification appears, so the does PiP. It then disappears along with the notification.

**Comment by etorkay** [comment]
> 

I can confirm. The same issue regarding the PiP disappearing after notification or any other Wingpanel notification like adjusting the volume, the volume pop-up also makes PiP disappear.
