### ISSUE TITLE
Alt+Tab switcher's background is always dark

### ISSUE THREAD

**Issue by TomiOhl** [elementary/gala#1706]
### What Happened?

The Alt+Tab switcher's background stays always dark, no matter the style set in the system. The color of the app names changes, but the background doesn't.
This only happens since 7.1.0.

### Steps to Reproduce

1. Toggle system style to dark
2. Alt+Tab - notice that the switcher's background is dark, the text is white (as expected)
3. Toggle system style to light
4. Alt+Tab - notice that the switcher's background is still dark and the text is black

### Expected Behavior

The switcher's background should be light with light system style.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment]
Probably introduced in https://github.com/elementary/gala/pull/1686

**Comment by TomiOhl** [comment]
Not sure about you but for me this fixed it only partially.
After reboot, starting with light theme everything is fine.
If I switch to dark theme and then back to light, the switcher's background stays dark.
I have installed all updates (including 7.1.1).

**Comment by TomiOhl** [comment]
What I did:
- be on v7.1.1, reboot
- theme is light, switcher is light
- change style to dark in settings/desktop
- theme is dark, switcher is dark
- change style back to light in settings/desktop
- theme is light, switcher's background is still dark
- now if I reboot, the switcher will be light (correct) until I switch to dark style

**Comment by lenemter** [comment]
That's weird, it doesn't happen on my side. Can you maybe reinstall gala `sudo apt reinstall gala` or give some logs (run `gala --replace` in Terminal and reproduce the bug)

**Comment by TomiOhl** [comment]
The only log that's printed to the terminal when reproducing the bug:
```
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2000003
```
I get this every time I switch windows via a three finger swipe gestures (I have touchégg configured to execute alt+tab / alt+shift+tab). What's weird is that I don't get this line when I'm pressing the keys themselves

Full log since running `gala --replace`:
```
libmutter-Message: 16:51:24.417: Running Mutter(Gala) (using mutter 42.9) as a X11 window and compositing manager

(gala:30784): libmutter-CRITICAL **: 16:51:24.646: meta_sound_player_play_from_theme: assertion 'META_IS_SOUND_PLAYER (player)' failed
Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.

(gala:30784): libmutter-CRITICAL **: 16:51:24.647: meta_sound_player_play_from_theme: assertion 'META_IS_SOUND_PLAYER (player)' failed
Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
Window manager warning: Trying to re-add keybinding "switch-to-workspace-last".
Window manager warning: Trying to re-add keybinding "move-to-workspace-last".
Window manager warning: Overwriting existing binding of keysym 2b with keysym 31 (keycode a).
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x6200003
Window manager warning: Overwriting existing binding of keysym 2b with keysym 31 (keycode a).

(gala:30784): Clutter-CRITICAL **: 16:51:39.393: clutter_animatable_get_actor: assertion 'CLUTTER_IS_ANIMATABLE (animatable)' failed

(gala:30784): Clutter-CRITICAL **: 16:51:39.393: clutter_animatable_get_actor: assertion 'CLUTTER_IS_ANIMATABLE (animatable)' failed
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2000003
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2000003
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2000003
```

(Haven't tried reinstalling yet, will try it later)

**Comment by TomiOhl** [comment]
Reinstalled gala, that didn't solve the problem either.

**Comment by TomiOhl** [comment]
Weird: I just reproduced the issue on another machine that had installed OS7 since the beginning and I've just installed updates on it.

**Comment by TomiOhl** [comment]
Finally it got fixed for me, too, on both machines, after updating to 7.1.2.

**Comment by TomiOhl** [comment]
It also seems to be affected by `gtk-application-prefer-dark-theme`? I accidentally left it set to 1, rebooted, and the switcher's background was always dark. Set it to 0, rebooted, and it changes style correctly again.
