### ISSUE TITLE
Animation for effect minimize and maximize

### ISSUE THREAD

**Issue by torikulhabib** [elementary/gala#171]
i hope elementary os add Animation for effect minimize and maximize.

**Comment by Djaler** [comment]
Does not it exist?

**Comment by torikulhabib** [comment]
![screenshot from 2018-02-18 20 02 46](https://user-images.githubusercontent.com/26135527/36352115-ba440e68-14e6-11e8-815f-668e2a42367a.png)

i hope there are option minimize and maximize animation.
like magic lamp or fade.

**Comment by Djaler** [comment]
This is not about elementary.

**Comment by peteruithoven** [comment]
@torikulhabib could you please clarify? 
You hope for what kind of animations? 
How does that relate to Universal Access? Do you want to be able to enable / disable those animations? Could you clarify why you think that's important?

**Comment by Djaler** [comment]
@peteruithoven he talk about animation change, like in KDE.

**Comment by torikulhabib** [comment]
@Djaler Yes..
@peteruithoven I wish there was an option to change the animation that varied.
I was amazed like an animation like a "magic lamp".
option to be changed option entered in univesal access.
This Option beautifull for elementary.
![efek-genie](https://user-images.githubusercontent.com/26135527/36352583-a2693230-14ed-11e8-83a9-98a80c7124d0.png)

**Comment by peteruithoven** [comment]
> I wish there was an option to change the animation that varied.

"That varied"? You want it to vary between different animations? 

I still don't understand what the type of animation has to do with Universal Access.

**Comment by torikulhabib** [comment]
@peteruithoven sorry i just want to have animation option.
so that more concise choice is put in universal access.
if there is no connection with universal access.
please create a new switchboard for animation. thanks

**Comment by danrabbit** [comment]
Sorry, we don't intend to support many types of animations. A core part of the elementary philosophy is that we don't hand over design or engineering decisions to our users. If the current animations are bad, we should try to make them better, but making them completely configurable Compiz-style isn't something we'd do.

Closing as "Out of Scope"
