### ISSUE TITLE
gala won't start due to a Glib error

### ISSUE THREAD

**Issue by jmaris** [elementary/gala#172]
Hi, 

I understand that Gala is primarily an ElementaryOS project, and so I can't expect it to run on OS's other than ElementaryOS, But I recently compiled it on Arch and am getting an error on launch followed by a Trace/breakpoint trap and core dump : 
```
(gala:11963): GLib-GIO-ERROR **: Settings schema 'org.gnome.desktop.peripherals.touchpad' does not contain a key named 'tap-and-drag'
Trace/breakpoint trap (core dumped)
```

It appears for some reason dconf-editor shows that while the tap-and-drag key exists, the schema doesn't. Should gala be creating this or is it created/installed by another program ?

**Comment by tintou** [comment]
That is probably solved by now, in any case it is tied to a specific GNOME Settings Daemon and libmutter version
