### ISSUE TITLE
Notification icon glitches

### ISSUE THREAD

**Issue by markodp** [elementary/gala#173]
When you get notification for low disk space or new printer added, the icons on notifications do not draw properly.

This is how i reproduced the issue:
```
notify-send "Icon Testing" "printer-symbolic" --icon=printer-symbolic
notify-send "Icon Testing" "drive-harddisk-symbolic" --icon=drive-harddisk-symbolic
```
![screenshot from 2018-02-11 12 12 45](https://user-images.githubusercontent.com/805017/36072744-40af7d74-0f25-11e8-872d-2d3933108f20.png)

But it's interesting, if you use icons that are symbolic links to this icons (like drive-harddisk-system-symbolic or printer-network-symbolic), they are drawn just fine...

**Comment by danrabbit** [comment]
This was an issue in the icon set and it was resolved
