### ISSUE TITLE
Cursor only visible in window screenshots

### ISSUE THREAD

**Issue by peteruithoven** [elementary/gala#1737]
### What Happened?

When using the [Screenshot app](https://github.com/elementary/screenshot) (which [uses Gala to take the screenshots](https://github.com/elementary/screenshot/pull/147)) to take a screenshot of an area or the whole screen, after a delay, it doesn't seem to include the cursor. 
I read in https://github.com/elementary/screenshot/pull/147 it might not be possible to take area screenshots in Wayland, but I'm using regular elementary OS, and thus not using Wayland. 

![Screenshot of Screenshot settings@2x](https://github.com/elementary/gala/assets/523210/d148e788-6110-413e-aecd-17a8b25d6311)

### Steps to Reproduce

1. Open Screenshot app
2. Select area option
3. Enable Grab pointer
4. Add a Delay in seconds of for example 2
5. If selected area option: Drag area
6. If selected area option: Move cursor within area

### Expected Behavior

Cursor is visible in screenshot

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by janxkoci** [comment]
I can confirm and add that the cursor happens to be in a wrong place in certain apps (OnlyOffice at least). I suspect it might be due to custom window borders of the app in question, as it's off only by a little offset.

I wanted to include a screenshot in a comment on a bug report elsewhere and couldn't because of this issue (the cursor position was the most important part).

**Comment by peteruithoven** [comment]
As someone who designs UI's, it's often crucial to share things with cursor, to explain. To show things like: 
![Color blind](https://github.com/elementary/gala/assets/523210/cfa5eff5-b69d-46aa-8415-aa418bd7da79)
Now I'm forced to take screenshots of the window and then crop it. For every example. 

Also keep in mind that with browsers, things like native dropdowns/selects are not even included in the window screenshots, meaning there is no way to include the cursor. 

I hope this will at least be fixed when we move to Wayland.

**Comment by teamcons** [comment]
Still present in eOS 8
