### ISSUE TITLE
Disconnecting external monitor breaks the multi-tasking view

### ISSUE THREAD

**Issue by fayjie92** [elementary/gala#1750]
### What Happened?

When an external display is disconnected, elementary OS multi-tasking view gets broken. For example, if I disconnect an external monitor in Ubuntu, it moves the opened windows to the active workspace of the primary monitor. On elementary OS, it results in a plain black background (with missing background image, on clicking the multi-tasking view) with the windows. Moving those windows to new (may be one or sometimes more) workspace/s produces correct workspace with the background image. 

### Steps to Reproduce

- Connect an external monitor while elementary OS is open.
- Create multiple workspaces, move some windows to the external monitor. 
- Disconnect the monitor (you see the black background in multi-tasking)

(Sometimes, it produces correct multi-tasking view though. Keep doing the experiment until you see the black background.)

### Expected Behavior

Like ubuntu, move all the opened windows (external display) to the active workspace in the primary monitor.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by TomiOhl** [comment]
This is related to #1518. Handling multiple monitors causes problems in the multitasking view

**Comment by fayjie92** [comment]
To be more specific, whenever I disconnect the external monitor, it creates something like this:
![Screenshot from 2023-09-21 18 23 59](https://github.com/elementary/gala/assets/32283602/b8062621-a941-45f9-a386-d23caa2dc62c)
