### ISSUE TITLE
For some windows, the resize area extends into shadow.

### ISSUE THREAD

**Issue by jeremypw** [elementary/gala#178]
An example I have found is the git gui window.  For this window hovering anywhere in the shadow shows the "resize" arrow.  Click on the shadow selects the window.

Another example is the Slack app window.

**Comment by cassidyjames** [comment]
This is for all legacy decorations

**Comment by donadigo** [comment]
Noting: this is caused by that we can't use Gtk inside Gala / mutter. We probably will need to do what everyone else is doing - that is carying out the Gtk widgets in another process and exposing a DBus interface to communicate with that.

**Comment by Djaler** [comment]
This is really annoying, yeah
