### ISSUE TITLE
Notifications appear in the middle of the screen

### ISSUE THREAD

**Issue by wout** [elementary/gala#1783]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
I've just done a clean install of elementary OS and now notifications show up in the middle of the screen. It is as if a bunch of invisible notifications are created before the actual notification. So the notification slides in from the top but it's slightly phased, just as it would slide in when there is are multiple notifications. And that's also how it disappears.

It happens with notifications for all apps btw, it's not app-specific.

### To Reproduce
This is a clean install, nothing unusual, so I'm not sure how to reproduce it.

### Expected behavior
Notifications should be in the upper-right corner.

### Screenshots or screen recordings
![image](https://github.com/elementary/notifications/assets/107324/1af0141e-29a2-45ea-b4e5-fc37f79ccaca)

## Platform Information
```neofetch
         eeeeeeeeeeeeeeeee            wout@Framey 
      eeeeeeeeeeeeeeeeeeeeeee         ----------- 
    eeeee  eeeeeeeeeeee   eeeee       OS: elementary OS 7 Horus x86_64 
  eeee   eeeee       eee     eeee     Host: Laptop (12th Gen Intel Core) A8 
 eeee   eeee          eee     eeee    Kernel: 6.2.0-26-generic 
eee    eee            eee       eee   Uptime: 1 day, 17 hours, 21 mins 
eee   eee            eee        eee   Packages: 1895 (dpkg), 57 (flatpak) 
ee    eee           eeee       eeee   Shell: bash 5.1.16 
ee    eee         eeeee      eeeeee   Resolution: 3000x2000, 3840x2160 
ee    eee       eeeee      eeeee ee   DE: Pantheon 
eee   eeee   eeeeee      eeeee  eee   WM: Mutter(Gala) 
eee    eeeeeeeeee     eeeeee    eee   Theme: io.elementary.stylesheet.mint [GTK3] 
 eeeeeeeeeeeeeeeeeeeeeeee    eeeee    Icons: elementary [GTK3] 
  eeeeeeee eeeeeeeeeeee      eeee     Terminal: io.elementary.t 
    eeeee                 eeeee       CPU: 12th Gen Intel i7-1280P (20) @ 4.700GHz 
      eeeeeee         eeeeeee         GPU: Intel Alder Lake-P 
         eeeeeeeeeeeeeeeee            Memory: 12543MiB / 64003MiB 

```

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by danirabbit** [comment]
Should have been fixed in #1748
