### ISSUE TITLE
alt+shift+tab

### ISSUE THREAD

**Issue by ovdeathiam** [elementary/gala#18]
~~If you have windows A,B,C,D and start to cycle through them using *ALT+TAB* till you reach window C and then still holding *ALT* key aditionally press shift the expected behavior would be to **not do anything** and wait for either pressing *TAB* or releasing *ALT* while still in the app switcher mode.
Instead gala's window switcher disables itself efectivley changing our window order to C,A,B,D.
Having still *ALT+SHIFT* pressed if we tap *TAB* it starts the gala's app switcher behavior again and selects window D.~~

Update:
Switching keyboard layout is set to alt+shift which interferes when using alt+tab in conjunction with pressing shift to cycle back. The WindowSwitcher disables itself triggering above issue.

**Comment by erandros** [comment]
I agree.  
Would it be ok to make 'Switch Layout' Alt + Caps Lock by default? Is there a problem in doing so?

**Comment by ovdeathiam** [comment]
It's probably set to alt+shift to resemble what people are familiar with when coming from windows.

**Comment by cassidyjames** [comment]
Moving this issue to https://github.com/elementary/default-settings/issues/4
