### ISSUE TITLE
Color Picker portal

### ISSUE THREAD

**Issue by danirabbit** [elementary/gala#1807]
### Problem

It seems like we don't provide the color picker portal

https://mastodon.social/@markjones@prazeworks.uk/111387220591024269

### Proposal

Provide the color picker portal

**Comment by davidmhewitt** [comment]
We already implement `pick_color` on the `org.gnome.Shell.Screenshot` interface:
https://github.com/elementary/gala/blob/72b9e012f3160ec8a65cd4a523dfae0dab96b765/src/ScreenshotManager.vala#L235

Shouldn't be too much work to expose it as a portal too.
