### ISSUE TITLE
Grey lines on primary monitor top and bottom

### ISSUE THREAD

**Issue by leolost2605** [elementary/gala#1815]
### What Happened?

My primary monitor has two grey strips on top and bottom both on desktop and multitasking view.

Desktop:
![Screenshot from 2023-12-26 18 10 15](https://github.com/elementary/gala/assets/106322251/9c3eec9e-e35b-467c-9966-6ff750706016)

Multitasking view:
![Screenshot from 2023-12-26 17 42 13](https://github.com/elementary/gala/assets/106322251/6a5892e7-5285-48ae-bdda-29566ebdc1bc)

### Steps to Reproduce

1. Compile gala from master
2. Restart gala

### Expected Behavior

No rounded corners and no grey strips

### OS Version

7.x (Horus)

### Software Version

Compiled from git

### Hardware Info

Dual monitor setup

Nouveau nvidia drivers

**Comment by leolost2605** [comment]
I just realized that the desktop on the secondary monitor also has rounded corners

**Comment by kerunaru** [comment]
I think those rounded corners on every display are intended... Aren't they, @danirabbit ?

**Comment by lenemter** [comment]
@kerunaru the issue is about gray lines on the top and bottom.

**Comment by kerunaru** [comment]
@lenemter, I supposed that but I've thrown the question just in case. The original issue description doesn't make clear what is the complaint: the grey lines, the rounded corners or both :sweat_smile:

**Comment by leolost2605** [comment]
Oh i didn't know the rounded corners on desktop are intentional 😅
I just thought them connected to the strips because of the recent introduction of rounded corners on multitasking view but I'll change the issue description

**Comment by leolost2605** [comment]
@lenemter I've got really no idea what any of this is doing but removing [`content.set_rounded_clip_bounds (rect);`](https://github.com/elementary/gala/blob/c62024acd20c2b82bffac960e9239aea9624eb3a/src/Background/BackgroundManager.vala#L127) makes the grey lines go away and I've still got rounded corners in the multitasking view 🤷
