### ISSUE TITLE
Display "blibs" at regular intervals

### ISSUE THREAD

**Issue by druidtides** [elementary/gala#182]
Recently the display has been blipping by which I mean, small audio beep, then screen goes black, then reappears a second later.  Nothing is lost as far as I can tell but it happens every 20 min sometimes.  I didn't have this problem until lately so it may be something with a component or library.  I have updated and upgraded everything and did my best to clean out the repository but it still occurs so I haven't located the source of the problem. "Report a Problem" always indicates Gala is involved but I can't tell what from.  I don't seem to be able to copy the Report a Problem contents to a file? I am happy to try and track this down but some guidance is appreciated.  Is there a way to get the report posted here?
thanks

**Comment by peteruithoven** [comment]
Please add some more system information. For example a screenshot of the System Settings About page or the result of [neofetch](https://github.com/dylanaraps/neofetch). 

Maybe check, when it happens if something shows up in logs like `dmesg`.

**Comment by druidtides** [comment]
gnome-session[3014]: ** (gala:17892): WARNING **: NotifyServer.vala:635: Text was empty (or contained only whitespace)
 kernel: [ 4565.767305] gala[17892]: segfault at 0 ip 00007efc13ea0acb sp 00007ffedb7d06d0 error 4 in libgala-notify.so[7efc13e8c000+1c000]
 gnome-session[3014]: gnome-session-binary[3014]: WARNING: Application 'gala.desktop' killed by signal 11
 gnome-session-binary[3014]: WARNING: Application 'gala.desktop' killed by signal 11

**Comment by druidtides** [comment]
eeeeeeeeeeeeeeeee            jross@JamiesHPlaptop 
      eeeeeeeeeeeeeeeeeeeeeee         -------------------- 
    eeeee  eeeeeeeeeeee   eeeee       OS: elementary OS 0.4.1 Loki x86_64 
  eeee   eeeee       eee     eeee     Host: HP 250 G5 Notebook PC 
 eeee   eeee          eee     eeee    Kernel: 4.4.0-116-generic 
eee    eee            eee       eee   Uptime: 1 hour, 23 mins 
eee   eee            eee        eee   Packages: 3914 
ee    eee           eeee       eeee   Shell: bash 4.3.48 
ee    eee         eeeee      eeeeee   Resolution: 1920x1080, 1920x1080, 1920x1080 
ee    eee       eeeee      eeeee ee   DE: Pantheon 
eee   eeee   eeeeee      eeeee  eee   WM: Mutter(Gala) 
eee    eeeeeeeeee     eeeeee    eee   Theme: Elementary [GTK3] 
 eeeeeeeeeeeeeeeeeeeeeeee    eeeee    Icons: Elementary [GTK3] 
  eeeeeeee eeeeeeeeeeee      eeee     Terminal: pantheon-termin 
    eeeee                 eeeee       Terminal Font: Roboto Mono 10 
      eeeeeee         eeeeeee         CPU: Intel i7-6500U (4) @ 3.100GHz 
         eeeeeeeeeeeeeeeee            GPU: Intel HD Graphics 520 
                                      Memory: 3525MiB / 15938MiB

**Comment by bmagyar** [comment]
I am seeing the same thing. 

log:
```
Sep 12 07:43:23 blackbrick kernel: [ 2225.612425] gala[10216]: segfault at 0 ip 00007faa1d0b9acb sp 00007ffe2494b310 error 4 in libgala-notify.so[7faa1d0a5000+1c000]
Sep 12 07:43:23 blackbrick gnome-session[1792]: gnome-session-binary[1792]: WARNING: Application 'gala.desktop' killed by signal 11
gnome-session-binary[1792]: WARNING: Application 'gala.desktop' killed by signal 11
gnome-session[1792]: Window manager warning: Trying to re-add keybinding "switch-to-workspace-last".
gnome-session[1792]: Window manager warning: Trying to re-add keybinding "move-to-workspace-last".
gnome-session[1792]: ** (gala:10653): WARNING **: Preferences.vala:192: '/usr/share/themes/elementary/plank/dock.theme' is read-only!
```

Dmesg reports pretty much the same
`[ 2225.612425] gala[10216]: segfault at 0 ip 00007faa1d0b9acb sp 00007ffe2494b310 error 4 in libgala-notify.so[7faa1d0a5000+1c000]`

```
         eeeeeeeeeeeeeeeee            
      eeeeeeeeeeeeeeeeeeeeeee         ---------------- 
    eeeee  eeeeeeeeeeee   eeeee       OS: elementary OS 0.4.1 Loki x86_64 
  eeee   eeeee       eee     eeee     Host: 20AN00C1UK ThinkPad T440p 
 eeee   eeee          eee     eeee    Kernel: 4.13.0-38-generic 
eee    eee            eee       eee   Uptime: 43 mins 
eee   eee            eee        eee   Packages: 4398 (dpkg) 
ee    eee           eeee       eeee   Shell: bash 4.3.48 
ee    eee         eeeee      eeeeee   Resolution: 1920x1080, 1920x1200 
ee    eee       eeeee      eeeee ee   DE: Pantheon 
eee   eeee   eeeeee      eeeee  eee   WM: Mutter(Gala) 
eee    eeeeeeeeee     eeeeee    eee   Theme: elementary [GTK3] 
 eeeeeeeeeeeeeeeeeeeeeeee    eeeee    Icons: elementary [GTK3] 
  eeeeeeee eeeeeeeeeeee      eeee     Terminal: terminator 
    eeeee                 eeeee       CPU: Intel i7-4710MQ (8) @ 3.500GHz 
      eeeeeee         eeeeeee         GPU: NVIDIA GeForce GT 730M 
         eeeeeeeeeeeeeeeee            GPU: Intel 4th Gen Core Processor 
                                      Memory: 4133MiB / 15732MiB 
```

**Comment by danrabbit** [comment]
Closing since this was reported against a much older version of elementary OS and is likely resolved by newer hardware enablement. Please feel free to reopen if the issue still occurs
