### ISSUE TITLE
Missing gala-daemon systemd service

### ISSUE THREAD

**Issue by bobby285271** [elementary/gala#1826]
### What Happened?

I am trying to [drop `--builtin`](https://github.com/elementary/session-settings/blob/3476c89bbb66564a72c6495ac0c61f8f9ed7a3ec/xsessions/pantheon.desktop#L4) from session-settings and gala-daemon no longer autostarts.

`gala-daemon.desktop` was set hidden under systemd:

https://github.com/elementary/gala/blob/167862ae223b3483336ad3ed45bc2326ac3c167a/data/gala-daemon.desktop#L13

***P.s.:** https://github.com/elementary/session-settings/issues/17#issuecomment-1562589852 is now part of gnome-session 46.alpha.* /cc https://github.com/NixOS/nixpkgs/pull/140429

### Steps to Reproduce

[Drop `--builtin`](https://github.com/elementary/session-settings/blob/3476c89bbb66564a72c6495ac0c61f8f9ed7a3ec/xsessions/pantheon.desktop#L4), open switchboard, right click the titlebar (which is why gala-daemon was introduced: https://github.com/elementary/gala/pull/179)

### Expected Behavior

I imagine we add services and targets here and add it as a [required components](https://github.com/elementary/session-settings/blob/3476c89bbb66564a72c6495ac0c61f8f9ed7a3ec/systemd/meson.build#L14) in session-settings like other GSD stuff

### OS Version

NixOS

### Software Version

Latest release (I have run all updates)

**Comment by Marukesu** [comment]
For someone wanting to open a PR, here i have a `io.elementary.gala.daemon@.service` with:

```ini
[Unit]
Description=Gala Daemon
BindsTo=io.elementary.gala@.service
After=io.elementary.gala@.service

[Service]
Type=dbus
BusName=org.pantheon.gala.daemon
ExecStart=/usr/bin/gala-daemon
Slice=session.slice
```

and a override to `io.elementary.gala@.service` with:
```ini
[Unit]
Requires=io.elementary.gala.daemon@.service # Could be a Wants, so gala doesn't fail to start without the daemon
```

This way there's no need to change the required components in the gnome-session units.
