### ISSUE TITLE
Multitasking View eats shortcuts

### ISSUE THREAD

**Issue by cassidyjames** [elementary/gala#185]
We had to pull the Multitasking View option from https://github.com/elementary/switchboard-plug-keyboard/pull/147 because Gala eats the super shortcut when in the multitasking view. This means we can open the overview, but can't close it.

**Comment by cassidyjames** [comment]
This also affects Super+Tab for switching workspaces, as reported at https://twitter.com/ninethehacker/status/1138326723085234176

**Comment by danirabbit** [comment]
It seems like this was fixed. Most likely in #1530
