### ISSUE TITLE
Be able to move a window left on the left-most workspace

### ISSUE THREAD

**Issue by Blast-City** [elementary/gala#187]
Hi.  

What do you guys think of this feature?  

This would make workspaces simpler to organize.

**Comment by cassidyjames** [comment]
Yeah, from a user perspective I like the idea that you can create a new workspace on the left as well as the right. This would make it feel a lot more flexible, and we already do this in the overview with drag-and-drop.

**Comment by Astro-City** [comment]
The only problem that i see happening is the animation that you get when you move a window to the second workspace will not be present. The focused windows will remain static and the other windows wil move like when you use the shortcut move to workspace X 

I tried to create a workspace to left of the first using the the overview (Super+Down) and it dindn't work.  

Is this a new feature on Juno or am i missing something?
