### ISSUE TITLE
Window switcher is missing Plank's shadow

### ISSUE THREAD

**Issue by cassidyjames** [elementary/gala#191]
Plank:
![screenshot from 2018-03-09 10 19 23 2x](https://user-images.githubusercontent.com/611168/37220305-75f52476-2383-11e8-9510-3576d97d8748.png)

Gala window switcher:
![screenshot from 2018-03-09 10 19 07 2x](https://user-images.githubusercontent.com/611168/37220326-7f06f9ea-2383-11e8-8e2a-daea32092ec0.png)

**Comment by lenemter** [comment]
Resolved in #1234
