### ISSUE TITLE
MultiTaskingView: Windows are all over the place sometimes

### ISSUE THREAD

**Issue by leolost2605** [elementary/gala#1911]
### What Happened?

Ignore the white borders that's because I disable shadow effects by returning a null texture since that's still using gtk :)

![Screenshot from 2024-05-26 14 22 42](https://github.com/elementary/gala/assets/106322251/08253ec9-76dd-40b5-93c1-9003e1f03bbe)
At the bottom is vscode

### Steps to Reproduce

AFAIK it's wayland only but that's as far as I got to find a common cause.
It seems to happen more frequently if a window is maximized?

### Expected Behavior

As on X

### OS Version

8.x (Early Access)

### Software Version

Compiled from git

### Log Output

```shell
Nothing relevant AFAICT
```

**Comment by bobby285271** [comment]
Don't know how relevant it is, I start experiencing the same (?) thing on x11 session on NixOS a year ago https://github.com/NixOS/nixpkgs/pull/222752#issuecomment-1482202967 when we are testing glib 2.76 update or even just G_SLICE=always-malloc 😕
