### ISSUE TITLE
Always on Top and Always on Visible Workspace Inconsistent

### ISSUE THREAD

**Issue by ryanleesipes** [elementary/gala#192]
I use the "Always on Top" and "Always on Visible Workspace" window options quite a lot. But for whatever reason it just randomly loses this setting and ends up behind windows. When I check the setting, it still appears to be set - but ends up behind other windows anyway. It might be something to do with whether the window it is interacting with is expanded, but the behavior is inconsistent enough that I've been able to reproduce it via any set process.

Terminal and Videos are the apps I use the option with most. Usually sitting on top of Firefox or Thunderbird in the top-left or bottom-right corner.

I'm using an up-to-date version of elementary OS 0.4.1 Loki.

**Comment by donadigo** [comment]
Looks like the issue was fixed in master, but wasn't released yet - https://github.com/elementary/gala/commit/7664aee55d0869b4b4eb771ea3461dec3a4e078f

**Comment by ryanleesipes** [comment]
If this works that is really great news @donadigo! Is there any way to tell when this will hit my desktop?

**Comment by donadigo** [comment]
@ryanleesipes really not sure. I'm not responsible for packaging, and last Gala release was long ago (I think Loki), you can be sure that this will land in Juno.

**Comment by danrabbit** [comment]
Closing since this is fixed in master
