### ISSUE TITLE
(7.0) Mousing over doesn't reveal the dock

### ISSUE THREAD

**Issue by ChildishGiant** [elementary/gala#1922]
### What Happened?

When testing `elementaryos-7.0-daily.20211205` I found that once hidden the dock can't be shown by mousing over, only by unmaximising the app etc.

### Steps to Reproduce

This behaviour happened from install. I am using Virtual Machine Manager and this happens both full screen and windowed.

https://user-images.githubusercontent.com/13716824/144754454-1fb9a544-ff27-4144-b7a0-f6ed93871b26.mp4

 

### Expected Behavior

Same behaviour as in Odin

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
Closing since this is an issue with the old dock unhide mechanism which has been completely rewritten for OS 8
