### ISSUE TITLE
Visual glitches when switching workspaces

### ISSUE THREAD

**Issue by leolost2605** [elementary/gala#1940]
### What Happened?

When switching workspaces via shortcuts (i.e. while not in the multitasking view) it seems to lag/stutter/glitch. Most notably while trying to switch to a new workspace while already on the last one without an open window the screen will almost completely be covered by a black thingy (?) instead of the nudge animation playing nicely.

### Steps to Reproduce

1. switch to the last workspace
2. try to switch to next workspace

### Expected Behavior

Dont glitch

### OS Version

8.x (Early Access)

### Software Version

Compiled from git

**Comment by leolost2605** [comment]
@danirabbit can you still reproduce this because I cant :shrug:? (Asking because you upvoted :))

**Comment by danirabbit** [comment]
I cannot!
