### ISSUE TITLE
Zoom turns screen grey on Wayland

### ISSUE THREAD

**Issue by danirabbit** [elementary/gala#1945]
### What Happened?

In the Wayland session zooming with Super + plus/minus turns the screen grey

### Steps to Reproduce

zoom with Super + plus/minus

### Expected Behavior

zoomed screen :)

### OS Version

8.x (Early Access)

### Software Version

Compiled from git

**Comment by leolost2605** [comment]
Some additional info: this is only happening if the dock is visible for some reason

**Comment by leolost2605** [comment]
Ok the reason for this is that we sometimes get some wild results when querying the ui_group for width and height (ranging from 0 to some random number) in `compute_new_pivot_point` in the zoom class. This leads to pivot points outside the 0 to 1 range causing the grey screen.
