### ISSUE TITLE
Launch Dock on X11

### ISSUE THREAD

**Issue by danirabbit** [elementary/gala#1965]
### What Happened?

We need a dock for the X11 session since the new dock only works with Wayland

### Steps to Reproduce

Start X11 session and see there's no dock since 956125b488ba3da2ea1b1d93ffa8c0521e14a3ff

### Expected Behavior

Make sure we launch Plank under X11

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by leolost2605** [comment]
I think maybe we should do that via a systemd unit or something similar which only launches on X. Because gala probably shouldn't become our makeshift session manager that launches everything :shrug:
