### ISSUE TITLE
Some apps ignore HiDPI mode

### ISSUE THREAD

**Issue by vjr** [elementary/gala#1967]
### What Happened?

Some apps like Google Chrome and Visual Studio Code, both installed from the official deb repos, do not pick up HiDPI mode in Gala Wayland session and are in 1x mode UI instead of 2x.

Other apps like Firefox and LibreOffice work OK though they are installed from flathub.

I'm unsure whether the issue is due to the apps being deb versus flatpak or whether there is some missing config in Gala like setting an env var for apps to pick up my HiDPI 2x setting.

If I run VSCode with `code . --force-device-scale-factor=2` the app itself looks OK except for the titlebar which is still 1x.

I am unable to capture a screenshot so hopefully this writeup is clear enough to explain.

### Steps to Reproduce

1. Installed apps Chrome and VS Code from their official deb repos.
2. Installed Firefox and LibreOffice from flathub.
3. Firefox and LibreOffice open in correct scale factor 2x HiDPI in Gala Wayland session.
4. Chrome and VSCode do not.

### Expected Behavior

Apps like VSCode and Chrome should pick up scaling factor (from Gala/Wayland?) correctly.

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by IzsakiRobi** [comment]
It is still present in the released elementaryOS 8.0. :(

**Comment by vjr** [comment]
I can confirm this issue is fixed by #2140 for me!
