### ISSUE TITLE
Add Wayland protocol extension stuff to LibGala

### ISSUE THREAD

**Issue by danirabbit** [elementary/gala#1992]
### Problem

We're coping a whole lot of code for the Dock, Panel, system dialogs, etc related to anchors and setting center etc

### Proposal

Is it possible to add this stuff to LibGala?

**Comment by danirabbit** [comment]
@leolost2605 is that feasible or no?

**Comment by tintou** [comment]
What you want is not libgala but another library

**Comment by tintou** [comment]
libpantheon-desktop or something, note that it can live inside Gala if required

**Comment by tintou** [comment]
It can actually even be part of Granite

**Comment by danirabbit** [comment]
I don't think Granite would be an appropriate place because that is targeted at app developers and this is just for our own shell components

But I'm not picky about if it should be in LibGala or a LibPatheon or whatever, just thinking about how we can maintain things easier and not duplicate code too much

**Comment by tintou** [comment]
libgala is for gala plugins (like the wingpanel plugin) so it's not the right target

**Comment by tintou** [comment]
I started a thing git@github.com:elementary/pantheon-wayland.git

**Comment by danirabbit** [comment]
Closing since we have the pantheon Wayland lib now
