### ISSUE TITLE
Hot corners activating in applications locking mouse, i.e. games

### ISSUE THREAD

**Issue by razpotnik** [elementary/gala#2012]
### What Happened?

When playing games that lock the mouse input (i.e. use the mouse for camera movement, etc.), the hot corners can be activated by moving the mouse into the corresponding direction, even though the mouse pointer itself is not visible on screen.

This happens in fullscreen apps, maximized apps and windowed apps whose window edges come close to the display hot corner in question.

Very annoying, especially in tense gaming moments :-)

### Steps to Reproduce

1. Activate a hot corner (in EOS, System settings -> Desktop -> Multitasking), in my example I will be using bottom right for 'Multitasking view' 
2. Launch an application that locks the mouse (in my example, Minecraft)
3. Move the mouse in the direction of the hot corner

### Expected Behavior

When focus is on an application that locks the mouse/fullscreen applications, do not activate hot corners.

The wording of the functionality is "When the pointer enters a display corner", but since the pointer is not visible and thus does not move, I wouldn't consider the current behavior expected.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment]
Fixed in https://github.com/elementary/gala/pull/1806
