### ISSUE TITLE
Taking screenshots is completely broken

### ISSUE THREAD

**Issue by lenemter** [elementary/gala#2014]
### What Happened?

1. Taking fullscreen screenshots produces black screen
2. On wayland taking screenshots to a clipboard is broken

### Steps to Reproduce

???

### Expected Behavior

Working screenshot feature

### OS Version

8.x (Early Access)

### Software Version

Compiled from git

**Comment by leolost2605** [comment]
> Taking fullscreen screenshots produces black screen

Hmm I can't reproduce this. Neither via shortcut, nor via the portal :shrug:

**Comment by lenemter** [comment]
I can't reproduce it anymore :shrug:
