### ISSUE TITLE
Support for Mutter 45/libmutter-13 is broken

### ISSUE THREAD

**Issue by pimvullers** [elementary/gala#2037]
[gala-8.0.0_mutter45.patch.gz](https://github.com/user-attachments/files/16676584/gala-8.0.0_mutter45.patch.gz)
### What Happened?

Gala 7.1.3 built fine on my system (Gentoo with Mutter 45.5), but trying out the new Gala 8.0.0 release caused various build issued. Attached patch tries to cover a number of the build breakers, but I get stuck at:

src/gala.p/ScreenshotManager.c: In function ‘gala_screenshot_manager_save_image_to_clipboard’:
src/gala.p/ScreenshotManager.c:2917:56: error: too many arguments to function ‘meta_selection_source_memory_new’
 2917 |                 _tmp16_ = (MetaSelectionSourceMemory*) meta_selection_source_memory_new ("image/png", _tmp15_, &_inner_error0_);
      |                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/gala.p/ScreenshotManager.c:42:
/usr/include/mutter-13/meta/meta-selection-source-memory.h:33:23: note: declared here
   33 | MetaSelectionSource * meta_selection_source_memory_new (const char *mimetype,
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

It is unclear to me whether this is no longer tested, or Ubuntu has some updates from Mutter 46 backported to 45

### Steps to Reproduce

Build gala-8.0.0 against Mutter 45.5 (without any backports)

### Expected Behavior

Build passes without any errors.

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment]
Ubuntu 24.04 provides Mutter 46 and therefore mutter 45 is untested. I'll look if something has changed in MetaSelectionSource recently

**Comment by pimvullers** [comment]
Building against Mutter 46.4 works as expected (but this version is not in the stable profile on Gentoo yet).
And also other packages like pantheon-greeter and wingpanel are not ready for mutter 46 yet (waiting for the eOS 8 versions of those).

**Comment by lenemter** [comment]
Can you check if https://github.com/elementary/gala/pull/2038 builds for you?

**Comment by lenemter** [comment]
https://github.com/elementary/gala/pull/2039 should fix the build, however without mutter 46 Wayland session will be broken
