### ISSUE TITLE
eOS 8: Multitasking view on wayland gets stuck grabbing window

### ISSUE THREAD

**Issue by teamcons** [elementary/gala#2064]
### What Happened?

Sometimes, when on the multitasking view (wayland) and grabbing a window to move it somewhere
grab gets stuck, and you cannot release without pressing escape

There does not seem to be a regularity to how often the issue occur, but sometimes it is quasi systematic

The bug can occur when clicking a window. Gala converts it into grabbing the window and refusing to release it.

### Steps to Reproduce

install eOS 8
go on wayland session
open a few windows
activate multitasking view
grab-release a few windows randomly
pointer will be stuck in grabbing mode at some point

### Expected Behavior

when releasing mouse, window gets released
when clicking on a window, the view switches to the window

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
Uncertain what to run. Cannot seem to replace a running gala like on x11
```

### Hardware Info

Intel® Core(TM) i3-7100U CPU @ 2.40GHz
Intel® HD Graphics 620

**Comment by desiderantes** [comment]
I can reproduce this on the X11 session
