### ISSUE TITLE
eOS 8: Terminal and System Settings have generic icon in multitasking view on Wayland

### ISSUE THREAD

**Issue by teamcons** [elementary/gala#2067]
### What Happened?

When in multitasking view:
Both Terminal and System Settings have the generic star-on-purple-square icon

### Steps to Reproduce

Wayland session
open terminal
open system settings
multitasking view, babey

### Expected Behavior

Both have their super cool icons when in multitasking, increasing my enjoyment of eOS 8 tenfolds and allowing me to use my computer

### OS Version

8.x (Early Access)

### Session Type

Secure Session (Wayland)

### Software Version

Latest release (I have run all updates)

**Comment by teamcons** [comment]
The issue is still present ! On RC, up to date.

**Comment by lenemter** [comment]
@teamcons The fix has not been released yet
