### ISSUE TITLE
Invisible window clones

### ISSUE THREAD

**Issue by leolost2605** [elementary/gala#2088]
Since #2072 some WindowClones are not visible (for me it's especially xwayland clients e.g. vs code). 
The issue temporarily fixed by #2072 is probably more severe (it can lead to everything breaking enough so that you have to restart gala and thus the session from a different tty) so I wouldn't revert for now.
But the root cause for that will be fixed in #2082 and thus that also reverts #2072 and fixes this issue.

**Comment by wout** [comment]
Is that why some windows are sometimes not rendered in multitasking view? For me, that happens a lot with Thunderbird, where only the application's icon is rendered, not the window.

If not, I'll open another issue with some more info.
