### ISSUE TITLE
Dock interacts with the mouse even with the window overlapping

### ISSUE THREAD

**Issue by diogopessoa** [elementary/gala#2101]
### What Happened?

Even with an application overlapping, the Dock reponds to the mouse. 

However, this only happens with the classic session (Xwindow). The issue doesn't occur in the secure session (Wayland).

Demo video:

https://github.com/user-attachments/assets/253b197c-b545-4314-ba8a-08fd44058e01

elementary OS 8 early access RC (classic session)

![Captura de tela de 2024-10-25 21 41 29](https://github.com/user-attachments/assets/be158102-751d-463f-846c-4979b8c70104)

### Steps to Reproduce

1. Maximize any application to overlap the dock;
2. The dock will hide;
3. Position the mouse in the dock area;
4. The name of the applications will apper and you can click to show or open them.

### Expected Behavior

When overlapping, the dock should not interact with the mouse.

### OS Version

8.x (Early Access)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Notebook Asus i5 
1280x720 screen

**Comment by totchi-lagawi** [comment]
I had this issue in the demonstration version of elementary OS. It disappeared as soon as I installed it.
