### ISSUE TITLE
Screenshot area is shown with a grey layer on top when issued via custom shortcut

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/gala#211]
(Moved from [this issue](https://github.com/elementary/screenshot-tool/issues/37))

5 out of 10 times when using `screenshot-tool -r` via the `Shift+PrtScrn` shortcut to select only an area of the screen, the screenshot is stored with a transparent grey layer on top. Example:

![](https://user-images.githubusercontent.com/6054951/37745637-aabf36b2-2d54-11e8-8abc-23e6da2e1995.png)

These are my specs:

AMD A8-3870 APU with Radeon(tm) HD Graphics
NVIDIA Corporation G96 [GeForce 9500 GT] (rev a1)

**Comment by Djaler** [comment]
I can confirm this. With own gala screenshotter, not with screenshot-tool

**Comment by jlnr** [comment]
I always use `screenshot-tool` to take screenshots and I'm seeing the same issue, so this could be related to https://github.com/elementary/screenshot-tool/issues/50 after all

**Comment by JCatrielLopez** [comment]
This is still happening to me on Juno. Specs:

![Screenshot from 2020-10-07 20-08-56](https://user-images.githubusercontent.com/31131027/95397210-046b5300-08d9-11eb-9744-582002cf15ae.png)
