### ISSUE TITLE
Multitasking view does not show the application windows, only the icon

### ISSUE THREAD

**Issue by diogopessoa** [elementary/gala#2128]
### What Happened?

In **classic session**, the multitasking view does not show the application windows, only the icon.

Classic session
![Captura de tela de 2024-11-29 09 22 27](https://github.com/user-attachments/assets/8d0ea0a7-f635-4fae-9f4d-0c07e49b9239)

the same does not happen in **safe session**
![Captura de tela de 2024-11-29 09 25 11](https://github.com/user-attachments/assets/03f5aeb4-a9dc-4aca-be7a-7750020e35b9)

### Steps to Reproduce

1. in the dock, click on multitasking view
2. the multitasking view will show open applications
3. only the icons will appear

### Expected Behavior

Multitasking view should show the window image and the application icon.

### OS Version

8.x (Circe)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

### Hardware Info

notebook Asus i5 8gb ram Intel HD Graphics 4000
monitor resolution 1366x768

**Comment by diogopessoa** [comment]
Can anyone reproduce this?

**Comment by leolost2605** [comment]
This is probably the same as #2088 which has a fix pending

**Comment by travrei** [comment]
I have the same problem 
![Captura de tela de 2024-12-04 20 43 33](https://github.com/user-attachments/assets/3413b836-5345-4b1d-9f59-e5edb1db2947)
don't tried in safemode yet
