### ISSUE TITLE
Text UI based Scaling: Tiny Titlebars in XWayland Apps

### ISSUE THREAD

**Issue by candiedoperation** [elementary/gala#2169]
### What Happened?

On a Wayland session, apps that run in X11 mode using the XWayland compatibility layer have a titlebar which does not respect text scaling settings. The screenshots have other windows, like Terminal and Files, open to depict scaling sizes.

![image](https://github.com/user-attachments/assets/ff95a48c-e1fd-4664-9b4e-6b31b95ab335)
![image](https://github.com/user-attachments/assets/1affdb25-58d1-4d5f-8982-f9c6509cdf99)

### Steps to Reproduce

1. Install some electron based app (like VSCode, Slack, etc.) or some other app that doesn't support Wayland by default.
2. Enable Text Scaling by increasing font-sizes from System Settings in Display > Text > Font Size
3. Set an increased DPI for X, `xrdb -merge <<< "Xft.dpi: 125"` (or update the `~/.XResources`)
4. Open the App you installed. The scaling inside the App, including the menu bar and other elements, work perfectly. But, the titlebar is too tiny.

### Expected Behavior

The text in the title bar should also scale thereby, making the title bar size match what other apps like Terminal and Files have. This behavior is standard in X11. But, considering the XWayland compatibility layer, there are some issues.

### OS Version

8.x (Circe)

### Session Type

Secure Session (Wayland)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
No Logs are Expected
```

### Hardware Info

No Graphic Drivers Installed
1920x1200 FHD Display
Dell XPS 15 9530

**Comment by lenemter** [comment]
Fixed in https://github.com/elementary/gala/pull/2140
