### ISSUE TITLE
Multitasking view not showing preview for newly opened windows

### ISSUE THREAD

**Issue by herculesgabriel** [elementary/gala#2179]
### What Happened?

Multitasking view doesn't show window preview for every new window. You need to switch workspaces, and go back to get it working.

![image](https://github.com/user-attachments/assets/c6bfbd01-6eef-445f-a75c-b829c5e5db7d)

It seems to be related to issues: #2128 #1326 #1354 

### Steps to Reproduce

1. Open a new app, like Files.
2. Open the multitasking view.
3. Switch to workspace on the right.
4. Switch back to main workspace.

### Expected Behavior

When opening a new app, its window's previews should be immediately visible in Multitasking View.

### OS Version

8.x (Circe)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Using latest Nvida drivers available from driver settings (nvidia-driver-550).

**Comment by leolost2605** [comment]
This is already fixed but not released yet :)
