### ISSUE TITLE
Add ability to selectively minimize different windows of the same app

### ISSUE THREAD

**Issue by SubhadeepJasu** [elementary/gala#228]
Better if I put an edge case which is very common. Let's say there are two windows of Firefox open. If I want to minimize just window A not B, there is no way to do it. Clicking on the icon on plank would cause both windows to get minimized at the same time which I don't want to at the moment. Also most importantly, if window A is open and B is minimized and I want to minimize A, clicking on the icon would cause B to restore instead of A being minimized. This is a recurring problem when an User has to handle or organize multiple windows of the same app. A common problem for users switching from Mac and Windows or even other distros.

With due respect, I wouldn't be wrong if I say that many user often download the tweak tool and get the minimize button in place, I cannot blame them for that. I do understand that the lack of minimize button in title bar is part of the aesthetics, but doesn't really make things better in the long run especially when this has so many trade-offs in the usability. Also I do understand that the absence of the minimize button is now a part of elementary OS's identity and uniqueness. So I wouldn't ask to bring the minimize button back, not fully.

There are some alternatives to this behavior that I want to suggest. 
**Alternative 1:**
Let's not keep a minimize button in the title bar by default. But when an user hovers over the title bar, the minimize button is shown. Clicking on the button would have the usual common behavior. When the mouse is not hovering on the title bar, the minimize button is hidden. (This might be the best idea.)
Pros: It wont take the user long to figure it out, since hovering over the title bar would simply show the minimize button. Its faster this way. Cons: A hidden button (if that is even a problem).
**Alternative 2:** 
No minimize button at all. Long press the left mouse button over the title bar without moving it would cause window to minimize. Pros: Solves the issue. Cons: User may not figure it out easily and its a slow method.
**Alternative 3**
Minimize button present on title bar by default. Pros: Solves the issue, Fastest method, User got nothing to learn. Cons: Breaks the unique style of elementary (Not recommended).

I personally would suggest an auto-hiding minimize button. And this is open to discussion.

**Comment by cassidyjames** [comment]
Minimize is not about aesthetics, it's about how apps are designed for elementary OS. First and third party apps made for elementary OS are fast to open and save their state. This means there's a lot less of a distinction between minimize and close, and we've chosen to focus on state-saving and fast opening over minimizing.

To solve your specific issue, you should be able to just right-click on a window's titlebar and minimize it. The fact that window menus don't show up for some apps is a bug (#174), and is being worked on as part of #179.

**Comment by SubhadeepJasu** [comment]
Hmm, that would work too. Thanks
