### ISSUE TITLE
No window icon

### ISSUE THREAD

**Issue by nick87720z** [elementary/gala#23]
When started from menu, it appears with default icon (be it gear or image of empty window).
This bug already appeared in similar project - go-for-it.
Yet would be nice to look for this one: https://github.com/mank319/Go-For-It/pull/97
(i don't know, does this suffer, but looking to xprop, i did not notice something related, only WM_CLASS)

Perfect todo app anyway, simplicity as is :)

**Comment by danrabbit** [comment]
Closing because this seems like an issue with a specific app
