### ISSUE TITLE
Cannot close empty workspace in overview

### ISSUE THREAD

**Issue by jlnr** [elementary/gala#235]
1. Open two spaces with one window each
2. From the middle workspace, move one window to the space on the right
3. Now try to close the middle workspace using the preview at the bottom

Expected result: I can close the current, empty workspace just like I can close other workspaces.

Actual result: No way to close the empty workspace. Not a problem once users learn/remember that empty spaces auto-close, but I found it surprising that I can't just click (X).

**Comment by lenemter** [comment]
Closing because the close button was removed in https://github.com/elementary/gala/pull/1794
