### ISSUE TITLE
Only show alt+tab animation when holding keys

### ISSUE THREAD

**Issue by jwinnie-the-great** [elementary/gala#236]
The Alt+Tab animation is great. However, it gets annoying when quickly cycling through windows.

![alt tabretry](https://user-images.githubusercontent.com/20506149/39391198-96ff19cc-4a54-11e8-9157-5652b3c525b2.gif)

Maybe there should be a timeout before the animation is triggered.

**Comment by lenemter** [comment]
Closing because Alt+Tab animation was changed in OS 6.1
