### ISSUE TITLE
Style multitasking view with CSS

### ISSUE THREAD

**Issue by danirabbit** [elementary/gala#243]
It would be really great to have control over styling this area from CSS instead of manually in Cairo. In particular I would like to be able to style:

- [ ] The background of the view itself (currently grey)
- [ ] The workspaces/wallpapers. Particularly with both inner and outer box shadow and border radius
- [ ] Close buttons
- [ ] The little workspace tiles at the bottom of the display

**Comment by danrabbit** [comment]
#250 styles outer shadow of the workspace clone

**Comment by lenemter** [comment]
Closing since gala no longer uses CSS for styling.
