### ISSUE TITLE
Blur your desktop when an app is open

### ISSUE THREAD

**Issue by brigazvi** [elementary/gala#246]
It can upgrade the user experience and his concentration at work.
Just like the human eye.

Here's a really, really bad example of what it should look like:
![example](https://user-images.githubusercontent.com/37640970/39774427-7b969d56-5303-11e8-82d3-dd9385825241.png)

**Comment by diazabdulm** [comment]
Not only would that affect some GPUs, it would also be an unnecessary/fancy addition. elementary is all about what's needed and not what's wanted.

**Comment by arshubham** [comment]
I am also against this, however something similar can be used to create a guided tour, during first run, with  a text overlay, or allow it within a single application window with widgets, something similar to what the gtk3 version of glade does.

**Comment by GammaGames** [comment]
The guided tour that shows features with the option for new users (all features) and users that upgrade from older versions (just newer features) would be awesome, I didn't even know about the housecleaning feature until the medium post about privacy today.

**Comment by brigazvi** [comment]
@GammaGames i think you need to create new issue about it.

**Comment by danrabbit** [comment]
I'm going to close this as "Design Conflict". This seems excessive to do for any window. I can see a case for doing this for special/important windows
