### ISSUE TITLE
Closing apps sometimes makes apps freeze

### ISSUE THREAD

**Issue by aggalex** [elementary/gala#248]
It's been a lot of times I've tried to close several apps, only to find the close button stuck in a pressed-mode and the app persisting on my screen, making me ether kill the app or use xkill or wait for the app to close itself (this can take from around 2 sec to minutes). This renders the system unusable for day-to-day usage. Here's a screenshot of the Terminal app doing it:
![screenshot from 2018-05-12 22 22 39](https://user-images.githubusercontent.com/11951328/39960879-7a6db256-5633-11e8-9c0f-15de153e41b5.png)
And this happens to most of the rest of the apps too, with the ones to which this is most likely to occur and have biggest timeout being Files, AppCenter, Web and Terminal. It's really annoying.

**Comment by lenemter** [comment]
Closing the issue because it's old and no more similar bug reports were filed.
