### ISSUE TITLE
External Subtitles not working with the defaut Video Player

### ISSUE THREAD

**Issue by OrkanSaklan** [elementary/gala#256]
External Subtitles seems to not work with the default Video Player coming with elementary OS.
I can select the subtitles and submit the change, but absolutely nothing happens. I did the same test in VLC, works fine. The format I used is .srt. I'm not really familiar with subtitles and their formats so I wanted to mention it.

**Comment by peteruithoven** [comment]
Hi, thanks for sharing, but this is the repository for Gala, the Window Manager. 
You're describing an issue for the Video player: https://github.com/elementary/videos

It's also an existing issue:
https://github.com/elementary/videos/issues/32
Also relevant:
https://github.com/elementary/videos/issues/63

**Comment by OrkanSaklan** [comment]
Oh sorry, didnt realize that Im in the wrong section. I'm glad that this issue is already tracked, well since 2017, how I see. I dont know what a ClutterGst bug is, but how can it be solved?

Thanks for your support!

**Comment by xaiki** [comment]
(please close this issue :) )
