### ISSUE TITLE
Showing the logout screen crashes Gala

### ISSUE THREAD

**Issue by tintou** [elementary/gala#264]
Discovered after adding a compositor to the greeter
![img_20180602_193049](https://user-images.githubusercontent.com/745535/40882295-197d7e42-66d5-11e8-9031-83ebd093b759.jpg)

**Comment by snowparrot** [comment]
beautiful mirror ;)

**Comment by Djaler** [comment]
This looks fixed to me. @tintou can you confirm?

**Comment by codygarver** [comment]
Reported #274 for my problem, thought it was the same as this issue before.
