### ISSUE TITLE
Opening Screenshot Tool crashes Gala

### ISSUE THREAD

**Issue by Djaler** [elementary/gala#267]
Can be related to https://github.com/elementary/gala/issues/264.
<details>
  <summary>Some logs</summary>
<pre>
июн 06 22:42:30 juno gala.desktop[12512]: **
июн 06 22:42:30 juno gala.desktop[12512]: mutter:ERROR:core/window.c:1523:meta_window_unmanage: assertion failed: (g_list_find (workspace->windows, window) == NULL)
июн 06 22:42:30 juno gnome-session[10651]: gnome-session-binary[10651]: WARNING: Application 'gala.desktop' killed by signal 6
июн 06 22:42:30 juno gnome-session-binary[10651]: WARNING: Application 'gala.desktop' killed by signal 6
июн 06 22:42:30 juno gnome-session[10651]: gnome-session-binary[10651]: WARNING: App 'gala.desktop' respawning too quickly
июн 06 22:42:30 juno gnome-session-binary[10651]: WARNING: App 'gala.desktop' respawning too quickly
июн 06 22:42:30 juno gnome-session-binary[10651]: Unrecoverable failure in required component gala.desktop
июн 06 22:42:30 juno gnome-session[10651]: gnome-session-binary[10651]: CRITICAL: We failed, but the fail whale is dead. Sorry....
июн 06 22:42:30 juno gnome-session-binary[10651]: CRITICAL: We failed, but the fail whale is dead. Sorry....
июн 06 22:42:30 juno dropbox.desktop[10930]: ICE default IO error handler doing an exit(), pid = 10967, errno = 11
июн 06 22:42:30 juno telegramdesktop.desktop[10931]: ICE default IO error handler doing an exit(), pid = 10931, errno = 11
июн 06 22:42:30 juno lightdm[10633]: pam_unix(lightdm:session): session closed for user djaler
июн 06 22:42:30 juno kernel: rfkill: input handler enabled
июн 06 22:42:30 juno gala.desktop[10913]: [11378:11378:0606/224230.052452:ERROR:x11_util.cc(90)] X IO error received (X server probably went away)
июн 06 22:42:30 juno gala.desktop[10913]: [11338:11338:0606/224230.054524:ERROR:chrome_browser_main_extra_parts_x11.cc(62)] X IO error received (X server probably went away)
июн 06 22:42:30 juno at-spi-bus-launcher[2268]: XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
июн 06 22:42:30 juno at-spi-bus-launcher[2268]:       after 799 requests (799 known processed) with 0 events remaining.
июн 06 22:42:30 juno bluetoothd[1009]: Endpoint unregistered: sender=:1.166 path=/MediaEndpoint/A2DPSource
июн 06 22:42:30 juno gsd-xsettings[10775]: gsd-xsettings: Fatal IO error 11 (Ресурс временно недоступен) on X server :0.
июн 06 22:42:30 juno bluetoothd[1009]: Endpoint unregistered: sender=:1.166 path=/MediaEndpoint/A2DPSink
июн 06 22:42:30 juno gsd-wacom[10787]: gsd-wacom: Fatal IO error 11 (Ресурс временно недоступен) on X server :0.
июн 06 22:42:30 juno gsd-keyboard[10851]: gsd-keyboard: Fatal IO error 11 (Ресурс временно недоступен) on X server :0.
июн 06 22:42:30 juno unknown[10840]: gsd-media-keys: Fatal IO error 11 (Ресурс временно недоступен) on X server :0.
июн 06 22:42:30 juno io.elementary.p[10934]: io.elementary.pantheon-agent-polkit: Fatal IO error 11 (Ресурс временно недоступен) on X server :0.
июн 06 22:42:30 juno nm-applet[10963]: nm-applet: Fatal IO error 11 (Ресурс временно недоступен) on X server :0.
июн 06 22:42:30 juno pantheon-mail[10929]: pantheon-mail: Fatal IO error 11 (Ресурс временно недоступен) on X server :0.
июн 06 22:42:30 juno pantheon-agent-[10938]: pantheon-agent-geoclue2: Fatal IO error 11 (Ресурс временно недоступен) on X server :0.
июн 06 22:42:30 juno gsd-power[10825]: gsd-power: Fatal IO error 11 (Ресурс временно недоступен) on X server :0.
июн 06 22:42:30 juno light-locker[10937]: light-locker: Fatal IO error 11 (Ресурс временно недоступен) on X server :0.
июн 06 22:42:30 juno deluge.desktop[10928]: deluge: Fatal IO error 11 (Ресурс временно недоступен) on X server :0.
июн 06 22:42:30 juno io.elementary.t[11862]: io.elementary.terminal: Fatal IO error 11 (Ресурс временно недоступен) on X server :0.
июн 06 22:42:30 juno gsd-clipboard[10806]: gsd-clipboard: Fatal IO error 11 (Ресурс временно недоступен) on X server :0.
июн 06 22:42:30 juno gsd-color[10777]: gsd-color: Fatal IO error 11 (Ресурс временно недоступен) on X server :0.
июн 06 22:42:30 juno wingpanel[11080]: wingpanel: Fatal IO error 11 (Ресурс временно недоступен) on X server :0.
июн 06 22:42:30 juno bamfdaemon[11048]: bamfdaemon: Fatal IO error 11 (Ресурс временно недоступен) on X server :0.
июн 06 22:42:30 juno systemd[2122]: bamfdaemon.service: Main process exited, code=exited, status=1/FAILURE
июн 06 22:42:30 juno systemd[2122]: bamfdaemon.service: Failed with result 'exit-code'.
июн 06 22:42:30 juno polkitd(authority=local)[1226]: Unregistered Authentication Agent for unix-session:c6 (system bus name :1.170, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale ru_RU.UTF-8) (disconnected from bus)
июн 06 22:42:30 juno systemd[2122]: bamfdaemon.service: Service hold-off time over, scheduling restart.
июн 06 22:42:30 juno systemd[2122]: bamfdaemon.service: Scheduled restart job, restart counter is at 1.
июн 06 22:42:30 juno systemd[2122]: Stopped BAMF Application Matcher Framework.
июн 06 22:42:30 juno systemd[2122]: Starting BAMF Application Matcher Framework...
июн 06 22:42:30 juno kernel: nvidia-modeset: Freed GPU:0 (GPU-11fb6f88-f786-fe94-e00b-53b6db4e9b96) @ PCI:0000:01:00.0
июн 06 22:42:30 juno pulseaudio[12532]: [pulseaudio] client-conf-x11.c: Вызов xcb_connection_has_error() вернул «true».
июн 06 22:42:30 juno bamfdaemon[12540]: Unable to init server: Не удалось подключиться к: В соединении отказано
июн 06 22:42:30 juno bamfdaemon[12540]: cannot open display: :0
июн 06 22:42:30 juno systemd[2122]: bamfdaemon.service: Main process exited, code=exited, status=1/FAILURE
июн 06 22:42:30 juno systemd[2122]: bamfdaemon.service: Failed with result 'exit-code'.
июн 06 22:42:30 juno systemd[2122]: Failed to start BAMF Application Matcher Framework.
июн 06 22:42:30 juno rtkit-daemon[2387]: Successfully made thread 12543 of process 12543 (n/a) owned by '1000' high priority at nice level -11.
июн 06 22:42:30 juno rtkit-daemon[2387]: Supervising 1 threads of 1 processes of 1 users.
июн 06 22:42:30 juno pulseaudio[12543]: [pulseaudio] pid.c: Stale PID file, overwriting.
июн 06 22:42:30 juno rtkit-daemon[2387]: Supervising 1 threads of 1 processes of 1 users.
июн 06 22:42:30 juno rtkit-daemon[2387]: Successfully made thread 12544 of process 12543 (n/a) owned by '1000' RT at priority 5.
июн 06 22:42:30 juno rtkit-daemon[2387]: Supervising 2 threads of 1 processes of 1 users.
июн 06 22:42:30 juno rtkit-daemon[2387]: Supervising 2 threads of 1 processes of 1 users.
июн 06 22:42:30 juno rtkit-daemon[2387]: Successfully made thread 12545 of process 12543 (n/a) owned by '1000' RT at priority 5.
июн 06 22:42:30 juno rtkit-daemon[2387]: Supervising 3 threads of 1 processes of 1 users.
июн 06 22:42:30 juno dbus-daemon[1014]: [system] Rejected send message, 2 matched rules; type="method_call", sender=":1.186" (uid=1000 pid=12543 comm="/usr/bin/pulseaudio --start --log-target=syslog " label="unconfined") interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" error name="(unset)" requested_reply="0" destination="org.bluez" (uid=0 pid=1009 comm="/usr/lib/bluetooth/bluetoothd " label="unconfined")
июн 06 22:42:30 juno pulseaudio[12543]: [pulseaudio] bluez5-util.c: GetManagedObjects() failed: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.186" (uid=1000 pid=12543 comm="/usr/bin/pulseaudio --start --log-target=syslog " label="unconfined") interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" error name="(unset)" requested_reply="0" destination="org.bluez" (uid=0 pid=1009 comm="/usr/lib/bluetooth/bluetoothd " label="unconfined")
июн 06 22:42:31 juno systemd[2122]: bamfdaemon.service: Service hold-off time over, scheduling restart.
июн 06 22:42:31 juno systemd[2122]: bamfdaemon.service: Scheduled restart job, restart counter is at 2.
июн 06 22:42:31 juno systemd[2122]: Stopped BAMF Application Matcher Framework.
июн 06 22:42:31 juno systemd[2122]: Starting BAMF Application Matcher Framework...
июн 06 22:42:31 juno bamfdaemon[12546]: Unable to init server: Не удалось подключиться к: В соединении отказано
июн 06 22:42:31 juno bamfdaemon[12546]: cannot open display: :0
июн 06 22:42:31 juno systemd[2122]: bamfdaemon.service: Main process exited, code=exited, status=1/FAILURE
июн 06 22:42:31 juno systemd[2122]: bamfdaemon.service: Failed with result 'exit-code'.
июн 06 22:42:31 juno systemd[2122]: Failed to start BAMF Application Matcher Framework.
июн 06 22:42:31 juno systemd[2122]: bamfdaemon.service: Service hold-off time over, scheduling restart.
июн 06 22:42:31 juno systemd[2122]: bamfdaemon.service: Scheduled restart job, restart counter is at 3.
июн 06 22:42:31 juno systemd[2122]: Stopped BAMF Application Matcher Framework.
июн 06 22:42:31 juno systemd[2122]: Starting BAMF Application Matcher Framework...
июн 06 22:42:31 juno bamfdaemon[12547]: Unable to init server: Не удалось подключиться к: В соединении отказано
июн 06 22:42:31 juno bamfdaemon[12547]: cannot open display: :0
июн 06 22:42:31 juno systemd[2122]: bamfdaemon.service: Main process exited, code=exited, status=1/FAILURE
июн 06 22:42:31 juno systemd[2122]: bamfdaemon.service: Failed with result 'exit-code'.
июн 06 22:42:31 juno systemd[2122]: Failed to start BAMF Application Matcher Framework.
июн 06 22:42:31 juno systemd[2122]: bamfdaemon.service: Service hold-off time over, scheduling restart.
июн 06 22:42:31 juno systemd[2122]: bamfdaemon.service: Scheduled restart job, restart counter is at 4.
июн 06 22:42:31 juno systemd[2122]: Stopped BAMF Application Matcher Framework.
июн 06 22:42:31 juno systemd[2122]: Starting BAMF Application Matcher Framework...
июн 06 22:42:31 juno bamfdaemon[12548]: Unable to init server: Не удалось подключиться к: В соединении отказано
июн 06 22:42:31 juno bamfdaemon[12548]: cannot open display: :0
июн 06 22:42:31 juno systemd[2122]: bamfdaemon.service: Main process exited, code=exited, status=1/FAILURE
июн 06 22:42:31 juno systemd[2122]: bamfdaemon.service: Failed with result 'exit-code'.
июн 06 22:42:31 juno systemd[2122]: Failed to start BAMF Application Matcher Framework.
июн 06 22:42:31 juno systemd[2122]: bamfdaemon.service: Service hold-off time over, scheduling restart.
июн 06 22:42:31 juno systemd[2122]: bamfdaemon.service: Scheduled restart job, restart counter is at 5.
июн 06 22:42:31 juno systemd[2122]: Stopped BAMF Application Matcher Framework.
июн 06 22:42:31 juno systemd[2122]: Starting BAMF Application Matcher Framework...
июн 06 22:42:31 juno bamfdaemon[12549]: Unable to init server: Не удалось подключиться к: В соединении отказано
июн 06 22:42:31 juno bamfdaemon[12549]: cannot open display: :0
июн 06 22:42:31 juno systemd[2122]: bamfdaemon.service: Main process exited, code=exited, status=1/FAILURE
июн 06 22:42:31 juno systemd[2122]: bamfdaemon.service: Failed with result 'exit-code'.
июн 06 22:42:31 juno systemd[2122]: Failed to start BAMF Application Matcher Framework.
июн 06 22:42:31 juno nvidia-persistenced[10489]: Received signal 15
июн 06 22:42:31 juno systemd[1]: Stopping NVIDIA Persistence Daemon...
июн 06 22:42:31 juno nvidia-persistenced[10489]: Socket closed.
июн 06 22:42:31 juno nvidia-persistenced[10489]: PID file unlocked.
июн 06 22:42:31 juno nvidia-persistenced[10489]: PID file closed.
июн 06 22:42:31 juno nvidia-persistenced[10489]: The daemon no longer has permission to remove its runtime data directory /var/run/nvidia-persistenced
июн 06 22:42:31 juno nvidia-persistenced[10489]: Shutdown (10489)
июн 06 22:42:31 juno systemd[1]: Stopped NVIDIA Persistence Daemon.
июн 06 22:42:31 juno systemd[1]: Starting NVIDIA Persistence Daemon...
июн 06 22:42:31 juno nvidia-persistenced[12562]: Verbose syslog connection opened
июн 06 22:42:31 juno nvidia-persistenced[12562]: Now running with user ID 120 and group ID 128
июн 06 22:42:31 juno systemd[1]: Started NVIDIA Persistence Daemon.
июн 06 22:42:31 juno nvidia-persistenced[12562]: Started (12562)
июн 06 22:42:31 juno nvidia-persistenced[12562]: device 0000:01:00.0 - registered
июн 06 22:42:31 juno nvidia-persistenced[12562]: Local RPC service initialized
июн 06 22:42:32 juno systemd[2122]: bamfdaemon.service: Service hold-off time over, scheduling restart.
июн 06 22:42:32 juno systemd[2122]: bamfdaemon.service: Scheduled restart job, restart counter is at 6.
июн 06 22:42:32 juno systemd[2122]: Stopped BAMF Application Matcher Framework.
июн 06 22:42:32 juno systemd[2122]: bamfdaemon.service: Start request repeated too quickly.
июн 06 22:42:32 juno systemd[2122]: bamfdaemon.service: Failed with result 'exit-code'.
июн 06 22:42:32 juno systemd[2122]: Failed to start BAMF Application Matcher Framework.
июн 06 22:42:32 juno kernel: nvidia-modeset: Allocated GPU:0 (GPU-11fb6f88-f786-fe94-e00b-53b6db4e9b96) @ PCI:0000:01:00.0
июн 06 22:42:32 juno acpid[971]: client 10480[0:0] has disconnected
июн 06 22:42:32 juno acpid[971]: client connected from 12553[0:0]
июн 06 22:42:32 juno acpid[971]: 1 client rule loaded
</pre>
</details>

**Comment by Djaler** [comment]
@danrabbit why you close this?

**Comment by danrabbit** [comment]
@Djaler my mistake, I thought the linked branch was merged not closed
