### ISSUE TITLE
Cancelling Logout dialog crashes gala

### ISSUE THREAD

**Issue by codygarver** [elementary/gala#274]
Session indicator -> Logout... -> Cancel -> crash

**Comment by codygarver** [comment]
It only happens the first time in a session, weird.

**Comment by cassidyjames** [comment]
I've had other apps do this as well, including my Principles app and WebPin. I thought @tintou had fixed this, and that it was related to the new compositor on the greeter.

**Comment by JosephMcc** [comment]
The error is: gala.desktop[1411]: mutter:ERROR:core/window.c:1523:meta_window_unmanage: assertion failed: (g_list_find (workspace->windows, window) == NULL)
