### ISSUE TITLE
Only move windows when switching workspaces

### ISSUE THREAD

**Issue by harveycabaguio** [elementary/gala#275]
Conceptually, if you think of wingpanel, dock, wallpaper, and windows as separate layers, the only one that needs to move when switching workspaces is the windows layer. Wingpanel + dock are omnipresent and stay the same across workspaces, and the wallpaper doesn't change across workspaces so it feels redundant to see it move as well.

**Comment by danrabbit** [comment]
The wallpaper should move because it’s consistent with multitasking view and how we show that each workspace is represented by a separate wallpaper.

Agree about dock and panel though since we show those as being pulled away in multitasking view

**Comment by janxkoci** [comment]
This would also make sense for current behaviour of wingpanel when changing workspaces where some windows are maximized (I was goint to open a new bug report to suggest a change that fits more with the current state).

Right now if you switch from workspace with maximized window (i.e. black wingpanel) into one without maximized window (i.e. transparent / translucent wingpanel), the wingpanel slides in with the new workspace, while changing it's state - this make no sense as the new workspace should just have the final wingpanel (i.e. transparent / translucent, no fading or change of state).

If you don't move wingpanel with the workspace, then fading to change it's state would make more sense.
