### ISSUE TITLE
[Idea for the lack of show desktop in Elementary] Make the super+d shortcut switch between the last workspace (empty) and the current one.

### ISSUE THREAD

**Issue by Blast-City** [elementary/gala#279]
Hi.  

One thing that i see pop up from time to time is the lack of a solution to show the desktop. 

Since the minimize function doesn't seem important on Elementary, minimize all windows is not a good solution.

The desktop is not an active part of the OS (lack of icons), but sometimes you're looking at something on the screen and you need to show to desktop.

I think that making the shortcut super+d switch between the last workspace (empty) and the current workspace would solve this issue while maintaining the Elementary workflow.

Even the animation ( switch-to-workspace-last ) is cool since it looks like you swipe everything out of the way.

What do you think?

**Comment by Astro-City** [comment]
I tried to do a script that shows how it would work.

If anybody want to try it just install xdotool, make the script executable a create a custom shortcut that points to the executable file.

`
#!/bin/bash
if	[[ ! -d /tmp/show_desktop/ ]]; then
	mkdir /tmp/show_desktop/
fi

cur_workspace=$(xdotool get_desktop)
num_of_workspaces=$(xdotool get_num_desktops)
num_of_workspaces=$(($num_of_workspaces-1))

if	[[ $cur_workspace -lt $num_of_workspaces ]]; then
	echo $cur_workspace > /tmp/show_desktop/test_cur_workspace
	xdotool set_desktop $num_of_workspaces
else
	xdotool set_desktop $(cat /tmp/show_desktop/test_cur_workspace)
fi
`
