### ISSUE TITLE
[ Confusing ] Two close(cross) buttons in the window manger. Theming helps !

### ISSUE THREAD

**Issue by SabareeshNv** [elementary/gala#28]
![screenshot from 2017-07-06 14 20 53](https://user-images.githubusercontent.com/7964105/27909531-b996cb70-626e-11e7-9e3a-5900dd6c9b9a.png)

Some applications can have two close buttons on the title bar. (Reference the screenshot) Both the buttons look same. User gets confused, especially if a user had installed elementary tweaks and opted for Windows like button layout. 
Theming can be used to change this problem.  Its not a deal breaking issue but more of a nuisance. I hope this gets fixed asap.

**Comment by cassidyjames** [comment]
This is an upstream bug in GTK; they're explicitly using the `process-stop-symbolic` icon as a fallback for window menus.

https://github.com/GNOME/gtk/blob/master/gtk/gtkheaderbar.c#L382

**Comment by cassidyjames** [comment]
I've filed the bug against GTK+ upstream https://bugzilla.gnome.org/show_bug.cgi?id=784624
