### ISSUE TITLE
Merge "Windows Overview" into "Multitasking View"

### ISSUE THREAD

**Issue by uncertainquark** [elementary/gala#287]
The "Mutitasking View", while being able to show the same window previews like the "Windows overview" is superior in functionality.

1. Windows in "Multitasking View" are keyboard navigable, unlike in "Windows overview".

![screenshot from 2018-07-08 22 02 50](https://user-images.githubusercontent.com/22585732/42421897-cdac6b3a-82fa-11e8-8d4a-e9e858d39ec2.png)
![screenshot from 2018-07-08 22 03 08](https://user-images.githubusercontent.com/22585732/42421900-d443b00c-82fa-11e8-9673-cbdc830a25cb.png)

2. Since it exposes the workspaces view too, you can close an entire workspace from there.

![screenshot from 2018-07-08 22 03 17](https://user-images.githubusercontent.com/22585732/42421903-dc5507fa-82fa-11e8-8ca1-5e365352ddbd.png)

Therefore, as suggested in #219, the "Multitasking view" and "Windows overview" should be merged.

**Comment by Astro-City** [comment]
Hi.

Right now there is two ways to highlight the selected windows. The silver outline (keyboard) and the circle with a x (mouse).

I think this two should be be merged as well. 

The circle with a x seems much more elegant, but is not that visible. 

What about the super+a and super+w? How would it work?

Another thing that would be cool is that alt+f4 should work on the workspace overview.

**Comment by janxkoci** [comment]
One point against merging: Multitasking view is slower (as in heavier on resources) compared to Windows overwiew (this is a regression in Juno - in Loki I noticed no difference in performance between the two). People like me who use this lightweight desktop on lower-spec devices (I bought 11" netbook specifically for eOS) do notice these kinds of slow-downs, while devs with macbooks might not :p

**Comment by peteruithoven** [comment]
I'm closing this one in favor of: https://github.com/elementary/gala/issues/485 even though this one is older, Cassidy collected more useful information.
