### ISSUE TITLE
Shift+PrtSc makes the sound of shutter even if we cancel taking a screenshot

### ISSUE THREAD

**Issue by ryonakano** [elementary/gala#290]
Shift+PrtSc makes the sound of shutter even if we cancel taking a screenshot.
On Juno. This happens from Juno Beta1 AFAIK

## Steps to reproduce the behavior

1. Press `Shift+PrtSc`
2. Cancel taking a screenshot with `Esc`
3. You will hear the sound of shutter although you canceled to take. And confirm that any screenshot was taken in this steps by opening Pictures folder

**Comment by ryonakano** [comment]
I'm not sure this is correct repo to submit this issue, so if not I'll close this ASAP (and will submit this at https://github.com/elementary/screenshot-tool)

**Comment by peteruithoven** [comment]
A workaround is using the screenshot tool. You can add a custom shortcut to execute:
`io.elementary.screenshot-tool -r`

**Comment by peteruithoven** [comment]
I think this issue adds little over #311, seeing that the <kbd>esc</kbd> should cancel, which naturally should also prevent the shutter sound. So I'm closing this one.
