### ISSUE TITLE
Add an API to remember window position

### ISSUE THREAD

**Issue by danirabbit** [elementary/gala#297]
It sounds like there is an intent in Gtk4 to remove functions related to setting window position. To prevent regression, we need to create some kind of API for applications to request that Gala remember their window position.

I think if we're smart we'll do this using relative units like percentage instead of absolute units so that we can preserve the users' intent if displays change such as moving from a docked laptop at work to the internal display at home.

**Comment by cassidyjames** [comment]
Relative using percentage, and center-weighted within the window, I think. So the developer doesn't have to try and figure things our regarding app geometry and whatnot. So they say, "I want the window to be centered around 25% horizontally, and 50% vertically" and we'll do our best effort to get the window near that position.

**Comment by orowith2os** [comment]
Does Gala *need* applications to opt in to remembering their positions and sizes? Couldn't it keep track of all of that internally and apply what it now knows? I want to say kwin_wayland does this.

**Comment by danirabbit** [comment]
@orowith2os I think when this was originally written we had the idea of some of the pre-installed apps being utilities where we don’t really want them to remember state, but I think looking at it now that we could assume that we want to preserve positions for all apps and if there are parts of the desktop that need an exception, then we can either hardcode those exceptions or create an opt-out mechanism. I think I agree we don’t need to make an opt-in mechanism here
