### ISSUE TITLE
Gala is causing issues in VLC

### ISSUE THREAD

**Issue by ghost** [elementary/gala#30]
Gala can make VLC's interface, and videos, look zoomed in. The issue is easily reproducible, open a video in VLC, maximize the window, and double click the video to make it go fullscreen, the image will look zoomed in.

Sometimes double clicking the video to exit the fullscreen mode makes the VLC interface interface look zoomed in as well, but this is not always reproducible.

This is a Gala issue (or at least elementary OS exclusive), since it doesn't happen in other Ubuntu flavours or KDE Neon, with the same version of VLC.

![vlc](https://user-images.githubusercontent.com/24446211/27997426-2f859d0a-64ce-11e7-8706-ef32baa52a6c.png)

![vlc - 02](https://user-images.githubusercontent.com/24446211/27997457-e26aa348-64ce-11e7-9e42-05a9e243355f.png)

**Comment by biswaz** [comment]
I have a similar issue.

**Comment by biswaz** [comment]
What debug info should I supply?

**Comment by Maccer1** [comment]
Go to VLC > Settings > Interface and untick "Resize Interface to Video Size". Does it solve your issue?

**Comment by Maccer1** [comment]
I don't seem to have this problem. Are you sure this issue isn't caused by your VLC configuration? Try to reset it and check again.

**Comment by biswaz** [comment]
Related issue: #153

**Comment by arshubham** [comment]
Doesn't seem to affect Juno beta1. Maybe it can be closed now.

**Comment by danirabbit** [comment]
This is a very old issue and nobody responded to the last comment, so I'm going to assume that it's fixed
