### ISSUE TITLE
Black area in top-left and top-right corners when plank isn't at bottom of screen

### ISSUE THREAD

**Issue by AkitakiKou** [elementary/gala#302]
In Juno beta 1, I found this tiny visual issue. When plank dock is placed on left side of the screen and a window is maximized, There's a small area that I expect to be transparent but is in black instead. The black area is visible on HiDPI displays. I know plank on left/right side is not the default setup, but I always do it on laptops to save vertical screen real estate.

Pictures attached to explain the issue better.
[Picture 1](https://i.imgur.com/Dv9zRVC.png)
[Picture 2](https://i.imgur.com/sR7QWv0.png)

**Comment by tintou** [comment]
Thanks for your report!
We don't support the dock being on an other position than the bottom one, this is why we don't expose this setting

**Comment by AkitakiKou** [comment]
Thanks for the reply. I understand your decision.
