### ISSUE TITLE
With Mutter new API | undefined symbol: meta_compositor_flash_screen

### ISSUE THREAD

**Issue by alex285** [elementary/gala#306]
With Mutter 3.29.4
```
gala: symbol lookup error: /lib64/libgala.so.0: undefined symbol: meta_compositor_flash_screen

```

I know that elementary isn't supposed to support Mutter 3.30, specially when there is not even a 3.30 release yet, but I'm mentioning the issue since @ricotz has already pushed this: https://github.com/elementary/gala/commit/be1729d5926bf574fe525dbdb18429dcda2f3721

also the libs are now 
```
'--pkg', 'libmutter-3',
'--pkg', 'mutter-cogl-3',
'--pkg', 'mutter-cogl-pango-3',
'--pkg', 'mutter-cogl-path-3',
'--pkg', 'mutter-clutter-3',
```

**Comment by alucryd** [comment]
Guess there are already some issues about gnome 3.30. Same story on Arch Linux, tried cherry-picking ricotz' branch on top of master, but the build fails almost immediately on undefined Meta.Screen: https://paste.xinu.at/R6OI/

**Comment by alucryd** [comment]
I see, thx for the heads up. It's not really arch-like to provide older versions though, we only do so if absolutely necessary. I'll consider it if users start a riot about gala not building anymore.

**Comment by alex285** [comment]
@alucryd just for reference if you're going to push on Arch

here is the Copr
https://copr.fedorainfracloud.org/coprs/decathorpe/elementary-nightly/

here's how they patch Gala Mutter 3.28
https://github.com/decathorpe/elementary-nightly-rpms/blob/8abba864268f26efcc72c395841d49e33c03cbb1/specs/gala/gala.spec#L35

obviously they keep original Mutter from Fedora repos, and @decathorpe additionally packages a `mutter328` only for Gala

**Comment by alucryd** [comment]
@ricotz I don't want to be pesky, but have you got any idea when you'll be able to look into mutter 3.30? I see your dedicated branch has disappeared. Packaging mutter 3.28 on Arch Linux is a real pain, it depends on other libraries that are also too recent and also need to be packaged alongside their most recent version.

**Comment by streambinder** [comment]
> @ricotz I don't want to be pesky, but have you got any idea when you'll be able to look into mutter 3.30? I see your dedicated branch has disappeared. Packaging mutter 3.28 on Arch Linux is a real pain, it depends on other libraries that are also too recent and also need to be packaged alongside their most recent version.
> I didn't realize the API had changed that much, I gave porting a try but I'm in way over my head. I generated the latest libmutter VAPI though in case you're interested: https://paste.xinu.at/TqZW7/

I'm in the very same situation, as I'm packaging Pantheon dependencies for [Solus](https://getsol.us) distribution, which actually upgraded `mutter` package to 3.32 series, breaking the ability to build `gala, `pantheon-greeter`, `pantheon-applications-menu` and `wingpanel` (and many others, consequently).
Are you planning to add support for `mutter` newer versions?

**Comment by tintou** [comment]
> Are you planning to add support for `mutter` newer versions?
Should happen before the end of the year but no estimate can be given at that time

**Comment by alex285** [comment]
im closing it, since @tintou already fixed that at https://github.com/elementary/gala/pull/566
