### ISSUE TITLE
Some Notifications Never Land in the Notification Area

### ISSUE THREAD

**Issue by amxmln** [elementary/gala#307]
In Juno Beta 1, some notifications, namely AppCenter Update notifications and Telegram (with notifications set to "native") don't end up in the notification center despite the option being active in the Notification settings.

In GNOME Shell, Telegram's native notifications are kept in the notification area, so unless GNOME is handling them in a special way, I don't think they're meant to disappear.

**Comment by cassidyjames** [comment]
@amxmln there was an issue where notifications weren't always being persisted due to a recent performance optimization—are you still seeing this on a fully updated Juno install? AppCenter notifications appear to work correctly now, but I'm not sure about Telegram.

**Comment by cassidyjames** [comment]
This issue was moved to elementary/wingpanel-indicator-notifications#50
