### ISSUE TITLE
Window Manager don't save windows states

### ISSUE THREAD

**Issue by yufelipeto** [elementary/gala#308]
Every time I open a program like Mail, it don't "_remember_" the configuration of the window like it don't start maximized like I set previously or the panel configuration. It occurs with every program I tried. It's really annoying to configure the window size and other properties every time I use a program.

**Comment by JosephMcc** [comment]
This is often up to the application itself and not the window manager. I'm not sure what you'd get into trying to have the window manager remember that for every window you might open.

**Comment by peteruithoven** [comment]
Relevant: https://github.com/elementary/granite/issues/224

**Comment by lenemter** [comment]
Fixed in https://github.com/elementary/gala/pull/1751
