### ISSUE TITLE
Switchers plank doesn't adapt size to HiDPI?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/gala#31]
The plank that's used when switching doesn't seem to adjust it's scale for HiDPI screens, while the default plank does. 

![peek 2017-07-14 18-15](https://user-images.githubusercontent.com/523210/28220712-d4bc22c6-68c0-11e7-9c5b-79104e5d7147.gif)

Also see:  https://bugs.launchpad.net/plank/+bug/1657616

**Comment by larsjarlvik** [comment]
Affects me too, just to clarify, it's not only after using the gsettings scaling-factor to to change to 2x but also when elementary detects my high dpi screen and sets the scaling automatically.

**Comment by cassidyjames** [comment]
There is a [$50 bounty](https://www.bountysource.com/issues/47675558-switchers-plank-doesn-t-adapt-size-to-hidpi) on this issue.
