### ISSUE TITLE
Filename of screenshots taken with Gala is not translated

### ISSUE THREAD

**Issue by ryonakano** [elementary/gala#310]
Name of screenshots that were taken with Gala is not translated, while ones that were taken with Screenshot app is translated.

## Steps to reproduce the behavior

1. Run Screenshot and take a screenshot
2. You may confirm that the screenshot you took is saved in your language name, e.g. "スクリーンショット 2018-08-01 19.43.39"
3. Press `PrtSc`, `Alt+PrtSc` or `Shift+PrtSc` and take a screenshot with Gala
4. You may confirm that the screenshot you took is saved in English name, e.g. "Screenshot from 2018-08-01 19-44-36"

**Comment by danrabbit** [comment]
So this string actually comes from GNOME Settings Daemon. Oddly it looks like it is not translated there in Japanese:

https://github.com/GNOME/gnome-settings-daemon/blob/2535cde979baa18d4e0569eeee9de9415cde51d0/po/ja.po#L1208

**Comment by ryonakano** [comment]
Thank you for your investigation! I'll submit a translation for that string then.
