### ISSUE TITLE
Shift+PrtSc takes screenshot even if we press Esc key while we're selecting area

### ISSUE THREAD

**Issue by ryonakano** [elementary/gala#311]
## Expected behavior

If we press `Esc` while we're selecting area, Shift+PrtSc should cancel taking a screenshot.

## Actual behavior

`Shift+PrtSc` takes screenshot even if we press `Esc` while we're selecting area.

## Steps to reproduce the behavior

1. Press `Shift+PrtSc` and press `Esc`
2. The action cancels and no screenshot is taken
3. Press `Shift+PrtSc`, drag to select area to grub, and press `Esc` without releasing your finger from touchpad/mouse
4. A screenshot is taken although we press `Esc` to cancel taking the screenshot

**Comment by peteruithoven** [comment]
When creating a custom keybinding to `io.elementary.screenshot-tool -r` cancel using <kbd>esc</kbd> does work as expected.

**Comment by danrabbit** [comment]
Closing because this seems to be fixed
