### ISSUE TITLE
i don't know about this

### ISSUE THREAD

**Issue by torikulhabib** [elementary/gala#315]
why emoji croped 
![screenshot from 2018-08-09 18-51-28](https://user-images.githubusercontent.com/26135527/43897127-4dea3688-9c05-11e8-99fb-bfe88438e533.png)
![screenshot from 2018-08-09 18-54-17](https://user-images.githubusercontent.com/26135527/43897264-ab7f1f70-9c05-11e8-9b61-b4d4c940644b.png)
![screenshot from 2018-08-09 18-56-34](https://user-images.githubusercontent.com/26135527/43897390-f853166c-9c05-11e8-98e5-283906e750c4.png)

**Comment by cassidyjames** [comment]
This is an upstream issue in GTK itself: https://gitlab.gnome.org/GNOME/gtk/issues/543
