### ISSUE TITLE
Mutually resize tiled windows

### ISSUE THREAD

**Issue by LeoTindall** [elementary/gala#317]
When windows are tiled, resizing one should resize adjacent windows, as shown below, to continue using the whole screen space.

Two windows are open:
![side by side](https://user-images.githubusercontent.com/3290365/43912527-1d582ef4-9bc8-11e8-94b9-ea9b0caa7213.png)

Upon clicking and dragging the centerline:
![oneclickresize](https://user-images.githubusercontent.com/3290365/43912526-1d326c46-9bc8-11e8-8de3-ed54e3095c71.png)

**Comment by donadigo** [comment]
This is already the case on Juno Beta1. Closing.
