### ISSUE TITLE
Unity Editor

### ISSUE THREAD

**Issue by pavlepiramida** [elementary/gala#318]
I wasnt sure where to file this issue,so I do apologize if this is the wrong place!

We have a situation which is pretty much Pantheon specific.

To cut long story shot I made a little sample of the issue
https://drive.google.com/file/d/1fqWUioxcrMcA3aj9_p6wm-wd9p-pizjg/view

Editor should not be able to scroll in anyway.
This only happens with Pantheon (Ive tested it on Gnome and KDE and could not reproduce it).

Could it be issue with elementary theme or with Gala itself?

Issue has been reported to Unity as well and I hope theyll be able to provide some more insight into whats happening on the video.

**Comment by pavlepiramida** [comment]
One more video of the issue

https://drive.google.com/open?id=1Twrb9XKMBQ-E8zsw8PIndYRJeERvTi_P

You can see that when editor scrolls,it gets rendered under wingpanel,and is just broken.

**Comment by AlonsoEnrique** [comment]
GTK_CSD=0 unity-executable solve the problem, but the dialog window file chooser does not work

**Comment by m93a** [comment]
I can confirm this is still an issue with elementary 5.1.2 and Unity 2019.3.8f1.

**Comment by ma1onso** [comment]
Update hotfix `GTK_MODULES=gail:atk-bridge GTK_CSD=0 /home/$USER/Unity/Hub/Editor/UNITY_VERSION/Editor/Unity -projectPath /home/$USER/PROJECT_NAME`

**Comment by tintou** [comment]
There is nothing we can do here on our side

**Comment by davidmhewitt** [comment]
This looks like it was related to the `GTK_CSD` environment variable anyway, so this should be resolved out of the box in elementary OS 6.
