### ISSUE TITLE
Can't copy or move multiple file

### ISSUE THREAD

**Issue by phamquangthinhs** [elementary/gala#319]
Here:
https://image.ibb.co/h1YJ1U/Screenshot_from_2018_08_12_16_30_57.png

**Comment by ryonakano** [comment]
Hello @phamquangthinhs 
Actually this issue has already reported [here](https://github.com/elementary/files/issues/583) so please close your issue.

And please make sure that you post your issue to the correct project (In this case, https://github.com/elementary/files).

But anyway, thank you for your reporting!
