### ISSUE TITLE
Notify user when they left/right click desktop multiple times

### ISSUE THREAD

**Issue by steakscience** [elementary/gala#323]
I understand elementary wants to have an empty desktop. However this is confusing to new users, a good way to help them out would be to have a tooltip appear after several left/right clicks on desktop, maybe saying something like "elementary doesn't support files on the Desktop, try using the Files app"

**Comment by cassidyjames** [comment]
If we're going this route at all, I think I'd rather just add a context menu to the Desktop or Wallpaper settings. This would re-enforce that there's no file management going on here, but be less condescending and give them something they can actually do.

**Comment by danrabbit** [comment]
Agreed. Closing as a duplicate of #113

**Comment by cassidyjames** [comment]
@danrabbit I think this is actually a dupe of #521; #113 looks like it's some custom menu feature request, but #521 is specifically about Display and Wallpaper settings.
