### ISSUE TITLE
Multitasking View Lag

### ISSUE THREAD

**Issue by ghost** [elementary/gala#328]
Is there a way to change the transition time during the transitions to the current running apps? My card doesn't works well and I want to disable the default transition time to a faster way.

**Comment by danirabbit** [comment]
Just following up here that these days there's a "reduced motion" setting in System Settings → Desktop → Appearance and I'm fairly certain we increased default animation speeds sometime in the last five years. So I think this is probably considered fixed?

Feel free to reopen with more info if this issue persists!
