### ISSUE TITLE
Translation files need updating

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/gala#333]
#179 contained some string additions

**Comment by codygarver** [comment]
Regenerating the files isn't picking up anything new, are you sure? Could some things be untranslatable that should be?

**Comment by davidmhewitt** [comment]
#179 adds a new file to POTFILES and that file definitely contains translatable strings. So there should definitely be some changes.

**Comment by davidmhewitt** [comment]
Actually I guess the same strings have just been moved from one file to another. I guess it should be fine. My bad.
