### ISSUE TITLE
window menus don't work on server-side decorations

### ISSUE THREAD

**Issue by decathorpe** [elementary/gala#338]
Even after the change to use a separate daemon for drawing window menus, they don't work for applications with server-side decorations (e.g. no Gtk.HeaderBar) -- for example, no window menu is drawn when right-clicking the title bar of gnome-terminal or firefox.

**Comment by cassidyjames** [comment]
@decathorpe that was already a bug, and the daemon fixed that for me here on elementary OS. Are you sure everything's up to date and the daemon is running?

**Comment by decathorpe** [comment]
Yes, and yes. I'm running gala from commit 9747bd6 (the latest and greatest right now) and gala-daemon is running in the session.

**Comment by cassidyjames** [comment]
Duplicate of #174 which was apparently never fixed.

**Comment by cassidyjames** [comment]
I will note that I get window menus for Firefox here, but not for Chromium, Electron, or Qt apps.

**Comment by nkkollaw** [comment]
Hello, I'm also not getting any menus. I built Gala from scratch on Xfce. What is the daemon fix..? How can I test that?

Thanks!!!
