### ISSUE TITLE
Can't change tiling position directly?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/gala#341]
It looks like applications in Juno that are already tiled to the left or right can't directly be tiled to the opposite side. It seems to go into a weird state where only some corners turn round. 
![screencast appcenter webm](https://user-images.githubusercontent.com/523210/45907246-7d350a80-bdf7-11e8-8735-c9d68e5a422c.gif)

**Comment by peteruithoven** [comment]
I tried reproducing this on Loki in a VM, but there it works fine.

**Comment by peteruithoven** [comment]
I've opened an issue in the Mutter issue queue: https://gitlab.gnome.org/GNOME/mutter/issues/343

**Comment by peteruithoven** [comment]
Maybe someone could try this with the latest Mutter version? Ruling out it's an already fixed issue.

**Comment by konstantinbo** [comment]
Happens to me too. I'd like to add another demonstration:

![window-tiling-glitch](https://user-images.githubusercontent.com/9221119/47151560-5e347600-d2da-11e8-880f-fc2de522ab5d.gif)

**Comment by peteruithoven** [comment]
@konstantinbo which screencast tool did you use? That pressed key visualization is nice.

**Comment by konstantinbo** [comment]
> @konstantinbo which screencast tool did you use? That pressed key visualization is nice.

It's a combination of Kazam (Screen record) and [Screenkey](https://github.com/wavexx/screenkey) to show the pressed keys. I used it in debug (-d) mode, because it wouldn't start normally.

**Comment by peteruithoven** [comment]
Thanks to a tip on Slack it looks like the issue is actually caused by Gala. The tip was that it might be caused by it getting stuck in an animation.

I've figured out that by removing the following check I can change tile position directly. 
https://github.com/elementary/gala/blob/master/src/WindowManager.vala#L963

**Comment by peteruithoven** [comment]
Now that I know a bit more, here is a easy way to reproduce it:
1. Open a fresh workspace 
2. Open an app like Files (not minimized or tiles)
3. Tile left by pressing super+ctrl+left
4. Then try tilling right by pressing super+ctrl+right
5. Weird things happen.

This seems to happen because in both tile locations the window has the same size and we depend on a size changed event to finish a animation. 
When the tile sides have a different size this is no issue.
