### ISSUE TITLE
UX: It's too easy to trigger the action "Close All Windows in Workspace" when switching between workspaces with mouse

### ISSUE THREAD

**Issue by megatux** [elementary/gala#348]
It's a destructive action, without any confirmation dialog and IMHO not very useful.
Happened to me several times. Specially with that delayed effect before "X" appears. You don't see it, go for a clicking a BUM! the "X" apperead and you did an unwanted destructive action.

![worspace close all](https://user-images.githubusercontent.com/850020/46208578-9101d480-c301-11e8-8447-a5feb32f55a1.png)

**Comment by naaando** [comment]
What's your user case to click on that? It's possible to navigate between workspaces with cmd + arrow left and right.
Maybe dragging to a trash can could help, but then users that just use this feature to close a workspace would need one more step.

**Comment by megatux** [comment]
You don't close a workspace, it disappears automatically when is empty.
I think the _use case_ for closing all apps in a workspace should be questioned, again, especially the current implementation so error-prone.

**Comment by megatux** [comment]
Maybe the "close all windows in this workspace" could be added above, at the top of the screen, with all the scaled windows, and not inside the small box at the bottom.

**Comment by megatux** [comment]
Any decision on this issue? I'm still clicking by error on the small (X). If you are ok with removing it I can take a look at the code.

**Comment by megatux** [comment]
Hi, friendly ping here :speaking_head: , I'd like to use Gala as my main WM again, but this kind of issues still bother me.

**Comment by lenemter** [comment]
@danirabbit What's your opinion on this?

**Comment by danirabbit** [comment]
@lenemter I personally have never used this feature. Might be worth removing it early in the OS 8 cycle and see if anyone complains
