### ISSUE TITLE
Use screenshot-tool for taking screenshots

### ISSUE THREAD

**Issue by peteruithoven** [elementary/gala#349]
Currently there are a couple of issues with how screenshots are handled by Gala:
- [Shift+PrtSc takes screenshot even if we press Esc key while we're selecting area](https://github.com/elementary/gala/issues/311)
- [Shift+PrtSc makes the sound of shutter even if we cancel taking a screenshot ](https://github.com/elementary/gala/issues/290)

Why not use the screenshot-tool?

**Comment by danrabbit** [comment]
We actually need to do the opposite because of Wayland

**Comment by peteruithoven** [comment]
Good point. I just read your comment here: https://github.com/elementary/gala/pull/95#issuecomment-333887201
