### ISSUE TITLE
Alt+Shift is default shortcut for "Switching Layout" in keyboard layout interferes with Cycle Windows Backwards

### ISSUE THREAD

**Issue by mahajanudit** [elementary/gala#351]
I am not sure if switcher is part of Gala or another repo, please do assign the issue to the right repo if it doesn't belong here. 
The issue is that Keyboard layout switcher is set to Alt+Shift which is also the keyboard shortcut for Cycle Windows Backwards. This causes annoying behavior.
In fact Alt+Shift+Tab is not even captured as a accelerator unless you disabled it in kayboard layout switching.

**Comment by peteruithoven** [comment]
I think there is already an open issue at: https://github.com/elementary/default-settings/issues/4

**Comment by mahajanudit** [comment]
Aah, my bad
