### ISSUE TITLE
Request: Enable searching in Windows overview/Show all Windows

### ISSUE THREAD

**Issue by mahajanudit** [elementary/gala#352]
In Show All Windows and Windows overview where you can see all windows tiled nicely, please enable searching the windows for more productivity. Even in multitasking view.
This used to be a functionality back in compiz. A nice overview title/windows search.

**Comment by robertmeta** [comment]
I was coming here to post exactly this.  This is one of the things I depend on in KDE day to day.  Being able to go to show all windows view and then start typing a part of the window title and having it dynamically reduce the windows in that interface.

**Comment by peteruithoven** [comment]
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/gala/issues/218
