### ISSUE TITLE
Usability: Switcher should quit and back to the original app on "Esc" [$5]

### ISSUE THREAD

**Issue by mahajanudit** [elementary/gala#354]
This is something I find very peculiar which is not implemented. Here is the use case,
user starts cycling thrrough the windows using "Alt+tab" and decides to cancel, there is no way of doing that. Intuitively, presses "Esc" but nothing happens. 
But pressing "Esc" cancels the Show all windows dialog, it even cancels the Application Menu and the Multitasking view, so this is very inconsistent behaviour.

**Comment by mahajanudit** [comment]
Wanted to see how the whole bounty thing works :)

**Comment by Blast-City** [comment]
> At what point would you press `Esc`? Once `Alt+Tab` has been released the Switcher already quits. `Alt+Esc` already performs a quick window switch between current and previous window so effectively cancels any number of contiguous `Alt+Tab` presses. However, after `Alt+Tab` you must release the `Alt` key before pressing `Alt+Esc`.
> 
> I guess fixing it so that pressing `Alt_Esc` without first releasing the `Alt` key might be acceptable?

Hi.

Alt+Esc is a shortcut in Elementary? Is this a Juno new feature?

**Comment by josenicomaia** [comment]
`Alt+Esc` is supported on Juno.
I don't know about other versions

**Comment by Blast-City** [comment]
> `Alt+Esc` is supported on Juno.
> I don't know about other versions

Thanks.

What is the difference between Alt+Tab and Alt+Esc? Is it just the window icons in the bottom?

I don't get why so much shortcuts that make essentially the same thing, but oh well...

**Comment by josenicomaia** [comment]
It's simple, when we are doing alt+tab we want to cancel it. But the current behavior doesn't support this.

**Comment by Blast-City** [comment]
> It's simple, when we are doing alt+tab we want to cancel it. But the current behavior doesn't support this.

Sorry if i wasn't clear. I agree with using Esc to cancel the window switcher. 

What I don't agree is the existence of the Alt+Esc shortcut (new in Juno) which does the same thing as Alt+Tab.

It would be much better if a fast Alt+Tab would not bring the dock animation in the bottom. Pressing it for a long time would do the current behavior and Esc would cancel it.

**Comment by codeluggage** [comment]
Alt+Esc quickly changes to the previous program, without anything else. I find it useful to immediately change to the previous app. 

I believe this is the current behavior in Windows (at least 10), which could make adoption easier for new users too.

I was thankful to see this shortcut here! 

+1 from me to make it possible to cancel the alt+tabbing and go back to the original program by pressing esc.
