### ISSUE TITLE
[i18n]Broken icon for gala-multitaskingview.desktop

### ISSUE THREAD

**Issue by bagjunggyu** [elementary/gala#358]
We still have an issue with broken icon for _gala-multitaskingview.desktop_ till to RC-1.
It can be resolved by deleting translations as **Icon[i18n]=multitasking-view** and leaving only **Icon=multitasking-view** itself in gala-multitaskingview.desktop file.

**Comment by opnay** [comment]
Also Korean (after build added Icon[lang]={translated multitasking-view})
I think to add blacklist  "data/gala-multitaskingview.desktop.in:7" in gala/po

**Comment by Suzamax** [comment]
[I proposed a pull request in order to fix this.](https://github.com/elementary/gala/pull/371)

**Comment by rscm** [comment]
this is currently on my gala-multitaskingview.desktop file @ Juno

> Icon[ca]=Vista de multitasca
> Icon[da]=multitasking-view
> Icon[en_GB]=multitasking-view
> Icon[es]=vista-multitarea
> Icon[fi]=multitasking-view
> Icon[fr]=multitasking-view
> Icon[id]=pancatugas-tampilan
> Icon[it]=vista-multitasking
> Icon[ja]=multitasking-view
> Icon[ko]=멀티태스킹 뷰
> Icon[lt]=multitasking-view
> Icon[nl]=multitasking-weergave
> Icon[pl]=podglad-wielozadaniowy
> Icon[ru]=Многозадачный вид
> Icon[vi]=multitasking-view
> Icon[zh_CN]=多任务视图
> Icon[zh_TW]=多工作業-檢視
> Icon=multitasking-view

we can see in what languages the problem persists... mine is Spanish [es]
I'll try editing the name of the icon now

**Comment by TheRock892** [comment]
same problem in italian languages.. 
..the string Icon in gala-multitaskingview.desktop in many language are have been translated while it should not be ..Icon string should be 'multitasking-view' in all languages!

**Comment by bagjunggyu** [comment]
resolved while upgrade
