### ISSUE TITLE
Juno Window Tiling Bug: Glitches when switching tiling sides with keyboard shortcuts

### ISSUE THREAD

**Issue by konstantinbo** [elementary/gala#364]
When I try to switch a (50%) tiled window of Files or Terminal from left to right or the other way i have to use the shortcut twice and and there is an inconsistency with the animation. I made this [video](https://gfycat.com/gifs/detail/AcceptableOffensiveIndigobunting) to illustrate the issue.
Bug is probably related to #361 
I'm using an Intel i5-4200U with integrated graphics if that's relevant.

**Comment by peteruithoven** [comment]
Duplicate: https://github.com/elementary/gala/issues/341
Please thumbs up this one: https://gitlab.gnome.org/GNOME/mutter/issues/343
