### ISSUE TITLE
Workspaces are not removed when they have no apps in them

### ISSUE THREAD

**Issue by Defman21** [elementary/gala#365]
I'm not sure if this is intentional or not, but if you move an app to a workspace and then move it from the workspace to your default workspace, the workspace is still there after re-opening workspace view.

I guess it's somehow related to [this issue](https://github.com/elementary/gala/issues/277) though the PR that fixes it is not merged.

**Comment by Philip-Scott** [comment]
Are you in a multi monitor setup? If so that fix has already been merged and will be out sooner than later :) 

#357

**Comment by Defman21** [comment]
Yeah. Good to know, thanks!
