### ISSUE TITLE
System completely freezes just before a notification comes up

### ISSUE THREAD

**Issue by dlbnco** [elementary/gala#369]
Happens randomly, or I just didn't notice any pattern.

It already happened on Loki, but were much worse. Now, on Juno, they still happen but it freezes for a shorter time.

Here are my specs:

```
OS: elementary OS 5.0 juno
Kernel: x86_64 Linux 4.15.0-36-generic
DE: GNOME 
WM: Mutter(Gala)
WM Theme: elementary
GTK Theme: elementary [GTK2/3]
CPU: Intel Core i7-5600U @ 4x 3.2GHz [82.0°C]
RAM: 5332MiB / 7855MiB
```

**Comment by peteruithoven** [comment]
For how long approximately does it freeze? 
For me its much less than a second. I only notice this while playing a video. 

We might want to investigate the following function:
https://github.com/elementary/gala/blob/master/plugins/notify/NotificationStack.vala#L50-L85
See if some part takes a long time.

**Comment by dlbnco** [comment]
@peteruithoven 

It is probably not more than 1 or 2 seconds. On Loki though it was definitely longer and happened more often.

I notice it more when video conferencing because I use the laptop function key to mute/unmute my mic, and that triggers the notification. So sometimes during a call, I press the button to unmute my mic, and because of the notification, everything freezes (even the muted status LED on my keyboard takes a little bit to turn off).

But right after the initial freeze, if I keep pressing the key continuously, the latency **won't** happen anymore, until I wait for a bit longer before pressing it again. So it seems that the freezing just happens while the service is at some kind of idle state.

**Comment by lenemter** [comment]
Closing because notifications were completely rewritten since 2018.
