### ISSUE TITLE
Network quick access window in wingpanel shows networks which aren't in reach, but were in reach earlier that day.

### ISSUE THREAD

**Issue by h3rzkasper** [elementary/gala#370]
![screenshot from 2018-10-18 22-42-00](https://user-images.githubusercontent.com/23639408/47209677-394f0a00-d391-11e8-9c83-30da80a2fb86.png)

The network quick access window in wingpanel shows networks which physically aren't in reach. They are shown with very good signal. Eduroam and HTWG-Guest are some of those. The PC was connected to Eduroam earlier that day.

Edit: After reboot they are gone and only networks in reach are shown.

**Comment by cassidyjames** [comment]
This issue was moved to elementary/wingpanel-indicator-network#110
