### ISSUE TITLE
Atom editor: invisible windows when starting maximized

### ISSUE THREAD

**Issue by darkwyrm** [elementary/gala#373]
Steps to reproduce:
1) Install Atom. Bug observed using version 1.31.2 x64
2) Start Atom and maximize.
3) Close window.
4) Start Atom again.

Symptoms:
Atom icon appears in dock. Application also responds to commands via right-click and atom -n from the Terminal spawns new windows. It is also possible to Alt-Tab to the invisible window, start typing, Alt+F4 to close, and the save changes dialog appears. The window will take focus (Alt+F shows the File menu, Atom icon shows in Dock when Alt-Tabbing), but it is not visible.

Oddly, toggling auto-hide in the Dock causes the window to appear, but it doesn't matter whether auto-hide is turned on or off and doing so doesn't fix the problem -- it only makes the invisible window visible until Atom is closed. New windows spawned from within the app are also invisible.

**Comment by Djaler** [comment]
Same thing with Insomnia

**Comment by MauricioFIUBA** [comment]
I have the same problem with atom, to make the window visible again, try to grab the edge of the windows and move it.

**Comment by cassidyjames** [comment]
I believe this is a duplicate of https://github.com/elementary/gala/issues/305.
