### ISSUE TITLE
Sublime Text tiling bug

### ISSUE THREAD

**Issue by Djaler** [elementary/gala#377]
Sometimes when I move sublime text window to right or left side of the screen, something strange is happening with it.

You can view this behaviour by the link https://youtu.be/w-H0KWXtgPA

**Comment by Waynekosimoto** [comment]
I have this but for chrome. It's quite infuriating.

**Comment by jwinnie** [comment]
Could you make a list of applications where this issue does and does not occur?

**Comment by cassidyjames** [comment]
It seems like Gala has an issue where a window attempts to tile to its exact same size, which is probably the actual root cause of #305. Native apps don't usually exhibit this because they change padding on the headerbar when tiling, so maybe their window size changes and avoids the issue.

**Comment by cassidyjames** [comment]
Going to close this as a dupe of #305 and consolidate info there.
