### ISSUE TITLE
⌘ key behavior as multitasking view

### ISSUE THREAD

**Issue by aluisiora** [elementary/gala#379]
Users who come from Windows have an alternative to use ⌘ to show the application menu.
This is an improvement request for users coming from GNOME Shell DE to select the ⌘ as a toggle to the Multitasking View throught the new Layout tab in the Keyboard Options.

**Comment by peteruithoven** [comment]
Shouldn't you add this to the Keyboard settings repo? I'm assuming you want to add this option to the "⌘ key behaviour" dropdown?
https://github.com/elementary/switchboard-plug-keyboard

**Comment by aluisiora** [comment]
Yeah! The report tool put me here. There is an open issue with the same request there, closing this one now.

Thank you! :)
