### ISSUE TITLE
Video issues with firefox PIP mode

### ISSUE THREAD

**Issue by arshubham** [elementary/gala#38]
When playing a video on Firefox nightly 56.0a1 in PIP mode, video pauses after few seconds after minimizing Firefox (audio works fine and continues playing). The video resumes after bringing Firefox in focus.

I will be happy to provide any logs if necessary. I am running eOS with daily PPA with all updates installed on HP Pavilion 15 laptop.

**Comment by parnold-x** [comment]
Maybe Firefox checks if it is minimized and then stop refreshing the video to save some cpu cycles.

**Comment by arshubham** [comment]
Closing this as it is not an elementary issue.
