### ISSUE TITLE
Corrupted screen after suspend with nvidia

### ISSUE THREAD

**Issue by vaclavhlobil** [elementary/gala#383]
This is how my login screen looks after waking computer from suspend. Juno final, fresh install, nvidia-drivers 390. I have found an article with some workaround (restarting gala): https://www.addictivetips.com/ubuntu-linux-tips/fix-nvidia-resume-bug-elementary-os-loki/
But this is no-way solution for common user, I think.

![img_20181022_070050](https://user-images.githubusercontent.com/35362874/47318763-38e29780-d64d-11e8-8936-1b974a6b5919.jpg)

**Comment by peteruithoven** [comment]
Thanks for the report! It's a known issue and a fix will be released soon, more info:
- https://github.com/elementary/gala/issues/21
- https://github.com/elementary/greeter/pull/170

Btw, you're screenshot was of the Greeter, which repo is: https://github.com/elementary/greeter
