### ISSUE TITLE
Don't calculate shadows while dragging

### ISSUE THREAD

**Issue by jwinnie-the-great** [elementary/gala#384]
I have experienced Gala hanging several times while dragging windows. Window shadows are not necessary while dragging windows, and they may cause extra compositor overhead. Would it make a performance difference if the shadow was disabled while the user is dragging a window?

**Comment by jwinnie** [comment]
This could also apply to maximize/minimize and tiling.

**Comment by eljefuri** [comment]
@jwinnie Curious to know what your graphics card / driver configuration is? It's odd that any machine today would have even the slightest issue with this, when an early 2000s a 233MHz computer with an 8MB ATI Rage graphics card could draw shadows all day long without issue via the Mac OS X compositor. Is it Gala that needs to be tremendously optimized, or some even lower-level aspect of the Linux desktop stack?

**Comment by jwinnie** [comment]
I have an Intel HD 5500 graphics card. Every other DE (GNOME, KDE, Budgie) runs fine, but Pantheon constantly hangs.

**Comment by polarnixdev** [comment]
I am having the same issue with shadows lagging behind when dragging windows quickly. I am on arch linux with a dedicated graphics card (rtx 2060) and nvidia drivers installed. Closing and reopening the window seems to fix the issue, but comes back later.

**Comment by lenemter** [comment]
Closing because drawing shadows is out of scope of gala. Mutter does this.
