### ISSUE TITLE
Disable Animation on application request

### ISSUE THREAD

**Issue by arshubham** [elementary/gala#385]
Some apps like  https://github.com/cassidyjames/ideogram and clipped need to be opened instantaniously for a optimal usage. 
Here is a related issue. https://github.com/cassidyjames/ideogram/issues/3

**Comment by danirabbit** [comment]
I don't think we want apps to be able to determine their own animation speed. There is a "reduce motion" setting in System Settings → Desktop → Appearance if you want to disable animations and I believe we've increased the default speed of animations sometime in the last five years. So I think this is more or less somewhere between design conflict and fixed
