### ISSUE TITLE
Custom resize by grabbing anywhere

### ISSUE THREAD

**Issue by jeremypw** [elementary/gala#386]
At the moment you can move a window either by grabbing the header bar or by holding down the `Super` key and grabbing anywhere in the window.

Custom resizing requires grabbing a fairly small target at the window corner (the required one may be off-screen).

It would be nice to have an additional method to resize the window by grabbing anywhere (the stationary corner being opposite to the quadrant grabbed). e.g. `Super`+`Alt`+ grab.

**Comment by cassidyjames** [comment]
Like Super + Right Click + Drag?

**Comment by jeremypw** [comment]
Ah - did not find that (tried several things).  I was surprised it did not seem to have been implemented.  I guess this reinforces my shortcut-overlay issue https://github.com/elementary/shortcut-overlay/issues/54

I'll close this.
