### ISSUE TITLE
Close of window doesn't work if window is fullscreen

### ISSUE THREAD

**Issue by yuki-93** [elementary/gala#390]
Hi guys, 

when I have one window in fullscreen, I am not able to close this. I have a dual screen VM with Juno. This only happens if the window is in the top most left corner. When I move it to right screen or having it not as fullscreen, everything works as supposed and I can close the app. 

I tried elementary build-in apps and also self installed apps, the behavior is same for all. I am using 0.5. Juno, which I updated handy from Loki througout adjusting the sources.list. 

Is there any protocol command, which I can call, to figure out where and why exactly Gala my crashes.

Thanks for your reply

**Comment by peteruithoven** [comment]
> I am using 0.5. Juno, which I updated handy from Loki througout adjusting the sources.list.

That is not the way to upgrade and this has been clarified in many places. I don't think we can support your current setup. Please perform a clean install and try this again. I'm closing this issue for now.

If this still happens after a clean install I have a few other questions:
1. You have Juno running in a VM?
2. Dual screen as in 2 monitors? 
3. I'm assuming Gala doesn't actually crash? It's just that closing full screen apps doesn't work?

You can get more information by restarting gala in the terminal and enabling all debug messages by running:
```
G_MESSAGES_DEBUG=all gala -r
```
Before you stop this process or the Terminal I recommend you run the following through the Applications menu:
```
gala -r
```
