### ISSUE TITLE
Chosing a workspace with only one app should exit Multitasking view

### ISSUE THREAD

**Issue by wout** [elementary/gala#392]
If a workspace has only one app, it would be much more convenient to exit Multitasking view immediately on choosing that workspace. Now, it's always an extra click to exit (or `esc`), which is unnecessary in almost every situation.

Maybe a shortcut to explicitly stay in Multitasking mode can be added as well (e.g.` shift/ctrl` + `click`). Or the other way around, to use ` shift/ctrl` + `click` to go to the workspace and exit Multitasking view.

**Comment by peteruithoven** [comment]
I might not understand you correctly, but what if you want to navigate to one workspace further? 
Currently you can go to Multitasking mode and keep pressing super + → to get to the right workspace. Wouldn't  this break that?

**Comment by wout** [comment]
I agree, when using `super` + `→`, this should not happen as one might be cycling through the workspaces. But clicking is a more definite action. Maybe and additional key combination to _go to and enter_ a workspace would be a safer bet. (e.g. `shift` + `click`).

**Comment by janxkoci** [comment]
What if you want to switch to that workspace to move that window to another workspace? In this scenario you would also be required to do some unnecessary actions.

IMHO current behaviour is the most consistent - I especially hate when stuff happens automatically without my explicit consent.

**Comment by wout** [comment]
I'm no linger using elementaryOS. So I'll close this issue.
