### ISSUE TITLE
Clash between Toggle maximized and Alt F11 in Blender 2.79

### ISSUE THREAD

**Issue by wout** [elementary/gala#394]
On hitting `Alt` + `F11` with the Blender window not maximized, everything is fine. Blender goes into full screen mode. But when the Blender window is maximized, things go south:

![screenshot from 2018-10-26 22-46-34](https://user-images.githubusercontent.com/107324/47591882-7dce3d00-d971-11e8-9d74-579099739007.png)

I can hit `Alt` + `F11` multiple times, every time with another outcome, but hardly ever what it should be.

**Comment by janxkoci** [comment]
I had similar issue with Mendeley reference manager in Loki, but it's gone now after update to Juno. These non-native apps always cause problems :/ I heard about Blender ignoring system themes etc before..

**Comment by wout** [comment]
Yeah, I left the elementary OS scene pretty soon after entering it. On Pop!_OS it just works (as expected). Maybe I'll come back in a few years.
