### ISSUE TITLE
Prevent PIP overlapping wingpanel?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/gala#397]
This might be personal but I don't like having the PIP over my Wingpanel blocking the view to my indicators. I know I could manually move the popup lower, but this takes more time. 
Should we limit the PIP window to always being below the Wingpanel?

## Without limit
![screenshot from 2018-10-27 04 14 26](https://user-images.githubusercontent.com/523210/47598679-006df100-d9a0-11e8-9497-1e4e71fcb6d0.png)

## With limit
![screenshot from 2018-10-27 04 16 28](https://user-images.githubusercontent.com/523210/47598678-006df100-d9a0-11e8-961b-b186f3bd3afb.png)
![screenshot from 2018-10-27 04 16 31](https://user-images.githubusercontent.com/523210/47598677-006df100-d9a0-11e8-83fa-e143aebe6dcd.png)

With the button locations as they are this does create a considerable margin. We could decrease this margin by moving the buttons a bit more inside the popup.

**Comment by cassidyjames** [comment]
The margin is an improvement over overlapping. I think it makes sense to reserve that space.

**Comment by peteruithoven** [comment]
I have some code ^ ready, but it depends on #396
