### ISSUE TITLE
Provide Support for Closing Window With Keyboard Shortcut

### ISSUE THREAD

**Issue by bliles** [elementary/gala#405]
I would really appreciate providing support for a default keyboard shortcut to close the current window. Cmd+Q would seem to be a logical default.

**Comment by artemanufrij** [comment]
what about Alt+F4?

**Comment by bliles** [comment]
That works, but then my issue is that the keyboard shortcut cannot be customized (as far as I can tell) like the shortcuts for minimize, maximize, etc.

**Comment by eljefuri** [comment]
Weird Windows shortcut keys are weird. 😊 On Mac, ⌘W closes nearly all windows.

I want to express my strong support for [this proposal] (https://github.com/elementary/switchboard-plug-keyboard/issues/69#issuecomment-338872844) instead of a one-size-fits-all approach.

**Comment by 4ugustin** [comment]
@bliles @eljefuri  You can bind this command which closes/terminates current active window/app to any shortcut you want in Keyboard settings:

`dbus-send --session --dest=org.pantheon.gala --print-reply /org/pantheon/gala org.pantheon.gala.PerformAction int32:15`

**Comment by bliles** [comment]
Very helpful though, thanks @4ugustin

**Comment by danrabbit** [comment]
The window close shortcut can be customized in System Settings → Keyboard.

Closing since this shortcut exists and can be changed
