### ISSUE TITLE
Horizontal screen wipe has low framerate

### ISSUE THREAD

**Issue by eljefuri** [elementary/gala#409]
_NOTE: I am not yet familiar enough with all the components of Elementary to know if this is the right place to post this, so please bear with me if I drop this into the wrong project!_

On most every notebook computer that I have tried, Elementary's horizontal screen wiping animations (e.g. moving between switchboard panels in System Settings) are rendered with an incredibly low framerate. Possibly 6 or 8fps max by my eye -- very choppy. In fact it seems to be even slower than the animation of moving between virtual desktops using the super key, which itself also renders at quite a low framerate (I estimate 12 or 14fps max).

I can hardly imagine that there is any computer around today which is not at least _physically capable_ of rendering this stuff blisteringly fast even on a low-end integrated chipset. Is Gala responsible, or is something else? And how can we improve it?

**Comment by cassidyjames** [comment]
This would be a GTK or driver issue, unrelated to Gala. Closing as it's out of scope and OP never responded.
