### ISSUE TITLE
Multitasking view not showing opened windows on secondary monitor

### ISSUE THREAD

**Issue by Chuque** [elementary/gala#416]
When using the shortcut [Super + S] (on default shortcuts) after setting workspaces to also work on secondary monitor, the secondary monitor turns to a dark background and show no current opened windows on it. It only shows opened windows on secondary monitor when using [Super + W].

Steps to reproduce:
- set workspaces to also work on secondary monitor with following terminal command:
gsettings set org.gnome.mutter workspaces-only-on-primary false
- open any windows on both primary and secondary monitor
- press [Super + S]

This "bug" also happens on eOS Loki. I am currently using eOS 5.0 Juno.

**Comment by keelnar** [comment]
Found this ticket after starting to fill out a feature request. Seems to be supported in other GNOME Shell derivatives, including Ubuntu and Pop!_OS.

**Comment by lenemter** [comment]
Fixed in https://github.com/elementary/gala/pull/1640.
