### ISSUE TITLE
Is there any interest in patching Gala for better integration of applications with menubar UI?

### ISSUE THREAD

**Issue by ripefig** [elementary/gala#420]
Here's a mockup for how this would look on Gnome. 

https://medium.com/@leftcrane/unity-headers-concept-using-server-side-hearderbars-to-create-a-consistent-customizable-and-fbdb0d9696c

It's basically a shortcut to creating the a reasonably unified UI/UX between the new Gnome/Elementary CSD apps and older traditional applications. This functionality is natively supported on QT5, for example, and could make a big difference even without using any Unity patches.

The default functionality would be just LIM (with maybe a potential to support other widgets at some future date.) This would require modifications to the window manager.

Later, people could add HUD and maybe an small menu custom tools drawer. The UX/UI of the underlying application is enhanced (but not seriously altered) and integrates with the header-bar design.

Elementary and Gnome have great designs but that design isn't achieving its potential if it is limited to a small selection of apps, leaving all the rest to use a completely different model.

**Comment by ripefig** [comment]
Some HUD mockups (obviously not elementary HIG): https://medium.com/@leftcrane/gui-hud-using-global-menu-features-hacks-572760272168

**Comment by Blast-City** [comment]
I like the idea of making it an icon that you would press and the menu (File, Edit, etc...) would appear. 

Since Gnome will remove the app menu, it wouldn't even add an addition icon to the icon count on non native apps.

**Comment by cassidyjames** [comment]
elementary will not rip widgets out of apps against the app author's will. If apps want to support some sort of special menu or command palette-type interface, that is possible within the app.

**Comment by ripefig** [comment]
@cassidyjames 

Who says it's against the author's will? All QT apps - and many others - officially and natively support this functionality, as do some GTK applications that use GMenuModel.  I've never heard any developer complain about global menus and HUD, quite the opposite.

Either the app supports it natively or there is a Unity patch for the app. In the former case you'd be violating the the app developer's will by not supporting this feature. In the latter case, you'd be violating the will of the developers who wrote the Unity patches.

Furthermore, you'd be restricting developer choice in choice in the future. Plenty of developers might want to implement consistent and native headerbars+HUD cheaply, without rewriting their entire app (or creating a destructive fork). They won't have that option.

Obviously, nobody is obligated to do anything in the open source world and you're free to close the issue. But your argument for closing actually works in reverse.
