### ISSUE TITLE
D-feet can't enable blur

### ISSUE THREAD

**Issue by matricci** [elementary/gala#424]
I'm trying to enable blur in the terminal window, by d-feet as shown in the video (https://www.youtube.com/watch?v=-_JQG7Q7MtE), but it is not working, it gives the following error message 'tuple type string not closed with)'.

Edit: My bad! It is not an issue with the code, the problem was that I was literally "copy and past" what the guy on the video was doing, but after one hour of research I saw that the version that I saw on the video are a little outdated. The main problem was that it was missing a lot of arguments. After changing the code, the 'DBus.vala', I corrected this by copying the original function and setting what I was missing hard coded on the function.

**Comment by Isaiah-1** [comment]
Where did you find the missing arguments? Was it just the DBus.vala that needed altering?

**Comment by matricci** [comment]
I have to read the source code again to confirm, but you'll need these arguments on D-Feet: uint32 xid, int x, int y, int width, int height, uint8 opacity

**Comment by Isaiah-1** [comment]
Alright, I have those arguments in dfeet. The error comes about at the method input stage: "tuple type string not closed with )". 

Also, video shows only unit32 xid argument beside both Enable and Disable blur. For some reason, int x, int y, int width, int height, uint8 opacity does not follow EnableBlurBehind.

Must be another issue. Thanks anyway.

**Comment by donadigo** [comment]
1. You must have the newest branch of https://github.com/elementary/gala/pull/224 installed.
2. Restart gala with `(gala -r &) &`.
3. Choose a target window, launch terminal, do `xwininfo`, click the window you want to blur behind.
4. Copy the hex number after `Window id:`.
5. Paste it into d-feet with other arguments separated by commas. This would be the final method input:
`0x320000a, 0, 0, 0, 0, 255`

**Comment by Isaiah-1** [comment]
Thanks. The input method took in dfeet. I still only get transparency but I'll re-install and try again.

**Comment by Isaiah-1** [comment]
Here's my result:

![Screenshot from 2019-12-07 13 17 02](https://user-images.githubusercontent.com/58569914/70378239-81fab700-18f4-11ea-9619-810818742aa0.png)

I'll keep looking for the issue. Just putting that in for documentation.

**Comment by donadigo** [comment]
The method returned you `False` which means that gala decided not to add the effect based on the renderer (makes sense because it seems like you're running it on a VM). Alternatively to force adding the effect you can remove line 294 in DBus.vala and recompile.

**Comment by IsaiahBC** [comment]
What I did was change the chipset values to true in Blurwindow.vala. Then it worked. I'll check the dbus line as well. 

I also got it up and running automatically with devilspie acting on the WM_CLASS. It takes a few commands that culminate with a gdbus call. Works pretty good.

**Comment by rbreaves** [comment]
Is it possible to get this running under a VM with blur, even if the performance would be poor?

I've attempted to merge the latest codebase with the #224 branch and it seems like it compiles and runs ok (w/o blur) inside of my VM after resolving merge conflicts and a few other minor things.

https://github.com/rbreaves/gala/tree/optimized-blur-vala

**Comment by matricci** [comment]
Yes, it's possible, although you have to change the source code, like @donadigo said

**Comment by rbreaves** [comment]
Ah of course.. he did say to remove a line in DBus lol.
