### ISSUE TITLE
Missing keys in settings schema causing login loop

### ISSUE THREAD

**Issue by peteruithoven** [elementary/gala#431]
I'm running a custom compiled gala version with my quarter tiling plugin (https://github.com/elementary/gala/pull/408) which adds keys to dconf `org.pantheon.desktop.gala.keybindings`. I noticed that when gala was updated I got stuck in a "login loop". Meaning that I would get the normal greeter, I would type in my password, which got approved but then I would be redirected to the greeter again. I've opened this StackExchange question: https://elementaryos.stackexchange.com/questions/17580/cant-login-in-a-login-loop 

I noticed the following logs:
```
dec 18 15:27:03 xps gala[4703]: Settings schema 'org.pantheon.desktop.gala.keybindings' does not contain a key named 'tile-topleft'
dec 18 15:27:04 xps gala[4716]: Settings schema 'org.pantheon.desktop.gala.keybindings' does not contain a key named 'tile-topleft'
dec 18 15:27:04 xps gnome-session-binary[4439]: Unrecoverable failure in required component gala.desktop
dec 18 15:27:04 xps gnome-session-binary[4439]: CRITICAL: We failed, but the fail whale is dead. Sorry....
```

It looks like there was a gala update which had overridden my custom gala version. I had to recompile and install my custom version before I could login again. 

I think it would be a good idea if Gala was more robust, but I'm not sure what the issue is in this case. 
1. Is the reinstalled version of Gala confused by the extra keys?
2. Or is my plugin for some reason still triggered, but it can't find these keys and it crashes gala?

This might be related to: https://github.com/elementary/gala/issues/172

**Comment by peteruithoven** [comment]
After reinstalling gala (`sudo apt install --reinstall gala libgala0`) I noticed that my plugin file is still in the plugins folder (`/usr/lib/x86_64-linux-gnu/gala/plugins`) which probably makes sense. But this means it's also still triggered. I reproduced my issue and noticed that manually removing the plugin so file enabled me to login again as well. Meaning it's issues 2.

**Comment by jlnr** [comment]
I've run into a similar login loop with the new move-maximized-workspace gsetting.

The solution for me was to delete the gala schema in `/usr/local/share/glib-2.0/schemas/`. It seems I've had accidentally built gala in /usr/local before, and I forgot to clean up the schema, so the new key caused the login loop. Thanks to donadigo for the pointer.

**Comment by tintou** [comment]
We can't be responsible for 3rd party plugins, if you're adding a plugin to Gala, you're trusting the plugin as its a major security entry point.
