### ISSUE TITLE
icons of workspaces placed incorrectly in multitasking view.

### ISSUE THREAD

**Issue by Amphyby** [elementary/gala#440]
![2019-01-04 16-25-23](https://user-images.githubusercontent.com/3951837/50690886-13f0a480-1040-11e9-8d1c-ffa433b605cb.JPG)

All the applications here opened in separate workspaces.

**Comment by Amphyby** [comment]
if some additional information on monitors setup is valuable:
On the photo is external HDMI monitor connected to the laptop with disabled via xrandr integrated monitor.

**Comment by peteruithoven** [comment]
Does this happen with specific applications?
Is your external monitor HiDPI or LowDPI? What about your integrated monitor?

**Comment by Amphyby** [comment]
integrated monitor is HiDPI: 13" 3200*1800
external monitor (which is the only active) is standard 25" with 2560*1080 (little bit wider than standard FullHD)

**Comment by Amphyby** [comment]
It persist on rebooting. and no - its doesn't seem to be application-specific.

**Comment by lenemter** [comment]
Closing the issue as stale.
