### ISSUE TITLE
Alt tab sometimes moves current window to background? 

### ISSUE THREAD

**Issue by peteruithoven** [elementary/gala#441]
In some cases when using <kbd>Alt</kbd> + <kbd>Tab</kbd> the current app (the one the user switches away from) is moved to the background, behind other apps, this makes the switch extra jarring. 

Below I'm for example switching between the Calculator and Screen Recorder.
![screen record from 2019-01-08 20 14 08 2x](https://user-images.githubusercontent.com/523210/50854693-0b70d480-1386-11e9-8717-ba77ab2c7ef1.gif)

Is there something we can do about the order of these apps while switching? 
I don't really understand the current order, understanding that better would probably help coming up with improvements. 

This is only relevant when we want to improve the current behavior, there is an issue on redesigning it completely: https://github.com/elementary/gala/issues/72

**Comment by Blast-City** [comment]
The window switcher needs a completely new design imo.

**Comment by lenemter** [comment]
Closing because window switcher was rewritten.
