### ISSUE TITLE
Notifications still make sound after being turned off

### ISSUE THREAD

**Issue by jtrees** [elementary/gala#443]
#### Steps to Reproduce

1. Open the Notifications Settings
2. Turn sounds off for "Other" applications
3. Open Spotify
4. Ensure "Show desktop notifications when the song changes" is selected
5. Start a playlist and wait for the track to change

#### Expected Behaviour

There should be a notification without sound.

#### Actual Behaviour

There is a notification with sound.

#### Notes

Spotify seems to be using a supported API, since the notification turns up in Notification Center and otherwise behaves like a native notification... It's just that the sound still plays.

Also, this issue most likely occurs with other programs.

**Comment by ernstki** [comment]
Can't reproduce this for the latest available Spotify client, 1.1.84.716.gc5f8b819, installed as a Flatpak via Sideload. I am using Jólnir (elementary OS 6.1) with the latest updates.

For me, Spotify shows up as a separate entry in the Notifications panel, and all the toggles there work as expected.

![Screenshot showing Notifications panel from System Settings, with the Spotify entry highlighted](https://user-images.githubusercontent.com/4009681/224648380-ef6496da-e468-4a31-a2de-e4b06afcb8ec.png)

Recommend closing the issue unless, @jtrees, you can still reproduce it on your end.

**Comment by jtrees** [comment]
Ah yeah, I've moved on from elementary OS so can't test it. Thanks for your feedback. I'll close the issue.
