### ISSUE TITLE
Notification button wrong size after DPI switch

### ISSUE THREAD

**Issue by peteruithoven** [elementary/gala#444]
When I connect my LoDPI projecter to my HiDPI laptop (in mirror mode) elementary OS has to switch from HiDPI to LoDPI. This causes a couple of issues in the UI, for example the notification close button becomes very big:
![screenshot from 2019-01-15 22 59 58](https://user-images.githubusercontent.com/523210/51212821-bd297b80-1919-11e9-8c5f-9baf272ef982.png)

**Comment by peteruithoven** [comment]
Looks like [Notification uses](https://github.com/elementary/gala/blob/master/plugins/notify/Notification.vala#L105) the [`Utils.create_close_button`](https://github.com/elementary/gala/blob/master/lib/Utils.vala#L314-L337) to create the close button. This utils which get's a `Gdk.Pixbuf` from `get_close_button_pixbuf`. This close button `Gdk.Pixbuf` seems cached, it's created once and then reused. 

I guess these kind of caches need to be destroyed when the ui scaling factor changes or check whether the scale of the `Gdk.Pixbuf` is correct and when needed recreate when it's not.

**Comment by worldofpeace** [comment]
This issue should be closed (Fixing wasn't a keyword to do it)
