### ISSUE TITLE
Maximising a window on a secondary monitor puts it on primary monitor

### ISSUE THREAD

**Issue by intercaetera** [elementary/gala#45]
![gif](https://thumbs.gfycat.com/UnlinedPertinentAstarte-size_restricted.gif)

**Comment by rankovic** [comment]
This happent to me too.

**Comment by rohitpaulk** [comment]
I can't replicate this on Hera. I have two secondary displays, maximizing on either seems to work. I tried exactly what OP did, and also a few other combinations.

**Comment by intercaetera** [comment]
Unfortunately, I haven't used elementary for over two years now so if you confirmed that this issue does not happen on the new version, I think it's okay to close it.

**Comment by ryonakano** [comment]
If someone can reproduce this issue again, feel free to reopen :)
