### ISSUE TITLE
Context menus improperly positioned in Firefox

### ISSUE THREAD

**Issue by far-echo** [elementary/gala#451]
Since Juno, dropdown and context menus in Firefox always pop up some two dozen pixels up relative to where they should be. See for yourself - the cursor wasn't moved:

![menu-problem](https://user-images.githubusercontent.com/46893605/51598788-5145a500-1f0f-11e9-8bd9-ce1976a0fe84.png)

This is very likely to be caused by the overlapping dropdown menu trick EOS uses. I also had no such problem with Loki, so it's a recent regression. I believe this is a window manager issue as switching to Adwaita theme didn't help any. It was reported at least twice on Reddit late last year and once here (#403).

**Comment by cassidyjames** [comment]
@far-echo what do you mean by “overlapping dropdown menu trick”? I don't believe that's anything we're doing in Gala…

**Comment by far-echo** [comment]
I mean just that - on Windows, dropdown menus are attached to the dropdown menu button:
![no-overlap](https://user-images.githubusercontent.com/46893605/51624205-650efc80-1f4b-11e9-9364-9fc47d77d5b3.png)

Elementary opts to display the menu over the button instead:
![overlap](https://user-images.githubusercontent.com/46893605/51624238-72c48200-1f4b-11e9-96d6-d63ca784bafd.png)

If the dropdown opens at the bottom of the screen, it instead, well, drops up and fails embarassingly? Anyway, look at the screenshot below, then take a look at the one at the first post, they're clearly related, as the unwanted offset is roughly the same in size:
![overlap-fail](https://user-images.githubusercontent.com/46893605/51624678-668cf480-1f4c-11e9-84ae-5011fe98adef.png)

I'm short of culpruits at the moment: it's either a css style (maybe switching to Adwaita didn't override some styles), or the window manager. It's most likely the latter, as the offset isn't static - it's calculated so that the button is overlapped by the currently selected item. I don't know if this is achievable using CSS alone:
![big-menu-overlap](https://user-images.githubusercontent.com/46893605/51625304-e49dcb00-1f4d-11e9-8439-c175a4650b4f.png)

I've also skimmed .css files for negative margins and didn't find any.

**Comment by cassidyjames** [comment]
@far-echo that's not anything elementary OS is doing specifically, though—that's GTK-standard behavior. I have a feeling this is just a bug in Firefox.

**Comment by far-echo** [comment]
@cassidyjames I've used Firefox with all Ubuntu versions since 16.04, never had any issues like that. If you insist the WM is not to blame, I'll take a deeper look at .css then.

**Comment by deadpixi** [comment]
Having Firefox use CSD works around the issue, but not everyone wants to use (or even knows about) Firefox CSD.

**Comment by cmburg** [comment]
> @cassidyjames I've used Firefox with all Ubuntu versions since 16.04, never had any issues like that. If you insist the WM is not to blame, I'll take a deeper look at .css then. Please note that this isn't unimportant as it looks - the Epiphany is a joke for any power user, and Firefox being glitched means people freaking out and maybe never returning, as I almost did.

I'm not sure but I think I have similar issues. When I write something in a text field FF puts the "suggestion box" right onto the textfield hiding everything I type. It annoys the crap out of me and I considered it to be an FF bug.

**Comment by peteruithoven** [comment]
There are some open Firefox issues: https://bugzilla.mozilla.org/buglist.cgi?quicksearch=context+menu+position

**Comment by deadpixi** [comment]
For the record, I've installed FVWM and Metacity on my Elementary box and run those in separate sessions and the Firefox issue goes away. Logging into Pantheon brings the issue back. It's somehow related to either Gala or the GTK stylesheet...

**Comment by Blast-City** [comment]
![menu-problem](https://user-images.githubusercontent.com/46893605/51598788-5145a500-1f0f-11e9-8bd9-ce1976a0fe84.png)

On this image, the separators are white on a grey background. Anyone knows if this if Mozilla or a elementary's issue?

**Comment by cmburg** [comment]
@Blast-City my ff-menu looks like yours but my libreoffice writer menus look fine (a shadow effect)

**Comment by Blast-City** [comment]
> @Blast-City my ff-menu looks like yours but my libreoffice writer menus look fine (a shadow effect)

Hi.

Thanks for you reply.

What colour are the check marks on the view menu? The problem that i have is that the check marks are white which makes it difficult to view since it have a low contrast against a grey background. The same problem that menu separators on Firefox have.

Thanks.

**Comment by cassidyjames** [comment]
Please file separate issues against the affected projects. This issue has unhelpfully become a catch-all for anything related to menus. Consequently, I'm going to close this as out of scope.
