### ISSUE TITLE
[New Feature] Merge static and dynamic workspaces.

### ISSUE THREAD

**Issue by Blast-City** [elementary/gala#455]
Right now, you either choose static or dynamic workspaces. If you choose static workspaces, you gain much more control.

What if there was a way to join both static and dynamic workspaces and have the best of two worlds?

**Here's how it would work:**

- There would be a "Workspaces" tab in the desktop settings.
- This tab would have just two options:
  1- Static wokspaces number. Box with a value and arrows. (Default value would be "0")
  2- Move fullscreen windows to a new workspace. Switch. ( Default value would be "Enabled")

With default settings, Elementary would work like now.

Whatever options you choose, the + workspace would always be present.

Exemple:

1- Choose "2" workspaces and choose "no" in move fullscreen windows to new workspace. Close the settings window.
2- If you pressed Super+Down this would show:
`Workspace 1 (empty) | Workspace 2 (empty) | +`
3- If you'd Go to the last workspace (+) and open a browser, workspace overview would show this:
`Workspace 1 (empty) | Workspace 2 (empty) | Workspace 3 ( browser) | +`

Everything that you'd put after the second workspace would work like Elementary works now (dynamically). Fullsceen windows would not leave their workspace (switch disabled).

**The Show Desktop Problem:**

A problem that occurs when you choose static workspaces is that the lack of a minimizing options makes showing the desktop/hiding all windows a problem. 

I like what the " hide all windows" option of Gnome and the Plank's desktop docklet do. I's fast and you remain in the workspace where you have hidden the windows, but i think that it might get confusing on a OS that doesn't seem to use the minimize option.

Since the empty "+" workspace would be present no matter how many static workspaces are chosen, pressing Super+d would always show the desktop by going to the empty workspace. Pressing it again would return to the previous workspace. Both with the swipe animation. See #279 

If a workspace is not populated when you press super+d, the shortcut wouldn't work.

Replace the Desktop docklet for a Icon that would do the same as Super+d.

**Comment by peteruithoven** [comment]
Could you clarify what you mean with both static and dynamic workspaces?

**Comment by Blast-City** [comment]
> Could you clarify what you mean with both static and dynamic workspaces?

org.pantheon.desktop.gala.behavior dynamic-workspaces false
org.gnome.desktop.wm.preferences num-workspaces

This two options.

Imagine that everytime you want to watch a movie, you want to do it in the the fourth workspace. Right know this is only possible if all workspaces before 4 would be populated.

This would please people who want more control over the workspaces while not messing with how Elementary works by default.

**Comment by peteruithoven** [comment]
A bit more information:
![screenshot from 2019-01-30 14 14 21](https://user-images.githubusercontent.com/523210/51983607-671c1280-2499-11e9-890d-61eb7d3e6785.png)
![screenshot from 2019-01-30 14 13 56](https://user-images.githubusercontent.com/523210/51983608-671c1280-2499-11e9-9277-cfbd87442e57.png)
