### ISSUE TITLE
Snapped windows can't be resized

### ISSUE THREAD

**Issue by LievenHanssen** [elementary/gala#46]
This has been a bug in elementary for some time now, when this affected me in Freya I made [a video](https://youtu.be/djBidsHLE2c) detailing the bug and reported it on [Launchpad](https://bugs.launchpad.net/gala/+bug/1479121) and opened a bounty on it. With the help of the community [the bounty](https://www.bountysource.com/issues/25109773-unable-to-resize-tiled-window?show_profile_modal=1) is now at $50. 

Quickly thereafter it was marked as a duplicate of [this bug report](https://bugs.launchpad.net/gala/+bug/1224727) where it was put on the wish list. I couldn't find it amongst the Github issues, so I thought I would refile it. Hopefully it will be readded to the wish list.

**Comment by Janiczek** [comment]
Seems like `mutter` (the library responsible for the tiling in `gala` right now) has landed some commits regarding this: see the [bug report](https://bugzilla.gnome.org/show_bug.cgi?id=645153)

`mutter` packages above v3.26.1 should contain the relevant code:
![commits](https://user-images.githubusercontent.com/149425/31607819-26f46318-b26e-11e7-8beb-0eeb9290c0b7.png)
I'm currently trying to install them in a VM to test it.

**Comment by Janiczek** [comment]
I haven't been able to get it to work, but I suspect I'm close.
Here are the `.deb` packages to install: [mutter_3.26.1.tar.gz](https://keybase.pub/janiczek/mutter_3.26.1.tar.gz)

The process:
1. install the Elementary OS on an empty VM
2. `apt update`, `apt upgrade`
3. extract the `.deb` packages and do `dpkg -i ./*.deb`
4. restart

Here is what I ended up with:
```
ii  gir1.2-mutter-1:amd64                          3.26.1-4+artful1                                          amd64        GObject introspection data for Mutter
ii  libmutter-1-0:amd64                            3.26.1-4+artful1                                          amd64        window manager library from the Mutter window manager
ii  libmutter0g                                    3.18.4-0ubuntu2+elementary0.4.2                           amd64        window manager library from the Mutter window manager
ii  mutter                                         3.26.1-4+artful1                                          amd64        lightweight GTK+ window manager
ii  mutter-common                                  3.26.1-4+artful1                                          all          shared files for the Mutter window manager
```

I suspect the `libmutter0g` is the culprit - it probably runs instead of the `libmutter-1-0`. Don't know what to do with it though.

**Comment by Janiczek** [comment]
So, I wasn't able to get this to run on elementary (even with `jhbuild` and building gala and all the dependencies from the latest sources), but I've at least tested the `mutter` behaviour on the [daily Ubuntu 17.10 ISO](http://cdimage.ubuntu.com/ubuntu/daily-live/20171017.1/). The resizing of tiled windows works (buggy, but works). The question is, when is elementary gonna get the new Mutter version (3.26.1 or higher)?

**Comment by cassidyjames** [comment]
This is working in Bionic-based Juno now.
