### ISSUE TITLE
Signal desktop client shown for other notifications

### ISSUE THREAD

**Issue by freaktechnik** [elementary/gala#467]
First off, not sure if this is the proper repository to file this in, but given that GitHub issues can now be moved between repos I'm pretty confident in filing this here.

## Steps to reproduce

- Install Signal Desktop client (`https://updates.signal.org/desktop/apt xenial main` https://signal.org/download/; beta works too)
- Logout and in again (or whatever makes it reload the relevant things)
- Get a notification in the "other" category, like the suspend warning

## Expected result

Notification has no icon or the icon it provided itself.

## Actual result

The signal icon is shown. the indicator properly shows it as "other" though. It didn't used to in Freya, yes this has been an issue in Freya, too.

**Comment by peteruithoven** [comment]
I wonder whether this is related to the following (fixed) issues?
https://github.com/elementary/wingpanel-indicator-notifications/issues/28
https://github.com/elementary/wingpanel-indicator-notifications/pull/44
I can imagine the Signal's app Linux integration isn't great.

**Comment by freaktechnik** [comment]
That'd make sense why it behaves properly in the notifications indicator but not for the notification that's actually shown?

**Comment by peteruithoven** [comment]
If you feel adventurous, the notifications are controlled by the notify Gala plugin:
https://github.com/elementary/gala/tree/master/plugins/notify
Some tips: 
https://elementary.io/docs/code/os-dev
https://elementary.io/docs/code/getting-started#notifications

**Comment by danrabbit** [comment]
Closing since this is a bug in signal and not in the notification server
