### ISSUE TITLE
System screenshot to clipboard doesn't work

### ISSUE THREAD

**Issue by sprite-1** [elementary/gala#474]
I have the following key binding

![image](https://user-images.githubusercontent.com/33685433/53467271-7a1e0480-3a90-11e9-981b-94d9147da20d.png)

I can see the flashing of the screen to indicate that a screenshot has been taken but nothing gets copied to the clipboard. It only started happening recently, I'm not sure which of the recent system updates broke it.

**Comment by peteruithoven** [comment]
@donadigo When I remove the `async` and `yield`'s the clipboard functionality seems to work again.

**Comment by peteruithoven** [comment]
When I log this error: https://github.com/elementary/gala/blob/master/src/ScreenshotManager.vala#L187
I get:
```
Error opening file “/tmp/gnome-settings-daemon-screenshot-NT3RXZ”: File exists
```

**Comment by peteruithoven** [comment]
Looks like another gala release was made which should include a fix
Version: 0.3.2~r690+pkg45~ubuntu5.0.1
On: 2019-03-05

**Comment by sprite-1** [comment]
Yeah this seems to be working now :tada: :tada:

**Comment by marwin1991** [comment]
I have the same issue :(

**Comment by peteruithoven** [comment]
@marwin1991 we've solved the issue though, so if it's broken for you that is probably because of something else. Better to open a new issue and please add lot's of information, like which elementary OS you're running, whether you're all up to date etc.

**Comment by 11noskcire** [comment]
> I have the same issue :(

me too! running on elementary os 7 horus
