### ISSUE TITLE
Multitasking view wallpaper DPI switch issue

### ISSUE THREAD

**Issue by peteruithoven** [elementary/gala#484]
The wallpaper that's shown in the background of workspaces in the Multitasking view doesn't seem to update properly after a DPI switch. 

![screenshot from 2019-03-01 23 53 24 2x](https://user-images.githubusercontent.com/523210/53671190-959a3280-3c7d-11e9-93b1-f0cf8bea55e4.png)

![screenshot from 2019-03-01 23 54 19](https://user-images.githubusercontent.com/523210/53671204-a6e33f00-3c7d-11e9-8b62-05919df211b9.png)

For reference, this is how it should look:
![screenshot from 2019-03-02 00 10 49 2x](https://user-images.githubusercontent.com/523210/53671658-b499c400-3c7f-11e9-904b-222da0004ef4.png)

**Comment by lenemter** [comment]
Fixed in #1344.
