### ISSUE TITLE
Selecting window on external monitor from dock changes workspace

### ISSUE THREAD

**Issue by Nine-H** [elementary/gala#499]
What happens:
- opened a vid in mpv on workspace 1
- dragged it to external monitor to watch
- made new workspace to work in
- accidentally buried mpv
- clicked icon on dock
- switched back to workspace 1

What should happen:
- don't change workspace when focusing windows on secondary monitor

**Comment by lenemter** [comment]
I'll close this because I cannot reproduce the issue in OS 7.1
