### ISSUE TITLE
Arranging multiple monitors on top of eachother

### ISSUE THREAD

**Issue by cmonagle** [elementary/gala#50]
Currently it isn't possible to position an external monitor above (or below?) the primary monitor. Not sure if this is a feature or a bug, but I'm hoping it's the latter.

Maybe relevant?:
https://elementaryos.stackexchange.com/questions/8415/multiple-monitors-not-functioning-properly
https://www.reddit.com/r/elementaryos/comments/6qzift/how_to_move_a_window_to_second_monitor_above/

**Comment by peteruithoven** [comment]
Could you describe why not? Where / how it fails? 
I've also had issues, where the Display settings interaction had hard to describe quirks, but I've been able to do this. 
Maybe if you experienced something similar you could create a screen recording?

**Comment by cmonagle** [comment]
Two screencasts:
First one demosntrastes bugginess attempting to stack monitors (though I was able to do it this time)
Second demonstrates that even after, you can't pass through wingpanel to actually move windows to the above the primary display.

[screencasts.zip](https://github.com/elementary/gala/files/1195459/screencasts.zip)

**Comment by peteruithoven** [comment]
I've also experienced the first issue (`Screencast from 2017-08-02 18.23.28`). 
The second I haven't experienced.

**Comment by derekmoyes** [comment]
I can make it work by making the top monitor the primary, and then dragging a windows to the bottom monitor. The dragged window forces me to place it in some sort of weird quadrant, but then I can resize the window as normal, and use it just fine. So strange.

**Comment by brcmesquita** [comment]
I get same issue here.
[https://media.giphy.com/media/pylvxXAVbyV1dneqkL/giphy.gif](https://media.giphy.com/media/pylvxXAVbyV1dneqkL/giphy.gif)

**Comment by brcmesquita** [comment]
`<div style="width:100%;height:0;padding-bottom:56%;position:relative;"><iframe src="https://giphy.com/embed/pylvxXAVbyV1dneqkL" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/elementary-os-pylvxXAVbyV1dneqkL">via GIPHY</a></p>`

**Comment by brcmesquita** [comment]
[](<div style="width:100%;height:0;padding-bottom:56%;position:relative;"><iframe src="https://giphy.com/embed/pylvxXAVbyV1dneqkL" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/elementary-os-pylvxXAVbyV1dneqkL">via GIPHY</a></p>)

**Comment by brcmesquita** [comment]
![](https://media.giphy.com/media/pylvxXAVbyV1dneqkL/giphy.gif)

**Comment by zagatta-sonah** [comment]
> I get same issue here.
> ![](https://camo.githubusercontent.com/3e3778b1eefcd2eace260cb200952522888db3df/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f70796c767858415662795631646e65716b4c2f67697068792e676966)

me too

would really like for this to work

**Comment by m0skit0** [comment]
Same issue here. After insisting it suddenly let me stack the monitors. However the top monitor behaves strangely. Maximizing the windows only takes 10% right of the screen and I can't move the windows in the middle of the screen; it's like the screen is split vertically in two parts. Making the top monitor the primary is not a valid solution for me because then the app bar is between the monitors which is annoying.

**Comment by brcmesquita** [comment]
> 
> 
> Same issue here. After insisting it suddenly let me stack the monitors. However the top monitor behaves strangely. Maximizing the windows only takes 10% right of the screen and I can't move the windows in the middle of the screen; it's like the screen is split vertically in two parts. Making the top monitor the primary is not a valid solution for me because then the app bar is between the monitors which is annoying.

Same Issue here.

**Comment by cassidyjames** [comment]
The various issues mentioned above have been fixed thanks to updates to the panel and Displays settings plug.
