### ISSUE TITLE
Weird workspace switcher animation after trying to move window to left of the first workspace using the move window keyboard shortcut.

### ISSUE THREAD

**Issue by Blast-City** [elementary/gala#503]
elementary OS Juno fully updated.

1- Open an app in workspace 1
2- Press Super+Alt+Left to try to move the window furthest to the left of the first workspace.
3- Press Super+Right to switch to workspace 2.

**Result:** The workspace switch animation is different than a simple Super+Right. It seems that the window on workspace 1 will move to workspace 2, but it doesn't.

**Comment by peteruithoven** [comment]
Could you include a screenrecording? I don't see a difference in the switch animation. I'd recommend using [Screenrecorder](https://appcenter.elementary.io/com.github.mohelm97.screenrecorder) using a small scale.

**Comment by Blast-City** [comment]
Super+Right > Super+Left
![switch_animation_normal](https://user-images.githubusercontent.com/33494283/55299228-ebebc400-5429-11e9-95f4-ab52613be783.gif)
Super+Alt+Left > Super+Right > Super+Left
![switch_animation_bug](https://user-images.githubusercontent.com/33494283/55299273-2ead9c00-542a-11e9-8dd7-197c58349949.gif)

**Comment by peteruithoven** [comment]
I'm afraid I can't reproduce. But I'll remove the incomplete. Thanks for the clear screen recordings.

**Comment by donadigo** [comment]
I can consistenly reproduce this.
