### ISSUE TITLE
Last workspace "limiter" animation is jerky.

### ISSUE THREAD

**Issue by Blast-City** [elementary/gala#504]
1- Login
2- Press Super+Right until you can't go any further.

**Result:** The "limiter" animation is jerky, unlike the first workspace limiter (Super+Left) limiter where it is smooth.

This problem stops after some time logged in. I haven't been able to pin point what makes it stop.

elementary OS Juno fully updated using new profile.

**Comment by peteruithoven** [comment]
Please include a screenrecording. I don't see a difference and I can usually reproduce issues with animations.

**Comment by Blast-City** [comment]
![limiter_animation](https://user-images.githubusercontent.com/33494283/55299202-c8287e00-5429-11e9-9aa6-8531df9e9a59.gif)

**Comment by Blast-City** [comment]
I found a better way to test this:

1- Open workspace overview.
3- Click on the "+" Square
2- Press Super+Right to see the "limiter" animation
3- Close workspace overview.
4- Press Super+Right  to see the "limiter" animation

Compare "2" and "4". The point 2 doesn't show the issue while the point 4 shows.

**Comment by andaran** [comment]
Faced the same problem, elementary os 5.1

https://user-images.githubusercontent.com/58528987/113671121-9ef8f300-96be-11eb-884d-3e5809edeb19.mp4

**Comment by lenemter** [comment]
Fixed in https://github.com/elementary/gala/pull/1803
