### ISSUE TITLE
Workspace overview. Moving a window that was previously selected with the keyboard (grey outline) makes the movable icon a grey box.

### ISSUE THREAD

**Issue by Blast-City** [elementary/gala#505]
1- Open two windows.
2- Go to the workspace overview (Super+Down)
3- Press the arrow keys to select a window with the keyboard (grey outline)
4- Try to move that window with the keyboard.

**Result:** Instead of a movable application icon you get a grey rectangle box.

elementary OS Juno Fully updated with a new user profile.

**Comment by peteruithoven** [comment]
Please include screenshots and or screenrecordings.

**Comment by peteruithoven** [comment]
![Screen record from 2019-03-31 15 05 56](https://user-images.githubusercontent.com/523210/55289391-903c1f00-53c6-11e9-9148-c263899d1ccc.gif)
