### ISSUE TITLE
Keyboard shortcuts and media keys broken with gnome-settings-daemon 3.32

### ISSUE THREAD

**Issue by worldofpeace** [elementary/gala#518]
Error is
```
gsd-media-keys[4270]: Failed to grab accelerators: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Type of message, “(a(suu))”, does not match expected type “(a(su))” (16)
```

It looks like budgie-desktop has been tracking all the changes to gnome-settings-daemon and mutter
so they've already investigated the issue and made a solution.

> https://github.com/solus-project/budgie-desktop/pull/1591

> The signature for the registration method has changed, so needs to be updated

> These changes landed in 3.31.9x cycle:
>
> Mutter: https://gitlab.gnome.org/GNOME/mutter/commit/00ca387ec7f6a864a35e0baee8c69cc71d60641e
>
> Gnome-Shell: https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/156/diffs
>
> And G-S-D might also have similar changes for following the Mutter 3.31.9x change...
>
> Regards.

Their patch was https://github.com/solus-project/budgie-desktop/pull/1591/commits/36b793bcc35bb406c325f553ac8127141dc3b14f.

**Comment by decathorpe** [comment]
This is an issue on fedora 30 as well:

https://github.com/decathorpe/elementary-nightly-rpms/issues/46

**Comment by sollymay** [comment]
looks like this is still an issue. My media shortcuts have been broken since around May. Only two that still work are volume up and down

**Comment by worldofpeace** [comment]
@tintou I believe #566 should have fixed this, but I get
```
[  172.347263] .gsd-media-keys[1035]: Failed to grab accelerator: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Type of message, “(suu)”, does not match expected type “(su)”
```

now.
