### ISSUE TITLE
Context menu gets out of sync

### ISSUE THREAD

**Issue by cassidyjames** [elementary/gala#520]
It seems the window context menu (when right-clicking a titlebar or headerbar) gets out of sync with reality, making it impossible to toggle things on or off sometimes.

An example: right-click a window and set it to "Always on visible workspace". Then right-click the window several times and see that sometimes it is correctly checked, and others it is not.

I believe it's the same/related issue, but then after that, it becomes impossible to uncheck it and the window is stuck being visible on all workspaces.

**Comment by janxkoci** [comment]
I tried to reproduce it shortly, but I don't see it.

**Comment by cassidyjames** [comment]
I should clarify how I can reliably reproduce this on a fully-updated fresh install of Juno:

- Open two windows (i.e. Files and Ephemeral)
- Set one (i.e. Files) as Always On Top
- Right-click the other's (i.e. Ephemeral's) headerbar

*Expected result:* Ephemeral is not Always On Top, and stays under Files.

*Actual result:* Ephemeral becomes Always On Top, and goes above Files.

After this, the state is inconsistent between the window and the menu.
