### ISSUE TITLE
Expose Wallpaper and Display settings on the Desktop like GNOME

### ISSUE THREAD

**Issue by uncertainquark** [elementary/gala#521]
GNOME, like elementary, doesn't have Desktop icons too. But it does make the menu useful by providing only three settings there:
1. Display settings
2. Change wallpaper
3. System settings

This falls in line with elementary's style of exposing relevant settings throughout the OS. For instance, the wingpanel indicators expose relevant settings rather conveniently. It would be great to extend this to the Desktop as well. It can also help set expectations of users coming from traditional desktop paradigms who might at first be confused as to why the right click isn't working!

**Comment by cassidyjames** [comment]
I have a prototype at https://github.com/elementary/desktop, but https://github.com/elementary/gala/issues/563 will need to be fixed first.

**Comment by cassidyjames** [comment]
According to people smarter than me (:wave: @tintou @davidmhewitt), the desktop context menu handling makes more sense to happen in Gala itself instead of a separate application. So I'll archive that repo and leave this open for someone to tackle within Gala itself.

**Comment by cassidyjames** [comment]
This was the menu I'd built there fwiw:

![Screenshot from 2019-06-25 10 48 20@2x](https://user-images.githubusercontent.com/611168/60117179-c9223080-9736-11e9-930d-4fde6f7fb69d.png)
