### ISSUE TITLE
External triggers to open instances of already open apps should open a new tab, not a new window

### ISSUE THREAD

**Issue by uncertainquark** [elementary/gala#523]
For example, if I click the folder icon on the Downloads panel on Firefox, and I already have the Files app open, gala should open a new tab of the download location, not a new window entirely.

**Comment by peteruithoven** [comment]
I'm afraid this isn't something Gala controls. This is up to the individual application. Just like each individual application describes whether it allows one or multiple windows open.

**Comment by uncertainquark** [comment]
Should I file this bug under Firefox or Files app then?

**Comment by peteruithoven** [comment]
Files in this case I believe. 
As far as I know, when applications open other applications they do something similar to `xdg-open text.pdf` for example. They don't specify other behavior. 

Then applications that [say they can open files](https://github.com/peteruithoven/resizer/blob/master/src/Application.vala#L29) will handle [how to react to opening files](https://github.com/peteruithoven/resizer/blob/master/src/Application.vala#L43-L46) (This is a simple example).

**Comment by uncertainquark** [comment]
Can you please "transfer" the issue to the Files repo in that case? I can't seem to find the transfer issue option @cassidyjames was mentioning elsewhere.
