### ISSUE TITLE
Duplicate Window Bug

### ISSUE THREAD

**Issue by LuigiTheHunter** [elementary/gala#528]
In some applications e.g (Boinc or PlayOnLinux) I have the following bug:
![image](https://user-images.githubusercontent.com/1367949/56468132-2b557100-6428-11e9-928f-fe4f9065fc06.png)

I can drag both "windows" to resize both of them. The inner or outer does not matter which one.

When I open an application through the terminal i get the following, I do not know if that is related to the issue or not:

> * BUG * In pixman_region32_init_rect: Invalid rectangle passed Set a breakpoint on '_pixman_log_error' to debug

Applications where the bug occurs:
- PlayOnLinux
- BOINC

**Comment by ryonakano** [comment]
@LuigiTheHunter Thank you for reporting the issue, but I'm afraid this issue is duplicate of #244.

**Comment by LuigiTheHunter** [comment]
@ryonakano thanks for pointing this out! :)
