### ISSUE TITLE
GitKraken app will not snap to the sides

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/gala#529]
Download latest GitKraken client (https://www.gitkraken.com/). The app will maximize when snapped to the top of the screen, but refuses to snap to either side.

**Comment by cassidyjames** [comment]
What screen size and resolution are you using? I'm guessing GitKraken has a minimum width set that is wider than half your display width. Can you manually resize it down to half or less of your screen width?

**Comment by Gabriel-p** [comment]
Samsung 23'', 1920x1080
