### ISSUE TITLE
Some programs have display issues and extra window borders.

### ISSUE THREAD

**Issue by EidoJ** [elementary/gala#530]
![Screenshot from 2019-04-25 21-20-40](https://user-images.githubusercontent.com/3705829/56762773-ef603a00-67a0-11e9-89b7-3e7768dfce78.png)
I have noticed this with two programs: BOINC Manager and PlayOnLinux.

Things I've noticed about the windows with these borders:
- On the active window (the one with
 the black bar as the header in the screenshot), both headers are dragable, but only the outer one can resize the window.
- With BOINC Manager, only the outer border's header can be used to move the inactive window. With PlayOnLinux, it accepts either window being moved around with either border.
- Both borders' close buttons work to close the window, and pressing where the close button should be reveales it:
![Screenshot from 2019-04-25 21-39-06](https://user-images.githubusercontent.com/3705829/56763524-f38d5700-67a2-11e9-9440-ec6af5545da4.png)
- Using Alt + PrtSc only takes a screenshot of the inner window, and when the selected window is the one with just the black header, the header appears translucent.
![Screenshot from 2019-04-25 21-46-10](https://user-images.githubusercontent.com/3705829/56763850-9e9e1080-67a3-11e9-914b-b5c4d26fdb79.png)
![Screenshot from 2019-04-25 21-45-06](https://user-images.githubusercontent.com/3705829/56763770-74e4e980-67a3-11e9-98b4-4d5f3b2faca5.png)

I use a Thinkpad T410 from 2010 with NVidia and Intel graphics, but only the Intel one seems active:
```
jodie@jodie-ThinkPad-T410:~$ glxinfo | grep -i vendor
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
    Vendor: Intel Open Source Technology Center (0x8086)
OpenGL vendor string: Intel Open Source Technology Center
```

**Comment by EidoJ** [comment]
This is what it looks like maximised:
![Screenshot from 2019-04-25 22-56-39](https://user-images.githubusercontent.com/3705829/56768018-80d5a900-67ad-11e9-97c0-a38dfd975949.png)

**Comment by James-Lochhead** [comment]
You might want to look here: https://github.com/elementary/gala/issues/244

**Comment by EidoJ** [comment]
Duplicate of #244 
I don't know if just closing it will cause the info here to be deleted, so I'm commenting and closing as duplicate. Sorry to spam your inbox.
