### ISSUE TITLE
Window not take focus

### ISSUE THREAD

**Issue by terrakok** [elementary/gala#545]
Issue sometimes reproduce on elementary OS 5.0 Juno.
I have Slack (on front side) and Telegram on first workspace and Firefox on second workspace.
When I click on Telegram icon in panel from second workspace then system scrolls to first but Telegram hasn't focus

**Comment by Blast-City** [comment]
> Issue sometimes reproduce on elementary OS 5.0 Juno.
> I have Slack (on front side) and Telegram on first workspace and Firefox on second workspace.
> When I click on Telegram icon in panel from second workspace then system scrolls to first but Telegram hasn't focus
> 
> Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/75147410-window-not-take-focus?utm_campaign=plugin&utm_content=tracker%2F62872462&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F62872462&utm_medium=issues&utm_source=github).

Hi.

Is it the same issue as this? #493

**Comment by terrakok** [comment]
Yes :+1:
