### ISSUE TITLE
Keyboard shortcuts don't work for non england keyboard layout

### ISSUE THREAD

**Issue by terrakok** [elementary/gala#549]
For several applications keyboard shortcuts work only with england keyboard.  
For example: SublimeText, AndroidStudio and other JetBrains applications.
I don't know what is reason.
PS: for xfce desktop it works fine

**Comment by peteruithoven** [comment]
Could you include examples of keyboard shortcuts?
Do these keyboard shortcuts work in Ubuntu for example?

**Comment by terrakok** [comment]
Yes, it works fine for Xubuntu.
I check it for SublimeText from fluthub and bug doesn't reproduce :disappointed_relieved: 
But for AndroidStudio Ctrl+C/Ctrl+V shortcuts don't work:

![](https://habrastorage.org/webt/m9/nm/pn/m9nmpnbaw2dbtxxbzbdoc96izg0.gif)

**Comment by lenemter** [comment]
Fixed in https://github.com/elementary/gala/pull/1589.
