### ISSUE TITLE
Decrease the close animation duration

### ISSUE THREAD

**Issue by donadigo** [elementary/gala#56]
We should consider lowering the close animation from `300` to like `225` or even `200`.

**Comment by danrabbit** [comment]
We probably need to establish some kind of ruleset for how we determine the length of different animations.

Material offers the following:
* 300ms default
* Elements entering the screen occur over 225ms
* Elements leaving the screen occur over 195ms
* Large full screen animations occur over 375ms (I have no idea what this means so I'd be tempted to say just stick to 300).

**Comment by donadigo** [comment]
That's the mobile section, desktop section says otherwise:

> Desktop
> 
> Desktop animations should be faster and simpler than their mobile counterparts. These animations should last 150ms to 200ms.
> 
> Because desktop transitions may be less noticeable, they should be immediately responsive and faster than their mobile counterparts.

**Comment by danrabbit** [comment]
When they're talking about tablet they say to increase the duration by 30% for the larger screen. By "Desktop" they mean web since Google doesn't make native desktop apps. Their reasoning for short transitions on web is

> Complex web transitions often result in dropped frames (unless they are built for GPU acceleration). Shorter durations will make these less noticeable because the animation completes faster.

**Comment by donadigo** [comment]
I'm also fine with 195.

**Comment by bksubhuti** [comment]
I like 500 ms.  I like eOS because of the animations.  I like to see the animations.  The slow close time makes no effect on my speed of workflow.  I do not need to wait for it to disappear before going somewhere else. Best to have a general setting.  Maybe without numbers.  I use the tweak tool.

**Comment by danrabbit** [comment]
Closing because this appears to be fixed
