### ISSUE TITLE
Move maximized windows to their own workspace

### ISSUE THREAD

**Issue by donadigo** [elementary/gala#570]
[Blockbuster](https://github.com/donadigo/blockbuster) has a feature where you can set an option to have maximized windows automatically moved to another workspace.

This requires working out some details, namely:
* Move the window to a new workspace that's created next to the current one or
* Move the window to the last workspace
* Closing that maximized window probably should remove the workspace it's on, just as it happens in the mentioned app

**Comment by danrabbit** [comment]
I think we probably should just use the exact same behavior here as we're using for fullscreen
