### ISSUE TITLE
Windows that start maximized or fullscreened should respect “Move windows to a new workspace” setting

### ISSUE THREAD

**Issue by Blast-City** [elementary/gala#573]
1- Open Terminal and other app.
2- Press F11 to put Terminal in fullscreen mode. Terminal moves to a new workspace.
3- Close Terminal.
4- Return to workspace in step 1 and open terminal again.

**Result:** Terminal opens in fullscreen mode, but doesn't move to a new workspace.

Relevant information:
#570
#571

**Comment by cassidyjames** [comment]
I _think_ I agree to this, especially now that we have optional maximize-to-new-workspace behavior; it's weird how sometimes (when explicitly maximizing) a window will go to a new workspace, but when opening a previously-maximized app it stays on the current workspace on top of my other windows.

Could use a second opinion from @elementary/ux though.

**Comment by cassidyjames** [comment]
I came to report this today after being annoyed by it again. Based on @danrabbit’s :+1: I'm gonna mark this as confirmed.
