### ISSUE TITLE
Apps shouldn't save window size/position if closed in maximized or fullscreen mode.

### ISSUE THREAD

**Issue by Blast-City** [elementary/gala#574]
1- Open Terminal and check window size position.
2- Maximize the window and close Terminal
3- Open Terminal and exit maximized mode

**Result:** The window is not the same size as it was on point 1.

The save state priority order should be:
Fullscreen [Y/N] > Maximize [Y/N] > "Normal window" [X,Y]

**Problem:** The window size/position will not be saved If an user start an app for the first time, adjusts the window size and position and before exiting maximized the window. So probably apps size/position should also be saved before entering maximize/fullscreen mode.

relevant info:
elementary/terminal#377
#572

**Comment by danrabbit** [comment]
Gala currently does not save any information about window size or position. Closing this as "Out of Scope" since it can't be solved within the scope of Gala.

There is already an open pull request for Terminal to address some of its save state issues: https://github.com/elementary/terminal/pull/375

**Comment by Blast-City** [comment]
> Gala currently does not save any information about window size or position. Closing this as "Out of Scope" since it can't be solved within the scope of Gala.
> 
> There is already an open pull request for Terminal to address some of its save state issues: [elementary/terminal#375](https://github.com/elementary/terminal/pull/375)

Hi.

Since this issue seems to affect other elementary apps (Files), how can i report this globally?

Thanks.

**Comment by danrabbit** [comment]
@Blast-City Since each app is responsible for saving its own state, you'll need to report an issue against each effected app. There's no way in GitHub to mark multiple repos as effected by a single issue
