### ISSUE TITLE
Dim parent windows

### ISSUE THREAD

**Issue by danrabbit** [elementary/gala#576]
There is a vestigial gsetting for this that appears to not do anything. But it would be a nice touch to dim parent windows of modal dialogs. This has become a pretty common design pattern across platforms.

**Comment by danrabbit** [comment]
I wonder if we might want to also consider effects like shrinking the parent slightly or blurring (to imply a move along the z axis) like so:

A dim with a shrink and the modal fading and dropping/sliding
![](https://cdn.dribbble.com/users/1641/screenshots/1028754/navbar-animation.gif)

[Another example with blur and white](https://dribbble.com/shots/6687235-Braze-Modal-w-Torchy)

A dim with the modal dropping and fading onto the parent
![](https://cdn.dribbble.com/users/361918/screenshots/4999299/framer-x-modals.gif)

A dim with kind of a cool center expand:
![](https://cdn.dribbble.com/users/824356/screenshots/3306078/set-more-cards-2-dribble-gif.gif)

**Comment by peteruithoven** [comment]
Interesting! 
I've had moments where I suddenly couldn't interact with a window and had to figure out that it was because of a model window somewhere, which for example was below the main window. This visual change might clarify why you can't interact with the main window in those cases.
