### ISSUE TITLE
No animation for tiled windows with tiled match

### ISSUE THREAD

**Issue by andreasfelix** [elementary/gala#582]
![animation4](https://user-images.githubusercontent.com/24651767/61176486-035a5180-a5c2-11e9-948b-b3ee397e511c.gif)
*(slowed down animation)*

It seems like there is no animation when tiling an already tiled window on top of another tiled window. This happens because of line 969:

https://github.com/elementary/gala/blob/a790d2d0f80be8c12a5afe2534ea17bd825f3a63/src/WindowManager.vala#L969-L975

Even I was the last one how edited this line, I just copied it from the previous code. The condition `window.get_tile_match () == null` introduced in #239. 

@donadigo was the idea of introducing this condition? I assume you wanted rule out animations when resizing of two tiled windows?

If this is the case, I think it could be simply fixed by using this condition only on the `size_changed` signal:
```vala
} else  { 
  ulong size_signal_id = 0U;
  ulong position_signal_id = 0U;
  if (window.get_tile_match () == null) { // don't animate resizing of two tiled windows
    size_signal_id = window.size_changed.connect (() => window_change_complete (actor, which_change, size_signal_id, position_signal_id));
  }
  position_signal_id = window.position_changed.connect (() => window_change_complete (actor, which_change, size_signal_id, position_signal_id));
  return; // must wait for size/position-changed-signal to get updated rect_frame
}
```

**Comment by donadigo** [comment]
@andreasfelix to be honest with you, I really don't know why I introduced this there. I predict that it was something wrong with how the animations worked when this wasn't ruled out. Either way there was some issue that I can't remember. 

I'm not sure if this happens still today with the current mutter version and I think it's worth a try.

**Comment by andreasfelix** [comment]
@donadigo, could it maybe be better to do this like GNOME shell
https://gitlab.gnome.org/GNOME/gnome-shell/blob/master/js/ui/windowManager.js#L1468

Instead of using callbacks for different signals of the individual windows, they use the "size-change" signal of the WM to prepare the animation and than play the animation when a "size-changed" signal of the WM is emitted. Also at the beginning of the `size_changed` method they rule out all resizing events, which is probably what you wanted to achieve with `if (window.get_tile_match () != null) return;` condition.

I tested to log the rectangle that bounds window in the `size_changed` method:
```vala
public override void size_changed (Meta.WindowActor actor) {
  unowned Meta.Window window = actor.get_meta_window ();
  var r = window.get_frame_rect ();
  debug("size_changed, window.get_frame_rect: x %d, y %d, w %d, h %d", r.x, r.y, r.width, r.height);
}
```
And this would actually return the updated size of the window (similar to the old `size_change` method). So there would be no need to connect signals 

```vala
ulong size_signal_id = 0U;
ulong position_signal_id = 0U;
size_signal_id = window.size_changed.connect (() => window_change_complete (actor, which_change, size_signal_id, position_signal_id));
position_signal_id = window.position_changed.connect (() => window_change_complete (actor, which_change, size_signal_id, position_signal_id));
```
to callbacks, just to await the new window size. One could just rename `void window_change_complete` to `public override void size_changed`.

Unfortunately I can't figure out the details, as these signals are not listed in https://developer.gnome.org/meta/ and I can't find an up-to-date API reference for mutter, which makes this difficult to implement for me ...
