### ISSUE TITLE
In the new version of Google Chrome the icon is located right over the close button in all app pages

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/gala#590]
Ii.e:

![DeepinScreenshot_Seleccionar área_20190803133208](https://user-images.githubusercontent.com/6054951/62414531-29887580-b5f3-11e9-91e7-b60ed1cb2d9d.png)

**Comment by cassidyjames** [comment]
Google Chrome is completely client-side decorated, meaning that there’s nothing to do with Gala or anything we can do to fix this from the elementary side. It looks like they did not test their latest update with any Linux desktops that have the close button on the left.

**Comment by cassidyjames** [comment]
You can try their issue/bug tracker: https://www.chromium.org/for-testers/bug-reporting-guidelines

**Comment by Gabriel-p** [comment]
Are you 100% sure this is Chrome's fault? Over there they tell me they can't reproduce it: https://bugs.chromium.org/p/chromium/issues/detail?id=990639#c5
