### ISSUE TITLE
Mutter performance patches

### ISSUE THREAD

**Issue by jacob1237** [elementary/gala#592]
Hi there,

This is more like a question rather than an issue. Just wondering, are the latest Mutter/Clutter performance patches going to be included anytime soon?

News: https://www.phoronix.com/scan.php?page=news_item&px=GNOME-3.34-Mutter-No-Frame-Skip

Actually, they progressed even more than the article mentioned. It seems that these patches will remove most of stuttering issues in animation frame rendering.

That would be very nice to have these patches included, because current rendering performance in Gala is a mess, especially when some OpenGL applications are running in the background (like Skype, OBS, etc.).

**Comment by tintou** [comment]
Unfortunately including upstream patches is not always possible, we need to update the whole desktop stack, graphic stack and kernel to enjoy the very latest optimization which will happen in elementary 6.0
