### ISSUE TITLE
Shortcut 'Alt + Tab' multiple use causes screen freeze.

### ISSUE THREAD

**Issue by OnComputable** [elementary/gala#593]
Usage :::   While muti-tasking I prefer using Alt +  Tab for switching between tasks.

Problem::  When I use this shortcut for multiple times, after certain usage the screen doesn't accept            any key or mouse click. It only can switch tasks and nothing else could be done.

For fixing it I have to again restart my laptop.

Device Information - 
Dual-Core Intel® Core™ i5-5200U CPU @ 2.20GHz
Intel Corporation HD Graphics 5500 (rev 09)
8.1 GB memory
983.4 GB storage

Os Information - 
elementary OS 5.0 Juno(64 bit)
Built on Ubuntu 18.04.2 LTS
Linux 4.15.0-55-generic
GTK+ 3.22.30

**Comment by lenemter** [comment]
I'll close the issue because it's old and no similar reports were filed.
