### ISSUE TITLE
Can't navigate open windows with keyboard when doing Super+A

### ISSUE THREAD

**Issue by marcelodeaguiar** [elementary/gala#6]
Every time I use super+A/super+w or super+s I have to move my hands from the keyboard to the mouse to select the window I want to navigate to. 
We should be able to navigate the windows using the keyboard arrows and select with [Enter].

It would be cool if each window had a shortcut tag above then to fast switch. Eg: Press supar+a then 1 to switch to first window.

**Comment by cassidyjames** [comment]
Super + A/Super + W is deprecated, and Super + S has keyboard navigation already with the arrow keys.

**Comment by nkkollaw** [comment]
@cassidyjames : who is supposed to close issues for this project? I see a lot of them are resolved, but stay open..?
