### ISSUE TITLE
Some animations missing on AMD laptop

### ISSUE THREAD

**Issue by calslate** [elementary/gala#602]
I recently purchased an Acer Swift 3 laptop. I'm dual-booting Windows and elementary OS, and noticed that a few animations that were present on my last laptop are missing. However, some still work. For example, loading spinners don't spin; transitions within windows don't slide. I am also unable to change the screen's brightness. Animations that do work include those of the multitasking view, changing desktops, and Plank's animations.

elementary is fully up-to-date, I am using an AMD 3500U mobile processor, with Radeon Vega 8 integrated graphics.
Is this an issue with AMD's hardware, acer's hardware, or elementary's software?

**Comment by Blast-City** [comment]
Hi.

Have you tried to update to the hwe kernel? https://wiki.ubuntu.com/Kernel/LTSEnablementStack

**Comment by calslate** [comment]
Thanks, that worked a treat! No more problems.
