### ISSUE TITLE
[Feature] Make window previews clickable in the alt+tab interface

### ISSUE THREAD

**Issue by apcamargo** [elementary/gala#608]
In a alt+tab interface with lots of opened windows, it would be faster if you could click on the desired window instead of having to cycle trough several windows until you get the one you want.

**Comment by Maccer1** [comment]
Isn't this the actual behaviour? When you press Alt+Tab and then click on the icons that appear at the bottom you can go to any open window.

**Comment by apcamargo** [comment]
The dock icons are clickable, but the window previews aren't.

**Comment by peteruithoven** [comment]
I feel like this doesn't apply to the current window switcher? As there are no window previews? Feel free to reopen otherwise.
