### ISSUE TITLE
Publish a new release!

### ISSUE THREAD

**Issue by quequotion** [elementary/gala#625]
The last official release of gala was [0.3.0](https://github.com/elementary/gala/commit/9119166f19d906429567b7fb1d29db28a2e7ba84), over four years ago.

I wouldn't ask for any sooner than "when it's ready", but I get the impression at least [0.3.2](https://code.launchpad.net/~elementary-os/+archive/ubuntu/stable/+sourcepub/10393774/+listing-archive-extra) is ready.

**Comment by eyelash** [comment]
See also #25 and #543

**Comment by quequotion** [comment]
In that case I'm going to close this as a duplicate of #25 .
