### ISSUE TITLE
There are artifacts after hide popup menus

### ISSUE THREAD

**Issue by terrakok** [elementary/gala#632]
There are artifacts after hide popup menus. It reproduces for any applications but not constantly.  
When i had tried to make screencast artifactes didn't reproduce!  

![ezgif-5-559ab31d7fce](https://user-images.githubusercontent.com/3532155/68288770-12e03780-0096-11ea-8e45-8c3f598ba63b.gif)

## Additional context
They hide when I
 * change window
 * tap Alt+Tab
 * call doc panel
 * scroll content inside current window.

### Expected behavior
Hide popup menu without artifacts

## Platform Information
![Снимок экрана от 2019-11-06 12-13-20](https://user-images.githubusercontent.com/3532155/68288856-37d4aa80-0096-11ea-8c6a-e28c4937f48c.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by davidmhewitt** [comment]
Hi, thanks for the report.

However, we already have an issue open about this in #605 , so I'll close this one in favour of that.
