### ISSUE TITLE
mutter 3.34: no notifications drawn

### ISSUE THREAD

**Issue by worldofpeace** [elementary/gala#636]
## Describe the bug
Testing with `notify-send $message` I expected to see a notification appear, it doesn't anymore with mutter 3.34 and gala.

### To Reproduce
1. `notify-send $message`
2. Expect a notification to slide in
3. It doesn't :frowning: 

## Platform Information

- [x] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

**Comment by worldofpeace** [comment]
Can confirm this is independent from https://github.com/elementary/gala/issues/637, as that's now fixed and I can still produce this.

**Comment by worldofpeace** [comment]
I'm noticing that it's not `no notifications drawn`. If I have many windows in a workspace, one fullscreene'd, a notification will be visible if incoming.

**Comment by danirabbit** [comment]
This is a really old issue report and since we've just added support for Mutter 44, I think this is likely fixed :)
