### ISSUE TITLE
plank allow setting icons for custom shell script or application

### ISSUE THREAD

**Issue by u007** [elementary/gala#645]
hi, i could drag my script or app to the plank bar at the bottom but it appears as gear. is it possible to setup icon for it?

and also will there be options to set plank position to the left or right?

thank you :)

**Comment by ryonakano** [comment]
Thanks for your report, but unfortunately Plank is out of our projects and there is nothing we can do here. You can report your issue at https://launchpad.net/plank.

> and also will there be options to set plank position to the left or right?

You can already do this by left-clicking the dock with Ctrl key pressed and choose "Preference"→"Position".
