### ISSUE TITLE
Add ability to take screenshots using the Print Screen button on keyboard.

### ISSUE THREAD

**Issue by SubhadeepJasu** [elementary/gala#65]
Add an ability to take screen-shot of entire screen with Print Screen button. Use of Alt+PrintScreen to take shot of the active window. Use of CTRL+Printscreen to take shot of selected region.

**Comment by matzipan** [comment]
This issue has already been fixed in daily, and I believe it was also covered by a stable Loki release, so please make sure your system is up to date.

**Comment by SubhadeepJasu** [comment]
I have the latest version and also the regular updates. But pressing printscreen does nothing. Neither does pasting it in a photo editor or LibreOffice Writer.

**Comment by SubhadeepJasu** [comment]
However it may have been a bug that crept in after install. In that case, its fine.

**Comment by matzipan** [comment]
Relevant commits: https://github.com/elementary/gala/search?utf8=%E2%9C%93&q=screenshot&type=Commits

**Comment by SubhadeepJasu** [comment]
Hmm, looks like it was indeed fixed. Thanks m8.
