### ISSUE TITLE
Option to disable snapping between windows (not tiling)

### ISSUE THREAD

**Issue by sprite-1** [elementary/gala#652]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

When I drag an application's title bar over another, it gets "stuck" for a few milliseconds before continuing to drag down.
![Screen record from 2019-12-10 00 09 41](https://user-images.githubusercontent.com/33685433/70452427-0eb69800-1ae2-11ea-816f-3d001544df83.gif)

**Describe the solution you'd like**

I would like an option to prevent his from happening.

**Existing work**

macOS and Windows 10 don't have this issue.

**Describe alternatives you've considered**

Re-compile with this feature disabled but I don't know what part of the code to edit to stop this from happening.

**Comment by cassidyjames** [comment]
I have always had mixed feelings about the snapping. I think it can be handy when you're trying to sort of manually tile (especially since we don't have anything more than half-tiling). But it does make moving overlapping windows around feel like it's a little janky. I wonder if we/Mutter could be smarter and only snap at lower velocity mouse movements?

**Comment by sprite-1** [comment]
Are you aware what portion of the code is responsible for this? I'm thinking of just recompiling it myself with that section commented out just so I can have a snap-free experience since I've never actually found myself using it so at this point it's more of an unwanted behaviour than anything for me

**Comment by fidelisakilan** [comment]
> I have always had mixed feelings about the snapping. I think it can be handy when you're trying to sort of manually tile (especially since we don't have anything more than half-tiling). But it does make moving overlapping windows around feel like it's a little janky. I wonder if we/Mutter could be smarter and only snap at lower velocity mouse movements?

it would be nice if we had a toggle in settings  for this window snap feature

**Comment by lenemter** [comment]
Seems like such functionality is no longer present in the newest mutter versions.
