### ISSUE TITLE
fails to compile against mutter 3.35.2+ (removed deprecated ClutterTexture)

### ISSUE THREAD

**Issue by decathorpe** [elementary/gala#659]
Looking at the [NEWS for mutter 3.35.2][0]

    * Remove deprecated ClutterTexture [Jonas; !932]

`ClutterTexture` and `ClutterTextureClass` were removed.

gala will probably have to be adapted to this change somehow ... at least according to the MR, it looks like alternatives are available:

https://gitlab.gnome.org/GNOME/mutter/merge_requests/932

[0]: https://gitlab.gnome.org/GNOME/mutter/blob/3.35.2/NEWS

**Comment by worldofpeace** [comment]
If it's deprecated it could be easier to implement, i.e no conditional compilation. Because you shouldn't use deprecated code paths, and hopefully the alternate codepaths are viable in older versions of mutter.

**Comment by decathorpe** [comment]
> If it's deprecated it could be easier to implement, i.e no conditional compilation. Because you shouldn't use deprecated code paths, and hopefully the alternate codepaths are viable in older versions of mutter.

@worldofpeace At least one hopes for that to be the case. On the other hand, I don't take anything for granted when talking about libmutter anymore

**Comment by kingodz** [comment]
Also https://gitlab.gnome.org/GNOME/mutter/merge_requests/458
Some Clutter types were replaced with graphene types: 

ClutterGeometry → graphene_rect_t
ClutterPoint → graphene_point_t
ClutterRect → graphene_rect_t
ClutterSize → graphene_size_t
ClutterVertex → graphene_size_t
ClutterVector* → graphene_vec*_t
ClutterVertex → graphene_point3d_t
CoglEuler → graphene_euler_t
CoglQuaternion → graphene_quaternion_t

**Comment by kingodz** [comment]
https://gitlab.gnome.org/GNOME/mutter/merge_requests/935
All the legacy API that deals with the implicit stacks are removed.

**Comment by tintou** [comment]
For the people watching this issue, we don't target unreleased versions so no move will be done right now.

**Comment by decathorpe** [comment]
@tintou I know, and that's completely understandable.

I originally opened the ticket as a "beware, this change will be coming in a future GNOME release", and looking at the timing of future release dates, it will probably be in ubuntu 20.04 LTS (the base base for the next elementaryOS release?).

And, for better or worse, I've switched all gala and greeter builds on fedora (both official packages and nightly builds) back to using the mutter 3.28 compat package for now ... which might break at any minute, since there's no guarantee that it will keep compiling and working on top of newer GNOME releases :frowning_face:

**Comment by tintou** [comment]
Fixed in master
