### ISSUE TITLE
Consistent, translateble screenshot folder and filename like screeshot-tool

### ISSUE THREAD

**Issue by queeup** [elementary/gala#664]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

Print key and screenshot-tool saves different directory and different filenames. https://github.com/elementary/gala/blob/master/src/ScreenshotManager.vala#L225

Print key saves to `~/Pictures/Screenshots(hard coded not translatable)/timestamp screenshot.png`
screenshot-tool saves to `~/Pictures/Screenshots(translatable string)/Screenshot from timestamp(translatable).png`

**Describe the solution you'd like**

I would like to have consistent screenshot directory and filename.
Same as screenshot-tool:
https://github.com/elementary/screenshot/blob/master/po/io.elementary.screenshot-tool.pot#L21
https://github.com/elementary/screenshot/blob/master/po/io.elementary.screenshot-tool.pot#L99

**Comment by danrabbit** [comment]
I've added ScreenshotManager to POTFILES, so the directory name should now be available for translation. However, I'm having trouble determining where the file name comes from. I'm not sure it comes from inside Gala

**Comment by queeup** [comment]
Thanks. I will translate on gnome then. Thanks for the link. I know what to change on gnome now.

**Comment by danrabbit** [comment]
@queeup There's a branch open that will change Screenshot Tool to use Gala for screenshots, so i think this will be automatically fixed at that time
