### ISSUE TITLE
Notification title text is sometimes cut off

### ISSUE THREAD

**Issue by markodp** [elementary/gala#666]
Notification popup seem to have some issues calculating over how many lines the title should be drawn. I noticed this while getting notification that computer will go to sleep.

To reproduce the same problem:
```
notify-send "This title is in one line"
notify-send "This title is long enough to span two lines"
notify-send "This is just in between and it is cutoff"
```

![Zaslonska slika 2019-12-18 22-10-33](https://user-images.githubusercontent.com/805017/71123960-22e64d80-21e4-11ea-970d-7f78a9c19f7b.png)

On latest elementary OS 5.1 stable

**Comment by lenemter** [comment]
I can't reproduce the issue on elementary OS 7. Notification were reworked in elementary OS 6, so I guess it was fixed back then.
