### ISSUE TITLE
Alt+Tab doesn't respect Plank themes

### ISSUE THREAD

**Issue by kmandarin-orange** [elementary/gala#669]
When using a theme for plank like paperterial from [here](https://github.com/kennyh0727/plank-themes), the alt+tab screen won't respect corner roundness attributes applied by the dock theme. The linked pics below should help show what I'm talking about.

![Screenshot from 2019-12-29 21 15 11](https://user-images.githubusercontent.com/55755379/71567129-619cc300-2a82-11ea-88c2-7eaaf2e1ee2e.png)
![Screenshot from 2019-12-29 21 17 48](https://user-images.githubusercontent.com/55755379/71567133-62cdf000-2a82-11ea-8205-ad70c68fc4f9.png)

**Comment by Blast-City** [comment]
Hi.
This is issue is a duplicate of #144 
You should close it. Sorry.

**Comment by kmandarin-orange** [comment]
Must have missed that when I look for duplicate issues, thanks for letting me know.
