### ISSUE TITLE
Double border with gtk3 apps using gdk_set_window_decorations()

### ISSUE THREAD

**Issue by donnie-j** [elementary/gala#671]
As reported and with example images [here](https://trac.wxwidgets.org/ticket/17971) there is an interaction between the WM and certain wxWidgets gtk3 programs that creates a double border, and two sets (!) of title bar & decorations.  This has been hard to track down... wxWidgets is really big and takes a while to compile.

I ran across an [example](https://github.com/thomasokken/free42) that uses only gtk3 today, which is significantly easier to debug.  To reproduce, make sure you have gtk3 development libraries, clone Free42 and do

```
# cd gtk
# make BCD_MATH=1 ; ./free42dec
```

This patch to Free42 stops the bug (and double border effect) from happening.  It seems to not matter what arguments gdk_set_window_decorations() is called with, the bug still occurs.  I'm pretty sure this is a bug in the WM, not in the code.

```
diff --git a/gtk/shell_main.cc b/gtk/shell_main.cc
index 2e3ef79d..b099b0f9 100644
--- a/gtk/shell_main.cc
+++ b/gtk/shell_main.cc
@@ -1113,8 +1113,8 @@ static void show_message(const char *title, const char *message, GtkWidget *pare
 
 static void no_mwm_resize_helper(GtkWidget *w, gpointer cd) {
     GdkWindow *win = gtk_widget_get_window(w);
-    gdk_window_set_decorations(win, GdkWMDecoration(GDK_DECOR_ALL
-                                    | GDK_DECOR_RESIZEH | GDK_DECOR_MAXIMIZE));
+//    gdk_window_set_decorations(win, GdkWMDecoration( GDK_DECOR_ALL
+//                                   | GDK_DECOR_RESIZEH | GDK_DECOR_MAXIMIZE));
     gdk_window_set_functions(win, GdkWMFunction(GDK_FUNC_ALL
                                     | GDK_FUNC_RESIZE | GDK_FUNC_MAXIMIZE));
 }
```

**Comment by donnie-j** [comment]
Update, tested with wxWidgets gtk3 from git: commenting out the 3 calls to gdk_window_set_decorations() in [toplevel.cpp](https://github.com/wxWidgets/wxWidgets/blob/master/src/gtk/toplevel.cpp) also suppresses the double borders bug.  With these 3 calls included, the same binaries work fine elsewhere, but are unusable on elementary OS.

To be clear, fixing wx is not correct... what appears to be happening is setting decorations is triggering a bug in the window manager, causing it to draw a second border etc, which is wrong.

**Comment by lenemter** [comment]
I believe it was fixed either in https://github.com/elementary/default-settings/pull/103 or in wxWidgets v3.0.5 as reported in https://github.com/elementary/default-settings/pull/103#issuecomment-769677970
