### ISSUE TITLE
Open a picture in picture window when switching to another worksplace from a fullscreen window

### ISSUE THREAD

**Issue by Maccer1** [elementary/gala#673]
Let's say you are watching a fullscreen video and then you need to check something that's open on another workspace but you still want to watch the video. Why don't automatically create a picture-in-picture window right when you switch to the other workspace?

This would increase the discoverability of PiP as well.

**Comment by cassidyjames** [comment]
This could be done if: 
- we have a PiP API for apps, and
- the app is aware of PiP (and probably opts into it)

I don't think we should guess whether or not something is a video, and I don't think we want to make all fullscreen windows turn into PiP when on other workspaces.

**Comment by lenemter** [comment]
I'll close the issue in favor of https://github.com/elementary/gala/issues/921.
