### ISSUE TITLE
Notifications do not render emoji properly.

### ISSUE THREAD

**Issue by joe733** [elementary/gala#675]
I used [reminduck](https://github.com/matfantinel/reminduck) to set up a notification saying: "Wake me up at 4 AM 🙂️"... but this is what I got: 
![Screenshot from 2020-01-07 12 46 19](https://user-images.githubusercontent.com/38415384/71876767-93cab680-314d-11ea-8458-087591e3d898.png)
The emoji is blacked-out. Interestingly it shows well in the drop-down notification centre.

You can reproduce by executing: `$ notify-send "message 🙂️"`

On the notification bubble:
![Screenshot from 2020-01-07 13 24 58](https://user-images.githubusercontent.com/38415384/71878515-d1314300-3151-11ea-8e01-8f6dd7138926.png)
In the notification centre:
![Screenshot from 2020-01-07 13 28 54](https://user-images.githubusercontent.com/38415384/71878516-d1c9d980-3151-11ea-9cfa-3df4ba0d3cfc.png)

**Comment by danrabbit** [comment]
Now that notifications are handled in a native Gtk server, this issue is fixed :)
