### ISSUE TITLE
non-gtk apps like windows button

### ISSUE THREAD

**Issue by msmaldi** [elementary/gala#678]
Today after update elementary, non-gtk apps like, vscode or virtualbox-qt, window button close maximize and close come back to original position (close on left and maximize on right).
I prefer use like Windows.

**Comment by kelvin-libercapital** [comment]
I have the same problem with Android Studio

**Comment by miguelsotobaez** [comment]
Have same problem here

#692

**Comment by edwinvandeven** [comment]
Yes can confirm this issue, it seems to happen to qt and electron apps. 
eg. KeepassXC or Spotify.

**Comment by msmaldi** [comment]
Is not problem on GALA, you can solve with:
`gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'`

**Comment by miguelsotobaez** [comment]
> Is not problem on GALA, you can solve with:
> `gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'`

Thank you!!

**Comment by msmaldi** [comment]
Is not problem on Gala, example of set configuration of minimize, maximize and close on right:

```bash
gsettings set org.pantheon.desktop.gala.appearance button-layout :minimize,maximize,close
gsettings set org.gnome.desktop.wm.preferences button-layout :minimize,maximize,close
gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/DecorationLayout': <':minimize,maximize,close'>, 'Gtk/DialogsUseHeader': <0>, 'Gtk/ShellShowsAppMenu': <0>}"
```
