### ISSUE TITLE
No minimize button in flatpak applications

### ISSUE THREAD

**Issue by miguelsotobaez** [elementary/gala#692]
Hi, after the last update, i dont have the minimize button in flatpak aplications anymore, how can i get back or delete the last update?

I have elementary OS 5.1 Hera
Linux 5.0.0-37-generic

Regards

**Comment by tintou** [comment]
We don't have minimize buttons in elementary at all.

**Comment by miguelsotobaez** [comment]
Ok, so its time to move to another os again. Thanks.
