### ISSUE TITLE
Wrong workspaces behavior

### ISSUE THREAD

**Issue by ghabit** [elementary/gala#695]
By default on login there are two workspaces open (screen attached). This issue leads to strange fullscreen behavior for fullscreen applications. For example videos in firefox app opens fullscreen in same workspace with firefox, but this behaviour changes after pressing multitask button or open other app fullscreen.
![Снимок экрана от 2020-01-11 01 51 56](https://user-images.githubusercontent.com/70936/72192098-74fe4580-3415-11ea-86a0-6964016ba266.png)
Also it makes impossible to switch fullscreen-on-new-workspace behaviour, it stops working again after multitasking button is pressed or some other app opened in fullscreen.

**Comment by Blast-City** [comment]
Hi.

Could you check #506 to see if it is the same issue? If it is, please close this one since it is a duplicate.

Thanks.

**Comment by ghabit** [comment]
Description looks similar.
