### ISSUE TITLE
Static number of workspaces broken

### ISSUE THREAD

**Issue by acls** [elementary/gala#698]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
These settings no longer work:
```
gsettings set org.pantheon.desktop.gala.behavior dynamic-workspaces false
gsettings set org.gnome.desktop.wm.preferences num-workspaces 10
```

### Expected behavior
I expect to always have 10 workspaces

## Platform Information
![System settings](https://user-images.githubusercontent.com/371976/72266597-f1428580-35db-11ea-8783-6245e3b7a3d4.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

## Additional context

Here's more info about the issue:
https://elementaryos.stackexchange.com/questions/22009/problem-with-fix-number-of-workspaces?newreg=96ff3fde478740c69a5d1a14f265add3

Some solutions that suggest using the above settings that no longer work:
https://elementaryos.stackexchange.com/questions/10013/how-to-disable-the-empty-workspace-that-appears-when-switching-between-them/10014#10014
https://www.reddit.com/r/elementaryos/comments/1s2svl/why_does_a_workspace_disappear_after_closing_an/
https://www.reddit.com/r/elementaryos/comments/9sw5hj/how_to_limit_workspace_to_1_in_juno/

**Comment by Blast-City** [comment]
Hi.

The solution has changed. If someone is interested instead of using `gsettings set org.pantheon.desktop.gala.behavior dynamic-workspaces false` use:

`gsettings set org.gnome.mutter dynamic-workspaces false`

**Comment by acls** [comment]
Thanks! I thought I had tried that, but apparently not because that works.
