### ISSUE TITLE
Wayland: design workspace communication API

### ISSUE THREAD

**Issue by donadigo** [elementary/gala#70]
This is optional but if we want to fully replace libbamf / libwnck we should implement this.

Couple of things a workspace API should have:
1. Get a list of workspaces
2. Get information about a particular workspace:
 * Index
 * Name (is that used?)
 * Size and position
 * The screen it's currently on
 * Get windows opened on this workspace

3. Performing different actions on a particular workspace:
 * Activating
 * Changing it's name (if there is an actual name)
 * Switching to it's neighbour

4. Receiving information about events:
 * Workspace changed it's name (if there is an actual name)
 * The workspace was activated

**Comment by properlypurple** [comment]
There is this, which would be the best thing to base on
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/40

**Comment by danirabbit** [comment]
I think I'm going to close this since we have already replaced bamf in the dock. So I think this is more or less fixed and we can add new API if we need it
