### ISSUE TITLE
Esc key to close switching between windows/apps during Alt+Tab 

### ISSUE THREAD

**Issue by vikasnataraja** [elementary/gala#707]
When switching windows using Alt+Tab, it would be nice to use the Esc key to **not** switch between windows. Basically, since we use Alt+Tab to switch between windows, Alt+Esc in that process to get out of the task view and back to the original window. I know this is supported in Windows 7/8/10 but it would be nice to have here.

### Platform information
elementaryOS 5.1 Hera
Dell XPS 13 9380
Dual booted system

**Comment by cassidyjames** [comment]
Transferred to Gala

**Comment by vikasnataraja** [comment]
Closing this issue since it is the same as #354, an open issue, already noted and labeled `Priority:Wishlist` with a Bounty.

**Comment by cassidyjames** [comment]
@vikasnataraja ah thank you! Duplicate results don't show up when transferring. :)
