### ISSUE TITLE
"Shutdown"/"Logout" dialog isn't an active window when there are other active windows

### ISSUE THREAD

**Issue by ryonakano** [elementary/gala#71]
## Actual behavior
![screenshot from 2017-09-10 00-22-59](https://user-images.githubusercontent.com/26003928/30241571-dab6c87a-95c0-11e7-8f01-817245a3f8ca.png)
By clicking the power icon on the leftmost of the wing panel and then "Shut Down...", a dialog which confirm that the user will truly shutdown. However, this dialog isn't an active window by defaults, like this screenshot above, when there are other active windows.

## Expected behavior
![screenshot from 2017-09-10 00-23-11](https://user-images.githubusercontent.com/26003928/30241575-e370a436-95c0-11e7-9e45-8480ce5a40bd.png)
This dialog should be an active window by defaults even if when there are other active windows.

## Steps to reproduce the behavior
1. Keep one or some apps' windows opened.
2. Click the power icon on the leftmost of the Wingpanel and select "Shut Down..."
3. Check whether the dialog is active or not, by checking the color of the button, etc.

**Comment by Astro-City** [comment]
Hi.  

I have the same issue.

Let me add that this also happens when you have an empty workspace and before clicking the shutdown button, you click another of the wingpanel icons.

**Comment by ryonakano** [comment]
Additional Info from #118:
This bug does not happen when the desktop is empty. Also, it does not happen in the case of "Logout" dialog.

**Comment by ryonakano** [comment]
This issue also happen in Juno Beta1

**Comment by ryonakano** [comment]
Closing because I can't reproduce this in Juno at all

**Comment by Blast-City** [comment]
Hi.

I think that this issue is back.

Could you please test if it's happening on your end?

I'm seeing this on the logout and power-off dialog windows.

**Comment by vjr** [comment]
Yes happens for me on Juno updated. Does not happen on Loki.

**Comment by ryonakano** [comment]
@Blast-City Yes, I can also confirm this on Juno again in the following cases:

* The logout dialog shown by selecting "Logout…" from Wingpanel Session Indicator
* The shutdown dialog shown by selecting "Shutdown…" from Wingpanel Session Indicator
* The logout dialog shown by pressing `Ctrl+Alt+Del`

However, interestingly it focus on the dialog by default in the following case:

* The shutdown dialog shown by tapping with 3 fingers on the icon of Wingpanel Session Indicator

Also, it seems now this issue happens even if you don't keep one or some window open.

**Comment by Blast-City** [comment]
![bug](https://user-images.githubusercontent.com/33494283/59157940-46994000-8aab-11e9-9f83-d61d2860fbf2.gif)

**Comment by ryonakano** [comment]
Closing in favor of https://github.com/elementary/wingpanel/issues/228#issue-468370212 because there are more reasonable reason why session dialogs lose focus is talked
