### ISSUE TITLE
Cannot switch windows using Alt+Tab when a window is in Full Screen mode

### ISSUE THREAD

**Issue by vikasnataraja** [elementary/gala#710]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
When a window is playing a video in Full Screen mode, it appears we cannot switch between windows. For example, if watching Youtube in Full Screen mode on a browser, using Alt+Tab to switch to a different window like Terminal does not work and just produces an error sound.

This occurs when any window is in Full Screen window (browser tab, VLC media player etc.).

**Edit**
After @Blast-City 's comment, I realize that Full screen videos are played by moving to a different workspace. In that case, it would be nice to still be able to use Alt+Tab to return the video to its original view (normal non-full screen video view), and original workspace and then switch windows. 

### To Reproduce
1. Open any browser, go to www.youtube.com
2. Click on any video, go to Full Screen by pressing F.
3. Use Alt+Tab to switch to another window
4. See error (error sound)

### Expected behavior
The window which is playing the video could reduce to Picture-in-Picture and then switch to the other window when Alt+Tab is used OR it could exit the Full Screen mode (and return to normal video mode) and then switch to the other window.

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version
- [x] I downloaded elementaryOS from the official website

**Comment by Blast-City** [comment]
Hi.

Maybe I'm not understanding, but that seems the normal elementary behaviour. Elementary creates a new workspace every time you put a window in fullscreen. On "To Reproduce" section try to press Super+Down after step 2 and see if the video didn't move to a workspace to the right in which you were.

**Comment by vikasnataraja** [comment]
@Blast-City You're right, I wasn't aware that elementaryOS switched Full Screen to a different workspace. However, using Super+Down only exits the Full screen mode and since it is still in a different workspace, using Alt+Tab to switch between windows won't work since my windows are in the original workspace. My idea was that if you use Alt+Tab while in Full screen mode, it should exit to normal view, return to the original workspace and switch between tabs. Does that make sense? I will edit my description to make it more clear.

**Comment by Blast-City** [comment]
> sing Alt+Tab to switch between windows won't work since my windows are in the original workspace. My idea was that if you use Alt+Tab while in Full screen mode, it should exit to normal view, return to the original workspace and switch between tabs. Does that make sense? I will edit my

Hi.

I only referred Super+Down as a way to show you a visual representation of what was happening.

The Alt+Tab makes sense. There is a similar issue, but it talks about making Alt+Tab switch windows on every workspaces. #406

**Comment by vikasnataraja** [comment]
Closing this issue since I realize it is quite similar to #406 but also to #673 (actually seems like a combination of the two issues) which has been labeled by @cassidyjames as `Priority:Wishlist`.
