### ISSUE TITLE
Dock popover and panel problem

### ISSUE THREAD

**Issue by kaanerdogan** [elementary/gala#712]
![Screenshot from 2020-01-17 05-04-18](https://user-images.githubusercontent.com/19195497/72585926-e7cd5c00-3900-11ea-8570-07741317c1ae.png)

I believe its become like this after an update that i did on 16 jan. Didn't install any application or something that can cause for this. Anyone has the same problem? I restarted or shutdown few times. Didn't change anything. 
If i click any of panel icons its corrects it self.

![Screenshot from 2020-01-17 08-06-48](https://user-images.githubusercontent.com/19195497/72585942-f3b91e00-3900-11ea-942c-ebdb6dc4151f.png)

**Comment by vikasnataraja** [comment]
Can you share your kernel version? I experienced a similar problem where I'd get noisy horizontal bars (like the ones you'd see on a CRT television) but when I restarted and switched to a different kernel, the problem seemed to go away. I looked at this wesbite when I was trying to solve that issue, might be worth a try: https://elementaryforums.com/index.php?threads/graphics-issues-intel.2457/

**Comment by kaanerdogan** [comment]
Solution is [here](https://elementaryos.stackexchange.com/questions/22090/something-wrong-with-my-panel-and-dock-popover) . I just updated display drivers and worked.
