### ISSUE TITLE
Provide an embedded screen-saver

### ISSUE THREAD

**Issue by tintou** [elementary/gala#716]
We need to provide our own screensaver embedded into Gala as light-locker is not being actively maintained anymore and it won't be secured enough for Wayland anyway.

**Comment by harveycabaguio** [comment]
Would it be good idea to mimic the always-on displays that some Android phones have? ie Time and date, currently playing song, little icons for notifications?

**Comment by worldofpeace** [comment]
@tintou Pretty please on this :rofl: 
There was a pretty UX destroying bug that happened with systemd and light-locker a while back, and there's plenty of issues in light-locker.
