### ISSUE TITLE
Screenshot shortcut do nothing

### ISSUE THREAD

**Issue by MauricioGlz** [elementary/gala#720]
## Prerequisites
- [x ] I have searched open and closed issues for duplicates.

## Describe the bug
When using any of the screenshots shortcuts (Shift + screen, alt + screen, Shift + Ctrl + screen, etc) there is no window for check the screenshot and the sound has a 5 seconds delay.

### To Reproduce
1. Press Shift + Screen
2. Nothing happens

### Expected behavior
Show the screenshot app for view the taken screenshot.

### Logs
Unable to find any error (tried gdb)

## Platform Information
 - OS: elementary OS 
 - OS Version: Juno
 - Hardware info: 
Dual-Core AMD A12-9720P RADEON R7, 12 COMPUTE CORES 4C+8G
Advanced Micro Devices, Inc. [AMD/ATI] Wani [Radeon R5/R6/R7 Graphics] (rev c8)

- [ x ] I'm using the latest released stable version

**Comment by lenemter** [comment]
The screenshot shortcuts intentionally don't open Screenshot app. The shortcuts are intended to make quick screenshots and save them automatically to clipboard or screenshots folder. Closing as design conflict.
