### ISSUE TITLE
Window close button on PWA

### ISSUE THREAD

**Issue by AleVul** [elementary/gala#721]
Close button for progressive web application is under window title and don't register the click event.

specs: https://imgur.com/a/ZoWReb0
apps installed: google drive, [material-ui][1]
expected: to be able to click on close button, and for the button to be left of window title (i guess?)
proof: [screenshot](https://imgur.com/a/PAUhsgy)

Note: i'm using google chrome 80

  [1]: https://material-ui.com/

**Comment by cassidyjames** [comment]
This looks like a bug in Chrome, Chromium, or whatever browser you're using. We don't have control over how that app decides to draw its window borders.
