### ISSUE TITLE
Closing windows in multi tasks

### ISSUE THREAD

**Issue by andrefcorreia** [elementary/gala#723]
Hello eOS users and Devs.
It's a simple thing, but it would make all the difference [at least for me].
When I'm using multi tasks, changing the screen with quick access corner [I think that is the name or 'hot corner' :)] with the mice, the "X" is very large and is very close to the click of the square to change the screen.
What happens is that sometimes I end up closing a multi-task screen by clicking on the big "X" by accident causing a great loss of activities that were open there. Please change that. Thanks.
Suggestion: some kind of confirmation before the total closure of the multi-task screen and the increase of the square view.
![eOs-mult-taksview](https://user-images.githubusercontent.com/7284944/74792186-6e2be380-529b-11ea-9c2b-2968286bbb40.png)

**Comment by Blast-City** [comment]
Hi.

I found an older issue (#348) that is similar to this. Could you please close this in favour of the older one. Sorry.

Thanks.
