### ISSUE TITLE
 suggestion for Wingpanel

### ISSUE THREAD

**Issue by 20alice2emanueli** [elementary/gala#724]
![Captura dee tela de 2020-02-24 19 13 48](https://user-images.githubusercontent.com/61390960/75198250-ec2a3780-573e-11ea-8318-b60574838da7.png)

**Comment by danrabbit** [comment]
Ayatana indicator support was removed intentionally. You can watch my talk on the matter here: https://www.youtube.com/watch?v=fPFdV-Z69Lo

Closing as a design conflict
