### ISSUE TITLE
Scroll on desktop to switch workspaces

### ISSUE THREAD

**Issue by cassidyjames** [elementary/gala#729]
I wonder if we could treat scrolling on the blank desktop the same as how we treat it in the multitasking overview. I.e. a mouse scroll or horizontal trackpad swipe while the cursor is over the wallpaper could switch workspaces. 

This would make it easier to switch between workspaces for mouse users.

**Comment by Blast-City** [comment]
Hi.
I think this idea has the same problem that scrolling on Plank icons have. The flow gets broken when there is fullscreen workspaces in the mix.

**Comment by hanaral** [comment]
Unless we are talking about trackpad gestures, scrolling on the desktop should be a no-go. If a user is wanting to switch desktops quickly, they will want to be able to switch back and fourth between workspaces conistently. This would have to stall this process as they would most likely have a maximised window in at least one of the workspaces. 
Maybe a pressure-reveal like switcher at the side of the screen would be better?

**Comment by cassidyjames** [comment]
Yeah I'm gonna close this as it doesn't really work with windows open :stuck_out_tongue_closed_eyes:
