### ISSUE TITLE
Gala background services are displayed as an icon in the Dock

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/gala#736]
Latest Hera 5.1 with all updates. Appears only recently. Right after system startup.
After a few seconds the icon disappears again. 
My expectation would be that this process runs in the background without being displayed.

**Comment by vjr** [comment]
FYI, this is already fixed in git master by this -> https://github.com/elementary/gala/pull/726

**Comment by vjr** [comment]
Also, duplicate of https://github.com/elementary/gala/issues/731

**Comment by 4jNsY6fCVqZv** [comment]
Thanks for your feedback and sorry for the extra noise. I hadn't checked the already closed issues for duplicates. Thanks to the people who already fixed the issue!
