### ISSUE TITLE
Tiling windows go under wingpanel

### ISSUE THREAD

**Issue by GammaGames** [elementary/gala#737]
Tiling windows causes the title bar to go under wingpanel. Might be something to do with having multiple monitors, but I'm not sure.

![Screen record from 2020-03-05 14 44 46-min](https://user-images.githubusercontent.com/7832163/76029004-ec6dc400-5ef0-11ea-8c35-097eea9cac61.gif)

![image](https://user-images.githubusercontent.com/7832163/76028950-d06a2280-5ef0-11ea-88d2-6cfa431dc40c.png)

**Comment by andreasfelix** [comment]
This might has something to do with https://github.com/elementary/wingpanel/pull/235. 

Could you make a screenshot of your monitor layout in the settings app, so I can try to reproduce it?

**Comment by GammaGames** [comment]
Sure!
![image](https://user-images.githubusercontent.com/7832163/76120177-294bc080-5fae-11ea-9467-379aa235058f.png)

**Comment by andreasfelix** [comment]
I can confirm this is a regression of elementary/wingpanel#235.

This should be fixed by https://github.com/elementary/wingpanel/pull/295. If
