### ISSUE TITLE
Chrome web-apps not showing a button to close the window

### ISSUE THREAD

**Issue by cllntn** [elementary/gala#742]
Basically when i create a web-app via chrome the "close" button is hidden behind the app icon.
![bug1](https://user-images.githubusercontent.com/61968584/76202630-7077c280-61f5-11ea-92e4-05fd53254fac.png)

**Comment by cassidyjames** [comment]
This is a bug in Chrome. We have no control over how Chrome draws its own client-side window decorations.

**Comment by aironsouza** [comment]
Hello, I'm no dev and this is my first take on github. May I ask to reconsider this decision? Look, I **know** that this is a problem on Chrome, but at the same time we have to take into account that Chrome it's the lead browser on the market, used by the vast majority of the users (68,5% of marketshare on desktops in march/2020).

**Maybe add some kind of mandatory margin, only a few pixels, on close button can solve this issue**? Web apps are very common nodaways, specially for apps like WhatsApp that doesn't have a native desktop app.

Seeing this error while setting an web app, non-tech users will probably think that elementary have a "bug" in web apps and not the other way around. Maybe It worth to take a look on possible solutions?

**Comment by cassidyjames** [comment]
@aironsouza we literally have no control of what is rendered inside the Chrome window, though. Even if we wanted to, we could not fix this issue. It needs to be fixed on the Chrome side because Chrome itself is doing the actual drawing of the window titlebar and borders.
