### ISSUE TITLE
Keyboard media controls do not work when in "Show all windows" view

### ISSUE THREAD

**Issue by vikasnataraja** [elementary/gala#743]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Media controls do not work when in the `Show all windows` view.

If applicable, add screenshots or screen recordings to help explain your problem.

### To Reproduce
1. Start playing some audio
2. Switch to `Show all windows` view (usually Super+A)
3. Try to use pause/play keyboard buttons to control media

### Expected behavior
Media controls should still work regardless of the view/mode.

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by devgkz** [comment]
Me too. Reprodused it for brightness. The action of the buttons is postponed until the mode is exited.
