### ISSUE TITLE
20_elementary.pantheon.wm.gschema.override refers to non-existent key

### ISSUE THREAD

**Issue by jeremypw** [elementary/gala#758]
I have searched open and closed issues for duplicates.

## Describe the bug

The gsettings override file 20_elementary.pantheon.wm.gschema.override refers to the key `button-layout` in the schema `[org.gnome.mutter:Pantheon]`.  This does not exist in Hera 5.1 daily.

### To Reproduce
1. Run `sudo glib-compile-schemas --dry-run --strict /usr/share/glib-2.0/schemas
` in a terminal.
2. Output `No such key 'button-layout' in schema 'org.gnome.mutter:Pantheon' as specified in override file '/usr/share/glib-2.0/schemas/20_elementary.pantheon.wm.gschema.override'`

### Expected behavior
No error

## Platform Information
Hera 5.1 daily.

I'm using the latest version from daily repository. Updated through AppCenter

**Comment by oberon-manjaro** [comment]
Confirming. Additionally also key `enable-animations` does not exist:
```
No such key “button-layout” in schema “org.gnome.mutter:Pantheon” as specified in override file “/usr/share/glib-2.0/schemas/20_elementary.pantheon.wm.gschema.override”; ignoring override for this key.
No such key “enable-animations” in schema “org.gnome.mutter:Pantheon” as specified in override file “/usr/share/glib-2.0/schemas/20_elementary.pantheon.wm.gschema.override”; ignoring override for this key.
```
