### ISSUE TITLE
How run `gala --replace` automatically when login to pantheon-session?

### ISSUE THREAD

**Issue by LinArcX** [elementary/gala#759]
This is not a bug-report. Just a question.

I'm packaging pantheon for void-linux. After login to pantheon(with lightdm), i have to manually run `gala --replace`. How can i automate it? 

I looked into `/usr/share/xsessions/pantheon.desktop` that contains:
```
[Desktop Entry]
Name=Pantheon
Comment=This session provides elementary experience
Exec=gnome-session --session=pantheon
TryExec=wingpanel
Icon=
DesktopNames=Pantheon
Type=Application
```

I've tried to change it like this:
```
[Desktop Entry]
Name=Pantheon
Comment=This session provides elementary experience
Exec=gnome-session --session=pantheon
TryExec=sh -c "wingpanel; gala --replace"
Icon=
DesktopNames=Pantheon
Type=Application
```
But in lightdm there is no pantheon entry to select.

**Comment by decathorpe** [comment]
You shouldn't need to start gala manually at all.

You can look at the fedora packages for how I'm handling it there, if that helps:

https://github.com/decathorpe/pantheon-session-settings

https://src.fedoraproject.org/rpms/pantheon-session-settings

**Comment by LinArcX** [comment]
I've got it. thank you so much.

I'm going to send my template files as PR to void team.
