### ISSUE TITLE
"Always on Visible Workspace" windows are remain invisible after changing workspace

### ISSUE THREAD

**Issue by alexeyten** [elementary/gala#764]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Windows that are on non-primary displays become invisible after switching workspaces. But they are still there, mouse pointer changes when I move mouse over invisible terminal and I even could select text on it (but don't see anything).

### To Reproduce
1. Open window on secondary display
2. Switch workspaces (Super-Tab)
3. Window disappear but it's still there and mouse pointer “sees” it and changes accordingly.

### Expected behavior
Windows should be visible

### Screenshots or screen recordings
See screen record https://yadi.sk/i/HB61PEYqx_wByQ

### Logs
```
lynn@hera:~$ dpkg -l | grep gala
ii  gala                                       3.3.0~r987+pkg54~ubuntu5.1.2.1                   amd64        Pantheon Window Manager
ii  libgala0:amd64                             3.3.0~r987+pkg54~ubuntu5.1.2.1                   amd64        Library to build plugins for Pantheon Window Manager
```

## Platform Information
![Screenshot from 2020-04-07 10-18-24](https://user-images.githubusercontent.com/44377/78640983-3d3e5700-78b9-11ea-90fb-4052484bebb8.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by oferz** [comment]
I'm seeing this as well after the latest updates, but for me it only happens after I've turn on the window's "Always on Visible Workspace" option for that window, and then switch to a different workspace.

**Comment by alexeyten** [comment]
Yep. All windows on non-primary displays have “Always on Visible Workspace” options that I can't turn off.

**Comment by alexeyten** [comment]
3.3.1 still affected

**Comment by alexeyten** [comment]
I've done some git bisecting. So bug was introduced in commit c43e2d0bcd62b427e2f4d9d16acb51b4b69ac75e

**Comment by cassidyjames** [comment]
I can confirm that windows that are always visible on workspaces are hidden and not re-shown when changing workspaces, and that windows on secondary displays are considered "Always on Visible Workspace" internally by Mutter. So this affects applet-type apps like Nimbus as well as multiple display users.
