### ISSUE TITLE
whether turn "dynamic-workspaces" on or off, nothing changed

### ISSUE THREAD

**Issue by in-character** [elementary/gala#770]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
- After updating system to the latest, if you turn  "dynamic-workspaces"  off in dconf-editor, it doesn't behave as it should be.
- In elementary os 5.1, if you turn it off, you can get what you want.

**Comment by Blast-City** [comment]
Hi.

What keys are you using?

"org.gnome.mutter dynamic-workspaces" and "org.gnome.desktop.wm.preferences num-workspaces" still work on my end.

**Comment by in-character** [comment]
Sorry, I have reinstalled elementary 5.1 and am not plan to update to the latest. 
I can comfirm that the option name is "dynamic-workspaces". It is maybe in " ....gala.behavior.dynamic-workspaces".

**Comment by in-character** [comment]
- I want to achieve this: if I press F11, firefox window will enter fullscreen-mode and still be in workspace 1.
1. In elementary 5.1, if I set "dynamic-workspaces"  as false, the above thing happens.
2. After updating to the latest system, if I set "dynamic-workspaces"  as false, the above thing doesn't happen. Firefox window still will be placing in a new workspace which is the behavior when  "dynamic-workspaces" is set as true.

**Comment by Blast-City** [comment]
>     * I want to achieve this: if I press F11, firefox window will enter fullscreen-mode and still be in workspace 1.
> 
> 
>     1. In elementary 5.1, if I set "dynamic-workspaces"  as false, the above thing happens.
> 
>     2. After updating to the latest system, if I set "dynamic-workspaces"  as false, the above thing doesn't happen. Firefox window still will be placing in a new workspace which should be the behavior when  "dynamic-workspaces" is set as true.

Hi.

Do this:

1- Open terminal and enter the following commands:
`gsettings reset org.pantheon.desktop.gala.behavior dynamic-workspaces`

`gsettings set org.gnome.mutter dynamic-workspaces "false"`

This should work.

**Comment by in-character** [comment]
Thanks a lot. It solved it.
