### ISSUE TITLE
Rudimentary Mixed DPI support

### ISSUE THREAD

**Issue by cassidyjames** [elementary/gala#771]
I _think_ this would be Gala's job since it's always running and knows about displays—though it could also be a separate thing like the System76 HiDPI daemon.

To minimally support mixed DPI without totally breaking or at least requiring fiddly user intervention in the Displays plug, we could automatically set some things when we detect a new mixed DPI configuration:

- Set any HiDPI displays to half their native resolution
- Set 1x scaling

This is what we've been offering as the least-bad solution for mixed DPI to users to do manually for years now, but I think it would make sense to automate it. **Note that we don't need to do this every time, because GNOME Settings Daemon** (I think) **seems to recognize previous display combinations and restore the setup automatically**. So this should only apply to new display combinations.

The System76 daemon does this exact method of resolution halving on the HiDPI display and setting 1x scaling, but it also tries to do _way_ too many other things dealing with previously-set resolutions and layouts and whatnot. 

This simpler fix could be a pretty straightforward way to at least make it less painful for users.

**Comment by danirabbit** [comment]
Closing since we have Mixed DPI support in the Wayland session now
