### ISSUE TITLE
Sudden logout or reboot after changing workspace / going into multitasking view

### ISSUE THREAD

**Issue by muonsei** [elementary/gala#779]
This happened to me twice while changing workspaces and switching apps in multitasking view. It suddenly just shows the "Lenovo" logo (my laptop is a Lenovo) and then goes back to the greeter. 

After I logging in, no apps are open and literally everything that I was doing was gone. I'm not sure if this is because of the latest update I installed today; my laptop was working fine for the past few days.

**Comment by itoshkov** [comment]
Most probably a duplicate of #766.

**Comment by muonsei** [comment]
I agree, I experienced the same problem. Thank you. I was just reporting from the About section of the System Settings.
