### ISSUE TITLE
Better workspaces

### ISSUE THREAD

**Issue by kp2401075** [elementary/gala#788]
Greetings from Australia.

You guys are doing very good work, keep it up.

This is the only feature missing from elementary in my opinion, everything else is pretty much perfect

## Prerequisites
- [x ] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
No, It is suggestion that would greatly improve workflow for a lot of people.

**Describe the solution you'd like**
Separate work-spaces for separate displays ( for multi monitor setup)
for example how mac OSX implements it.
![image](https://user-images.githubusercontent.com/20717654/80792669-644a2900-8bd8-11ea-990a-ad259f298b21.png)

 Not sure if something like this is already in the works or plans ahead
**Describe alternatives you've considered**

An alternative would be workspace extending to secondary display.
pretty much how gnome implements it [with works-spaces spanning displays option from tweaks]
changing work-space on one display also changes it on second

**Comment by kp2401075** [comment]
![image](https://user-images.githubusercontent.com/20717654/81759133-2f5aa200-9507-11ea-99b7-e8e6cd90ed81.png)

Another example of what I'm talking about just in case the one above doesn't make sense.

**Comment by lenemter** [comment]
Duplicate of #26
