### ISSUE TITLE
1:1 response when swipe to switch workspaces

### ISSUE THREAD

**Issue by danrabbit** [elementary/gala#789]
~A three-finger horizontal swipe should switch workspaces. Ideally we'd track the swipe 1:1 as in Hdy.Paginator~

Now that we're shipping touchegg, this feature exists, but it should still be a 1:1 response.

**Comment by andirsun** [comment]
Could be possible a three-finger down to hide all wokspaces and show the homescreen ? and again three finger up to re-open ?

**Comment by danrabbit** [comment]
@andirsun that is filed as https://github.com/elementary/gala/issues/790

**Comment by andirsun** [comment]
> @andirsun that is filed as https://github.com/elementary/gala/issues/790

Ohh sorry my mistake thanks a lot .

**Comment by danrabbit** [comment]
This could possibly be resolved by https://github.com/elementary/gala/pull/958 or a follow-up to that branch

**Comment by JoseExposito** [comment]
I'm on it https://github.com/elementary/gala/pull/972

**Comment by danrabbit** [comment]
Fixed in #983!
