### ISSUE TITLE
Black screen on resume.

### ISSUE THREAD

**Issue by Nine-H** [elementary/gala#79]
I'm not sure about the [entomology](https://en.wikipedia.org/wiki/Entomology) of this bug, and I'm not sure if it should be filed here or in greeter but it's been annoying me for a while and deserves some kind of research and documentation (also it can be fixed using gala input so it could be a missing function in resume code).

When I let my computer go to sleep (as opposed to suspending it with my screen) sometimes when I wake it up the password field on greeter is missing I can make that reappear by closing the computer to suspend and then reopening it, usually this means when I log in I get a black screen with a cursor. This can _usually_ be corrected by tapping a gala hotkey (super-tab usually works) then closing the screen to suspend, then logging in as normal.

I'm on a sandy bridge laptop with an i7-2620M, intel hd3000 graphics, 8GB ram, with loki installed and a quite elderly 7400rpm hard disk. When it happens I can access the virtual terminals using `ctrl` + `alt` + `Fn` so if anybody has trouble reproducing it and wants debug info I can cat some data into a text file and post it for you.

**Comment by matzipan** [comment]
Generally sounds like a graphics driver issue, so I'm gonna mark as invalid. Please advise if this is not the case.

**Comment by Nine-H** [comment]
It's the default driver and the computer works fine in freya as well as XFCE and gnome on 16.04 so I'm not completely convinced. Would running edge drivers be a good idea?
