### ISSUE TITLE
1:1 response when vertical push/pull to open/close multitasking view

### ISSUE THREAD

**Issue by danrabbit** [elementary/gala#790]
~3 fingers pushing away/up should open multi-tasking view. The reverse gesture should close it~

This feature now exists in elementary OS since we ship touchégg, but it should still be a 1:1 response

**Comment by andirsun** [comment]
Did you mean something like touchegg gestures ?
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/22928302/97195910-d8c1e700-1779-11eb-93c5-b93a36b62ad6.gif)

**Comment by danrabbit** [comment]
This could possible be resolved by https://github.com/elementary/gala/pull/958 or a follow up to that branch

**Comment by hanaral** [comment]
FYI the feature-gestures branch now moves between overview and desktop 1:1 as the gesture happens

**Comment by JoseExposito** [comment]
Once https://github.com/elementary/gala/pull/958 gets reviewed this can be closed.

**Comment by danrabbit** [comment]
Fixed in #983
