### ISSUE TITLE
Add minimize window button to windows

### ISSUE THREAD

**Issue by KarkanAlzwayed** [elementary/gala#791]
This is probably the most complained about on reddit. Having a toggle in settings to enable a minimize (or other options) button, without having to download elementary tweaks, would be great. I personally never use the maximize button (double click the bar and call it a day), but I do use the minimize pretty much the whole time I am working on my laptop.
Thank you

**Comment by hanaral** [comment]
The idea is that you fully utilise the workspace system and not constantly minimise and maximise apps, as most apps dont fully exit when you close an app.

**Comment by vikasnataraja** [comment]
I believe this is a feature and not an issue. However, if you do want the minimize button, try installing [Tweaks](https://github.com/elementary-tweaks/elementary-tweaks).

**Comment by Hacime** [comment]
> The idea is that you fully utilise the workspace system and not constantly minimise and maximise apps, as most apps dont fully exit when you close an app.

I would also prefer a toggle in the settings where users can choose if they want a minimize button instead of giving them no choice (or installing tweaks).

**Comment by hanaral** [comment]
>> The idea is that you fully utilise the workspace system and not constantly minimise and maximise apps, as most apps dont fully exit when you close an app. ...

@Hacime this is more of a matter of maintaining a specific workflow, having a minimise/maximise option would imply that it’s a part of the HIG.

**Comment by cassidyjames** [comment]
elementary OS does not use minimize, by design. Regardless, Gala is not in charge of what apps draw inside their windows.
