### ISSUE TITLE
A way to disable the behavior that the window moves to the next workspace automatically when you make it fullscreen

### ISSUE THREAD

**Issue by KarkanAlzwayed** [elementary/gala#792]
This is extremely frustrating. Every time I open my browser it jumps to a separate workspace. To avoid that, I would have to remember to get out of fullscreen before closing my browser. I never work on the browser without it being in fullscreen and having to keep switching to a smaller window before closing the browser is kind of annoying.
Thank you

**Comment by Blast-City** [comment]
Hi.

Please close this issue. #738 will fix this.

Thanks.
