### ISSUE TITLE
Give visual feedback when snapping Windows to the left/right

### ISSUE THREAD

**Issue by uncertainquark** [elementary/gala#8]
Right now, when trying to snap a window to the left/right, there is absolutely no visual feedback available. It would be nice to have snap animation like in other DEs that show how the windows will snap.

Similarly, trying to quarter tile Windows using Shift key + mouse drag, there is no animation feedback.

**Comment by cassidyjames** [comment]
If I recall, there was a problem with our version of Mutter lacking this functionality. We should see if we get it for free from a newer Mutter before re-implementing this in Gala itself.
