### ISSUE TITLE
Pointer revealer conflicts with copy/pasting in non-GTK apps

### ISSUE THREAD

**Issue by febrezo** [elementary/gala#800]
I am experiencing a strange behaviour with the pointer revealer in certain third party applications. Activating it makes me unable to copy/pasting information from platforms like Twitter in Firefox. This behaviour is not taking place in Google Chrome or Epiphany. When trying to copy the selected text from a tweet I am writing, the information is not being copied. Even, when trying to paste information, it is pasted always at the beginning of the tweet, not placing it at the current position of the cursor. 

A similar experience is taking place when manually copying passwords or usernames from KeePass UI, as I'm reporting shortly to the Keepass project. 

It has not been till now that I have been able to link both issues. I can confirm that deactivating the mouse pointer makes both apps work smoothly. 

I know that this is an issue that is linked to very concrete applications out of the scope of the switchboard, but I think that it is still interesting to report this just in case a similar behaviour appears in the future in other applications.

**Comment by lenemter** [comment]
Closing because I cannot reproduce the issue anymore on both X11 and Wayland.
