### ISSUE TITLE
Notifications transparent using eOS daily on Ubuntu 20.04

### ISSUE THREAD

**Issue by jakubklos77** [elementary/gala#804]
Using the daily PPA on Ubuntu 20.04 results in all notifications being transparent. This also applies to Volume Up/Down notifications. I am reporting this as a beta tester of eOS

Prerequisities:
- Ubuntu 20.04 LTS
- Make sure the ppa:elementary-os/stable and ppa:elementary-os/os-patches is used
- Make sure that "elementary" theme is selected in Ubuntu "gnome-tweaks"
- Login to pantheon and simply pres Volume Up on the keyboard (see the notification is transparent as on the screenshot)

### Expected behavior
A notification with background is required just like in Juno

### Screenshots 
![Screenshot from 2020-05-17 08-08-45](https://user-images.githubusercontent.com/6850822/82137150-d09e6c80-9815-11ea-96e1-7c56734ebea0.png)
![Screenshot from 2020-05-17 08-08-57](https://user-images.githubusercontent.com/6850822/82137152-d1370300-9815-11ea-91c8-45931d7c56ce.png)

## Platform Information
![Screenshot from 2020-05-17 08-14-37](https://user-images.githubusercontent.com/6850822/82137228-7a7df900-9816-11ea-9d35-7dc7afc7df3e.png)

**Comment by danrabbit** [comment]
This is completely unsupported. We have not made a release of elementary OS using a 20.04 repository

**Comment by jakubklos77** [comment]
I am aware of that but I suppose the development of eOS 6.0 is already active and the "focal" repository is live so soon or later this issue will need to be fixed. I am merely addressing it.

**Comment by danrabbit** [comment]
The new notifications server relies on styles from the new sass-based stylesheet. So this is expected if you’re still using the old stylesheet.

When we’re ready for public testing, we’ll make images available with the correct out-of-the-box configurations.

I appreciate your desire to help, but issues reported from an unsupported combination of configurations, software sources, and operating systems takes time away that could be spent doing this work.

**Comment by jakubklos77** [comment]
Understood, thank you

**Comment by mohanen** [comment]
For Dark theme i added the elementary os 6 notification css snippet in the `/usr/share/themes/elementary/gtk-3.0/gtk-dark.css` and it worked.

Add this to the end of `/usr/share/themes/elementary/gtk-3.0/gtk-dark.css `

```
window.notification .draw-area {
  background-color: #333;
  border-radius: 0.500000001rem;
  box-shadow: inset 0 -1px 0 0 alpha(@highlight_color, 0.2), inset 0 1px 0 0 alpha(@highlight_color, 0.3), inset 1px 0 0 0 alpha(@highlight_color, 0.07), inset -1px 0 0 0 alpha(@highlight_color, 0.07), 0 0 0 1px rgba(0, 0, 0, 0.75), 0 3px 8px 2px rgba(0, 0, 0, 0.2), 0 5px 5px -3px rgba(0, 0, 0, 0.5), 0 8px 5px 1px rgba(0, 0, 0, 0.2); }
  window.notification .draw-area image {
    color: rgba(255, 255, 255, 0.78); }
  window.notification .draw-area label.title {
    font-weight: 700; }
  window.notification .draw-area .urgent label.title {
    color: @error_color; }
  window.notification .draw-area progressbar progress,
  window.notification .draw-area progressbar trough {
    box-shadow: none;
    border: none;
    border-radius: 0.500000001rem;
    margin: 0; }
  window.notification .draw-area progressbar progress,
  window.notification .draw-area progressbar progress:backdrop {
    background: rgba(255, 255, 255, 0.78); }
  window.notification .draw-area progressbar trough {
    background: rgba(255, 255, 255, 0.15); }
```

**Comment by jakubklos77** [comment]
> For Dark theme i added the elementary os 6 notification css snippet in the `/usr/share/themes/elementary/gtk-3.0/gtk-dark.css` and it worked.
> 
> Add this to the end of `/usr/share/themes/elementary/gtk-3.0/gtk-dark.css `
> 
> ```
> window.notification .draw-area {
>   background-color: #333;
>   border-radius: 0.500000001rem;
>   box-shadow: inset 0 -1px 0 0 alpha(@highlight_color, 0.2), inset 0 1px 0 0 alpha(@highlight_color, 0.3), inset 1px 0 0 0 alpha(@highlight_color, 0.07), inset -1px 0 0 0 alpha(@highlight_color, 0.07), 0 0 0 1px rgba(0, 0, 0, 0.75), 0 3px 8px 2px rgba(0, 0, 0, 0.2), 0 5px 5px -3px rgba(0, 0, 0, 0.5), 0 8px 5px 1px rgba(0, 0, 0, 0.2); }
>   window.notification .draw-area image {
>     color: rgba(255, 255, 255, 0.78); }
>   window.notification .draw-area label.title {
>     font-weight: 700; }
>   window.notification .draw-area .urgent label.title {
>     color: @error_color; }
>   window.notification .draw-area progressbar progress,
>   window.notification .draw-area progressbar trough {
>     box-shadow: none;
>     border: none;
>     border-radius: 0.500000001rem;
>     margin: 0; }
>   window.notification .draw-area progressbar progress,
>   window.notification .draw-area progressbar progress:backdrop {
>     background: rgba(255, 255, 255, 0.78); }
>   window.notification .draw-area progressbar trough {
>     background: rgba(255, 255, 255, 0.15); }
> ```

Brilliant, thank you! Works great.
