### ISSUE TITLE
unknown notification about update

### ISSUE THREAD

**Issue by DinoHasagic** [elementary/gala#808]
Always appear unknow notification about some kind update !!!

.. system is update and working perfectly... except boring notification, nothing happend after apply!!

![Selection_087](https://user-images.githubusercontent.com/65661475/82444764-05275800-9aa4-11ea-9b1c-9301b34b8057.jpg)
/home/dino/Pictures/Shutter/Selection_087.jpg
![Selection_089](https://user-images.githubusercontent.com/65661475/82444862-212af980-9aa4-11ea-95f3-5497d58013c2.jpg)

**Comment by tintou** [comment]
It seems like you've tried to install `ttf-mscorefonts-installer` but this package requires to accept the EULA, you can finish its installation by putting `sudo apt install ttf-mscorefonts-installer` inside a terminal.

**Comment by DinoHasagic** [comment]
It looks terminal command(sudo apt install ttf-mscorefonts-installer) helped, solved!

:)

**Comment by danrabbit** [comment]
Closing since this isn't an issue about Gala
