### ISSUE TITLE
Notifications render too far to the right on the primary monitor

### ISSUE THREAD

**Issue by alfonsojon** [elementary/gala#821]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
I'm running Elementary OS 6.0-next on Ubuntu 20.04 as a base (I changed my /etc/apt/sources.list on Elementary OS 5.0 and changed PPAs to the daily PPAs to "upgrade). I noticed when notifications appear, they appear a little too far to the right, going onto the monitor right of my primary monitor.

Edit: Running Gala version 3.3.2

### To Reproduce
1. Run Elementary's Daily PPA on Ubuntu 20.04 base
2. Get a notification and have multiple monitors
3. Become slightly demoralized when the notification spans onto the monitor right of the primary monitor

### Expected behavior
Notifications render properly in the top right of the screen

### Screenshots or screen recordings
![Screenshot from 2020-05-27 22 26 22](https://user-images.githubusercontent.com/1163298/83095555-3b974100-a069-11ea-9d94-155c53c32114.png)

### Logs
N/A

## Platform Information
![Screenshot from 2020-05-27 22 30 43](https://user-images.githubusercontent.com/1163298/83095793-b95b4c80-a069-11ea-959b-b3ebb47f551e.png)
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the daily PPA on Ubuntu 20.04
- [ ] I'm using the latest released stable version

## Additional context

I am aware the setup I am running is not "supported", but it seems this is not an issue caused by my setup; rather, a bug in how notifications are rendered. I figured this is an issue with window management, so I opened the issue here. I apologize in advance if this is the wrong place to open an issue for this bug.

**Comment by Dirli** [comment]
Confirm. And it seems that it depends on the screen resolution, because I have a monitor with a small resolution, notifications are completely displayed on the second monitor.
perhaps the problem will disappear after changing the plugin to daemon?

**Comment by davidmhewitt** [comment]
Hey, thanks for the report!

This does seem to be an issue I can reproduce so I'll mark it as confirmed. Someone else also reported it recently and I did a little investigation, so I'll add my findings here too for posterity:

Possibly to do with this:

https://github.com/elementary/gala/blob/ad2a9daebbf5232529f577227f1aad1d932a0124/src/NotificationStack.vala#L29

not matching this?

https://github.com/elementary/notifications/blob/af532299d02eb8dc3b33ba4598b313f76e734c43/src/AbstractBubble.vala#L64

**Comment by hanaral** [comment]
This also affects the new swipe to dismiss gesture:
![Screenshot from 2020-10-23 19-03-15](https://user-images.githubusercontent.com/58219504/97038835-5233bc80-1563-11eb-81c8-acaa924e1e37.png)
