### ISSUE TITLE
Displays remain black

### ISSUE THREAD

**Issue by davidak** [elementary/gala#83]
I put my Dell laptop into the docking station with 2 external Dell displays connected. The displays remain black. I disconnected the laptop and connected again, 3 times. Then also the laptop display went black (Sep 20 10:02). It was still black after disconnecting... i had to hard reboot it! (Sep 20 10:09)

Here you have the syslog:

[syslog.txt](https://github.com/elementary/gala/files/1317439/syslog.txt)

Very often this lines appear:

```
Sep 20 10:00:30 Latitude-E5470 kernel: [350726.425428] [drm:intel_wait_ddi_buf_idle [i915]] *ERROR* Timeout waiting for DDI BUF C idle bit
Sep 20 10:00:30 Latitude-E5470 kernel: [350726.486989] [drm:intel_dp_set_idle_link_train [i915]] *ERROR* Timed out waiting for DP idle patterns
```

---
```
elementary OS 0.4.1 Loki
Kernel 4.10.0-33-generic #37~16.04.1-Ubuntu
on Dell Latitude E5470 (Intel i5, 8 GB RAM)
```

**Comment by matzipan** [comment]
Is there anything leading you to believe this issue lies in gala and is not a driver issue?

**Comment by matzipan** [comment]
Closing as invalid until you advise otherwise.

**Comment by davidak** [comment]
@matzipan i'm not sure what component leads to this issue. There is no general elementary OS repository here so i thought this might be the right place.

**Comment by matzipan** [comment]
Even so, elementary only ships the kernels and the drivers that Ubuntu LTS ships, so it is not up to us to fix it.
