### ISSUE TITLE
Screenshots come out dark.

### ISSUE THREAD

**Issue by jcrollard84** [elementary/gala#831]
This is a new issue for me. I've been using Elementary for awhile and noticed this happening very recently. Here is an example (sorry best example I have lol).

The odd thing is it doesn't always do it. I just tried to reproduce it with a new screenshot, but it didn't. But it does it often. I just cant choose when it happens. 
![Screenshot from 2019-05-06 00 44 33](https://user-images.githubusercontent.com/45309255/57212707-6e235700-6f99-11e9-9be8-7d48c5a88ba8.png)

**Comment by danrabbit** [comment]
This should be fixed now that screenshot uses the gala interfaces
