### ISSUE TITLE
Multi task view: incorrect selection border on the active window

### ISSUE THREAD

**Issue by megatux** [elementary/gala#846]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Extending #415 to a more focused issue.
When going to multi-task view, the white border for the current active window is not the right one.

### To Reproduce
1. Have a workspace with several windows
2. Super+Down key to activate multi-task view
3. See if the selected window in this view is the right one. If it is, then choose another and repeat from step 2.

### Expected behavior
the selection in the multi-task view should match the active window, with focus.

### Screenshots or screen recordings

![Screen record from 2020-06-09 12 04 23](https://user-images.githubusercontent.com/850020/84165750-6ced1500-aa4a-11ea-8ce6-4295061d7633.gif)

## Platform Information
 - OS: elementary OS
 - OS Version Juno 5.1

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by leolost2605** [comment]
Fixed in #1849
