### ISSUE TITLE
Picture-in-Picture area selection being offset

### ISSUE THREAD

**Issue by rockerbacon** [elementary/gala#849]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

The area selection in Picture-in-Picture is being offset in both X and Y axis.

In the recording bellow, you can see that only the orange area is selected but the Picture-in-Picture window shows the white portion around the selection.

### Screenshots or screen recordings

![](https://media.giphy.com/media/gLX9N7sXr6SSjU5Lfd/giphy.gif)

### Expected behavior

The Picture-in-Picture window should display exactly what was selected.

## Platform Information

The bug is present on all my devices, 2 laptops and 1 desktop. Each with completely different hardware but all using Hera 5.1.5.

One of the notebooks was outdated (Hera 5.1.2) and only started showing the behavior after updating and rebooting (still worked fine before the reboot).

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context

I've used Picture-in-Picture for a long time and it used to work fine. I've been experiencing this bug for quite some time now (can't tell exactly when it started) and I just lived with it hoping for an update to fix the issue.

**Comment by cassidyjames** [comment]
@rockerbacon are you on HiDPI?

**Comment by rockerbacon** [comment]
> @rockerbacon are you on HiDPI?

All devices are on LoDPI. There seems to be no option for HiDPI in any of them, only LoDPI and Pixel Doubled.

**Comment by cassidyjames** [comment]
@rockerbacon sorry, HiDPI = Pixel Doubled. I could reproduce this in the past, but can't on my current machine. But I've definitely seen it before. Can you still reproduce it after running all available updates and restarting?

**Comment by rockerbacon** [comment]
> @rockerbacon sorry, HiDPI = Pixel Doubled. I could reproduce this in the past, but can't on my current machine. But I've definitely seen it before. Can you still reproduce it after running all available updates and restarting?

Yes, I can reproduce it with the latest updates on all 3 machines.

I just tested changing to Pixel Doubled and restarting and it also shows the same behavior.

**Comment by rockerbacon** [comment]
@cassidyjames I noticed today that the problem is only present when the window is floating. Whenever it is tiled or maximized the offset is so small you can only see it if you intentionally search for it.

I didn't noticed this before because newly open windows are always floating but are sized to occupy the entire screen.

**Comment by m93a** [comment]
I have the exact same issue, but only with some applications. For example, I can reproduce this behavior consistently in Evince, however in Brave Browser everything always works as expected. I'm on 6.1 Jólnir, LoDPI and no font scaling.
