### ISSUE TITLE
Close button isn't available in Google Chrome progressive web app

### ISSUE THREAD

**Issue by lmjsprog** [elementary/gala#855]
Sorry, I don't know if the problem related to the Elementary. A logotype overlaps the window close button. It's no problem as I can close the window in other ways, but it doesn't look pretty.

![image](https://user-images.githubusercontent.com/45996373/85204295-305bcc00-b31c-11ea-9e58-97a2155b301e.png)

**Comment by danrabbit** [comment]
This is unfortunately outside of our control since these window decorations are drawn by Chrome and not by Gala
