### ISSUE TITLE
Misplaced Restore Down Button in current Firefox build (Flatpak & Repo versions)

### ISSUE THREAD

**Issue by profbib** [elementary/gala#868]
## Prerequisites
- [ x] I have searched open and closed issues for duplicates.

## Describe the bug
I am using Firefox installed from the main Ubuntu software repository and have not had any issues in the past.  However, when I opened it 2-3 days ago to take care of some online tasks, I noticed that the Restore Down button had moved from the far right-hand corner of the window to the right, adjacent to the close window button.

This does not affect the performance of the application, but it is an annoying little visual glitch, so I wanted to report it since I know that you guys care about those things.

I tried uninstalling/purging and reinstalling, but nothing changed.  Installing Firefox from the Flatpak repository shows the same problem.

If applicable, add screenshots or screen recordings to help explain your problem.

### To Reproduce
1. Install Firefox
2. See misplaced Restore Down button.

### Expected behavior

I expect the window buttons to be in their usual positions.

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/25838163/87034731-f4df4f80-c1ad-11ea-9b74-19ce1a1425c2.png)

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [ x] I'm using the latest released stable version

**Comment by danrabbit** [comment]
Firefox draws its own decorations. This cannot be solved in Gala. Please report the issue against Firefox.

Closing as “Out of Scope” since this is a bug in Firefox
