### ISSUE TITLE
Auto-tiling feature like in Pop_OS!

### ISSUE THREAD

**Issue by reesericci** [elementary/gala#870]
## Prerequisites
-  I have searched open and closed issues for duplicates. - check!

## Feature
**Is your feature request related to a problem? Please describe.**

I think it would be really cool if an option for auto-tiling windows was added like what is found in Pop_OS! 's gnome shell.

**Describe the solution you'd like**

When I enable this feature, it would automatically tile my windows in a preferred layout. (Select from common layouts found in tiling window managers; e.g. master & stack, bsp, etc)

**Existing work**
The Pop_OS! Gnome shell has this feature, but I'm envisioning choosing between layouts.

**Describe alternatives you've considered**
None

**Additional context**
Kinda like a tiling WM, slapped onto a DE (pantheon).

**Comment by reesericci** [comment]
@elementary any update?

**Comment by Selduro** [comment]
Having an such extensive tiling-manager would of course be awesome. I for now would be completely satisfied if I had the possibility to not only manually split the windows vertically but also horizontally so that the window automatically occupies a quarter of the screen in the corner that I pull it in.

**Comment by reesericci** [comment]
any other response?

**Comment by Julioevm** [comment]
I  think there are a couple of PRs with functionality to enhance the tiling aspect.

**Comment by reesericci** [comment]
ok

**Comment by cassidyjames** [comment]
Duplicate of #316
