### ISSUE TITLE
Alt-TAB cycles between apps forward, but there's no Alt-Shift-TAB to cycle backwards

### ISSUE THREAD

**Issue by dennismayr** [elementary/gala#873]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Alt-TAB cycles apps forward, but there's no Alt-Shift-TAB to cycle backwards.
I can't recall if previous _elementary OS_ versions did include this behavior.
(as developers, you'll relate to cycling through *many* apps)

### To Reproduce
1. Open any 3 apps A, B & C
2. Press `Alt-TAB` to cycle to the next, from app A -> B
3. Press `Alt-Shift-TAB` to try cycling back to the previous app: B <- A
4. OS cycles to the next app after the next app: B -> C

### Expected behavior
OS cycles back to the previous app: A <- B

## Platform Information
![](https://imgur.com/ihFSxMs.png)
 - OS: elementary OS 5.1.6
 - OS Version: Hera
 - Hardware info: ThinkPad T410s: CPU: i5 540M, GPU: Nvidia NVS3100M, memory: 8Gb

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
Because of an _IntelliJ_ quirk (_IDEA_ and _Android Studio_), I have to use `ibus` as input method for "dead keys" (à, è, ì, ö, û, etc.) to be recognized by these two IDEs.

**Comment by tom-james-watson** [comment]
This bug has been around for quite a while.

This fix seems to highlight the source of the issue: https://elementaryos.stackexchange.com/a/9277
