### ISSUE TITLE
Increase zoom factor in Gala's Zoom plugin

### ISSUE THREAD

**Issue by mmohsinkhan** [elementary/gala#876]
I am a software developer with eye sight problem, I need screen magnification to carry out routine work on my computer.

Screen magnification works on Elementary OS but current max magnification factor (2.5 times) is not enough for me. Please make it at least 6 times. If required I can open Pull Request with increased magnification factor.

For now I have build and installed gala from source after increasing magnification factor. 

Best Regards

**Comment by meisenzahl** [comment]
I saw your post on Reddit some time ago and actually wanted to create an issue here. Good that you were faster 😀️

How did you implement it? Did you just increase the maximum zoom factor to `6.0f`? https://github.com/elementary/gala/blob/266bc587e9aa2ade7a14347212a6f19041b03a6d/plugins/zoom/Main.vala#L85-L86

So you can now increase the zoom factor with a step size from `0.5f` to `6.0f`? https://github.com/elementary/gala/blob/266bc587e9aa2ade7a14347212a6f19041b03a6d/plugins/zoom/Main.vala#L124

Maybe it would be a good idea to make the maximum zoom factor and step size adjustable in [Switchboard Display Plug](https://github.com/elementary/switchboard-plug-display)?

**Comment by mmohsinkhan** [comment]
Good to see you here, because of you I'm using EOS as my daily driver.

I made the simplest change possible to make it work on my system, changed 2.5f to 6.0f on line # 85 :).

+1 for Switchboard Display Plug option.

**Comment by meisenzahl** [comment]
> Good to see you here, because of you I'm using EOS as my daily driver.

Because of me? What have I done? 😅️

**Comment by mmohsinkhan** [comment]
> Because of me? What have I done?

It was not possible for me to use EOS with out of the box magnification factor. Because of your answer on Reddit I was able to increase magnification factor.

**Comment by meisenzahl** [comment]
I didn't answer your question at Reddit. Another user was faster 😁️

**Comment by mmohsinkhan** [comment]
> I didn't answer your question at Reddit. Another user was faster

Ohh. Hehe.
But still I must say thanks, you are marking required updates in source code here.
