### ISSUE TITLE
graphic glitch when window snapping to edges 

### ISSUE THREAD

**Issue by fidelisakilan** [elementary/gala#883]
i am experiencing glitch in animations when the window is resized to snap in the edge 
i have reinstalled it fresh too.
GPU:integrated intel UHD 620 graphics 
Ver: elementary 5.1.6
screen recorded:  https://photos.app.goo.gl/1R7qoCe2rp39Hy4Q7

**Comment by lenemter** [comment]
Closing because I don't observe this issue in OS 7 and the attached video was deleted.
