### ISSUE TITLE
Quarter tiling doesn't work like quarter tiling at all!

### ISSUE THREAD

**Issue by uncertainquark** [elementary/gala#9]
Using Shift + mouse drag on Windows to quarter tile them doesn't work as intended. It instead seems like 40% tiling, takes more space than needed.

![screenshot from 2017-05-20 09-40-09](https://cloud.githubusercontent.com/assets/22585732/26272867/97bd5072-3d12-11e7-887c-052cc5334d38.png)

And a second app quarter tiled to its right takes less space than intended.

![screenshot from 2017-05-20 09-40-34](https://cloud.githubusercontent.com/assets/22585732/26272870/a906654e-3d12-11e7-873e-6d3fa8038bb7.png)

**Comment by peteruithoven** [comment]
I think shift is more of a "snapping" feature. So when dragging a window it will snap to the borders of the screen or to borders of other windows, keeping the original size. Same for resizing, it will snap to nearby borders. 
I'm actually curious where you read about this shift feature, I read it very recently on Reddit.

**Comment by MrHuds0n** [comment]
I am quite sure the Shift+Drag is a feature from X Window Manager, not specific to Elementary. I might be wrong on that though.

**Comment by peteruithoven** [comment]
I'm pretty sure this is a feature coming from [Mutter](https://gitlab.gnome.org/GNOME/mutter) which is used by both Gnome shell and elementary Gala.

**Comment by artm** [comment]
Does that mean that in the next version of the eOS the snapping/tiling feature will catch up with that of gnome shell's? What I miss most from the snap in gnome shell is the ability to resize both snapped windows at once. And a minor annoyance is that the windows fly to the opposite monitor size in Multitasking View. I recognize both problems from Gnome Shell a year ago.

**Comment by peteruithoven** [comment]
> What I miss most from the snap in gnome shell is the ability to resize both snapped windows at once

I can confirm that this works in elementary OS Juno.

But @uncertainquark are you sure this issue isn't opened because of an erroneous assumption?

I've opened a seperate quarter tiling issue in the past: https://github.com/elementary/gala/issues/105
