### ISSUE TITLE
Window comes unfocused to the foreground when already opened

### ISSUE THREAD

**Issue by inad9300** [elementary/gala#90]
Steps to reproduce:
1. Open Files.
2. Open any other app, e.g. Calendar.
3. Open Files through the Applications menu.
4. Notice how Files comes to the foreground with a new tab opened, but does not get the focus, which makes for a bad user experience for keyboard-centric users.

Might be a problem with Files...

**Comment by Philip-Scott** [comment]
Might be a duplicate of #1

**Comment by lenemter** [comment]
Closing because the issue cannot be reproduced on OS 8.
