### ISSUE TITLE
Issue. Freezing A lot and getting stuck

### ISSUE THREAD

**Issue by weatheralex1** [elementary/gala#901]
This os is less stable than Windows 10. If freezes on me a lot. I think there should be a stability update. Plus It would get stuck on playing videos sometimes.
![Screenshot from 2020-08-20 12-16-16](https://user-images.githubusercontent.com/61258302/90797795-1e2be900-e2df-11ea-9f58-1fc9f66f3f6c.png)
Just so you know my hardware. And OS Version. 
When Ever I play Minecraft or Have a few pages open on Chrome. Sometimes I will be watching a Youtube video on Chrome, Firefox or Epiphany and All of a sudden It just freezes, and I am not even at half the memory. I mean I would understand If I was hitting the maximum memory, but I am not.

**Comment by danrabbit** [comment]
Can you be more specific about the problem you encountered? Are there reproducible steps to cause a freeze to occur? Does the freeze occur when using a specific app or when any video is playing from any app?

**Comment by hanaral** [comment]
Do you know whether you are using the built in open source graphics drivers or did you install the proprietary ones from the appcenter? Also do you have hardware acceleration enabled in Firefox or chrome?

**Comment by weatheralex1** [comment]
> Do you know whether you are using the built in open source graphics drivers or did you install the proprietary ones from the appcenter? Also do you have hardware acceleration enabled in Firefox or chrome?

I am using the open source graphics drivers. Yes I have hardware acceleration on in Chrome and Firefox

**Comment by hanaral** [comment]
Are there any visual glitches when playing videos? Does it do this with any other OSes apart from Windows?

**Comment by weatheralex1** [comment]
> Are there any visual glitches when playing videos? Does it do this with any other OSes apart from Windows?

No and No

**Comment by lenemter** [comment]
Closing the issue as stale.
