### ISSUE TITLE
missing support for mutter 3.38 / libmutter-7

### ISSUE THREAD

**Issue by decathorpe** [elementary/gala#902]
gala does neither install (missing libmutter-6 in repos) nor build (missing support for libmutter-7) on fedora 33+, so the Pantheon session is either broken or cannot be installed right now.

I tried to introduce a compat package for mutter 3.36 (while fedora 33+ has mutter 3.38 right now) - similar to what I did for mutter 3.28 until versions 3.30+ were supported - but it looks like that isn't going to work this time due to package conflicts and other dependency upgrades.

I'm not sure what amount of work still needs to be done on top of the WIP PR opened by @tintou here:
https://github.com/elementary/gala/pull/854

But it looks like mutter developers have - again - messed up (or removed) several APIs between libmutter-6 and libmutter-7.

Can I submit a PR based on @tintou 's branch to at least get the meson plumbing into place, so we can iteratively adapt to the libmutter-6→7 API changes, or would you recommend a different approach?

---

See also these Red Hat Bugzilla entries:
- [RHBZ#1831485: FTI: gala: gala, gala-devel, gala-libs](https://bugzilla.redhat.com/show_bug.cgi?id=1831485)
- [RHBZ#1863591: gala: FTBFS in Fedora rawhide/f33](https://bugzilla.redhat.com/show_bug.cgi?id=1863591)
- [RHBZ#1871485: F34FailsToInstall: gala, gala-devel, gala-libs](https://bugzilla.redhat.com/show_bug.cgi?id=1871485)

**Comment by decathorpe** [comment]
I've built on top of #854 and layered some ugly hacks on top so gala at least compiles aganist 3.38:
https://github.com/decathorpe/gala/tree/libmutter-7

I have not tested whether it works yet, since I'll still have to adapt wingpanel first.

**Comment by decathorpe** [comment]
fedora 33 currently has some issues with X11 based sessions, so I can't test gala and greeter on mutter 3.38 right now.

But gala+wingpanel compiled with the mutter 3.38 support changes seem to launch fine and don't crash, I just can't interact with the session at all, so YMMV and the ugly hacks I made to get it to compile are probably not suitable for merging.

**Comment by alucryd** [comment]
Gonna chime in on this as well since Arch Linux is pushing the Gnome 3.38 update. @decathorpe Will borrow your patch for the time being, thanks!

**Comment by alucryd** [comment]
Looks like I'm not out of the woods yet, missed that "can't interact with the session" bit. I see @tintou pushed another commit since then, but it's still not enough to get it to build here: https://paste.xinu.at/0KhV7yPdEyHJwBQG/

**Comment by decathorpe** [comment]
Fixed by: https://github.com/elementary/gala/pull/854
