### ISSUE TITLE
Reveal Pointer Location steals focus

### ISSUE THREAD

**Issue by danirabbit** [elementary/gala#914]
1. Turn on pointer reveal
2. Focus any element which makes it easy to see when focus is gained or lost, such as this textbox on GitHub
3. Notice that while Ctrl is held down, focus is stolen

This can lead to unintended results in apps that react when focus leaves an entry such as in Inkscape:

1. Create a shape on screen
2. Overwrite its value for height or width with your own value (but do not use decimal places). For example type in `22`.
3. Select this value and attempt to copy it with Ctrl + C
4. Notice that when you press Ctrl, focus is lost which mean Inkscape converts the value to include `.0` and your selection is cleared before you are able to copy the value.

**Comment by cassidyjames** [comment]
I've confirmed this in apps other than Inkscape as well; any app that does something on a widget's focus-out are affected.

**Comment by leolost2605** [comment]
This seems to be fixed?

**Comment by danirabbit** [comment]
I can't reproduce this anymore in a Wayland session but it does still occur in X11. This might be one of these things that is just a quirk of X11 and can't be solved there. I'm fine closing this as fixed
