### ISSUE TITLE
Background flashes while switching workspaces with multiple displays

### ISSUE THREAD

**Issue by danrabbit** [elementary/gala#926]
While using multiple displays, the background flashes while switching workspaces using keyboard shortcuts.

My guess is that this has to do with a kind of hacky thing that was done to give the illusion of space between workspaces. Gala is drawing over the workspace instead of them actually being spread apart during the animation. So we can probably remove that completely

**Comment by hanaral** [comment]
Can confirm this, it seems to shift the background image in the animation and then ping back to its 'true' position. It does this with vertical displays too even with single display layouts but I might need to open a seperate report for that.

**Comment by JoseExposito** [comment]
It is completely replacing the wallpaper in the current desktop with a grey square. The animation is too fast to notice it, but if you slow it down it is easier to see.

This was driving me crazy!
