### ISSUE TITLE
Desktop native keyboard layout configuration for portability

### ISSUE THREAD

**Issue by devgkz** [elementary/gala#931]
What you think about excluding keyboard config (KeyboardManager.vala) from Gala for using in other desktop environments with their own keyboard layout configuration system?
Or make ability to disable gala's keyboard manager by config or command line options.
This could make the gala more portable to other desktops.

**Comment by danrabbit** [comment]
As we move to Wayland it's unrealistic to think that the desktop environment and window manager are uncoupled. It's probably not worth spending energy in this direction

**Comment by devgkz** [comment]
Yes, you're right. Thanks for answer.
Will transition to Wayland completed in 6.0 (Odin) version?
