### ISSUE TITLE
Main display notification bubbles bleed through on secondary

### ISSUE THREAD

**Issue by hanaral** [elementary/gala#932]
I only got to test this the other day with my new laptop. It seems that notification bubbles on the main display become misaligned and show up partially on the secondary display, when their software layout is with the secondary to the right of the main one.

**Comment by davidmhewitt** [comment]
Can confirm this on my PC with only a single monitor, but a silly nvidia driver that reports 2 connected monitors (even when there isn't).

**Comment by davidmhewitt** [comment]
Possibly to do with this:

https://github.com/elementary/gala/blob/ad2a9daebbf5232529f577227f1aad1d932a0124/src/NotificationStack.vala#L29

not matching this?

https://github.com/elementary/notifications/blob/af532299d02eb8dc3b33ba4598b313f76e734c43/src/AbstractBubble.vala#L64

**Comment by hanaral** [comment]
> Can confirm this on my PC with only a single monitor, but a silly nvidia driver that reports 2 connected monitors (even when there isn't).

I'm on AMD + Mesa right now, and my laptop is Intel + Mesa. I presume that it is in the notification system like you said

**Comment by davidmhewitt** [comment]
Ah, I see this is already reported under #821 so I'll close this issue in favour of the one that has some nice screenshots that show the issue and move my comment over there.
