### ISSUE TITLE
Volume feedback fails to display (Hera)

### ISSUE THREAD

**Issue by mcclurgm** [elementary/gala#935]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
On my system, the volume popup displays rarely, if ever. I hear the volume level clicks and the volume changes, but the popup does not appear.

### To Reproduce
Haven't found any steps to reproduce this... I know the code path that causes it though, see below.

### Expected behavior

The volume popup should appear.

### Logs

Every time I click a volume button on my keyboard, I see this message:
```
** (gala:23561): CRITICAL **: 07:43:36.810: gala_dbus_notifications_notify: assertion 'self != NULL' failed
```

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

I'm using a compiled version from May, after the latest release (I'm not running Odin, so not using the latest git version)

## Additional context

Here's what I've found based on the log message:

- The error happens on `MediaFeedback.vala:122`. The `notifications` variable is null. This seems to mean that sending the notification fails.
- This null is caused because it's never set from the default value in `handle_name_owner_changed()`.
- The `name` variable appears to have the value `:1.518`, which is not `org.freedesktop.Notifications` as the code expects. So this method exits early, before the `notifications` object ever takes on a value.

I'm not sure what causes this change in the value of `name` (not familiar with DBus) but this appears to be what's causing the bug. If it's possible to keep going with a different name, then simply removing the assumption of a certain name would probably fix this issue.

**Comment by lenemter** [comment]
Closing because notifications were rewritten in OS 6.
