### ISSUE TITLE
Multitasking view does not update when scale changes

### ISSUE THREAD

**Issue by danrabbit** [elementary/gala#943]
If I change display scale, the position of the workspace squares in the multitasking view does not update to reflect the new scale

1. Start your session in HiDPI
2. Switch to a LoDPI environment such as when attaching an external display
3. Enter multitasking view and notice the position of workspace squares at the bottom of the display is significantly offset

**Comment by JoseExposito** [comment]
Should have been fixed by https://github.com/elementary/gala/pull/1163
