### ISSUE TITLE
Add Take Screenshot to the header context menu

### ISSUE THREAD

**Issue by danrabbit** [elementary/gala#955]
## Problem

It’s a long multi-step process to open the screenshot app, select the window capture mode, then ensure the correct window is focused when the screenshot occurs 

## Proposal

Add a menu item “Take Screenshot” (or “Capture” I’m not sure which language we typically use) to the header context menu

Cassidy pointed out that this is also a natural place to expose the keyboard shortcut for window captures

**Comment by cassidyjames** [comment]
We use “Take Screenshot” as the action in Screenshot, and the term “grab” for the different modes in Screenshot—i.e. “Grab the current window”. For the app actions, it’s just “Screenshot of…”

I feel like “take” or “capture” work equally well here, but we should update the Screenshot app itself to be more consistent with what we decide (https://github.com/elementary/screenshot/issues/195).
