### ISSUE TITLE
Ship preferences-desktop-workspaces instead of multitasking-view

### ISSUE THREAD

**Issue by fabiozaramella** [elementary/gala#957]
## Proposed change
As proposed on Slack I think it would be appropriate to ship `preferences-desktop-workspaces` from the icons theme instead of the current `multitasking-view` because it better reppresent the actual result of the action and also matches the icon used in the Keyboard Plug.
This depends on: https://github.com/elementary/icons/issues/974

**Comment by 4jNsY6fCVqZv** [comment]
@fabiozaramella Do you see a possible link to https://github.com/elementary/icons/issues/961 here?

**Comment by fabiozaramella** [comment]
Maybe, at least for "Multitasking and Window Management" but I'm not sure which name should the icon take at the end between `preferences-desktop-workspaces` and `multitasking-view`, I guess the second one, but is up to the @elementary/ux team.
