### ISSUE TITLE
Add screenshot image to clipboard automatically

### ISSUE THREAD

**Issue by tetebueno** [elementary/gala#964]
## Feature
Maybe this is not the repo to submit this, help me out here.

When using any of the screenshot shortcuts, such as the `Shift` `Print`, the screenshot is automatically saved in `~/Pictures/Screenshots`. It'd be useful to also have it available in the clipboard too so it's ready to be pasted anywhere.

**Describe the solution you'd like**
As mentioned above.

**Existing work**
I don't know if I've seen this on Windows 10. Not sure.

**Describe alternatives you've considered**
This can also be achieved using the Screenshot application, but the idea of the shortcut is to avoid the need to open an application for addional settings.

**Comment by cassidyjames** [comment]
The risk here is losing clipboard data, especially as we don't have any sort of persistent clipboard manager or anything. If someone copied a big chunk of text, takes a screenshot, and then pastes, it might be annoying that they don't paste that text.

**Comment by alexeyten** [comment]
Don't we already have this?

![image](https://user-images.githubusercontent.com/44377/98728176-2d847500-23aa-11eb-9fcb-e85b08d04b74.png)

**Comment by tetebueno** [comment]
Just realized the shortcuts were already there and tested them. Thanks.

Closing the issue as there's no need to fall into the risk @cassidyjames mentioned.

Cheers.
