### ISSUE TITLE
WindowSwitcher class causes hangs/crashes on Wayland 

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/gala#971]
Opening this for tracking against the Wayland project board.

The `WindowSwitcher` class currently depends on Plank which currently tries to initialize GTK (for styling stuff I think) during Gala startup. For the same reasons as mentioned in #970 , this causes Gala to hang on startup.

This should be resolved by replacing the plank-based window switcher by a new design. Details here: https://github.com/elementary/gala/issues/72

**Comment by danrabbit** [comment]
@davidmhewitt this can be closed now yeah?

**Comment by davidmhewitt** [comment]
I'd imagine so. I'll re-open if it's somehow still an issue.
