### ISSUE TITLE
Add gesture to switch between windows on a touchpad

### ISSUE THREAD

**Issue by fs3o5** [elementary/gala#979]
## Problem

There is no way to cycle through open windows on a touchpad.

## Proposal

Since we are now getting a lot of gestures I would like to see a way to cycle through windows using a touchpad.
Perhaps simular to how windowes does it. [Example at 0:51](https://youtu.be/cN-Y4LR5r-8?t=51)

**Comment by JoseExposito** [comment]
I cannot tell you if this is something the elementary team wants to include by default. But, you will be able to configure it if you want:

https://github.com/JoseExposito/touchegg#keyboard-shortcut-send_keys

```
<gesture type="SWIPE" fingers="3" direction="LEFT">
  <action type="SEND_KEYS">
    <repeat>true</repeat>
    <modifiers>Alt_L</modifiers>
    <keys>Shift_L+Tab</keys>
    <decreaseKeys>Tab</decreaseKeys>
  </action>
</gesture>

<gesture type="SWIPE" fingers="3" direction="RIGHT">
  <action type="SEND_KEYS">
    <repeat>true</repeat>
    <modifiers>Alt_L</modifiers>
    <keys>Tab</keys>
    <decreaseKeys>Shift_L+Tab</decreaseKeys>
  </action>
</gesture>
```
