### ISSUE TITLE
Windows changing sizes and positions when re-entering suspended user session

### ISSUE THREAD

**Issue by janga1** [elementary/gala#981]
# What Happened

Regularly, when I suspend my session and later log back in, I can see my windows being resized and moving to another place (happens very fast). Not a huge problem, but still quiet annoying. Here is an example:

Before suspending user's session:

![Before](https://user-images.githubusercontent.com/35235201/101163356-ca49d380-3633-11eb-95b8-6516061b1882.png)

After logging back into user's session:

![After](https://user-images.githubusercontent.com/35235201/101163352-c8801000-3633-11eb-8fd9-47b70fc77d06.png)

Although these screenshots were taken a day apart for this example, the example is a real one (I did not change the position or size of the window).

# Expected Behaviour

Session should be restored as was before suspending: all windows keep their respective sizes and positions on the screen.

# Important Notes

1. This isn't a lot to go on, but I will update when I learn more about the problem.
1. It does not always happen(!). <s>I think it happens when the session is suspended for a while (hours).</s> It happens both after short and long suspensions, but not consistently in any way.
1. This problem only started occurring when I changed my resolution from 4K to HD some time ago (because laptop battery). So I expect this to be a big clue.
1. The windows always get positioned near the top left corner of the screen. Sizes also seem pretty much the same each time.
1. Sometimes not all windows are affected. (possibly GTK only problem..?)

**Comment by janga1** [comment]
Still clueless... happens frequently and randomly. Anyone who can help me track down the source of this issue?

**Comment by Blast-City** [comment]
Hi.

Sorry I can't help, but this issue reminds me a lot of #580.

**Comment by janga1** [comment]
> Hi.
> 
> Sorry I can't help, but this issue reminds me a lot of #580.

I took a look, but #580 is not an issue I'm having. The resizing and repositioning only happens after a session was suspended and the user re-enters that session. Unfortunately this doesn't always happen for me, making it difficult to say what could be causing this... Thanks for reaching out though.

**Comment by Blast-City** [comment]
Hi

Sorry if I was not clear. I was refereeing just the window resize. Since both situations cause the same issue it's possible they have something in common which makes it easy to find what the problem is.

**Comment by janga1** [comment]
Not sure how, but this issue is old news. Thanks everyone.
