### ISSUE TITLE
Wrong Window Shadow

### ISSUE THREAD

**Issue by adrianptr** [elementary/gala#986]
The reported bug is very simple: when open Firefox Developer Tools window, the shadow not appear correctly.
I attach screenshot of problem.

![Screenshot-12-11-2020](https://user-images.githubusercontent.com/23382033/101944627-4cfeff80-3bed-11eb-93ef-be8ea4ff5b07.png)

Premise: i encounter the problem only in Firefox secondary windows (Es Developer Tools).

**Comment by martinstork** [comment]
Duplicate of [elementary/gala#948](https://github.com/elementary/gala/issues/948)

**Comment by lenemter** [comment]
Duplicate of #948
