### ISSUE TITLE
Request: Chrome OS-like shortcut for tab switching in Epiphany

### ISSUE THREAD

**Issue by KibSquib48** [elementary/gala#987]
Sorry if this is not the right place to request this feature, I know it's technically a feature request for Epiphany but afaik the touchegg implementation is at the window manager level so I thought it might be better to post here

## Problem
There is no easy quick way to switch between tabs with the touchpad

## Proposal
Add a gesture similar to the one in Chrome OS to switch tabs

## Prior Art
In Chrome OS, you swipe left or right with 3 fingers on the touchpad, which makes a subtle highlight appear on the tab that is about to be selected. The tab that is selected depends on how far your fingers move. This is a huge boost in my productivity on Chrome OS and I miss it every time I use any other OS, so I would like to see it here in Epiphany

**Comment by JoseExposito** [comment]
I don't think the elementary team wants to add more gestures for the moment, and in my opinion this should be designed and implemented by the Epiphany devs for a better user experience.

However, you can always configure Touchégg to emulate the behaviour you mentioned. Try to add this at the bottom of your config file (`/home/<your user>/.config/touchegg/touchegg.conf`):

```xml
  <application name="Epiphany">
    <gesture type="SWIPE" fingers="3" direction="LEFT">
      <action type="SEND_KEYS">
        <repeat>true</repeat>
        <modifiers>Control_L</modifiers>
        <keys>Page_Up</keys>
        <decreaseKeys>Page_Down</decreaseKeys>
      </action>
    </gesture>

    <gesture type="SWIPE" fingers="3" direction="RIGHT">
      <action type="SEND_KEYS">
        <repeat>true</repeat>
        <modifiers>Control_L</modifiers>
        <keys>Page_Down</keys>
        <decreaseKeys>Page_Up</decreaseKeys>
      </action>
    </gesture>
  </application>
```

Remember that this is just a keyboard emulation, so the experience is not going to be like in Chrome OS.

**Comment by danrabbit** [comment]
Yeah as José pointed out this is better reported upstream in Epiphany Gitlab. In-app gestures need to be done at the app level to get 1:1 responsiveness
