### ISSUE TITLE
Communicating with Touchégg should not pass structs via a socket

### ISSUE THREAD

**Issue by danrabbit** [elementary/gala#990]
@tintou's comments here:
> I'm not really a fan of passing structs via a socket, you can also use D-Bus over a socket instead which would make it look better for inter-process communication.
> for an example on how to do it, it's what I've done for switchboard:
> https://github.com/elementary/applications-menu/blob/master/src/synapse-plugins/worker-link.vala
> https://github.com/elementary/applications-menu/blob/master/src/synapse-plugins/switchboard-plugin.vala
> https://github.com/elementary/applications-menu/blob/master/src/synapse-plugins/switchboard-plugin/plugin.vala

**Comment by JoseExposito** [comment]
This could be an interesting addition, specially to make easier from higher level languages that don't have access to the big variety of ints C++ has or that might align memory in a different way, like JS.

I'll look into this, but with low priority.

**Comment by JoseExposito** [comment]
I just finished the implementation upstream: https://github.com/JoseExposito/touchegg/issues/436

As soon as I figure out how D-Bus works in Vala, I'll do my best to port it.

**Comment by meisenzahl** [comment]
@JoseExposito looking at [your implementation](https://github.com/JoseExposito/touchegg/blob/42bb9748e2c140095c0fd572f3c03f6a3fcc81c6/src/daemon/dbus.h) using only signals it should be pretty forward:

1. [Create an interface for the D-Bus service](https://github.com/elementary/switchboard-plug-about/blob/f8392a34ae3eff9a54219f0b718055cb6134004a/src/Interfaces/FwupdManager.vala#L23)
2. [Get a proxy for the service](https://github.com/elementary/switchboard-plug-about/blob/f8392a34ae3eff9a54219f0b718055cb6134004a/src/Interfaces/FwupdManager.vala#L285)
3. [Connect to the signal on the proxy](https://github.com/elementary/switchboard-plug-about/blob/f8392a34ae3eff9a54219f0b718055cb6134004a/src/Interfaces/FwupdManager.vala#L287)

If I can help you in any way, let me know :)
