### ISSUE TITLE
Add a gap between workspaces when swiping/navigating

### ISSUE THREAD

**Issue by danrabbit** [elementary/gala#991]
## Problem

It wasn't as noticeable before, but now that you can just sit here in in-between states it doesn't look as clean that workspaces are just right up against each other

![Screenshot from 2020-12-16 13 21 47@2x](https://user-images.githubusercontent.com/7277719/102407912-b1311300-3fa1-11eb-920b-569172958453.png)

## Proposal

There should be some space between workspaces. Usually we do 24px of space between discrete sections in the UI

**Comment by ibrahimrahman** [comment]
Maybe the workspace could zoom out a little, revealing the gray Workspace Overview backdrop, as the animation starts. This would seperate the workspaces. And then the new workspace zooms in to fill the screen as the animation finishes.

**Comment by JoseExposito** [comment]
Fixed here: https://github.com/elementary/gala/pull/996

This is how it looks like:

![workspaces-separation](https://user-images.githubusercontent.com/1335948/102804051-7ff97e00-43b9-11eb-9386-8bf94cebe396.png)

I mean, it doesn't look bad, but maybe some other design could be explored. I'm personally not a big fan of moving the dock and the panel.
